### ISSUE TITLE
Form Email 2 doesn't work with email field ID shortcode

### ISSUE THREAD

**Issue by parfilov** [elementor/elementor#10967]
- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

If I want to sent the Email 2 after submit, I should use Email field shortcode for To field to send the 2-nd email to the website visitor.
When I do this there is error occurring while sending email. 

## Steps to reproduce

1. Place form widget;
2. Set Email and Email 2 on the Action After Submit toggle;
3. Take the email field ID shortcode and put into the To field of the Email 2;
4. Save document and try to send the form.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.41 (Unix) OpenSSL/1.1.1
	MySQL version: mariadb.org binary distribution v5.7.27
	PHP Version: 7.3.13
	PHP Max Input Vars: 1000
	PHP Max Post Size: 1024M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.3.2
	Site URL: http://test.wplovers.pw
	Home URL: http://test.wplovers.pw
	WP Multisite: No
	Max Upload Size: 1 GB
	Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 2
	Debug Mode: Inactive

== Theme ==
	Name: Doch
	Version: 1.0.0
	Author: Brainstorm Force
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 2.3.4
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 YaBrowser/20.2.0.1145 Yowser/2.5 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.9.7
		Author: Elementor.com

	Elementor Pro
		Version: 2.9.1
		Author: Elementor.com


== Elements Usage ==
	
	archive : 7
		archive-posts : 3
		form : 2
		heading : 3
		jet-listing-grid : 2
		text-editor : 1
		theme-archive-title : 1
	footer : 2
		heading : 2
		nav-menu : 1
		social-icons : 1
	header : 2
		image : 1
		nav-menu : 2
		search-form : 2
		theme-site-logo : 1
	jet_header : 0
		icon-list : 1
		image : 1
	page : 7
		button : 16
		divider : 17
		form : 1
		gallery : 2
		heading : 81
		icon : 4
		icon-box : 3
		icon-list : 5
		image : 38
		image-box : 6
		image-carousel : 2
		menu-anchor : 2
		portfolio : 1
		posts : 1
		social-icons : 1
		spacer : 6
		text-editor : 23
	popup : 12
		button : 4
		form : 3
		heading : 7
		icon : 2
		image : 1
		nav-menu : 2
		spacer : 2
		text-editor : 2
	product : 
		button : 1
		heading : 2
		jet-listing-dynamic-terms : 1
		share-buttons : 1
		woocommerce-breadcrumb : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-data-tabs : 1
		woocommerce-product-price : 1
		woocommerce-product-related : 1
		woocommerce-product-short-description : 1
		woocommerce-product-title : 1
		woocommerce-product-upsell : 1
	section : 17
		button : 8
		divider : 3
		form : 3
		heading : 78
		icon : 7
		icon-box : 47
		icon-list : 2
		image : 4
		media-carousel : 1
		nav-menu : 2
		pafe-form-builder-field : 17
		pafe-form-builder-submit : 1
		shortcode : 1
		social-icons : 1
		text-editor : 10
		woocommerce-product-content : 1
	single : 6
		author-box : 1
		form : 1
		heading : 4
		icon : 1
		icon-list : 2
		image : 1
		jet-engine-booking-form : 1
		jet-images-layout : 1
		jet-listing-dynamic-field : 1
		jet-listing-dynamic-repeater : 1
		post-comments : 1
		post-info : 1
		table-of-contents : 1
		theme-post-content : 2
		theme-post-excerpt : 1
		theme-post-title : 3
		video : 1
	wp-post : 2
		form : 1
		gallery : 1
		heading : 2
		icon-box : 1
		image : 3
		jet-custom-menu : 2
		read-more : 1
		text-editor : 3
	wp-page : 22
		breadcrumbs : 1
		button : 13
		divider : 4
		form : 4
		gallery : 3
		heading : 50
		html : 1
		icon-list : 1
		image : 35
		image-box : 8
		image-gallery : 1
		jet-listing-grid : 3
		menu-anchor : 1
		nav-menu : 1
		pafe-form-builder-field : 4
		pafe-form-builder-submit : 1
		pafe-multi-step-form : 1
		posts : 1
		social-icons : 2
		spacer : 1
		text-editor : 39
		video : 1
		wc-elements : 2
	product-archive : 0
		heading : 1
		sidebar : 1
		theme-archive-title : 1
		wc-archive-products : 2
	jet-listing-items : 0
		button : 3
		heading : 3
		image : 1
		jet-listing-dynamic-field : 5
		jet-listing-dynamic-image : 5
		jet-listing-dynamic-link : 2
		jet-listing-dynamic-meta : 1
		woocommerce-product-price : 1


== Log ==
	
Log: showing 13 of 132020-02-06 16:39:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.0-beta2',
  'to' => '2.9.0-beta3',
)]
2020-02-07 11:41:03 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.0-beta3',
  'to' => '2.9.0-beta4',
)]
2020-02-17 14:35:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.0-beta4',
  'to' => '2.9.2',
)]
2020-02-18 15:03:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.3',
  'to' => '2.8.4',
)]
2020-02-28 12:23:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.2',
  'to' => '2.9.3',
)]
2020-03-06 20:28:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.3',
  'to' => '2.9.4',
)]
2020-03-07 12:22:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.4',
  'to' => '2.9.0-beta1',
)]
2020-03-11 17:08:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.4',
  'to' => '2.9.5',
)]
2020-03-11 17:08:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.0-beta1',
  'to' => '2.9.0-beta2',
)]
2020-03-12 18:26:17 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.5',
  'to' => '2.9.6',
)]
2020-03-15 23:14:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.0-beta2',
  'to' => '2.9.0-beta3',
)]
2020-03-17 21:29:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.0-beta3',
  'to' => '2.9.1',
)]
2020-03-25 17:13:00 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.6',
  'to' => '2.9.7',
)]

PHP: showing 11 of 11PHP: 2020-02-06 17:08:26 [warning X 302][/home/wpltest18/webapps/test_wplovers_pw/wp-content/plugins/elementor/includes/base/controls-stack.php::1174] array_merge(): Expected parameter 1 to be an array, null given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-02-06 18:25:43 [warning X 1][/home/wpltest18/webapps/test_wplovers_pw/wp-content/plugins/elementor/includes/template-library/sources/local.php::839] unlink(/home/wpltest18/webapps/test_wplovers_pw/wp-content/uploads/elementor/tmp/5e3c3e07d4797/__MACOSX): Is a directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-02-06 19:42:20 [notice X 1][/home/wpltest18/webapps/test_wplovers_pw/wp-content/plugins/elementor-pro/modules/query-control/module.php::359] Undefined index: q [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-02-07 11:58:29 [error X 1][/home/wpltest18/webapps/test_wplovers_pw/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::259] Uncaught Error: Call to a member function update_meta() on null in /home/wpltest18/webapps/test_wplovers_pw/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:259
Stack trace:
#0 /home/wpltest18/webapps/test_wplovers_pw/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(180): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(5246, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/wpltest18/webapps/test_wplovers_pw/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/wpltest18/webapps/test_wplovers_pw/wp-includes/class-wp-hook.php(288): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/wpltest18/webapps/test_wplovers_pw/wp-includes/class-wp [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-02-13 16:46:59 [notice X 1][/home/wpltest18/webapps/test_wplovers_pw/wp-content/plugins/elementor/includes/elements/column.php::1020] Undefined index: _column_size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-02-19 12:28:38 [notice X 4][/home/wpltest18/webapps/test_wplovers_pw/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-02-19 12:55:56 [notice X 12][/home/wpltest18/webapps/test_wplovers_pw/wp-content/plugins/elementor/includes/base/element-base.php::471] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-02-22 11:36:43 [warning X 1][/home/wpltest18/webapps/test_wplovers_pw/wp-content/plugins/elementor/includes/template-library/manager.php::473] fclose() expects parameter 1 to be resource, null given [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-17 22:33:48 [error X 2][/home/wpltest18/webapps/test_wplovers_pw/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::259] Uncaught Error: Call to a member function update_meta() on null in /home/wpltest18/webapps/test_wplovers_pw/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:259
Stack trace:
#0 /home/wpltest18/webapps/test_wplovers_pw/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(180): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(519, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/wpltest18/webapps/test_wplovers_pw/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/wpltest18/webapps/test_wplovers_pw/wp-includes/class-wp-hook.php(288): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/wpltest18/webapps/test_wplovers_pw/wp-includes/class-wp- [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-22 20:37:31 [error X 1][/home/wpltest18/webapps/test_wplovers_pw/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::259] Uncaught Error: Call to a member function update_meta() on bool in /home/wpltest18/webapps/test_wplovers_pw/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:259
Stack trace:
#0 /home/wpltest18/webapps/test_wplovers_pw/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(180): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/wpltest18/webapps/test_wplovers_pw/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/wpltest18/webapps/test_wplovers_pw/wp-includes/class-wp-hook.php(288): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/wpltest18/webapps/test_wplovers_pw/wp-includes/class-wp [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-03-24 21:40:56 [notice X 11][/home/wpltest18/webapps/test_wplovers_pw/wp-content/plugins/elementor/core/files/css/base.php::724] Undefined index: _id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 19 of 19JS: 2020-02-06 15:08:47 [error X 191][http://test.wplovers.pw/wp-content/plugins/piotnet-addons-for-elementor-pro/assets/js/minify/pafe-editor.min.js?ver=5.15.12:1:713] Cannot read property \'trim\' of undefined 
JS: 2020-02-06 16:27:15 [error X 12][http://test.wplovers.pw/wp-content/plugins/piotnet-addons-for-elementor-pro/assets/js/minify/pafe-form-builder.min.js?ver=5.15.12:5:25993] Stripe is not defined 
JS: 2020-02-07 15:18:57 [error X 42][http://test.wplovers.pw/wp-content/plugins/piotnet-addons-for-elementor-pro/assets/js/minify/form-builder.min.js?ver=5.20.0:4:16752] Cannot read property \'url\' of undefined 
JS: 2020-02-13 15:24:16 [error X 4][http://test.wplovers.pw/wp-admin/post.php?post=519&action=elementor:2:9] $ is not a function 
JS: 2020-02-28 10:40:41 [error X 1][http://test.wplovers.pw/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.2:31:199356] Cannot read property \'widgets_settings\' of undefined 
JS: 2020-03-02 08:37:09 [error X 2][http://test.wplovers.pw/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.8.4:2:54702] Cannot read property \'top\' of undefined 
JS: 2020-03-07 10:19:12 [error X 2][http://test.wplovers.pw/wp-content/plugins/elementor/assets/js/common.min.js?ver=2.9.4:2:106905] Routes: `` not found. 
JS: 2020-03-20 17:41:53 [error X 8][http://test.wplovers.pw/wp-content/uploads/winp-css-js/5469.js?ver=1581608634:5:2] ymaps is not defined 
JS: 2020-03-22 18:30:45 [error X 1][http://test.wplovers.pw/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view5481\") has already been destroyed and cannot be used. 
JS: 2020-03-22 18:32:34 [error X 2][http://test.wplovers.pw/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view69\") has already been destroyed and cannot be used. 
JS: 2020-03-22 18:43:12 [error X 1][http://test.wplovers.pw/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view77\") has already been destroyed and cannot be used. 
JS: 2020-03-22 18:45:36 [error X 1][http://test.wplovers.pw/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view89\") has already been destroyed and cannot be used. 
JS: 2020-03-22 18:49:41 [error X 2][http://test.wplovers.pw/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view98\") has already been destroyed and cannot be used. 
JS: 2020-03-22 19:13:09 [error X 5][http://test.wplovers.pw/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view106\") has already been destroyed and cannot be used. 
JS: 2020-03-24 17:15:48 [error X 1][http://test.wplovers.pw/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view1662\") has already been destroyed and cannot be used. 
JS: 2020-03-24 17:18:02 [error X 1][http://test.wplovers.pw/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view103\") has already been destroyed and cannot be used. 
JS: 2020-03-24 17:18:52 [error X 1][http://test.wplovers.pw/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view1375\") has already been destroyed and cannot be used. 
JS: 2020-03-24 17:53:19 [error X 1][http://test.wplovers.pw/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=2.9.1:2:44626] Cannot read property \'settings\' of undefined 
JS: 2020-03-25 14:50:11 [error X 1][http://test.wplovers.pw/wp-content/plugins/elementor/assets/js/common.min.js?ver=2.9.6:2:98603] Commands internal: `document/history/delete-transaction` not found. 


				
```
</details>

**Comment by mutakisan** [comment]
I'm having this very issue too.
The  "To" field is not accepting field ID shortcode anymore.
It worked in 2.9.6.

**Comment by Ersonusaini** [comment]
Face Same issues also

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.9.3

Feel free to update

Thanks!

**Comment by santiagogaal** [comment]
Solved  add "" in name of shortcode

**Comment by ayyazahmad** [comment]
Elementor Form is working fine. 
But when we use Email 2 with field ID Shortcode, it throws error messages.

**Comment by WebGiant** [comment]
This bug still exists in Elementor 3.4.3 and Elementor Pro 3.4.0.  If "Email2" is used, and the shortcode [field id="email"] is used as the "To" address, then it simply fails to send anything (without errors).

**Comment by Moranne** [comment]
The bug remains in Elementor 3.5.0 and Elementor Pro 3.5.2

**Comment by mapmusic** [comment]
Same in 3.55/3.62

**Comment by ingrid2107** [comment]
Copying the shortcode ([field id="email"] ) from the shortcode field in the settings of the email-field and pasting it in the 'to'-field of email2 - worked for me. Same with other fields used in email & email2.

**Comment by mackyangeles** [comment]
Issue is happening again with Elementor 3.7.8 and Elementor Pro 3.7.7 Email 2 with [field id="email"] as TO is not working having an error issue alert when sending form.

**Comment by paulaime** [comment]
I'm using Elementor 3.10.1, and I'm also having this issue when I use a short code in the email or email 2.
It's pretty annoying and should definitely be fixed.

**Comment by marcieee73** [comment]
Still happening

**Comment by ronaldaug** [comment]
Confirmed , still happening in the latest version. 
Whenever I send both Email and Email2, it always fail.
I can only send one of them.

**Comment by boydeveloper1** [comment]
Still having same issues too

**Comment by romerocox** [comment]
Facing the very same issue on Elementor Pro Version: 3.16.1

**Comment by juandelossantos** [comment]
The issue is still happening on version 3.16.2

**Comment by hking1991** [comment]
Having this issue to: Version 3.16.6

**Comment by XeOS1977** [comment]
This issue is still occurring on version 3.17.1 and to be more specific. It seems exclusive to users on MacOS. On Windows machines I'm unable to reproduce but on MacOS instantly.

**Comment by jamshidpour** [comment]
This issue still exists in elementor version 3.18.2

**Comment by hirschferkel** [comment]
Will there ever be a fix for this? No idea how to populate the From Email field so it will work? Is there any hack?

**Comment by DaljitKhalsa** [comment]
This issue is still present on the latest version of elementor's pro plugin Version 3.18.2

Can someone please contact the support team and aware them about this thread and tell them that many people are trying to find the solution? I noticed that in some versions of the Elementor plugin, the Email2 thing/feature does work. But I do not remember which version it was. A temporary solution is to remove the Email2 feature. I am Daljit Singh from Khalsa Website Designers. If someone else is facing the same, issue, contact me via my website, and let's get that fixed from Elementor's support team. If more people contact them about an issue they solve it fast. Otherwise, they don't care much.

**Comment by eliendauwe** [comment]
I came here looking for a solution for the same issue. Retyping the quotes as @ntbosscher suggested worked for me. Thanks!

**Comment by vafelu** [comment]
I resolved this issue with the correct setup of DNS records: DKIM and SPF.

**Comment by brunoaguilar0114** [comment]
> I resolved this issue with the correct setup of DNS records: DKIM and SPF.

Hello. Could you please help me to disguise how to set up this correctly? because I did it and it didn't work either

**Comment by CJ484** [comment]
Yea I can say that in elementor 3.25.5 and elementor 3.25.3, the issue still continues. I did try adding the shortcodes to both "To: " field on "email" and "email 2". It does seem that the first "email" works when I add both actions together. If I remove "email" from the action then "email 2" will work. But I do wish that the issue resolves

**Comment by soyjulius** [comment]
The issue persists, and upon further investigation in the "Delivery Report," the status shows the following:

**`Recipient: discarded`**

This suggests that the delivery is being intentionally dropped or discarded for some reason. Could you please provide additional insight into why this is occurring or suggest a way to resolve the issue? Thank you!

**Comment by mirzayan8** [comment]
> I was able to use this workaround:
> 
> * send only 1 email and cc my team
> * in the `to` use the shortcode. Check that you have standard double quotes and not the rich-text double quotes. I had to re-type mine manually to get it to work

This is the solution if you are facing it in 2025. Just simply copy the shortcode & paste it on "to" field. That works.

**Comment by dqwebanddesign** [comment]
Working with short code in 2025

**Comment by saulmoniq** [comment]
Maybe this can help someone, my email 2 wasn't working due to an "$" inside the subject (it was a price tag) this caused the email 2 to not be sent. After deleting it, it worked.

**Comment by captivatemediaqld** [comment]
> Maybe this can help someone, my email 2 wasn't working due to an "$" inside the subject (it was a price tag) this caused the email 2 to not be sent. After deleting it, it worked.

OK October 2025 same issue. Thank you @saulmoniq ! I discovered I had a "dash" in my subject line which was causing the error. Removed the dash, simplified the email subject and worked perfectly. Can now both "email" and "email2"
