### ISSUE TITLE
✅ 🔗 🐞 Can't edit global widget (Related to #19456) - [ED-10226]

### ISSUE THREAD

**Issue by albe89albe** [elementor/elementor#11474]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

I have a CallToAction button that I need to reproduce in several pages. It works just fine, is a simply button that throws a popup. I made it a global widget and reuse it across the website. But if I want to edit the global widget, the left sidebar of the Elementor editor becomes empty.
I have no way to edit this global widget. The rare thing is that appears to be hapening just with this global widget, I have others like a carousel that I can edit, but this one of the button, I can't.
There are some places where I use the shortcode of the button to reuse it. Don't know if this makes any difference.
If I enable safe mode, I can edit it. That makes me think that this is some compatibility issue.
![globalWidgetNoEdit](https://user-images.githubusercontent.com/18534010/82878884-6a63c900-9f3c-11ea-94c5-8417e9cb488c.jpg)
## Steps to reproduce

At least in my website:
- Create a pop-up
- Create a button that shows that pop-up on click
- Make the button a global widget
- Go to another page, reuse the button
- Try to edit the global widget without unlinking it

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MySQL Community Server (GPL) v5.7.28
	PHP Version: 7.3.17
	PHP Max Input Vars: 5000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.4.1
	Site URL: https://aleasoft.com
	Home URL: https://aleasoft.com
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: -1
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: Europe/Madrid
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.3.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36

== Active Plugins ==
	Alea Plugin
		Version: 1.1.0
		Author: Alberto

	Duplicate Post
		Version: 3.2.4
		Author: Enrico Battocchi

	Elementor
		Version: 2.9.8
		Author: Elementor.com

	Elementor Pro
		Version: 2.9.4
		Author: Elementor.com

	Google Analytics for WordPress by MonsterInsights
		Version: 7.10.4
		Author: MonsterInsights

	Really Simple SSL
		Version: 3.3.3
		Author: Rogier Lankhorst, Mark Wolters

	Redirection
		Version: 4.7.2
		Author: John Godley

	Visualizer: Tables and Charts for WordPress
		Version: 3.4.3
		Author: Themeisle

	Wordfence Security
		Version: 7.4.7
		Author: Wordfence

	WPML Multilingual CMS
		Version: 4.3.14
		Author: OnTheGoSystems

	Yoast SEO Premium
		Version: 14.1
		Author: Team Yoast


== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com


== Elements Usage ==
	
	archive : 5
		archive-posts : 1
		spacer : 2
		theme-archive-title : 1
	footer : 5
		form : 1
		google_maps : 2
		heading : 2
		icon-list : 2
		nav-menu : 1
		social-icons : 1
	header : 5
		icon-list : 1
		image : 1
		nav-menu : 1
		search-form : 1
		shortcode : 2
		social-icons : 1
	page : 1
		button : 3
		divider : 1
		form : 1
		heading : 2
		icon-box : 4
		icon-list : 3
		image : 2
		menu-anchor : 1
		spacer : 6
		text-editor : 8
		theme-site-logo : 1
	popup : 3
		form : 3
		heading : 3
	single : 11
		post-navigation : 1
		shortcode : 2
		spacer : 2
		theme-post-content : 2
		theme-post-title : 2
	widget : 0
		button : 10
		media-carousel : 19
		nav-menu : 316
	wp-page : 308
		button : 105
		countdown : 7
		counter : 8
		divider : 29
		flip-box : 11
		form : 25
		global : 79
		google_maps : 6
		heading : 840
		html : 19
		icon : 29
		icon-box : 64
		icon-list : 22
		image : 145
		image-box : 112
		image-carousel : 8
		media-carousel : 1
		menu-anchor : 7
		posts : 5
		price-list : 4
		price-table : 14
		reviews : 1
		shortcode : 443
		social-icons : 5
		spacer : 404
		star-rating : 3
		tabs : 15
		testimonial : 39
		text-editor : 309
		theme-post-title : 1
		video : 8


== Log ==
	
JS: showing 20 of 34JS: 2020-04-03 12:57:24 [error X 2][https://aleasoft.com/wp-admin/post.php?post=43507&action=elementor:19:13] Unexpected token \'.\' 
JS: 2020-04-20 14:42:54 [error X 1][https://aleasoft.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.7:7:57120] Blocked a frame with origin \"https://aleasoft.com\" from accessing a cross-origin frame. 
JS: 2020-04-20 17:08:06 [error X 3][https://aleasoft.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=2.9.7:2:58852] Cannot read property \'attributes\' of undefined 
JS: 2020-04-21 11:10:35 [error X 1][https://aleasoft.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view22381\") has already been destroyed and cannot be used. 
JS: 2020-04-21 15:42:57 [error X 1][https://aleasoft.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view943\") has already been destroyed and cannot be used. 
JS: 2020-04-21 15:48:35 [error X 13][https://aleasoft.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view945\") has already been destroyed and cannot be used. 
JS: 2020-04-21 15:50:20 [error X 1][https://aleasoft.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view2733\") has already been destroyed and cannot be used. 
JS: 2020-04-21 15:56:43 [error X 3][https://aleasoft.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view942\") has already been destroyed and cannot be used. 
JS: 2020-04-21 16:06:33 [error X 1][https://aleasoft.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view956\") has already been destroyed and cannot be used. 
JS: 2020-04-21 16:10:18 [error X 3][https://aleasoft.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view959\") has already been destroyed and cannot be used. 
JS: 2020-04-22 07:50:57 [error X 1][https://aleasoft.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view1184\") has already been destroyed and cannot be used. 
JS: 2020-04-22 07:54:26 [error X 1][https://aleasoft.com/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5:22:19954] View (cid: \"view1276\") has already been destroyed and cannot be used. 
JS: 2020-05-05 13:34:04 [error X 16][https://aleasoft.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.8:31:183966] Cannot read property \'match\' of undefined 
JS: 2020-05-18 14:38:18 [error X 1][https://aleasoft.com/wp-content/plugins/elementor/assets/js/editor-document.min.js?ver=2.9.8:2:187452] Cannot read property \'map\' of undefined 
JS: 2020-05-18 14:58:36 [error X 1][https://aleasoft.com/wp-admin/post.php?post=92053&action=elementor#:10:5] a is not defined 
JS: 2020-05-18 14:58:37 [error X 1][https://aleasoft.com/wp-admin/post.php?post=92053&action=elementor#:10:5] aler is not defined 
JS: 2020-05-18 15:04:15 [error X 1][https://aleasoft.com/wp-admin/post.php?post=92053&action=elementor#:2:1] Invalid or unexpected token 
JS: 2020-05-18 15:25:01 [error X 2][https://aleasoft.com/wp-admin/post.php?post=92053&action=elementor#:11:5] Unexpected token \'}\' 
JS: 2020-05-19 09:53:24 [error X 1][https://aleasoft.com/wp-admin/post.php?post=92053&action=elementor:16:32] missing ) after argument list 
JS: 2020-05-22 15:20:04 [error X 1][https://aleasoft.com/wp-admin/load-scripts.php?c=1&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,shortcode,utils,wp-util,wp-backbo&loadchunk_1=ne,media-models,moxiejs,plupload,wp-plupload,jquery-ui-sortable&ver=5.4.1:4:1825] cannot call methods on resizable prior to initialization; attempted to call method \'destroy\' 

Log: showing 7 of 72020-03-18 12:15:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.8.5',
  'to' => '2.9.1',
)]
2020-03-30 16:47:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.6',
  'to' => '2.9.7',
)]
2020-03-30 16:47:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.1',
  'to' => '2.9.2',
)]
2020-04-20 14:15:45 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.2',
  'to' => '2.9.3',
)]
2020-04-20 14:15:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.2',
  'to' => '2.9.3',
)]
2020-04-22 09:06:12 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.7',
  'to' => '2.9.8',
)]
2020-05-08 10:00:54 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.9.3',
  'to' => '2.9.4',
)]

PHP: showing 1 of 1PHP: 2020-04-20 14:15:50 [warning X 1][/homepages/1/d810730684/htdocs/web_aleasoft/wp-content/plugins/elementor/core/files/manager.php::115] unlink(/homepages/1/d810730684/htdocs/web_aleasoft/wp-content/uploads/elementor/css/post-89215.css): No such file or directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
```
</details>

**Comment by lior-sh** [comment]
Hi @albe89albe,

We are investigating this issue. Meanwhile, you can workaround by refresh the page.
Thanks

**Comment by mjcreative** [comment]
I am experiencing a similar issue on global widgets that are forms, when clicking on the redirect option the editor panel goes blank.

**Comment by blackashconsulting** [comment]
I was also experiencing this problem with v. 2.10.2. rolling back to v. 2.9.5 fixed the issue for me. 

> I am experiencing a similar issue on global widgets that are forms, when clicking on the redirect option the editor panel goes blank.

**Comment by mjcreative** [comment]
I wish this bug would get fixed, it has been like this for weeks and messes up form tracking on all of my sites.

**Comment by blackashconsulting** [comment]
is there any update on this? Or is this now part of the larger issue of global settings not working at all?

**Comment by pixelxcode** [comment]
+1. Cannot edit global widget either.

**Comment by jtgoebel** [comment]
I can't edit global widget either.

**Comment by fansboy** [comment]
Is there any solution for this issue? I've met the same one recently.

**Comment by soydelia** [comment]
I can't edit global widget either.

**Comment by pl207-unikent** [comment]
My issue is similar but slightly different. If I add the global widget to a new page it appears on the live site but not in the edit screen. The heading in these same section appears and is editable - global widget does not and cannot be seen in Navigator either.

**Comment by sederholm** [comment]
Just lie the OP, I have a global button, that I cannot edit—?

**Comment by FabioMoura** [comment]
Experiencing the same issue...

**Comment by fgm9000** [comment]
Experiencing the same issue...

**Comment by fgm9000** [comment]
> Hi @albe89albe,
> 
> We are investigating this issue. Meanwhile, you can workaround by refresh the page.
> Thanks.

Refreshing the page doesn't work

**Comment by GESign** [comment]
Dear Support,
Same issue here. I can edit a part of the global widgets but some of them not. It would be important to able to edit those as well.

**Comment by moscoz** [comment]
Same issue here. Refreshing the page does not solve it.

**Comment by melisaciputra** [comment]
Same issue here too. I created accordion global widget and unable to edit it. I was basically thrown to /wp-admin/edit.php each time I try to edit it. Please take a look and let us know if you need more info.

**Comment by TheOriginal-OG** [comment]
Yes, see if there is a gray spot where your widget used to be? If there is and you hover over it, it will outline and give you the corner you can click to edit. BUT what I experience is now I can see the widget but it won't let me edit it. I click the "edit" button in Global Widgets and it goes blank. Then I go click the corner of the widget and the edit button comes back. I click it again and it disappears. So I accidentally pulled the widget and dropped it in another section. And after I dragged it back to where I wanted it, the editing started working again. I don't know why...🤷‍♂️

**Comment by minioyatar** [comment]
This is what I see in the console when I hit edit my global form widget. I hope it helps


common.min.js?ver=3.2.3:2 TypeError: Cannot read property 'id' of undefined
    at i.get (editor.min.js?ver=3.2.3:2)
    at initialize (editor.min.js?ver=3.2.3:2)
    at initialize (editor.min.js?ver=3.2.3:2)
    at i.h.View (load-scripts.php?c=0&load[chunk_0]=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,wp-api-request&ver=5.4:12)
    at i.constructor (backbone.marionette.min.js?ver=2.4.5.e1:24)
    at i.constructor (backbone.marionette.min.js?ver=2.4.5.e1:24)
    at i.constructor (backbone.marionette.min.js?ver=2.4.5.e1:25)
    at i [as constructor] (load-scripts.php?c=0&load[chunk_0]=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,wp-api-request&ver=5.4:12)
    at i [as constructor] (load-scripts.php?c=0&load[chunk_0]=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,wp-api-request&ver=5.4:12)
    at new i (load-scripts.php?c=0&load[chunk_0]=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,wp-api-request&ver=5.4:12)
consoleError @ common.min.js?ver=3.2.3:2
onCatchApply @ editor.min.js?ver=3.2.3:2
run @ editor.min.js?ver=3.2.3:2
forEach.o.<computed> @ editor.min.js?ver=3.2.3:2
run @ common.min.js?ver=3.2.3:2
run @ common.min.js?ver=3.2.3:2
editGlobalModel @ editor.min.js?ver=3.2.2:2
onEditButtonClick @ editor.min.js?ver=3.2.2:2
dispatch @ load-scripts.php?c=0&load[chunk_0]=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,wp-api-request&ver=5.4:5
r.handle @ load-scripts.php?c=0&load[chunk_0]=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,wp-api-request&ver=5.4:5

**Comment by coryhubbell** [comment]
+1 no global widget editing possible. When I go to elementor editor the fields show up as undefined and the global widget panel goes blank.

**Comment by TheOriginal-OG** [comment]
> +1 no global widget editing possible. When I go to elementor editor the fields show up as undefined and the global widget panel goes blank.

Just drag the widget out of that spot and drop it in another, then drag it back and drop it where it was, after that, my widget started working right again.

**Comment by marcelestela** [comment]
Same problem here. Did any one fix it? :(

**Comment by TheOriginal-OG** [comment]
@marcelestela Just drag the widget out of that spot and drop it in another, then drag it back and drop it where it was, after that, my widget started working right again. This was my original post:

Yes, see if there is a gray spot where your widget used to be? If there is and you hover over it, it will outline and give you the corner you can click to edit. BUT what I experience is now I can see the widget but it won't let me edit it. I click the "edit" button in Global Widgets and it goes blank. Then I go click the corner of the widget and the edit button comes back. I click it again and it disappears. So I accidentally pulled the widget and dropped it in another section. And after I dragged it back to where I wanted it, the editing started working again. I don't know why...🤷‍♂️

**Comment by Aviad-Herman** [comment]
Hello,
Is this still an issue or has it been solved in the latest versions of Elementor?

If the bug persists, we recently updated the infrastructure behind Global Widgets. The update is currently only available on Elementor's developer edition releases (https://elementor.com/blog/introducing-beta-developer-edition/). Could you see if the bug still happens on the developer release?

Important note: the developer releases should not be used on live sites

**Comment by genowales** [comment]
The issue still persists from what I can see. The workaround I found was to copy the global widget anywhere on to the page, then click edit, save, then delete again – the original global widget will be updated.

**Comment by psmcdowell** [comment]
I continue to experience the same issues on several widgets. The work around does not work for me. When I move the widget, edit, save, then try to delete, I lose the entire section.

**Comment by Morgunov-Vitaly** [comment]
The same issue!

**Comment by debslo** [comment]
I was having issues with global widgets. Unable to unlink them, and nothing updating. I have just updated to the latest version of Elementor Pro today (3.5.2) and it all seems to be working again. Although there might still be issues when using global widgets in the Astra custom-layouts sections... the global widget didn't seem to update in the custom-layout Footer I'd built, but I don't need it to be global, so I just unlinked it and it's fine. Global widgets in other areas of the site are working OK for me.

**Comment by oligenom** [comment]
Same here. Accordeon Widget is not updating after change.

**Comment by danielpschmidt** [comment]
we have the same issue here. cannot unllink, cannot edit correctly - so e.g. when adding new fields does not accept that as for global widget. Version 3.5.1

**Comment by sirhenryhu** [comment]
Bravo. The issue described as above remains even it is **_2022_** NOW!!

**Comment by lensbreak** [comment]
This bug is still present. Really, soon I will turn away from Elementor. This is the 1000th time I find bugs reported here that are YEARS old but seems like nobody at Elementor cares about. Only thing they care is that Cloud Site that NOBODY needs! We paid for a plugin and expect it to be maintained.

**Comment by GESign** [comment]
I turned to Oxygen Builder finally a year ago. I have problems there as well but because of other external plugins (what is my choice) under the builder. Thank God the problems are much smaller there. The system is robust. Pro is lot more freedom next to robust system and Con is that is a more technical solution. It is good when You know html and css.

**Comment by Aylonltd** [comment]
This shit is embarassing. A premium product being sold and unmaintained for 2 years.
I sent an email to the support team, let's see if they wake up.

**Comment by Gabugbuster** [comment]
@lensbreak This bug was fixed a long time ago by Elementor pro 3.5.1. The developers revamped the whole infrastructure of the Global widget to fix several bugs that affected this feature. The remaining issues are apparently with old global widgets (created before pro 3.5.1), which are on the developers' roadmap.

**Comment by Stas0238** [comment]
I decided to wake everyone up here to "give a push" to Elementor devs together to fix this BUG asap. Just leave a link so anyone could leave own comments or let's write few of them here. 

Link -> https://github.com/elementor/elementor/issues/19456 

Agreed to @lensbreak that it needs to wait years to get an answer from their support but mostly the answer we got is not as good as it was expected for long time waiting for it. 
Examples -> https://wordpress.org/support/topic/get_style_depends-on-edit-mode-only/, https://wordpress.org/support/topic/advanced-section-options/, https://wordpress.org/support/topic/get_script_depends-based-on-option/.

Also I would recommend for @lensbreak, @sirhenryhu, @mjcreative (and all others who has time to read) to check one of my chat history with Elementor devs-> https://github.com/elementor/elementor/issues/16881.

@rami-elementor please, take a look on those issues that started far away in 2020...

Regards, @stas0238

**Comment by schmekism** [comment]
waste of my time I'm sure... not sure if it is related, but none of my global widgets are editable at the moment

**Comment by diegodtlaprint** [comment]
3+ years later, still cannot edit a global widget
![image](https://github.com/elementor/elementor/assets/114035780/53d0e538-51ee-4797-ae90-711eae6a9697)

**Comment by diegodtlaprint** [comment]
!!!! you can add the global widget to a page, then choose to edit the global widget there - not from saved templates

**Comment by d-eco-creative** [comment]
> !!!! you can add the global widget to a page, then choose to edit the global widget there - not from saved templates

Thanks, this solution worked for me. Add global widget to the page from the global menu and then the editing option is provided

<img width="362" alt="Screenshot 2023-10-27 at 13 01 17" src="https://github.com/elementor/elementor/assets/1027049/94d070eb-00de-4397-b5a3-56f788d4609c">
 
<img width="364" alt="Screenshot 2023-10-27 at 13 03 44" src="https://github.com/elementor/elementor/assets/1027049/916f649d-90aa-4046-b6cb-f90d2cc7564c">

**Comment by SirChopper** [comment]
> > !!!! you can add the global widget to a page, then choose to edit the global widget there - not from saved templates
> 
> Thanks, this solution worked for me. Add global widget to the page from the global menu and then the editing option is provided
> <img alt="Screenshot 2023-10-27 at 13 01 17" width="362" src="https://private-user-images.githubusercontent.com/1027049/278622819-94d070eb-00de-4397-b5a3-56f788d4609c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NjcxMTEsIm5iZiI6MTcwNjQ2NjgxMSwicGF0aCI6Ii8xMDI3MDQ5LzI3ODYyMjgxOS05NGQwNzBlYi0wMGRlLTQzOTctYjVhMy01NmY3ODhkNDYwOWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjhUMTgzMzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWJkZjNjOGMyYWQwMDNhMjU0MmIwNTQzYzMxOWFhNjQ4ZTdhOWZlZTY2MTU0Yzg5ZmQ1YjhmZWE4OWMyOWUxMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Dp1cfcOxgy_3FTZIjkKHi12b9_TxxDROL2gYsp-_ppw"> <img alt="Screenshot 2023-10-27 at 13 03 44" width="364" src="https://private-user-images.githubusercontent.com/1027049/278623206-916f649d-90aa-4046-b6cb-f90d2cc7564c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NjcxMTEsIm5iZiI6MTcwNjQ2NjgxMSwicGF0aCI6Ii8xMDI3MDQ5LzI3ODYyMzIwNi05MTZmNjQ5ZC05MGFhLTQwNDYtYjZjYi1mOTBkMmNjNzU2NGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjhUMTgzMzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmRlMGMzYWQ4YTUxZWE1MTZiMTFlMjYxNTIzNmJiZjg2N2Q0NmQ2MTg1NjljYzEyMGM1NjAwNjk1MDRkODU1MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5BcRSPQSbtCNda47FQQbz_CP4Y7o8lt-9OPhSgPOtII">

This is true but there is still no way to translate the GLOBAL WIDGETS ? Using WPML premium but Global Widgets are not available for translations. I ge the No Permissions message.....? Frustrating.

**Comment by nicholaszein** [comment]
Hello everyone!

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.19.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
