### ISSUE TITLE
Gallery multiple galleries lightbox shows all images

### ISSUE THREAD

**Issue by SimpelMind** [elementor/elementor#11809]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

I have a gallery with multiple galleries. If I press on a image in a other gallery instead of the all filter. The Lightbox opens as normal but when you use the arrow, I also see the photos from other galleries. Also the number in the left top corner shows the the amount of images from the all filter and not the amount of images from the selected gallery.

The moment I open one of the other galleries instead of the all filter. And I go through the photos with the arrows, I also see the photos from other galleries.

## Steps to reproduce

1. Create a gallery with multiple galleries.
2. Set link to media file
3. Selected one of the galleries(not the **All filter**)
3. Press on the first image in the gallery the Lightbox should open.
4. In the left top corner the stands the number of where the images stand in all filter and not in selected gallery.
5. If you use the arrow's, you will see the images of all other galleries also. 

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently.

## Environment

<details>
<summary>System Info</summary>

- Astra Pro 2.5.1 (Thema)
- WordPress 5.4.2
- Elementor 2.9.13
- Elementor Pro 2.10.3
- PHP 7.3.18

</details>

**Comment by GithubWernerWohnbau** [comment]
The same here ... 2 Gallaries (with lightbox) shows the images from the other gallery on the site.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.0.2

Feel free to update

Thanks!

**Comment by wholeheartcreative** [comment]
It’s March 2021, and I’m still having the exact issue.

**Comment by klecka** [comment]
This issue is not resolved as of Elementor Pro 3.2.2

**Comment by bodhi1970** [comment]
Have same issue still in July 2021. This is an issue that haven't been solved yet properly.

**Comment by klecka** [comment]
Found this snippet to fix the issue provisionally. Maybe you need to update the classes

<script>
jQuery(function ($) {​​​​​
    $(document).ready(function ($) {​​​​​
        var i = 0;
        $('.elementor-image-gallery').each(function () {​​​​​
            var oldAttrLightbox = $(this).find('a').attr('data-elementor-lightbox-slideshow');
            var newAttrLightbox = oldAttrLightbox + i;
            $(this).find('a').attr('data-elementor-lightbox-slideshow', newAttrLightbox);
            i = i + 1;
        }​​​​​)
    }​​​​​)
}​​​​​);
</script>

**Comment by bodhi1970** [comment]
Hi and thanks. I added that snippet in the Elementor custom code but it did not work. Also tried with other snippet plugin in.

**Comment by klecka** [comment]
Add it with elementor custom code before the closing </body>-tag.
You might have to alter '.elementor-image-gallery' or 'data-elementor-lightbox-slideshow' according to your markup. Check with developer tools in your browser.

**Comment by iamAloTheGreat** [comment]
Hello, I'm having the same issue. Is this solution possible with Elementor free version?

**Comment by kaspars17** [comment]
Hi, it is November 2021, issue still exists. I have all images grouped in one lightbox slideshow from many separate elementor-image-carousel.
@klecka thanks for the snippet - it worked by targeting '.elementor-image-carousel'

**Comment by klecka** [comment]
> This issue has been resolved in Elementor Pro v3.0.2
> 
> Feel free to update
> 
> Thanks!

This is still not solved. Please reopen the issue!

**Comment by frussane** [comment]
> > This issue has been resolved in Elementor Pro v3.0.2
> > Feel free to update
> > Thanks!
> 
> This is still not solved. Please reopen the issue!

@shilo-ey

**Comment by tole011** [comment]
This is so annoying. I have a listing with multiple galleries from separate stories. Imagine how it looks when you see images from all stories in a lightbox. PLEASE fix this!!!

**Comment by nahid-hridoy** [comment]
Still Not Fixed? Really Nice from Elementor.

**Comment by klecka** [comment]
> Still Not Fixed? Really Nice from Elementor.

Not yet, no

**Comment by mikeecho2** [comment]
April 2023, Almost 3 YEARS NOW ELEMENTOR, and STILL NOT RESOLVED

**Comment by CoSciBlog** [comment]
got the problem with elementor loop element and gallerys inside the loop, when i open one gallery/lightbox it shows all images from every slider/gallery on the page, so around 60 images in total instead of around 5 per loop item.

**Comment by StarEyedGoatCat** [comment]
Hi Guys!

The previous code is working for me with a small change

Try this:

jQuery(document).ready(function ($) {
    var i = 0; $('.elementor-image-carousel-wrapper').each(function () {
        var oldAttrLightbox = $(this).find('a').attr('data-elementor-lightbox-slideshow');
        var newAttrLightbox = oldAttrLightbox + i; $(this).find('a').attr('data-elementor-lightbox-slideshow', newAttrLightbox);
        i = i + 1;
    })
})

**Comment by cthollaway** [comment]
Having the same issue. When using the Image Carousel widget with a loop the lightbox shows all images that are loaded on that page and not just the images from that specific post.

**Comment by rloes** [comment]
+1 still an issue

**Comment by tole011** [comment]
After 3 years of waiting for a proper fix, I've switched to Bricks Builder, and won't look back... Best of luck to everyone.

**Comment by nicholaszein** [comment]
Hello everyone,

as indicated before when this issue was closed, it was indeed fixed in version 3.0.2.

However, if you are experiencing a similar issue, you need to submit a new Bug Report, following the Bug Report guidelines and providing the necessary information so we can validate your issue and provide a fix for it. Commenting on a closed issue that was tested and fixed, won't fix other issues you might be experiencing. Each website is unique and despite our extended efforts, Elementor can't predict every single case.

If you think this is a bug, please do like @rloes did and follow the guidelines for opening a new [🐞 Bug Report](https://github.com/elementor/elementor/issues/new?assignees=&labels=status%2Fawaiting_triage&template=bug.yml), so we can help you better.

Thanks for understanding. 🙏
