### ISSUE TITLE
Editor is stuck when set to "Access to edit content only" in Role Manager

### ISSUE THREAD

**Issue by dasigna** [elementor/elementor#12521]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

since 3.08 the editor generally is loading remarkable slower - the avove issue occurs when you set an user with ability to "editing content only".
the the loading of the editor is stuck forever - even in safe mode.
reverting back role with no el restrictions, editor works again for editor role.

no issue with 3.07, no prob with admin.

## Steps to reproduce

create user as editor, restrict to edit content only, start editor for some page ...

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
obsolete... alright with 3.07 and 3.04 pro

just EL/pro, GP

```
</details>

**Comment by portrayaloflife** [comment]
+1

**Comment by givenmedia** [comment]
I updated a website with the “Hello Theme” to Elementor 3.0.8 yesterday and everything seemed fine, but today the website Editor with only EDITOR rights calls, saying, he can't see the 'Edit with Elementor' Button, which he couldn't. I went through various trouble shooting steps including deactivating all the plugins and even with NO plugins except Elementor installed, it wouldn't give the EDITOR back the 'Edit with Elementor' button. So eventually I rolled back Elementor from 3.0.8. to 3.0.7. but it still wouldn't work. The only thing that then DID WORK, was rolling back to Elementor Version 3.0.6. I'm sharing this, to maybe help someone else who might have EDITORs who lost their 'Edit with Elementor' Button. I hope this gets solved in 3.0.9. Ben Pines
 🙂
The thing worth mentioning here though, is that the ADMINs could see the button but NOT the EDITORS. I checked the usual Elementor Settings to make sure Elementor was allowed for PAGE and POST edits and it was, and then checked if EDITORs were ALLOWED to use ELEMENTOR with the Elementor User Roles and they were. So pushing Elementor back to 3.0.6 brought back the 'Edit with Elementor' for Editors.

I have it not just on this site but numerous others that I tested this morning. 👍

**Comment by schndr-cdn** [comment]
It's important. It's also happened to all our clients. They can't edit their pages.

**Comment by portrayaloflife** [comment]
It's been days and clients still can't edit their own website... THIS IS AN URGENT ISSUE!!!!

**Comment by portrayaloflife** [comment]
@arielk is there an ETA?

**Comment by makaus** [comment]
Indeed, our clients can't edit anything right now..
As a temp fix, they can edit anything now..

**Comment by givenmedia** [comment]
I tried this morning the Elementor 3.0.9. but sadly it didn't solve the problem. The Editor role still doesn't see the 'Edit with Elementor' button anymore. So I reverted back to Elementor 3.0.6. again to give the Editor the Button back. Maybe 3.0.10 will solve it?

**Comment by dasigna** [comment]
... i am having some training coming up - would be nice if there will be a solution asap!

**Comment by portrayaloflife** [comment]
please fix this

**Comment by zbyyna** [comment]
Please, fix it this issue. My clients wants to edit our websites content and we cant..When will it be fixed, please?

**Comment by dasigna** [comment]
seems to be solved with 3.0.10

at least from my side :)

thanks. closing this.

**Comment by givenmedia** [comment]
I've updated to Elementor 3.0.10 and am still experiencing this problem. The 'Edit with Elementor' is not appearing as expected for Editors but only for Admins.
