### ISSUE TITLE
Js error in console to version 3.2.1 and 3.2.0

### ISSUE THREAD

**Issue by Eliofilo** [elementor/elementor#14642]
Hi 

in version 3.2.1 and 3.2.0 it's not possibile use "Style" in "Section", it's all gray without field! And receive this in console:

underscore.min.js?ver=1.8.3:2 Uncaught SyntaxError: Unexpected identifier
    at new Function (<anonymous>)
    at Function.v.template (underscore.min.js?ver=1.8.3:2)
    at f.TemplateCache.Marionette.TemplateCache.compileTemplate (common.min.js?ver=3.2.1:2)
    at f.TemplateCache.load (backbone.marionette.min.js?ver=2.4.5.e1:24)
    at Function.get (backbone.marionette.min.js?ver=2.4.5.e1:24)
    at n.getTemplate (editor.min.js?ver=3.2.1:2)
    at n._renderTemplate (backbone.marionette.min.js?ver=2.4.5.e1:25)
    at n.render (backbone.marionette.min.js?ver=2.4.5.e1:25)
    at n.renderChildView (backbone.marionette.min.js?ver=2.4.5.e1:24)
    at n._addChildView (backbone.marionette.min.js?ver=2.4.5.e1:24)

common.min.js?ver=3.2.1:2 Uncaught ReferenceError: originalEvent is not defined
    at onError (common.min.js?ver=3.2.1:2)
    at dispatch (jquery.min.js?ver=3.5.1:2)
    at v.handle (jquery.min.js?ver=3.5.1:2)

I have disactiveted all plug-in and use the safe mode! 
But the problem goes away if you use version 3.1.4....

**Comment by Vitromara** [comment]
I have the same Problem and the same workaround (3.1.4)

**Comment by AliceNatali** [comment]
Hello, I am a new member. I am building my site with Astra and Elementor (free). I have the same problem as you with the last version of Elementor 3.2.1. , I can't use the image, video and other widgets anymore.... with 3.1.4 everything is back to normal. I'm not very experienced, so I would like to ask: what happens if I don't update Elementor? Should I avoid updating it forever or should I wait before trying again?

**Comment by DorShahar** [comment]
Hi @Vitromara  and @Eliofilo ,
Could you share steps to reproduce and your system info please?
I couldn't reproduce the issue.

@AliceNatali , we encourage you to update the versions, since we are handling bugs and releasing more features. The best practice is to backup your site.

**Comment by Eliofilo** [comment]
Yes: https://drive.google.com/file/d/14A3UdFBDx7K7xvA2n2knbmelYrlufoUy/view


https://user-images.githubusercontent.com/6224066/115712375-fd87c780-a374-11eb-87e7-3af2dcf51513.mp4

**Comment by Toni-X** [comment]
I have the same problem on all websites where I updated from 3.1.4 to 3.2.1, wordpress 5.3 to 5.7

- Open any page in elementor or create a new one
- Page settings > errors in console log
- Select any section > Style tab > errors in console log

Downgrading to 3.1.4 fix it.

**Comment by shilo-ey** [comment]
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me (shilo-ey) and reference this issue.

Thanks.

**Comment by Eliofilo** [comment]
I have send mail :)

**Comment by nicoblg** [comment]
Hi, same problem here in two different wordpress installation, tried to clear browser and server cache, rollback to 3.2.0, disable plugins and switch to wordpress default theme, all without success.
Only fix seems to rollback to 3.1.4.

Console report an error on this line
`r = new Function(a.variables || "obj", "_", a)`
regarding an Unexpected Identifier.

**Comment by FrancoStino** [comment]
Same Problem

**Comment by Eliofilo** [comment]
hey give us an update !!! I also wrote to the email as suggested !!! I have 1300 blocked sites ....

**Comment by FrancoStino** [comment]
Style not working...

**Comment by nicoblg** [comment]
My suggestion is to downgrade to 3.1.4, going in settings and rolling back to that

**Comment by fleks** [comment]
Instead of downgrading you can try to change the language to English - this helped with the empty Image blocks for example.
Try switching language to English:
- Impostazioni > Generali > Lingua del sito: English (United States)
- Ajustes > Generales > Idioma del sitio: English (United States)
- Opções > Geral > Idioma do site: English (United States) 
- Einstellungen > Allgemein > Sprache der Website: English (United States)

**Comment by Eliofilo** [comment]
sorry but it's not a solution.... the problem is real! you have the video and other customers have this same problem...

**Comment by shilo-ey** [comment]
Thanks for reporting.

We will address this issue soon and release a patch.

Please follow this thread for updates.

Thanks!

**Comment by relima** [comment]
Same problem

**Comment by igelpi** [comment]
Hello guys, 
I have the same problem too, I think from a couple of days or so.
I've tried to upgrade Elementor/Elementor PRO to Version 3.2.1. but nothing changes.
I also tried to manually deactivate all the other plugins, but nothing changed as well.
Only switching to "English" language seems to solve the problem, but of course it is not desirable as the base language of the website is different.
Please let me know should you need any other additional information that may be of help.

Best Regards

IG

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.2.2

Feel free to update

Thanks!

**Comment by Eliofilo** [comment]
ok it's solved thanks a lot!

**Comment by igelpi** [comment]
OK,
 I confirm issue has been solved on my side after upgrading to v3.2.2.

Thanks for the support and quick resolution!

**Comment by marekmaurizio** [comment]
6 days to solve this for paid users is not quick. Whatever.

**Comment by mguillou56** [comment]
I still have a problem with JS not working on my website.

For instance the links for this gallery don't work. I also couldn't implement MegaMenu extensions.

Can you help me please ?

https://polesante-kervignac.fr/#gallerylinks

Thanks and best regards.
