### ISSUE TITLE
Deprecated: Elementor\Scheme_Typography is deprecated

### ISSUE THREAD

**Issue by riadnassour** [elementor/elementor#14656]
Deprecated: Elementor\Scheme_Typography is deprecated since version 2.8.0! Use Elementor\Core\Schemes\Typography instead.

After updating Elementor to Version 3.2.1 this message showed in the Home page as I'm enabling debug mode.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

**Comment by Echantris** [comment]
We have more then 40 Sites running for our clients on elementor.
So far i have this issue on 1 site after updating now.

Any updates?

**Comment by starkapandan** [comment]
same here + "PHP Deprecated: Elementor\Scheme_Color...."

**Comment by CBFackh** [comment]
+1
When searching for the error, I see a ton of pages having the same issue.

**Comment by Echantris** [comment]
Actually i fixed it.. but dont know exactly what in the steps i did solved this:

- first I deactivated the plugins
- then i roll back the version to 3.2 (for pro and element)
- after this i deleted the pro plugin and reinstalled it
- also i had elementor essentials extra pluin installed and deactivated this (since i dont use any features of t)

since i have caching plugin I deleted the cache and the cache in NGINX server.

Fixed

**Comment by DorShahar** [comment]
Hi 
It might be that the "elementor essentials extra" is used the deprecated method and therefore the error been presented.

For the other users with this issue - please deactivate Elementor Addons first in order to understand if the problem is not on our end.  If this is the case - this will help us to communicate to the Addons about the problem.


Many thanks.

**Comment by treant-prime** [comment]
Disabling 3rd party components 'solved' this.
**Essential Addons Plugin:**
- Flip Box
- Table of Contents

**Happy Addon Plugin:**
- Flip Box
- Team member
- Post List
- Card

Components was disabled via plugin settings.
Yet, my problem persists: i've lost content form my site since it was based around those components. Rollbacking to earlier elementor plugin version didn't help. Is my database corrupted by this new update?

**Comment by riadnassour** [comment]
> Disabling 3rd party components 'solved' this.
> **Essential Addons Plugin:**
> 
> * Flip Box
> * Table of Contents
> 
> **Happy Addon Plugin:**
> 
> * Flip Box
> * Team member
> * Post List
> * Card
> 
> Components were disabled via plugin settings.
> Yet, my problem persists: i've lost content form my site since it was based around those components. Rollbacking to earlier elementor plugin version didn't help. Is my database corrupted by this new update?

Thank you!

when disabled these Essential Addons Plugin extensions:

Flip Box
Table of Contents

the issue has been solved.

**Comment by shilo-ey** [comment]
Hey everyone, thank you for your report.

We have a detailed deprecations list we manage and update every version.

We recommend you to contact the plugin author (and we will do so as well) and ask them to make their addon compliant with the latest version of Elementor.

Thanks
