### ISSUE TITLE
Impossible to remove eicons

### ISSUE THREAD

**Issue by astbarc** [elementor/elementor#14712]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

The following code to remove the eicons included in this [page](https://elementor.com/help/speed-up-a-slow-site/)  isn't working in the lastest version of elementor (3.22) 

```
add_action( 'wp_enqueue_scripts', 'remove_default_stylesheet', 20 ); 
function remove_default_stylesheet() { 
	wp_deregister_style( 'elementor-icons' ); 
}
```
I thinks this is caused by these css styles that are now included in the last version.  The font is loading via css font-face

```
@font-face {
  font-family: 'eicons';
  src: url("../lib/eicons/fonts/eicons.eot?5.10.0");
  src: url("../lib/eicons/fonts/eicons.eot?5.10.0#iefix") format("embedded-opentype"), url("../lib/eicons/fonts/eicons.woff2?5.10.0") format("woff2"), url("../lib/eicons/fonts/eicons.woff?5.10.0") format("woff"), url("../lib/eicons/fonts/eicons.ttf?5.10.0") format("truetype"), url("../lib/eicons/fonts/eicons.svg?5.10.0#eicon") format("svg");
  font-weight: normal;
  font-style: normal; }
```

**Comment by Rushdiey** [comment]
This problem occur to me also.

**Comment by shilo-ey** [comment]
Thank you for reporting.

We will examine the issue and update here with an update.

**Comment by mehedihasanziku** [comment]
This is an clear mistake, it's forcefully added in 

**"frontend.min.css"**

`https://plugins.trac.wordpress.org/browser/elementor/tags/3.2.2/assets/css/frontend.min.css`

search keyword:  **"eicons.woff"**

**Comment by shaneonabike** [comment]
Same problem for me. In my case I found them in the custom-frontend.min.css file. I really want to unload these so they aren't downloaded and just stick to font-awesome thanks!

**Comment by pako69** [comment]
+1

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.2.3

Feel free to update

Thanks!

**Comment by Zetanova** [comment]
with elementor css perf options enabled, elementor will include the font-face in `<style id="elementor-frontend-inline-css">` block

**Comment by Tygovanommen** [comment]
> with elementor css perf options enabled, elementor will include the font-face in `<style id="elementor-frontend-inline-css">` block

For me the font is included without this enabled

**Comment by EXECdesign** [comment]
Same here - and even with EP 3.5.1 it's still the same situation as it was before:
https://github.com/elementor/elementor/pull/15014#issuecomment-931368087

**Comment by rotemee** [comment]
@Tygovanommen @Zetanova @EXECdesign Thank you for your comments:

1. The inline-CSS will be removed.
2. In order to prevent the loading of the e-icons assets (font + CSS file) you can use the new experiment called "Inline Font Icons" (Admin >> Elementor >> Settings >> Experiments), which will render the e-icons as SVG tags without loading the font+ CSS files.

A little bit more info regarding the e-icons assets loading:

A few months ago we've made a change with how the e-icons CSS file is loaded, we've moved the external file content (elementor-icons.css) into the frontend.css file in order to save an additional request to an external file, and therefore, the elementor-icons.css file was not loaded by default.

**Recently we've made an additional change**, in order to take it one step further (in terms of performance), icons that are using the e-icons library can be loaded as SVG tags without the need for the font or CSS files.
**But,** in order to get this performance boost you need to activate the "Inline Font Icons" experiment (which will also make the Font-Awesome icons to be loaded as SVG tags).

In order to support users that still want to use the e-icons library (font + CSS file) we've restored the loading method of the elementor-icons.css file, to be loaded as an external file (and not part of the frontend.css file) so that it would be easier
to dequeue it if needed.

If you have any more questions please let me know.

Thanks.

**Comment by Tygovanommen** [comment]
> @Tygovanommen @Zetanova @EXECdesign Thank you for your comments:
> 
> 1. The inline-CSS will be removed.
> 2. In order to prevent the loading of the e-icons assets (font + CSS file) you can use the new experiment called "Inline Font Icons" (Admin >> Elementor >> Settings >> Experiments), which will render the e-icons as SVG tags without loading the font+ CSS files.
> 
> A little bit more info regarding the e-icons assets loading:
> 
> A few months ago we've made a change with how the e-icons CSS file is loaded, we've moved the external file content (elementor-icons.css) into the frontend.css file in order to save an additional request to an external file, and therefore, the elementor-icons.css file was not loaded by default.
> 
> **Recently we've made an additional change**, in order to take it one step further (in terms of performance), icons that are using the e-icons library can be loaded as SVG tags without the need for the font or CSS files. **But,** in order to get this performance boost you need to activate the "Inline Font Icons" experiment (which will also make the Font-Awesome icons to be loaded as SVG tags).
> 
> In order to support users that still want to use the e-icons library (font + CSS file) we've restored the loading method of the elementor-icons.css file, to be loaded as an external file (and not part of the frontend.css file) so that it would be easier to dequeue it if needed.
> 
> If you have any more questions please let me know.
> 
> Thanks.

After enabling the experiment and adding the snippet to remove eicons it is still included inline.

**Comment by sabrina-zeidan** [comment]
Same for me, FA is gone, but eicons is loaded as usual. The feature is called called "Font-Awesome Inline" not "Inline Font Icon" asyou mentioned @rotemee 
I'm at Elementor 3.4.8 and Elementor PRO 3.3.6 which are the latest for now.  Is there anything that I miss? Or it's just upcoming update for now?

**Comment by EXECdesign** [comment]
> @Tygovanommen @Zetanova @EXECdesign Thank you for your comments:
> 
>     1. The inline-CSS will be removed.
> 
>     2. In order to prevent the loading of the e-icons assets (font + CSS file) you can use the new experiment called "Inline Font Icons" (Admin >> Elementor >> Settings >> Experiments), which will render the e-icons as SVG tags without loading the font+ CSS files.
> 
> 
> A little bit more info regarding the e-icons assets loading:
> 
> A few months ago we've made a change with how the e-icons CSS file is loaded, we've moved the external file content (elementor-icons.css) into the frontend.css file in order to save an additional request to an external file, and therefore, the elementor-icons.css file was not loaded by default.
> 
> **Recently we've made an additional change**, in order to take it one step further (in terms of performance), icons that are using the e-icons library can be loaded as SVG tags without the need for the font or CSS files. **But,** in order to get this performance boost you need to activate the "Inline Font Icons" experiment (which will also make the Font-Awesome icons to be loaded as SVG tags).
> 
> In order to support users that still want to use the e-icons library (font + CSS file) we've restored the loading method of the elementor-icons.css file, to be loaded as an external file (and not part of the frontend.css file) so that it would be easier to dequeue it if needed.
> 
> If you have any more questions please let me know.
> 
> Thanks.

Same here: All sites with "Font-Awesome Inline" ACTIVE still have Eicons font. Also tested logged out state in different browser to ensure the state of a 3rd party viewer.

@rotemee so it seems all you wrote is just not correct (would be great if it would be!).

**Comment by rotemee** [comment]
@Tygovanommen @sabrina-zeidan @EXECdesign 
Everything that I wrote relates to version 3.5.0 (I've updated bullet number 1 on my previous comment), including the experiment name that will be changed from "Font-Awesome Inline" to "Inline Font Icons".

**Comment by JMMCoding** [comment]
> > @Tygovanommen @Zetanova @EXECdesign Thank you for your comments:
> > 
> > 1. The inline-CSS will be removed.
> > 2. In order to prevent the loading of the e-icons assets (font + CSS file) you can use the new experiment called "Inline Font Icons" (Admin >> Elementor >> Settings >> Experiments), which will render the e-icons as SVG tags without loading the font+ CSS files.
> > 
> > A little bit more info regarding the e-icons assets loading:
> > A few months ago we've made a change with how the e-icons CSS file is loaded, we've moved the external file content (elementor-icons.css) into the frontend.css file in order to save an additional request to an external file, and therefore, the elementor-icons.css file was not loaded by default.
> > **Recently we've made an additional change**, in order to take it one step further (in terms of performance), icons that are using the e-icons library can be loaded as SVG tags without the need for the font or CSS files. **But,** in order to get this performance boost you need to activate the "Inline Font Icons" experiment (which will also make the Font-Awesome icons to be loaded as SVG tags).
> > In order to support users that still want to use the e-icons library (font + CSS file) we've restored the loading method of the elementor-icons.css file, to be loaded as an external file (and not part of the frontend.css file) so that it would be easier to dequeue it if needed.
> > If you have any more questions please let me know.
> > Thanks.
> 
> After enabling the experiment and adding the snippet to remove eicons it is still included inline.

Could you advise on what code snippet you tried to remove the eicons? I'm also having this issue and struggling to remove them and I'd like to try all avenues - thank you!

**Comment by Tygovanommen** [comment]
> @Tygovanommen @sabrina-zeidan @EXECdesign Everything that I wrote relates to version 3.5.0 (I've updated my previous comment to be more accurate), including the experiment name that will be changed from "Font-Awesome Inline" to "Inline Font Icons".

After changing the options you suggest in the updated comment I'm still seeing the fonts inline.

**Comment by rotemee** [comment]
@Tygovanommen Can you please share a link to a page where this happens?

**Comment by wpinfusion** [comment]
With Inline Fonts set to Inactive in the experiments section, I still can't dequeue `elementor-icons`

**Comment by f3bruary** [comment]
With Inline Fonts set to Inactive in the experiments section, I still can't dequeue `elementor-icons`

**Comment by dkiryakov** [comment]
Anyone else still having this issue? I'm still experiencing it despite having "Inline Font Icons" feature active.

**Comment by dkiryakov** [comment]
@rotemee you can check the above on donutmachines dot com (want to avoid robots here)
