### ISSUE TITLE
Cant use WooCommerce product description as dynamic data

### ISSUE THREAD

**Issue by BrockwayProd** [elementor/elementor#16367]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

It is currently impossible to use the product full description as dynamic data (not the short one, the normal one).
We should be able to use any data from the product.

## Steps to reproduce

No step to reproduce, as it's just missing for some weird reason

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.16.1
	MySQL version: Percona Server (GPL), Release '13', Revision '6f7822f' v8.0.22-13
	PHP Version: 7.4.18
	PHP Max Input Vars: 10000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.8.1
	Site URL: https://www.lessavoyards.fr
	Home URL: https://www.lessavoyards.fr
	WP Multisite: No
	Max Upload Size: 512 Mo
	Memory limit: 4512M
	Permalink Structure: /%postname%/
	Language: fr-FR
	Timezone: Europe/Paris
	Debug Mode: Inactive

== Theme ==
	Name: Kadence
	Version: 1.1.4
	Author: Kadence WP
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 5.10.2
		Author: Delicious Brains

	Advanced Order Export For WooCommerce (Pro)
		Version: 3.1.9
		Author: AlgolPlus

	AeroCheckout: Custom WooCommerce Checkout Pages
		Version: 2.8.1
		Author: WooFunnels

	Antispam Bee
		Version: 2.10.0
		Author: pluginkollektiv

	ATUM Export Pro
		Version: 1.3.5
		Author: Stock Management Labs™

	ATUM Inventory Management for WooCommerce
		Version: 1.9.4
		Author: Stock Management Labs™

	ATUM Product Levels
		Version: 1.6.2
		Author: Stock Management Labs™

	Autonami Marketing Automations Connectors
		Version: 2.0.3
		Author: WooFunnels

	Autonami Marketing Automations For WordPress
		Version: 2.0.6
		Author: BuildWooFunnels

	Autonami Marketing Automations Pro
		Version: 2.0.4
		Author: WooFunnels

	Carousel Upsells and Related Product for Woocommerce
		Version: 0.4.5
		Author: Dan Zakirov

	CartPops Pro
		Version: 1.4.7
		Author: CartPops.com

	Code Snippets
		Version: 2.14.2
		Author: Code Snippets Pro

	Convert Pro
		Version: 1.7.3
		Author: Brainstorm Force

	Cost of Goods by PixelYourSite
		Version: 1.0.10
		Author: PixelYourSite

	Coupon Import Export for WooCommerce Add-on
		Version: 1.0.2
		Author: Webtoffee

	Elementor
		Version: 3.4.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.4.1
		Author: Elementor.com

	ELEX Bulk Edit Products, Prices & Attributes for Woocommerce
		Version: 2.6.1
		Author: ELEX

	FiboSearch - AJAX Search for WooCommerce
		Version: 1.13.0
		Author: FiboSearch Team

	Flexible Shipping
		Version: 4.8.1
		Author: WP Desk

	Google Tag Manager for Wordpress
		Version: 1.13.1
		Author: Thomas Geiger

	GridPane Redis Object Cache
		Version: 1.5.6
		Author: Version Forked by GridPane | Till Krüss

	Gumlet
		Version: 1.2.3
		Author: Gumlet

	Import Export for WooCommerce Wrapper
		Version: 1.0.4
		Author: Webtoffee

	Loco Translate
		Version: 2.5.3
		Author: Tim Whitlock

	ManageWP - Worker
		Version: 4.9.10
		Author: GoDaddy

	Nginx Helper
		Version: 2.2.2
		Author: rtCamp

	OrderBumps: WooCommerce Checkout Offers
		Version: 1.11.0
		Author: WooFunnels

	Order Import Export for WooCommerce Add-on
		Version: 1.0.2
		Author: Webtoffee

	PixelYourSite PRO
		Version: 8.4.1
		Author: PixelYourSite

	Product Catalog Feed Pro by PixelYourSite
		Version: 5.1.2
		Author: PixelYourSite

	Product Import Export for WooCommerce Add-on
		Version: 1.0.3
		Author: Webtoffee

	Redirection
		Version: 5.1.3
		Author: John Godley

	Sendcloud | Smart Shipping Service
		Version: 2.0.3
		Author: Sendcloud B.V.

	User Import Export for WooCommerce Add-on
		Version: 1.0.4
		Author: Webtoffee

	WooCommerce
		Version: 5.6.0
		Author: Automattic

	Woocommerce - Guaranteed Reviews Company
		Version: 1.2.2
		Author: Guaranteed Reviews Company

	WooCommerce Attribute Swatches by Iconic
		Version: 1.3.4
		Author: Iconic <support@iconicwp.com>

	WooCommerce PayPal Checkout Gateway
		Version: 2.1.3
		Author: WooCommerce

	WooCommerce PDF Invoices & Packing Slips
		Version: 2.9.3
		Author: Ewout Fernhout

	WooCommerce PDF Invoices & Packing Slips Professional
		Version: 2.6.4
		Author: Ewout Fernhout

	WooCommerce Stripe Gateway
		Version: 5.5.0
		Author: WooCommerce

	Woo Discount Rules
		Version: 2.3.8
		Author: Flycart

	Woo Discount Rules PRO 2.0
		Version: 2.3.8
		Author: Flycart

	WooFunnels Funnel Builder
		Version: 1.7.1
		Author: BuildWooFunnels

	WooFunnels Funnel Builder Pro
		Version: 1.11.2
		Author: BuildWooFunnels

	WP-Sweep
		Version: 1.1.5
		Author: Lester 'GaMerZ' Chan

	WP Grid Builder
		Version: 1.5.9
		Author: Loïc Blascos

	WP Grid Builder - Elementor
		Version: 1.0.5
		Author: Loïc Blascos

	WP Mail SMTP
		Version: 3.0.3
		Author: WPForms

	YITH WooCommerce Barcodes Premium
		Version: 2.1.0
		Author: YITH

	Yoast SEO
		Version: 17.1
		Author: Team Yoast


== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 
		Author: GoDaddy

	WP CLI Login Command Server
		Version: 1.2
		Author: Evan Mattson


== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibilité non spécifiée
	WP Grid Builder - Elementor: Compatibilité non spécifiée

== Elementor Pro - Compatibility Tag ==
	


== Elements Usage ==
	
	footer : 1
		form : 1
		heading : 3
		icon-list : 3
		image-box : 4
		social-icons : 1
	header : 1
		heading : 1
		icon-list : 2
		nav-menu : 2
		theme-site-logo : 1
		wp-widget-dgwt_wcas_ajax_search : 1
	product : 1
		accordion : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-images : 1
		woocommerce-product-price : 1
		woocommerce-product-related : 1
		woocommerce-product-short-description : 1
		woocommerce-product-title : 1
	wp-page : 1
		button : 5
		heading : 8
		image : 4
		text-editor : 1
		wpgb-grid : 1
	product-archive : 1
		text-editor : 1
		theme-archive-title : 1
		wpgb-grid : 1


== Log ==
	
PHP: showing 5 of 5PHP: 2021-08-17 18:30:30 [notice X 12][/var/www/lessavoyards.fr/htdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-08-24 16:41:42 [notice X 1][/var/www/lessavoyards.fr/htdocs/wp-content/plugins/elementor-pro/license/updater.php::83] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-09-15 13:16:12 [notice X 2][/var/www/lessavoyards.fr/htdocs/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-09-20 14:24:44 [notice X 2][/var/www/lessavoyards.fr/htdocs/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::40] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-09-20 14:49:49 [error X 1][/var/www/lessavoyards.fr/htdocs/wp-content/plugins/elementor/core/documents-manager.php::527] Uncaught Error: Call to a member function get_post() on bool in /var/www/lessavoyards.fr/htdocs/wp-content/plugins/elementor/core/documents-manager.php:527
Stack trace:
#0 [internal function]: Elementor\Core\Documents_Manager->ajax_save()
#1 /var/www/lessavoyards.fr/htdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#2 /var/www/lessavoyards.fr/htdocs/wp-includes/class-wp-hook.php(303): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#3 /var/www/lessavoyards.fr/htdocs/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#4 /var/www/lessavoyards.fr/htdocs/wp-includes/plugin.php(470): WP_Hook->do_action()
#5 /var/www/lessavoyards.fr/htdocs/wp-admin/admin-ajax.php(187): do_action()
#6 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 20 of 212021-08-18 23:08:44 [info] elementor::elementor_updater Started 
2021-08-18 23:08:44 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-18 23:08:44 [info] Elementor/Upgrades - _on_each_version Finished 
2021-08-18 23:08:44 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.0',
  'to' => '3.4.1',
)]
2021-08-24 03:06:28 [info] elementor::elementor_updater Started 
2021-08-24 03:06:28 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-24 03:06:28 [info] Elementor/Upgrades - _on_each_version Finished 
2021-08-24 03:06:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.1',
  'to' => '3.4.2',
)]
2021-08-24 16:41:53 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.7',
  'to' => '3.3.8',
)]
2021-08-30 14:19:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.2',
  'to' => '3.4.3',
)]
2021-08-30 14:19:16 [info] elementor::elementor_updater Started 
2021-08-30 14:19:16 [info] Elementor/Upgrades - _on_each_version Start  
2021-08-30 14:19:16 [info] Elementor/Upgrades - _on_each_version Finished 
2021-08-30 14:19:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.2',
  'to' => '3.4.3',
)]
2021-08-30 14:19:16 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.2',
  'to' => '3.4.3',
)]
2021-09-01 19:50:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.3.8',
  'to' => '3.4.1',
)]
2021-09-15 10:21:11 [info] elementor::elementor_updater Started 
2021-09-15 10:21:11 [info] Elementor/Upgrades - _on_each_version Start  
2021-09-15 10:21:11 [info] Elementor/Upgrades - _on_each_version Finished 
2021-09-15 10:21:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.4.3',
  'to' => '3.4.4',
)]
```
</details>

**Comment by Asored-D** [comment]
+1 We very need this.. :-)

**Comment by avivu** [comment]
Hello,
This issue has been resolved in Elementor Pro v3.7.0

Feel free to update

Thanks!

**Comment by szsbay** [comment]
Hello,
now there ist a product description, but the code has been cleaned up, all paragraphs and lists have been removed. How can I get a raw format?

**Comment by stijns96** [comment]
Same problem here... Customer complained about why he has to add <br> in his visual text short description editor in a product. If we don't do this, it will only output spaces instead of breaks. Shame this still doesn't work...

**Comment by tonyparker2000** [comment]
If this has been resolved why cant I se it in version 3.10?
![image](https://user-images.githubusercontent.com/54977666/221841576-a0c866c8-a318-4bbe-81ae-46d526bf1914.png)

**Comment by phkoon** [comment]
There's a problem: it now is available, but neither Product Description nor Product Short Description preserve their formatting when assigned as dynamic tags.

Is this still going to be addressed?

**Comment by Kunnaalsoni** [comment]
Still facing this issue, on the product page, dynamic product description is fetching me description but it is random, we get randomised product description,

**Comment by phkoon** [comment]
@shilo-ey @avivu 

Please, take a look at this issue again
