### ISSUE TITLE
Slideshow doesn't transition between slides gracefully

### ISSUE THREAD

**Issue by kadoogan55** [elementor/elementor#1671]
The slideshow doesn't transition well between slides. Issues noted as follows:

- No settings for transitioning between slides
- Existing default transitions between slides are very abrupt and only work on the images
- Text does not transition in slides, but simply disappears
- Ken Burns effect works great until transitioning between slides. For a split second the image goes back to regular size after zooming in, then very abruptly transitions to next slide.

I have noticed these issues overall with any slider added via Elementor.

I would consider the slider feature to be about 90% complete at this point until those problems are resolved. Surprised it was released in this state, to be honest.

**Comment by joshmarom** [comment]
Hi @kadoogan55.
Could you please clarify some of the points you brought up?

> No settings for transitioning between slides
What kind of settings would you expect to have?

> Existing default transitions between slides are very abrupt and only work on the images
What would be the ideal transition in your opinion?

Thanks for your feedback.

**Comment by mjflower** [comment]
I agree. I see exactly the same issue. It.jumps as if it reverts each slide to its original position before if transitions to the next.

**Comment by kadoogan55** [comment]
Hi there - sorry, I have been busy for a few days. I have noticed since then that Chrome seems to do the abrupt changes and such, but Firefox does it slightly better - so it may be some problem between Chrome and Elementor.

Overall, my suggestion would be to check out most popular slideshow plugins to see what one might expect (not just me)...

But, to be more thorough:

Could you please clarify some of the points you brought up?

No settings for transitioning between slides
>>> What kind of settings would you expect to have?
- Most sliders allow a setting for actual transition time, and not only the time the slide remains onscreen. - Also, many sliders allow you to pick a different transition on a slide by slide basis, and not just an overall transition setting for the whole slideshow (many will have the overall default transition setting as well, but allow you to set individual transitions per slide as well.
- Most sliders transition out with the same transition they came in with, but in reverse (Slight in from the left - slide out to the left)
There are likely more examples, but I hope you get the idea...

Existing default transitions between slides are very abrupt and only work on the images
>>> What would be the ideal transition in your opinion?
- Well, not just my opinion, but rather what many users would expect from the average slider...
- Control over the transition time would be a great start
- Control over the transition type between slides
- Text transitioning properly - not just disappearing, but rather fading, sliding or zooming out (as I mentioned earlier in this particular message, there may be an issue with Elementor sliders and Chrome and that may be a result of that).

That's it.  :)

**Comment by riverharbor** [comment]
Same problem here. Safari and Firefox work fine.  However Slides using Ken Burns effect on Chrome do not transition correctly as noted above. 

Settings: 

<img width="284" alt="Screen Shot 2019-04-18 at 6 22 32 PM" src="https://user-images.githubusercontent.com/5295486/56395009-fd451680-6206-11e9-88ce-85aa90893197.png">

**Comment by normundslauva** [comment]
Same for me. Client asks to fix this but only thing I can do currently is disable Ken Burns effect

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.7

Feel free to update

Thanks!

**Comment by amyriounis** [comment]
@shilo-ey 
I believe this issue isn't fully addressed in v2.7.

I still experience a similar problem like the 4rth point 
> Ken Burns effect works great until transitioning between slides. For a split second the image goes back to regular size after zooming in, then very abruptly transitions to next slide.

To recreate:
 - On a section's Background (style tab) add a slideshow with 2 pics.
 - Set infinite loop to "Yes"
 - Set transition to "Fade"
 - Set Ken Burns effect to "Yes"

The first time the whole slideshow runs, it works ok. After that, the issue I quoted above starts happening. 

Elementor v2.9.8
Elementor Pro v2.9.3.

**Comment by boutzamat** [comment]
This is definately not resolved at all. I'm still experiencing the same. And as usual, the support requests gets ignored just like the above comment 2 years ago saying that it is not resolved.

**Comment by digitalpasskey** [comment]
Likewise, same issue for me with the Ken Burns effect jumping back to original size for a split second before transitioning to the next slide. Weirdly though, it only happens between the 1st and second slide, and only after the slide show has completed the first round and is repeating.

**Comment by nebelung** [comment]
Just in case someone will pay attention to this...???...the issue with the Fade not working properly with the Ken Burns effect still remains. It would be lovely if we can get this addressed. Thanks.

**Comment by Seleneca** [comment]
I am not experiencing the same problems above, but I have a problem with the _Elementor Slides_ widget and the _Elementor Image Carousell_ Widget because the FADE transition causes each slide to fade in _and_ to fade out.  I'd rather each image just fade in. And the next slide should fade into the that preceeded it.   I am comparing illustrated models where many objects stay visible in both views, so when the first image fades out, it causes a visual flash or pulse as the second image fades in.  I'm having to use a plug-in slide program because that one fades in, but does not fade out each slide.  To replicate my issue, simply load two of the exact same images into the Elementor Slides widget and set the transition to fade, and you will see the "pulse."   The splash page of my site, uses this technique to have lights on towers flash on an off without having to make a video.  httpsSeleneca.city](https://seleneca.city

**Comment by hybridmuse** [comment]
>  For a split second the image goes back to regular size after zooming in, then very abruptly transitions to next slide.

Same here, the bug happens after a full cycle, between the last and first image.

It's a shame this has never been fixed in over 6 years.
Unfortunately, such buggy behavior can't be shipped on production sites.

@shilo-ey would you explain why this was closed in 2019?

This was also reported (and ignored) in issue #1370

**Comment by mstudioIL** [comment]
It still don't wrok

**Comment by boutzamat** [comment]
This (like most other issues) is being ignored. Unsubbing.

**Comment by projectpi-ca** [comment]
> This issue has been resolved in Elementor Pro v2.7
> 
> Feel free to update
> 
> Thanks!

Running Elementor 3.27.6  and Elementort Pro 3.27.4. It is definitely not fixed.
