### ISSUE TITLE
[DEV 3.6] Now that we have the Container, Section-Wrap Needs to Go

### ISSUE THREAD

**Issue by zeinnicholas** [elementor/elementor#16950]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
In the spirit of optimizing the code, this would be a great time to completely remove the `.elementor-section-wrap` div from anywhere, either by adding it to the "Optimized DOM Output" experiment or by adding a new experiment for us to choose if we want yet another DOM depth. It doesn't do any difference since we already wrap everything under the `.elementor` tag.

**Describe the solution you'd like**
I would like to remove the `.elementor-section-wrap` div tag from the DOM when activating the "Optimized DOM Output" experiment just like you already do with the `.elementor-inner` div. Just change the lines `985` to `993` from `core/base/document.php` and replace them with this:

````
(...)
<?php if ( ! $is_dom_optimization_active ) { ?>
<div class="elementor-inner">
    <div class="elementor-section-wrap">
        <?php $this->print_elements( $elements_data ); ?>
    </div>
</div>
<?php } ?>
(...)
````

**Describe alternatives you've considered**
There are two alternatives I considered.

***1. Adding a new Experiment***
Include the "Remove Section Wrap" experiment turned off by default with all the disclaimers you'd like then apply the following changes to the lines from `982` to `993` like above:
````
(...)
$is_dom_optimization_active = Plugin::$instance->experiments->is_feature_active( 'e_dom_optimization' );
$is_section_wrap_removal_active = Plugin::$instance->experiments->is_feature_active( 'e_section_wrap_removal' );
?>
<div <?php Utils::print_html_attributes( $this->get_container_attributes() ); ?>>
	<?php if ( ! $is_dom_optimization_active ) { ?>
	<div class="elementor-inner">
	<?php } ?>
                <?php if ( ! $is_section_wrap_removal_active ) { ?>
		<div class="elementor-section-wrap">
                <?php } ?>
			<?php $this->print_elements( $elements_data ); ?>
                <?php if ( ! $is_section_wrap_removal_active ) { ?>
		</div>
                <?php } ?>
	<?php if ( ! $is_dom_optimization_active ) { ?>
	</div>
	<?php } ?>
(...)
````
... with the accompanying changes to everything else, including adding the experiment options, and making the necessary changes to `editor.js`.

***2. Adding a PHP Filter*** 
for the frontend output of the tag so more advanced users can decide if they want the `.elementor-section-wrap` or not. A simple `apply_filters` would suffice.

**Additional context**
I see no benefit of having such a tag added to the DOM except for internal purposes that can be easily adapted.

**Comment by paauserrat** [comment]
Also, add auto to overflow!

**Comment by arielk** [comment]
It's completely on our roadmap, and we'll remove it in one of the following versions

**Comment by zeinnicholas** [comment]
> It's completely on our roadmap, and we'll remove it in one of the following versions

That's awesome news @arielk! 

Thanks for letting us know! I'm looking forward to have a leaner DOM! =)

**Comment by avivu** [comment]
Hello,
This issue has been resolved in Elementor Pro v3.6.6

Feel free to update

Thanks!

**Comment by zeinnicholas** [comment]
Thank you @avivu! That's awesome! =)

**Comment by shilo-ey** [comment]
This issue was also handled in Elementor v3.6.0

Feel free to update

Thanks!

**Comment by Mohsen-Khakbiz** [comment]
hey everyone
is there any reason `.elementor-section-wrap` still exists in the editor?
it's causing problems where we're targeting elements in css or js
