### ISSUE TITLE
🐞 Bug in Accordion and toggle widget - pro 3.6 (By opening the toggle and accordion, the screen scrolls down.)

### ISSUE THREAD

**Issue by 79ho3ein** [elementor/elementor#17821]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After updating elementor pro, the page moves automatically when the Accordion and toggle open. Please watch the video below. The screen moves every time I open the toggle.
**This error occurs if we create a header in the theme builder and stick it at the top.**

https://user-images.githubusercontent.com/77163248/153746414-11c33cf5-d2a9-4637-97a0-45736e6ff760.mp4

### Steps to reproduce

1- Create a header in elementor theme builder.
2- Stick it on top : https://prnt.sc/26vitri
3- Save the header and set its display conditions to entire site.
4- Create a page and add a toggle widget.
5- Then follow the video above and open the toggle. You will see that there is a bug.
6- Go back to the header and disable the Sticky top option. The bug will be fixed.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

elementor
elementor pro
wordpress
hello elementor 

is update.

**Comment by rami-elementor** [comment]
@79ho3ein 

* what version of Elementor & Elementor Pro are you using?
* we need the full system info.

**Comment by 79ho3ein** [comment]
hello @rami-elementor 

I examined this problem and found out exactly what the problem was. The problem is with the new version of elementor pro.
This error occurs if we create a header in the theme builder and stick it at the top. **So to reproduce this bug, please follow the steps below :**
1- Create a header in elementor theme builder.
2- Stick it on top : https://prnt.sc/26vitri
3- Save the header and set its display conditions to entire site.
4- Create a page and add a toggle widget.
5- Then follow the video above and open the toggle. You will see that there is a bug.
6- Go back to the header and disable the Sticky top option. The bug will be fixed.

In fact, this bug occurs in stage 2. This bug is present in the new version of elementor pro. Also, unfortunately, this bug has caused similar interference in other plugins. For example, the variable selection section of the jet woobuilder plugin is also affected by this elementor pro bug. I hope this bug is fixed so we can use the new version of elementor pro.

**details :** 

elemntor : 3.5.5
elementor pro 3.6.1
hello elementor : 2.5.0
wordpress : 5.9

**Comment by Trinto610** [comment]
facing the same issue.... Hope they fix it soon....

**Comment by Michaelgimii** [comment]
I have this problem too

**Comment by Michaelgimii** [comment]
Please fix this problem. Despite this bug I can not migrate to 3.6. Certainly many users have this problem.

**Comment by alisadrona** [comment]
+1

**Comment by andriussok** [comment]
Please check my response to sticky header issue fix here:
[https://github.com/elementor/elementor/issues/17839#issuecomment-1041925736](url)

**Comment by 79ho3ein** [comment]
> Please check my response to sticky header issue fix here: [https://github.com/elementor/elementor/issues/17839#issuecomment-1041925736](url)

Hi, There is nothing to see...

**Comment by andriussok** [comment]
@79ho3ein the URL href was incorrect in my comment, comment edited.

**Comment by projoomexperts** [comment]
Same issue here. Have sticky header. clicking on the tab  makes the page scroll down.

**Comment by Michaelgimii** [comment]
Are developers aware of this?

**Comment by Michaelgimii** [comment]
excuse me @shilo-ey , Are you aware of this bug?

**Comment by Trinto610** [comment]
This issue has not been solved in new elemetor pro 3.6.3 update @shilo-ey , please fix this bug...

**Comment by 79ho3ein** [comment]
Still in 3.5.2 ...

**Comment by shilo-ey** [comment]
Hey all,

This issue will be fixed in both Elementor v3.6.0 and Elementor Pro v3.6.4

Thanks for reporting

**Comment by 79ho3ein** [comment]
thank you @shilo-ey

**Comment by msd-ld** [comment]
Still not fixed with Elementor Pro v3.6.4

This seems to occur on Firefox and Chrome and not Safari. It also affects the Tab widget as well as the Accordion and Toggle widgets as well.

To test you must add one of these widgets further down a page of content so that the page has somewhere to scroll to.

**Comment by ellainegab** [comment]
This issue is occurring on my end as well that I'm handling. So when opening the horizontal tabs the screen scrolls down as well. Do we have a solution for this?

WordPress Version 5.9.2
Elementor Version 3.5.6
Elementor Pro Version 3.6.4

**Comment by 79ho3ein** [comment]
@ellainegab 

This bug will be fixed by updating elementor to version 3.6. If the time is not extended, version 3.6 will be released in 3 days.

**Comment by ellainegab** [comment]
@79ho3ein thanks for the info

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.6.0

Feel free to update

Thanks!

**Comment by 79ho3ein** [comment]
thank you @shilo-ey

**Comment by Csaba01** [comment]
Thanks shilo-ey.

**Comment by 79ho3ein** [comment]
Oh, I'm still experiencing this jump on mobile! This time the jump does not occur due to the opening of a fever or an accordion, but due to scrolling on the screen. (But the accordion widget is on the page and the header is sticky at the top)
@shilo-ey , If you did not succeed in reproducing this bug, please let me know so that I can find out more about this bug.

**Comment by mahmood** [comment]
still not fixed issue on elementor 3.10.2

**Comment by neuralive2023** [comment]
This issue is not fixed in version 3.10.2

**Comment by nicholaszein** [comment]
Hi @mahmood and @neuralive2023,

I've tested this issue again using the latest versions of Elementor and Elementor Pro (3.11.1). I couldn't reproduce it using both the container and section, as seen in the videos below.

### _Containers_

https://user-images.githubusercontent.com/113993460/220467903-7f0c187b-8a14-4aba-9d3b-55cc9465b0e0.mp4

### _Sections_

https://user-images.githubusercontent.com/113993460/220467928-45cbe79e-87c0-44dc-add4-fec5527d7f66.mp4



----
Please update to the latest version if you haven't already, and clear your cache (this is very important). It's also important to ensure you are not modifying how Elementor scripts are loaded in any way, including if you're using any performance optimization solution as minify and combining both JS and CSS. We need to isolate the issue as much as possible to find the possible bug or conflict.

If after updating both versions of Elementor and Elementor Pro you still experience the same issue, please open a new Bug Report and follow the instructions in the report form so we can verify the root of your issues.

Thanks 🙏
