### ISSUE TITLE
Elementor global widget bug🐞 Bug report: 

### ISSUE THREAD

**Issue by nicolebbcpa** [elementor/elementor#17954]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When a global widget is on your page and you try to edit, it triggers the endless loading page. 

### Steps to reproduce

1) create a global widget 
2) add it to a page
3) save
4) try to edit the page

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx
	MySQL version: MariaDB Server v10.3.34
	PHP Version: 7.4.28
	PHP Memory Limit: 512M
	PHP Max Input Vars: 6144
	PHP Max Post Size: 2047M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: There are some writing permissions issues with the following directories/files:
		 - WordPress root directory
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.1
	Site URL: https://boyer-boyer.com
	Home URL: https://boyer-boyer.com
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Admin Email: nicole@boyer-boyer.com
	Debug Mode: Inactive

== Theme ==
	Name: OceanWP Child
	Version: 1.0
	Author: Nick
	Child Theme: Yes
	Parent Theme Name: OceanWP
	Parent Theme Version: 3.1.3
	Parent Theme Author: OceanWP

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36

== Active Plugins ==
	Akismet Anti-Spam
		Version: 4.2.2
		Author: Automattic

	Elementor
		Version: 3.6.0-dev40
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.0-dev26
		Author: Elementor.com

	Jetpack
		Version: 10.7-a.5
		Author: Automattic

	Ocean Extra
		Version: 1.9.3
		Author: OceanWP

	Ocean Sticky Header
		Version: 1.1.11
		Author: OceanWP

	Page Optimize
		Version: 0.5.2
		Author: Automattic

	Post Duplicator
		Version: 2.28
		Author: Metaphor Creations

	Redirection
		Version: 5.2.3
		Author: John Godley

	Site Kit by Google
		Version: 1.68.0
		Author: Google

	TranslatePress - Multilingual
		Version: 2.2.1
		Author: Cozmoslabs, Razvan Mocanu, Madalin Ungureanu, Cristophor Hurduban

	Yoast SEO
		Version: 18.2
		Author: Team Yoast

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

	WP.com Site Helper
		Version: 
		Author: 

== Elements Usage ==
	
	footer : 2
		heading : 10
		icon-box : 6
		icon-list : 4
		image : 2
		social-icons : 1
	header : 1
		button : 1
		image : 1
		nav-menu : 1
	popup : 16
		button : 3
		heading : 22
		image : 15
		social-icons : 12
		spacer : 16
		text-editor : 31
	section : 1
		image : 3
	widget : 0
		divider : 1
		form : 1
	wp-page : 17
		blockquote : 9
		button : 65
		divider : 3
		form : 7
		google_maps : 1
		heading : 91
		icon-box : 11
		image : 55
		image-box : 25
		social-icons : 16
		spacer : 32
		star-rating : 9
		testimonial : 9
		text-editor : 73

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	: Inactive by default
	Container: Inactive by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Inactive by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 322022-02-17 12:28:55 [info] elementor::elementor_updater Started 
2022-02-17 12:28:55 [info] Elementor/Upgrades - _on_each_version Start  
2022-02-17 12:28:55 [info] Elementor/Upgrades - _on_each_version Finished 
2022-02-17 12:28:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev38',
  'to' => '3.6.0-dev39',
)]
2022-02-17 12:28:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev38',
  'to' => '3.6.0-dev39',
)]
2022-02-22 13:03:12 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev39',
  'to' => '3.6.0-dev40',
)]
2022-02-22 13:03:16 [info] elementor::elementor_updater Started 
2022-02-22 13:03:16 [info] Elementor/Upgrades - _on_each_version Start  
2022-02-22 13:03:16 [info] Elementor/Upgrades - _on_each_version Finished 
2022-02-22 13:03:16 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.0-dev39',
  'to' => '3.6.0-dev40',
)]
2022-02-22 15:32:32 [info] elementor-pro::elementor_pro_updater Started 
2022-02-22 15:32:32 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-02-22 15:32:32 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-02-22 15:32:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0-dev5',
  'to' => '3.7.0-dev25',
)]
2022-02-22 15:32:32 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0-dev5',
  'to' => '3.7.0-dev25',
)]
2022-02-23 09:50:48 [info] elementor-pro::elementor_pro_updater Started 
2022-02-23 09:50:48 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-02-23 09:50:48 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-02-23 09:50:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0-dev25',
  'to' => '3.7.0-dev26',
)]
2022-02-23 09:50:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.0-dev25',
  'to' => '3.7.0-dev26',
)]

JS: showing 6 of 6JS: 2022-02-04 20:18:54 [error X 7][https://boyer-boyer.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.0-dev37:2:478959] elementor.getCurrentElement(...).getContainer is not a function 
JS: 2022-02-04 20:19:49 [error X 72][https://boyer-boyer.com/wp-content/plugins/elementor/assets/js/common.min.js?ver=3.6.0-dev37:2:223706] Cannot read properties of undefined (reading \'global\') 
JS: 2022-02-04 20:26:47 [error X 9][https://boyer-boyer.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.0-dev37:2:543930] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-02-04 20:26:47 [error X 83][https://boyer-boyer.com/wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.6.0-dev37:2:37170] id invalid type: string. 
JS: 2022-02-04 20:26:57 [error X 40][https://boyer-boyer.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.0-dev37:2:415880] Cannot read properties of undefined (reading \'isEditable\') 
JS: 2022-02-04 20:27:00 [error X 272][https://boyer-boyer.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.0-dev37:2:387481] Cannot read properties of undefined (reading \'model\') 

PHP: showing 4 of 4PHP: 2022-02-13 21:21:33 [notice X 4][/srv/htdocs/wp-content/plugins/elementor-pro/modules/forms/classes/form-record.php::179] Undefined index: referrer [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-22 14:46:01 [notice X 5][/srv/htdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-22 15:18:14 [notice X 8][/srv/htdocs/wp-content/plugins/elementor/core/debug/inspector.php::73] strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-02-22 15:54:09 [notice X 1][/srv/htdocs/wp-content/plugins/elementor/core/experiments/experiments-reporter.php::89] Undefined index: title [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.6.4

Feel free to update

Thanks!

**Comment by cfgs** [comment]
Im facing the exact same issue. The writer of this thread seems to have even a higher version for Elementor Pro when reading his post.

We are running the following:
Elementor - Version 3.6.0
Elementor Pro - Version 3.6.4

Any clue regarding how to solve this, due to the 3.6.4 version doesn't seem to fix it.

**Comment by mooverflow** [comment]
Hi, i have a same problem : ".../wp-json/elementor/v1/globals... error 500" since Elementor Pro - Version 3.6.4 update
Elementor - Version 3.6.0
Elementor Pro - Version 3.6.4

**Comment by sg6** [comment]
I have the same issue, regardless of version 3.6.1 or 3.6.4 - it still exists.

**Comment by havn** [comment]
Same issue,  Elementor Version 3.6.6, Elementor Pro Version 3.7.2.

**Comment by sunabove** [comment]
I have encountered the same problem.
I cannot edit any page using elementor editor.

I hope to cancel out buying elementor pro.

**Comment by DareDevil1111** [comment]
Hey there,

You have to simply delete any of the saved templates or globals you have and then it gets fixed.

Cheers

**Comment by sg6** [comment]
If this is happening on a single widget, it's probably because of some naming issue. Rename your widget and try it again. Please be aware that this might delete all your previous usages of this widget.

```public function get_name()
    {
        return 'my-new-widget-name';
    }```
    
Use only lowercase chars (a-z) and dashes in the widget's name... I've added a space in the string, not the first time, and this fucked up everything, without telling me what's wrong. Finally I found out why this occasionally happens to me :D
