### ISSUE TITLE
🐞 Bug report: 

### ISSUE THREAD

**Issue by michael-v-bloom** [elementor/elementor#19390]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After updating the Elementor plugin with the latest version 3.7.0, which was recently released, the Elementor tool doesn't load at all. Keeps on loading during initial grey screen. 

This happens both in Normal Mode and Safe Mode.

In the Console there are 2 main errors appearing:

1) 2022-08-08 15:33:17 [error X 8][https://studyyoga.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.7.0:2:4155] elementorDevTools is not defined 
2) 2022-08-08 15:50:30 [error X 2][https://studyyoga.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.0:3:872751] elementorFrontend is not defined 

From before the update and after the update nothing has been done to the website, no additional code nor elements.

Also tried removing all plugins and custom code, but it doesn't solve the issue.
Checked on the Linux server for latest updates and PHP version: everything runs ok.

Main issue in the latest update.

Any ideas? We need to proceed with the website development, so the issue is quite urgent! Thank you.

### Steps to reproduce

After updating the Elementor plugin with the latest version 3.7.0, which was recently released, the Elementor tool doesn't load at all. Keeps on loading during initial grey screen. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.41 (Ubuntu)
	MySQL version: (Ubuntu) v8.0.30
	PHP Version: 7.4.3
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://studyyoga.com
	Home URL: https://studyyoga.com
	WP Multisite: No
	Max Upload Size: 56 MB
	Memory limit: 2048M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: contact@dezea.digital
	Debug Mode: Inactive

== Theme ==
	Name: BuddyBoss Child
	Version: 1.0.1
	Author: BuddyBoss.com
	Child Theme: Yes
	Parent Theme Name: BuddyBoss Theme
	Parent Theme Version: 2.0.7
	Parent Theme Author: BuddyBoss

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

== Active Plugins ==
	Auto Login on Register for BuddyBoss
		Version: 1.0.0
		Author: Xavier Lopez

	BuddyBoss Platform
		Version: 2.0.7
		Author: BuddyBoss

	BuddyBoss Platform Pro
		Version: 2.0.5
		Author: BuddyBoss

	Elementor
		Version: 3.7.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.3
		Author: Elementor.com

	ImageMagick Engine
		Version: 1.7.4
		Author: Orangelab

	LearnDash HUB
		Version: 1.0.0
		Author: LearnDash

	LearnDash LMS
		Version: 4.3.0.2
		Author: LearnDash

	LearnDash LMS - Elementor
		Version: 1.0.3
		Author: LearnDash

	LearnDash LMS - ProPanel
		Version: 2.1.4.1
		Author: LearnDash

	WPCode - Insert Headers, Footers, and Code Snippets
		Version: 2.0.1
		Author: WPCode

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Elementor Experiments ==
	Optimized DOM Output: Inactive
	Improved Asset Loading: Inactive
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Accessibility Improvements: Inactive
	Additional Custom Breakpoints: Active
	Import Export Template Kit: Inactive
	Hide native WordPress widgets from search results: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Landing Pages: Inactive
	Color Sampler: Inactive
	Favorite Widgets: Inactive
	Admin Top Bar: Inactive
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 262022-07-03 23:33:47 [info] elementor::elementor_updater Started 
2022-07-03 23:33:47 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-03 23:33:47 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-03 23:33:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-03 23:33:47 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-27 23:33:49 [info] elementor::elementor_updater Started 
2022-07-27 23:33:49 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-27 23:33:49 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-27 23:33:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-07-27 23:33:49 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-08-01 11:33:48 [info] elementor-pro::elementor_pro_updater Started 
2022-08-01 11:33:48 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-01 11:33:48 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-01 11:33:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-01 11:33:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-08 11:33:55 [info] elementor::elementor_updater Started 
2022-08-08 11:33:55 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-08 11:33:55 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-08 11:33:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]
2022-08-08 11:33:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]

PHP: showing 9 of 9PHP: 2022-06-19 14:58:21 [error X 1][/var/www/studyyoga.com/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on null in /var/www/studyyoga.com/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /var/www/studyyoga.com/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /var/www/studyyoga.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /var/www/studyyoga.com/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /var/www/studyyoga.com/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /var/www/studyyoga.com/wp-includes/plugin.php(476): WP_Hook->do_action()
#6 /var/www/studyyoga.com/wp-admin/admin-ajax.php(187): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-20 17:56:33 [error X 4][/var/www/studyyoga.com/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /var/www/studyyoga.com/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /var/www/studyyoga.com/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /var/www/studyyoga.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /var/www/studyyoga.com/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /var/www/studyyoga.com/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /var/www/studyyoga.com/wp-includes/plugin.php(476): WP_Hook->do_action()
#6 /var/www/studyyoga.com/wp-admin/admin-ajax.php(187): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-21 15:58:41 [notice X 1][/var/www/studyyoga.com/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-22 14:04:12 [notice X 2137][/var/www/studyyoga.com/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1483] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-01 10:29:16 [notice X 35][/var/www/studyyoga.com/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1446] Trying to access array offset on value of type null [array (
  'trace' => '
#0: /var/www/studyyoga.com/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php(1446): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/controls-stack.php(2221): ElementorPro\Modules\NavMenu\Widgets\Nav_Menu -> render()
#2: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
#3: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/widget-base.php(750): Elementor\Widget_Base -> render_content()
#4: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/element-base.php(447): Elementor\Widget_Base -> print_content()
',
)]
PHP: 2022-07-01 10:29:16 [notice X 35][/var/www/studyyoga.com/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1459] Trying to access array offset on value of type null [array (
  'trace' => '
#0: /var/www/studyyoga.com/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php(1459): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/controls-stack.php(2221): ElementorPro\Modules\NavMenu\Widgets\Nav_Menu -> render()
#2: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
#3: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/widget-base.php(750): Elementor\Widget_Base -> render_content()
#4: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/element-base.php(447): Elementor\Widget_Base -> print_content()
',
)]
PHP: 2022-07-01 10:29:16 [notice X 35][/var/www/studyyoga.com/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1470] Trying to access array offset on value of type null [array (
  'trace' => '
#0: /var/www/studyyoga.com/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php(1470): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/controls-stack.php(2221): ElementorPro\Modules\NavMenu\Widgets\Nav_Menu -> render()
#2: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
#3: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/widget-base.php(750): Elementor\Widget_Base -> render_content()
#4: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/element-base.php(447): Elementor\Widget_Base -> print_content()
',
)]
PHP: 2022-07-01 10:29:16 [notice X 35][/var/www/studyyoga.com/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1483] Trying to access array offset on value of type null [array (
  'trace' => '
#0: /var/www/studyyoga.com/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php(1483): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/controls-stack.php(2221): ElementorPro\Modules\NavMenu\Widgets\Nav_Menu -> render()
#2: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
#3: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/widget-base.php(750): Elementor\Widget_Base -> render_content()
#4: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/element-base.php(447): Elementor\Widget_Base -> print_content()
',
)]
PHP: 2022-08-08 15:32:58 [notice X 3][/var/www/studyyoga.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 7 of 7JS: 2022-06-20 11:55:12 [error X 77][https://studyyoga.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:421003] Cannot read properties of undefined (reading \'get\') 
JS: 2022-06-20 12:07:07 [error X 11][https://studyyoga.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:516092] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-06-26 15:48:46 [error X 36][https://studyyoga.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:459676] Cannot read properties of null (reading \'toLowerCase\') 
JS: 2022-06-28 11:55:03 [error X 2][https://studyyoga.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:362278] Cannot read properties of undefined (reading \'isEditable\') 
JS: 2022-06-28 13:46:38 [error X 1][https://studyyoga.com/wp-content/plugins/elementor-pro/assets/lib/sticky/jquery.sticky.min.js?ver=3.7.2:1:741] Failed to execute \'getComputedStyle\' on \'Window\': parameter 1 is not of type \'Element\'. 
JS: 2022-08-08 15:33:17 [error X 8][https://studyyoga.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.7.0:2:4155] elementorDevTools is not defined 
JS: 2022-08-08 15:50:30 [error X 2][https://studyyoga.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.0:3:872751] elementorFrontend is not defined 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	LearnDash LMS - Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by shilo-ey** [comment]
Hey @michael-v-bloom 

Thank you for reporting.


Can you please share this with our support for further investigation?

Thanks.

**Comment by dixoncd** [comment]
Any update on this?  We're seeing the same thing after upgrading to 3.7

**Comment by bdthemes** [comment]
Same issue for me too

**Comment by lontafara** [comment]
![image](https://user-images.githubusercontent.com/4528633/183885909-55914f5e-03d3-4e9e-be9f-a0b82ffbc01f.png)


Same error for me!


Uncaught ReferenceError: elementorDevTools is not defined
    at get CommandHistory [as CommandHistory] (editor-document.min.js?ver=3.7.0:2:25976)
    at 4147 (editor.min.js?ver=3.5.1:2:56055)
    at __webpack_require__ (editor.min.js?ver=3.5.1:2:193776)
    at 90413 (editor.min.js?ver=3.5.1:2:54480)
    at __webpack_require__ (editor.min.js?ver=3.5.1:2:193776)
    at 60118 (editor.min.js?ver=3.5.1:2:57781)
    at __webpack_require__ (editor.min.js?ver=3.5.1:2:193776)
    at 53425 (editor.min.js?ver=3.5.1:2:67418)
    at __webpack_require__ (editor.min.js?ver=3.5.1:2:193776)
    at editor.min.js?ver=3.5.1:2:194003

**Comment by michael-v-bloom** [comment]
> Hey @michael-v-bloom
> 
> Thank you for reporting.
> 
> Can you please share this with our support for further investigation?
> 
> Thanks.

Hi @shilo-ey,

I have submitted a ticket to support for this issue, but they haven't responded to it yet.

However, we are seeing this issue more and more, and it looks like we are not alone. Main reason being the new Elementor version (3.7.0)... 

Could you take a closer look to it within your DEV department?

Best regards,
Michael.

**Comment by ddgoehler** [comment]
We're having a similar issue in the Editor after Update to Elementor Pro 3.7.3 (from 2.something):
The editor will load, but I can't switch to the Style-tab of any element.

Uncaught ReferenceError: elementorDevTools is not defined
    at n.onReady (editor.min.js?ver=3.7.0:3:286320)
    at Object._triggerMethod (backbone.marionette.min.js?ver=2.4.5.e1:24:7999)
    at n.triggerMethod (backbone.marionette.min.js?ver=2.4.5.e1:24:21465)
    at n.onRender (editor.min.js?ver=3.7.0:3:222711)
    at Object._triggerMethod (backbone.marionette.min.js?ver=2.4.5.e1:24:7999)
    at n.triggerMethod (backbone.marionette.min.js?ver=2.4.5.e1:24:21465)
    at n.render (backbone.marionette.min.js?ver=2.4.5.e1:25:1223)
    at Jn (underscore.min.js?ver=1.13.3:2:7455)
    at n.<anonymous> (underscore.min.js?ver=1.13.3:2:7867)
    at n.render (underscore.min.js?ver=1.13.3:2:1065)


System info:
Operating System:	Linux	
Software:	LiteSpeed	
MySQL version:	MariaDB Server v10.5.16	
PHP Version:	7.3.33
WP Version:	6.0.1
Hello Elementor:	2.3.1

**Comment by ddgoehler** [comment]
Updating the php version and the Hello Elementor theme did not work.
There's also another error in the JS console:

dev-tools.min.js?ver=3.7.0:2 Uncaught TypeError: Cannot read properties of undefined (reading 'deprecated')
    at dev-tools.min.js?ver=3.7.0:2:5656
    at Array.forEach (<anonymous>)
    at Module.notifyBackendDeprecations (dev-tools.min.js?ver=3.7.0:2:5576)
    at new Module (dev-tools.min.js?ver=3.7.0:2:5364)
    at dev-tools.min.js?ver=3.7.0:2:6122
    at dev-tools.min.js?ver=3.7.0:2:6181
    at dev-tools.min.js?ver=3.7.0:2:6185

**Comment by michael-v-bloom** [comment]
After checking in the console logs, we've identified a couple of error sources here:

1) File source > **web-cli.min.js?ver=3.7.0**

`17341: (C,T,B)=>{
      "use strict";
      var L = B(73203);
      Object.defineProperty(T, "__esModule", {
          value: !0
      }),
      T.default = void 0;
      var q = L(B(78983))
        , $ = L(B(42081))
        , U = function() {
          function Console() {
              (0,
              q.default)(this, Console)
          }
          return (0,
          $.default)(Console, null, [{
              key: "error",
              value: function error(C) {
                  $e.devTools && $e.devTools.log.error(C),
                  C instanceof $e.modules.HookBreak || console.error(C)
              }
          }, {
              key: "warn",
              value: function warn() {
                  for (var C, T = 'font-size: 12px; background-image: url("'.concat(elementorWebCliConfig.urls.assets, 'images/logo-icon.png"); background-repeat: no-repeat; background-size: contain;'), B = arguments.length, L = new Array(B), q = 0; q < B; q++)
                      L[q] = arguments[q];
                  L.unshift("%c  %c", T, ""),
                  (C = console).warn.apply(C, L)
              }
          }]),
          Console
      }();
      T.default = U
  }`

**ReferenceError: elementorDevTools is not defined
    at get elementWrappers [as elementWrappers] (frontend.min.js?ver=3.7.0:formatted:202:66)
    at _default.prepareOptions (frontend.min.js?ver=3.7.3:2:3715)
    at _default.activate (frontend.min.js?ver=3.7.3:2:4557)
    at frontend.min.js?ver=3.7.3:2:4975
    at Array.forEach (<anonymous>)
    at _default.toggle (frontend.min.js?ver=3.7.3:2:4821)
    at _default.<anonymous> (frontend.min.js?ver=3.7.0:formatted:356:28)
    at e.each.r.<computed> [as toggle] (frontend-modules.min.js?ver=3.7.0:2:9858)
    at _default.onInit (frontend.min.js?ver=3.7.3:2:5194)
    at Module.trigger (frontend-modules.min.js?ver=3.7.0:2:11217)**

---------------------------------------------------------------------------------------------------

2) File source > **frontend.min.js?ver=3.7.0**

`class Frontend extends elementorModules.ViewModule {
            constructor() {
                super(...arguments),
                this.config = elementorFrontendConfig,
                this.config.legacyMode = {
                    get elementWrappers() {
                        return elementorFrontend.isEditMode() && elementorDevTools.deprecation.deprecated("elementorFrontend.config.legacyMode.elementWrappers", "3.1.0", "elementorFrontend.config.experimentalFeatures.e_dom_optimization"),
                        !elementorFrontend.config.experimentalFeatures.e_dom_optimization
                    }
                },
                this.populateActiveBreakpointsConfig()
            } 
. . .`

**Uncaught (in promise) ReferenceError: elementorDevTools is not defined
    at get elementWrappers [as elementWrappers] (frontend.min.js?ver=3.7.0:formatted:202:66)
    at _default.prepareOptions (frontend.min.js?ver=3.7.3:2:3715)
    at _default.activate (frontend.min.js?ver=3.7.3:2:4557)
    at frontend.min.js?ver=3.7.3:2:4975
    at Array.forEach (<anonymous>)
    at _default.toggle (frontend.min.js?ver=3.7.3:2:4821)
    at _default.<anonymous> (frontend.min.js?ver=3.7.0:formatted:356:28)
    at e.each.r.<computed> [as toggle] (frontend-modules.min.js?ver=3.7.0:2:9858)
    at _default.onInit (frontend.min.js?ver=3.7.3:2:5194)
    at Module.trigger (frontend-modules.min.js?ver=3.7.0:2:11217)**

Then follows ...

**Uncaught ReferenceError: elementorDevTools is not defined
    at get elementWrappers [as elementWrappers] (frontend.min.js?ver=3.7.0:formatted:202:66)
    at _default.prepareOptions (frontend.min.js?ver=3.7.3:2:3715)
    at _default.activate (frontend.min.js?ver=3.7.3:2:4557)
    at frontend.min.js?ver=3.7.3:2:4975
    at Array.forEach (<anonymous>)
    at _default.toggle (frontend.min.js?ver=3.7.3:2:4821)
    at later (frontend.min.js?ver=3.7.0:formatted:351:27)**

Then follows another one ...

**Uncaught ReferenceError: elementorDevTools is not defined
    at get elementWrappers [as elementWrappers] (frontend.min.js?ver=3.7.0:formatted:202:66)
    at _default.prepareOptions (frontend.min.js?ver=3.7.3:2:3715)
    at _default.activate (frontend.min.js?ver=3.7.3:2:4557)
    at frontend.min.js?ver=3.7.3:2:4975
    at Array.forEach (<anonymous>)
    at _default.toggle (frontend.min.js?ver=3.7.3:2:4821)
    at _default.<anonymous> (frontend.min.js?ver=3.7.0:formatted:356:28)
    at e.each.r.<computed> (frontend-modules.min.js?ver=3.7.0:2:9858)
    at dispatch (jquery.min.js?ver=3.6.0:2:43064)
    at v.handle (jquery.min.js?ver=3.6.0:2:41048)**

Then follows the last one ...

**Uncaught ReferenceError: elementorDevTools is not defined
    at get elementWrappers [as elementWrappers] (frontend.min.js?ver=3.7.0:formatted:202:66)
    at _default.prepareOptions (frontend.min.js?ver=3.7.3:2:3715)
    at _default.activate (frontend.min.js?ver=3.7.3:2:4557)
    at frontend.min.js?ver=3.7.3:2:4975
    at Array.forEach (<anonymous>)
    at _default.toggle (frontend.min.js?ver=3.7.3:2:4821)
    at later (frontend.min.js?ver=3.7.0:formatted:351:27)**

---------------------------------------------------------------------------------------------------

@shilo-ey Any updates?

**Comment by dixoncd** [comment]
> Hey @michael-v-bloom
> 
> Thank you for reporting.
> 
> Can you please share this with our support for further investigation?
> 
> Thanks.

Why is this marked closed?

**Comment by salvvvv** [comment]
Any update? I have the same issue.

**Comment by Ashic90** [comment]
same here, you should hurry to solve this, because for 2 days I can't edit with elementor ... soooo

**Comment by ProgYaghouti** [comment]
I went back to the previous version from the tools section and the previous version works fine (previous version 2.6.8)

**Comment by michael-v-bloom** [comment]
> > Hey @michael-v-bloom
> > Thank you for reporting.
> > Can you please share this with our support for further investigation?
> > Thanks.
> 
> Why is this marked closed?

Not sure, @shilo-ey just closed my issue report and referenced to contact Support. But, it's been 2 days without any answers from them, and it clearly looks like an issue with the latest update.

We'll have to rollback to the previous version probably.

**Comment by mdca** [comment]
I'm seeing the same error, how can this be closed?

**Comment by ddgoehler** [comment]
Rolling back to:
Elementor v3.6.8 and
Elementor Pro v3.6.5

removed the issue for me - and worked without any issues.

**Comment by ofyalcin** [comment]
Same error here.

**Comment by eden-sonder** [comment]
Same issue here. Rolling back fixed the problem. I noticed it when trying to use the posts query. And when I right click on it, it says "Save as global [PRO]". I am obviously using the pro version already. When I roll back, it has the normal Save as Global and recognizes I'm using pro. 

== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.51 (Debian)
	MySQL version: mariadb.org binary distribution v10.4.20
	PHP Version: 7.4.30
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected
	== WordPress Environment ==
	Version: 6.0.1
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 256M
	Debug Mode: Active

**Comment by NikkaIt** [comment]
Same issue here after updating to Elementor 3.7.1 and Elementor Pro 3.7.3.
Rolling back Elementor 3.6.8 and Elementor Pro 3.7.2 fixed the problem.
<img width="1211" alt="Elementor_3 7 1 and Pro_3 7 3" src="https://user-images.githubusercontent.com/36760975/184681125-fa03f8f1-34ac-438b-9049-aea1c7763c84.png">

**Comment by ouakkrim** [comment]
Same issue Here, Rolled back to 
Elementor: 3.6.8
Elementor Pro: 3.6.5
Fixed the issue for now.

![image](https://user-images.githubusercontent.com/84095617/184685948-d994eae3-f658-4083-85bd-d40a06807ec4.png)

**Comment by rayhanuddin2019** [comment]
same issue https://prnt.sc/o0oBZILVoNd0
elementor 3.6.8 okey

**Comment by manuelricci** [comment]
Same issue here. Rolled back to Elementor 3.6.8 and Elementor PRO 3.6.5 and seems to be working

**Comment by BigBenSolutions** [comment]
same issue here.

**Comment by Studiostekker** [comment]
Error still present in 3.7.1. Rolling back the free edition to 3.6.8 is the only fix for now..

**Comment by salvvvv** [comment]
I rolled back to v. 3.6.8 (Elementor free) and the PRO version to v. 3.7.3 and works fine. But, do you know why after some time Elementor free auto-update to v. 3.7.1 automatically? I have the auto-update option disabled, so it's weird.

**Comment by Micu22** [comment]
Same issue, on all sites, no matter the server / environment

**Comment by somejuandk** [comment]
Same issue on several sites, has apparently nothing to do with conflicting plugins/themes as far as I can tell.
Rollback of Elementor plugin to v.3.6.8 fixes the issue (pro still on v.3.7.3)

**Comment by AdLucky1001** [comment]
I am having the same issue. First I have thought that the Rank Math was causing the issue, then that it was my Theme but now I see that this is the new Elementor update. I have not done anything to my site for days and came back to the issue. I see that people are having this problem for days, so I hope it will get resolved quickly. I just had to rollback the Elementor free to v.3.6.8 and left the Elementor Pro as is and it is working properly now.

**Comment by nakov** [comment]
I have the same issue with **Elementor 3.7.1** + **Elementor Pro 3.7.3**:
  - Uncaught ReferenceError: elementorDevTools is not defined
  - Cannot read properties of undefined (reading 'deprecated')
  
Like the others recommended, rolling back to **Elementor v3.6.8** + **Elementor Pro v3.6.5** solves the problem.

I have two Elementor Pro-based Web sites, on the same hosting, environment, using the same WP theme.
One of them works with Elementor 3.7.1 + Elementor Pro 3.7.3 and in the same time the other fails. I switched off caching and CloudFlare, and still the problem is there. Both site run similar plugins, but not exact. Maybe some plugin causes this incompatibility.

**Comment by manuelricci** [comment]
> I have the same issue with **Elementor 3.7.1** + **Elementor Pro 3.7.3**:
>   - Uncaught ReferenceError: elementorDevTools is not defined
>   - Cannot read properties of undefined (reading 'deprecated')
>   
> Like the others recommended, rolling back to **Elementor v3.6.8** + **Elementor Pro v3.6.5** solves the problem.
> 
> I have two Elementor Pro-based Web sites, on the same hosting, environment, using the same WP theme.
> One of them works with Elementor 3.7.1 + Elementor Pro 3.7.3 and in the same time the other fails. I switched off caching and CloudFlare, and still the problem is there. Both site run similar plugins, but not exact. Maybe some plugin causes this incompatibility.

I don't think is an incompatibility between plugins or themes. I got the error with the default theme active and only Elementor and Elementor PRO installed

**Comment by AdLucky1001** [comment]
Did anyone find the solution to this issue? I am talking to the support and he had me download and upload elementor pro from the scratch (which didn't work), now asking to increase PHP limit which I have to wait to do so few hours. I feel like they are trying to not acknowledge that there is an actual issue at this point.

**Comment by ernestorivero** [comment]
Same problem here.

**Comment by bdkoder** [comment]
It's already gone a couple of days, but the problem is not solved yet. We are facing the same errors very badly - 

Elementor Version - 3.7.1

Only Rollback to 3.6.8 working well. The Elementor team should focus on this kind of serious error at first.

![image](https://user-images.githubusercontent.com/35867332/185042445-5a38177b-1645-4a5c-88b3-67951ffb0bcb.png)

**Comment by jeanlevatic** [comment]
I had the same problem, the rollback to elementor 3.6.8 worked fine even with pro version 3.7.3. 

Please correct this problem.

**Comment by andrewhenke** [comment]
Same issue here across several websites, this is affecting a lot of our clients.

**Comment by brentcopeland** [comment]
This has completely stopped our webdev team and impacted our schedule greatly, please publish a fix, asap.


Same issue here on all websites.

**Comment by andrewhenke** [comment]
> This has completely stopped our webdev team and impacted our schedule greatly, please publish a fix, asap.
> 
> Same issue here on all websites.

If you use Elementor safe mode you can edit as usual, it's just a huge pain to deal with the issue as it is.

**Comment by w3b-beweb** [comment]
Same issues here; rollback to 3.6.8 and wait for a fix seems the best option right now

**Comment by brentcopeland** [comment]
> > This has completely stopped our webdev team and impacted our schedule greatly, please publish a fix, asap.
> > Same issue here on all websites.
> 
> If you use Elementor safe mode you can edit as usual, it's just a huge pain to deal with the issue as it is.

Some aspects are working in safe mode, but some things, like reverting to a past version are not.  going to rollback I guess.

**Comment by AdLucky1001** [comment]
I have updated PHP memory limit to 512MB (per Elementor Support request - which would be actually ridiculous to require for an update) and that didn't fix anything for anyone wondering if that would solve the issue.

**Comment by Fullstak-nl** [comment]
@shilo-ey maybe reopen the issue again to prevent people from going crazy about all of this?

**Comment by VermontMediaSolutions** [comment]
We are getting the same error after update to 3.7.0 and 3.7.1 ... . Roll back to 3.6.8 is the only thing that works. Other than the elmentor and elementor pro plugins we do NOT have any of the same plugins as the original poster listed.

**Comment by seanbajuice** [comment]
Same problem here, I had to roll back to 3.68

**Comment by FauzanEdris** [comment]
The status is merged, is this issue fixed? @shilo-ey

**Comment by abbas374** [comment]
> I have the same issue with **Elementor 3.7.1** + **Elementor Pro 3.7.3**:
> 
> * Uncaught ReferenceError: elementorDevTools is not defined
> * Cannot read properties of undefined (reading 'deprecated')
> 
> Like the others recommended, rolling back to **Elementor v3.6.8** + **Elementor Pro v3.6.5** solves the problem.
> 
> I have two Elementor Pro-based Web sites, on the same hosting, environment, using the same WP theme. One of them works with Elementor 3.7.1 + Elementor Pro 3.7.3 and in the same time the other fails. I switched off caching and CloudFlare, and still the problem is there. Both site run similar plugins, but not exact. Maybe some plugin causes this incompatibility.

Bro I have same site on two hosting. With all plugins and themes. Exactly same. One is working and one is not. Both sare the same site. Rolling back is not helping a lot. Elementor support has not responded. All people are experiencing the issue in a different way but error is same elementor dev tools are not defined

**Comment by AdLucky1001** [comment]
This is the response I’ve got from the Tier 2 Elementor Support:

“**If you have used the scrolling effect in the header/footer template**, then the Elementor editor is not loading, and the editor is stuck to a grey screen. This is the known bug with the latest Elementor version; our developers are already working on the fix.”

**Comment by ivan-peshko-upqode** [comment]
I faced the same issue. Most likely related to query posts. Are there any updates?

**Comment by HuthDev** [comment]
Facing same issue

**Comment by mdca** [comment]
I've deactivated all plugins, that could have had any impact and the error
was still there.

Dne pá 19. 8. 2022 0:31 uživatel John Scott ***@***.***>
napsal:

**Comment by manuelricci** [comment]
> Looks like this might be linked to 3rd party plugins and how they're initialising widgets. Here's a thread where the OP fixed the issue: https://wordpress.org/support/topic/referenceerror-elementordevtools-is-not-defined/
> 
> 

Change the source code of the plugin as suggested in the topic you linked is a worst practice. The only good solution, at the moment, is rolling back to elementor 3.6.8

**Comment by jimyaghi** [comment]
i experience this issue when attempting to access the STYLE tab of sections. the content of the tab is blank and a javascript error is reported about elementorDevTools is not defined. Upon setting a breakpoint in the editor.min.js for where elementorDevTools is being set, it appears to fail as it attempts to add deprecation object.

the latest version i could roll back to where the error did not exist was 3.6.8. 

@manuelricci  I don't think that it is related to 3rd party plugins. or rather 3rd party plugins are where those deprecation warnings need to be reported, so they are users of the feature being introduced. The fix you reference merely ensures the dev tools are not called. Before the fix, elementorDevTools was referenced in order to report a backend deprecation. When the suggested code modification is applied, the deprecation is repaired so elementorDevTools does not need to report anything so the error shouldn't (theoretically) occur.

i couldn't easily figure out what the issue was, unfortunately. but it looks like something introduced in version 3.7.0 that seems to be overlooked.

**Comment by michael-v-bloom** [comment]
**Latest update:** Elementor 3.7.2 has been released, and now updated. Loading of Elementor now works fine. Will be testing to see if any other issues arise, but it seems to be working as before. 

@udidol Thank you for the fix!

**Comment by shilo-ey** [comment]
Hey all, thank you for reporting.

This issue has been resolved in Elementor v3.7.2

Feel free to update

Thanks!

**Comment by jimyaghi** [comment]
I can confirm that this issue has not been resolved in 3.7.2. And the reason is the following oversight you can find [here](https://github.com/elementor/elementor/blob/cf465842dd6e009cd50847f4ed2b8e289b875a10/modules/dev-tools/assets/js/module.js#L29):

```
	window.elementorDevTools = new Module();
	window.elementorDevTools.deprecation = new Deprecation();
```

You will note that we call the constructor for the elementorDevTools module here then we set its deprecation property. However, the constructor references this property before it is set.

You can see it [here](https://github.com/elementor/elementor/blob/cf465842dd6e009cd50847f4ed2b8e289b875a10/modules/dev-tools/assets/js/module.js#L6)

```
	constructor() {
		this.notifyBackendDeprecations();
	}
```
and if you look at the definition for notifyBackendDeprecations() you will find  [here](https://github.com/elementor/elementor/blob/cf465842dd6e009cd50847f4ed2b8e289b875a10/modules/dev-tools/assets/js/module.js#L15) that we reference this.deprecation property before it has been set

```
		Object.entries( notices ).forEach( ( [ key, notice ] ) => {
			this.deprecation.deprecated( key, ...notice );
		} );
```

I would suggest to fix it by doing the following:

```
import Deprecation from './deprecation';

/* global elementorDevToolsConfig */

export default class Module {
	constructor() {
                 /**** ADD THIS LINE HERE ****/
                this.deprecation = new Deprecation();
                /************************************/
		this.notifyBackendDeprecations();
	}

	notifyBackendDeprecations() {
		// eslint-disable-next-line camelcase
		const notices = elementorDevToolsConfig.deprecation.soft_notices;

		Object.entries( notices ).forEach( ( [ key, notice ] ) => {
			this.deprecation.deprecated( key, ...notice );
		} );
	}

	consoleWarn( ...args ) {
		const style = `font-size: 12px; background-image: url("${ elementorDevToolsConfig.urls.assets }images/logo-icon.png"); background-repeat: no-repeat; background-size: contain;`;

		args.unshift( '%c  %c', style, '' );

		console.warn( ...args ); // eslint-disable-line no-console
	}
}

if ( ! window.elementorDevTools ) {
	window.elementorDevTools = new Module();
        /***** REMOVE THIS LINE ****/
	// window.elementorDevTools.deprecation = new Deprecation();
       /**********************************/
}
```

Please fix it asap in version 3.7.3 because it's causing a big problem for us.

**Comment by bensaine** [comment]
Can confirm that this issue is not resolved in Elementor v3.7.2, it should be reopened @shilo-ey

**Comment by deputt** [comment]
> We're having a similar issue in the Editor after Update to Elementor Pro 3.7.3 (from 2.something): The editor will load, but I can't switch to the Style-tab of any element.
> 
> Uncaught ReferenceError: elementorDevTools is not defined at n.onReady (editor.min.js?ver=3.7.0:3:286320) at Object._triggerMethod (backbone.marionette.min.js?ver=2.4.5.e1:24:7999) at n.triggerMethod (backbone.marionette.min.js?ver=2.4.5.e1:24:21465) at n.onRender (editor.min.js?ver=3.7.0:3:222711) at Object._triggerMethod (backbone.marionette.min.js?ver=2.4.5.e1:24:7999) at n.triggerMethod (backbone.marionette.min.js?ver=2.4.5.e1:24:21465) at n.render (backbone.marionette.min.js?ver=2.4.5.e1:25:1223) at Jn (underscore.min.js?ver=1.13.3:2:7455) at n. (underscore.min.js?ver=1.13.3:2:7867) at n.render (underscore.min.js?ver=1.13.3:2:1065)
> 
> System info: Operating System: Linux Software: LiteSpeed MySQL version: MariaDB Server v10.5.16 PHP Version: 7.3.33 WP Version: 6.0.1 Hello Elementor: 2.3.1
> 
> Updating the php version and the Hello Elementor theme did not work. There's also another error in the JS console:
> 
> dev-tools.min.js?ver=3.7.0:2 Uncaught TypeError: Cannot read properties of undefined (reading 'deprecated') at dev-tools.min.js?ver=3.7.0:2:5656 at Array.forEach () at Module.notifyBackendDeprecations (dev-tools.min.js?ver=3.7.0:2:5576) at new Module (dev-tools.min.js?ver=3.7.0:2:5364) at dev-tools.min.js?ver=3.7.0:2:6122 at dev-tools.min.js?ver=3.7.0:2:6181 at dev-tools.min.js?ver=3.7.0:2:6185
> 
> Rolling back to: Elementor v3.6.8 and Elementor Pro v3.6.5
> 
> removed the issue.

It seems a code change in Elementor starting 3.7.0 caused a conflict with Elementor Pack Pro (bdthemes): clicking on the Style-tab hides the Style-tab entirely. We're using Elementor Prol. The latest 3.7.2 did not resolve the issue.

This conflict resolves when we disabled Elementor Pack Pro OR roll back Elementor to 3.6.8.

Seems to be a repeat of a similar bug as per https://wordpress.org/support/topic/style-tab-in-the-visual-editor-disappears-on-click/

**Comment by deputt** [comment]
> i experience this issue when attempting to access the STYLE tab of sections. the content of the tab is blank and a javascript error is reported about elementorDevTools is not defined. Upon setting a breakpoint in the editor.min.js for where elementorDevTools is being set, it appears to fail as it attempts to add deprecation object.
> 
> the latest version i could roll back to where the error did not exist was 3.6.8.
> 
> @manuelricci I don't think that it is related to 3rd party plugins. or rather 3rd party plugins are where those deprecation warnings need to be reported, so they are users of the feature being introduced. The fix you reference merely ensures the dev tools are not called. Before the fix, elementorDevTools was referenced in order to report a backend deprecation. When the suggested code modification is applied, the deprecation is repaired so elementorDevTools does not need to report anything so the error shouldn't (theoretically) occur.
> 
> i couldn't easily figure out what the issue was, unfortunately. but it looks like something introduced in version 3.7.0 that seems to be overlooked.

bdthemes claims that this bug may have caused the disappearing Style-tab issue when Elementor Pack Pro is installed. However, the disappearing Style-tab still happens with 3.7.2. Rolling back to Elementor 3.6.8 resolves the issue. Hope Elementor can help resolve this matter. Will also raise the issue again with bdthemes.

**Comment by astbarc** [comment]
I've just updated to version 3.7.2 and the error is still there:

![image](https://user-images.githubusercontent.com/2587221/185857441-7880fc51-8366-49c6-92fb-683135d9fda3.png)

**Comment by aflhyperscale** [comment]
Same issues for me with the latest version rolled back to 3.6.8 on the free version and latest version of the Pro version and all is working ok

**Comment by asansano** [comment]
same issue here on 3.7.2

![image](https://user-images.githubusercontent.com/41288623/185956293-8fc2c31d-b3fc-48c5-93eb-c8c476765621.png)

**Comment by adriancical** [comment]
Same problem here, "editor.min.js?ver=3.7.1:3 Uncaught ReferenceError: elementorDevTools is not defined..."
Something has been pushed without testing it first, it broke all our Elementor websites.

**Comment by Thedrelle** [comment]
I am also experiencing this issue. 

Viewing style tab in any element, or trying to access any tab in nav menu element results in grey window, same error provided by other users. 

Rolling Elementor back to 3.6.8 fixes the problem. Did not have to roll back Elementor Pro

**Comment by adriancical** [comment]
Yesm I have done a database backup first and then rolling the Elementor
back to 3.6.8 solved the problem. The PRO part I have not rolled back. It
was enough to roll back the free plugin part.

**Comment by wiesys** [comment]
I can confirm that the issue is still present in the latest Elementor release.
The only workaround for me is rolling back to version 3.6.8.

**Comment by matipojo** [comment]
Hi @wiesys It's already fixed in the develop branch, and will be release with 3.7.3 on Sunday.

**Comment by wiesys** [comment]
> Hi @wiesys It's already fixed in the develop branch, and will be release with 3.7.3 on Sunday.

That's great – thank you! :)

**Comment by deputt** [comment]
> Hi @wiesys It's already fixed in the develop branch, and will be release with 3.7.3 on Sunday.

I confirm the disappearing Style-tab issue has been fixed with 3.7.3. TQVM!

**Comment by bagesjo** [comment]
Hi, we still got the same problem, running elementor free version 3.7.3. For us it doesn't work rolling back to 3.6.8, the problem persists.

**Comment by udidol** [comment]
@bagesjo It could be a cache issue. Regenerate your files via `Admin Dashboard > Elementor > Tools`, then do a hard reload of your front end page (Ctrl + F5 on Windows)

**Comment by bagesjo** [comment]
> @bagesjo It could be a cache issue. Regenerate your files via `Admin Dashboard > Elementor > Tools`, then do a hard reload of your front end page (Ctrl + F5 on Windows)

Thanks for your answer @udidol Tried this, unfortunatly it didn't help. Issue persists.

**Comment by matipojo** [comment]
> > @bagesjo It could be a cache issue. Regenerate your files via `Admin Dashboard > Elementor > Tools`, then do a hard reload of your front end page (Ctrl + F5 on Windows)
> 
> Thanks for your answer @udidol Tried this, unfortunatly it didn't help. Issue persists.

Hi @bagesjo can you please paste here your console error?

**Comment by nakov** [comment]
> > @bagesjo It could be a cache issue. Regenerate your files via `Admin Dashboard > Elementor > Tools`, then do a hard reload of your front end page (Ctrl + F5 on Windows)
> 
> Thanks for your answer @udidol Tried this, unfortunately it didn't help. Issue persists.

I also think that your problems comes from some kind of **caching**.

Try to **clear all possible caches**, used on your web site:
   - Caching plugins such as `W3 Total Cache`, `Litespeed Cache`, `WP-Optimize` and others
   - External caching mechanisms, for example CloudFlare
Also try to **reboot your server** (Apache, MySQL, nginx, redis, ...). This will regenerate all in-memory based caching mechanisms.

**Comment by bagesjo** [comment]
@nakov Hi Nakov, thanks for your message. I have now tried to clear all cache I can think of, deleted the cache folder from the FTP also and restarted the server numerous times. We had breeze caching plugin installed from the start, but I have purged it and now the plugin is no longer activated. 

Also got message from Ultimate Addons support to try updating the latest elementor, 3.7.4 and pro version 3.7.5. Did this and deleted all cache again and restarted the server and regenerated the files via Admin Dashboard > Elementor > Tools and then hard reloaded the page. I have also tried in incognito tab. Still the same problem occurs. Don't really know what to try next?

**Comment by matipojo** [comment]
> @nakov Hi Nakov, thanks for your message. I have now tried to clear all cache I can think of, deleted the cache folder from the FTP also and restarted the server numerous times. We had breeze caching plugin installed from the start, but I have purged it and now the plugin is no longer activated.
> 
> Also got message from Ultimate Addons support to try updating the latest elementor, 3.7.4 and pro version 3.7.5. Did this and deleted all cache again and restarted the server and regenerated the files via Admin Dashboard > Elementor > Tools and then hard reloaded the page. I have also tried in incognito tab. Still the same problem occurs. Don't really know what to try next?

Hi @bagesjo, please paste here your console error.

**Comment by bagesjo** [comment]
Hi @matipojo See below, also attached a printscreen if thats easier. 


editor.min.js?ver=3.6.8:3 TypeError: Cannot read properties of undefined (reading 'global')
    at n.isGlobalControl (editor-modules.min.js?ver=3.6.8:2:15414)
    at Object.<anonymous> (editor-modules.min.js?ver=3.6.8:2:15217)
    at Function.each (load-scripts.php?c=0&load%5Bchunk_0%5D=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&load%5Bchunk_1%5D=hooks&ver=6.0.2:4:3053)
    at n.getStyleControls (editor-modules.min.js?ver=3.6.8:2:14938)
    at editor-modules.min.js?ver=3.6.8:2:15100
    at Function.N (load-scripts.php?c=0&load%5Bchunk_0%5D=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&load%5Bchunk_1%5D=hooks&ver=6.0.2:2:9438)
    at h.Collection.each (load-scripts.php?c=0&load%5Bchunk_0%5D=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&load%5Bchunk_1%5D=hooks&ver=6.0.2:10:1129)
    at Object.<anonymous> (editor-modules.min.js?ver=3.6.8:2:15073)
    at Function.each (load-scripts.php?c=0&load%5Bchunk_0%5D=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&load%5Bchunk_1%5D=hooks&ver=6.0.2:4:3053)
    at n.getStyleControls (editor-modules.min.js?ver=3.6.8:2:14938)
consoleError @ editor.min.js?ver=3.6.8:3
editor-modules.min.js?ver=3.6.8:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'global')
    at n.isGlobalControl (editor-modules.min.js?ver=3.6.8:2:15414)
    at Object.<anonymous> (editor-modules.min.js?ver=3.6.8:2:15217)
    at Function.each (load-scripts.php?c=0&load%5Bchunk_0%5D=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&load%5Bchunk_1%5D=hooks&ver=6.0.2:4:3053)
    at n.getStyleControls (editor-modules.min.js?ver=3.6.8:2:14938)
    at editor-modules.min.js?ver=3.6.8:2:15100
    at Function.N (load-scripts.php?c=0&load%5Bchunk_0%5D=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&load%5Bchunk_1%5D=hooks&ver=6.0.2:2:9438)
    at h.Collection.each (load-scripts.php?c=0&load%5Bchunk_0%5D=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&load%5Bchunk_1%5D=hooks&ver=6.0.2:10:1129)
    at Object.<anonymous> (editor-modules.min.js?ver=3.6.8:2:15073)
    at Function.each (load-scripts.php?c=0&load%5Bchunk_0%5D=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&load%5Bchunk_1%5D=hooks&ver=6.0.2:4:3053)
    at n.getStyleControls (editor-modules.min.js?ver=3.6.8:2:14938)

<img width="1913" alt="Skärmavbild 2022-09-01 kl  13 07 50" src="https://user-images.githubusercontent.com/40461843/187899873-ab008409-cf0c-45f7-9d7c-b5e5dfecba2f.png">

**Comment by matipojo** [comment]
> Hi @matipojo See below, also attached a printscreen if thats easier.
> 
> editor.min.js?ver=3.6.8:3 TypeError: Cannot read properties of undefined (reading 'global') at n.isGlobalControl (editor-modules.min.js?ver=3.6.8:2:15414) at Object. (editor-modules.min.js?ver=3.6.8:2:15217) at Function.each (load-scripts.php?c=0&load%5Bchunk_0%5D=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&load%5Bchunk_1%5D=hooks&ver=6.0.2:4:3053) at n.getStyleControls (editor-modules.min.js?ver=3.6.8:2:14938) at editor-modules.min.js?ver=3.6.8:2:15100 at Function.N (load-scripts.php?c=0&load%5Bchunk_0%5D=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&load%5Bchunk_1%5D=hooks&ver=6.0.2:2:9438) at h.Collection.each (load-scripts.php?c=0&load%5Bchunk_0%5D=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&load%5Bchunk_1%5D=hooks&ver=6.0.2:10:1129) at Object. (editor-modules.min.js?ver=3.6.8:2:15073) at Function.each (load-scripts.php?c=0&load%5Bchunk_0%5D=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&load%5Bchunk_1%5D=hooks&ver=6.0.2:4:3053) at n.getStyleControls (editor-modules.min.js?ver=3.6.8:2:14938) consoleError @ editor.min.js?ver=3.6.8:3 editor-modules.min.js?ver=3.6.8:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'global') at n.isGlobalControl (editor-modules.min.js?ver=3.6.8:2:15414) at Object. (editor-modules.min.js?ver=3.6.8:2:15217) at Function.each (load-scripts.php?c=0&load%5Bchunk_0%5D=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&load%5Bchunk_1%5D=hooks&ver=6.0.2:4:3053) at n.getStyleControls (editor-modules.min.js?ver=3.6.8:2:14938) at editor-modules.min.js?ver=3.6.8:2:15100 at Function.N (load-scripts.php?c=0&load%5Bchunk_0%5D=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&load%5Bchunk_1%5D=hooks&ver=6.0.2:2:9438) at h.Collection.each (load-scripts.php?c=0&load%5Bchunk_0%5D=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&load%5Bchunk_1%5D=hooks&ver=6.0.2:10:1129) at Object. (editor-modules.min.js?ver=3.6.8:2:15073) at Function.each (load-scripts.php?c=0&load%5Bchunk_0%5D=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&load%5Bchunk_1%5D=hooks&ver=6.0.2:4:3053) at n.getStyleControls (editor-modules.min.js?ver=3.6.8:2:14938)
> 
> <img alt="Skärmavbild 2022-09-01 kl 13 07 50" width="1913" src="https://user-images.githubusercontent.com/40461843/187899873-ab008409-cf0c-45f7-9d7c-b5e5dfecba2f.png">

Hi, Thanks, it looks like you are running Elementor 3.6.8, not 3.7.x.

**Comment by bagesjo** [comment]
Hi again @matipojo Yes, this time I tried that because Ultimate Addons support adviced me to try downgrading to that version. I have tried with 3.7.4 aswell, see below:

web-cli.min.js?ver=3.7.4:3 TypeError: Cannot read properties of undefined (reading 'global')
    at n.isGlobalControl (editor-modules.min.js?ver=3.7.4:2:15625)
    at Object.<anonymous> (editor-modules.min.js?ver=3.7.4:2:15428)
    at Function.each (load-scripts.php?c=0&load%5Bchunk_0%5D=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&load%5Bchunk_1%5D=hooks&ver=6.0.2:4:3053)
    at n.getStyleControls (editor-modules.min.js?ver=3.7.4:2:15149)
    at editor-modules.min.js?ver=3.7.4:2:15311
    at Function.N (load-scripts.php?c=0&load%5Bchunk_0%5D=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&load%5Bchunk_1%5D=hooks&ver=6.0.2:2:9438)
    at h.Collection.each (load-scripts.php?c=0&load%5Bchunk_0%5D=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&load%5Bchunk_1%5D=hooks&ver=6.0.2:10:1129)
    at Object.<anonymous> (editor-modules.min.js?ver=3.7.4:2:15284)
    at Function.each (load-scripts.php?c=0&load%5Bchunk_0%5D=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&load%5Bchunk_1%5D=hooks&ver=6.0.2:4:3053)
    at n.getStyleControls (editor-modules.min.js?ver=3.7.4:2:15149)
error @ web-cli.min.js?ver=3.7.4:3
editor-modules.min.js?ver=3.7.4:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'global')
    at n.isGlobalControl (editor-modules.min.js?ver=3.7.4:2:15625)
    at Object.<anonymous> (editor-modules.min.js?ver=3.7.4:2:15428)
    at Function.each (load-scripts.php?c=0&load%5Bchunk_0%5D=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&load%5Bchunk_1%5D=hooks&ver=6.0.2:4:3053)
    at n.getStyleControls (editor-modules.min.js?ver=3.7.4:2:15149)
    at editor-modules.min.js?ver=3.7.4:2:15311
    at Function.N (load-scripts.php?c=0&load%5Bchunk_0%5D=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&load%5Bchunk_1%5D=hooks&ver=6.0.2:2:9438)
    at h.Collection.each (load-scripts.php?c=0&load%5Bchunk_0%5D=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&load%5Bchunk_1%5D=hooks&ver=6.0.2:10:1129)
    at Object.<anonymous> (editor-modules.min.js?ver=3.7.4:2:15284)
    at Function.each (load-scripts.php?c=0&load%5Bchunk_0%5D=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&load%5Bchunk_1%5D=hooks&ver=6.0.2:4:3053)
    at n.getStyleControls [(editor-modules.min.js?ver=3.7.4:2:15149)]

<img width="962" alt="Skärmavbild 2022-09-01 kl  14 32 08" src="https://user-images.githubusercontent.com/40461843/187914679-3e21ad35-8f19-4d8a-aacb-09c8ed413998.png">

**Comment by ozbaster** [comment]
Hello everyone, for me, unfortunately nothing is solved.

Elementor and Elementor Pro 3.7.4, the problem continues.

I managed, however, to understand that the conflict is generated in some way with the Yoast Premium plugin and that it only happens with elements already present on the page.

For example a header widget.
When I create a new one, the problem disappears.

I asked Elementor and Yoast for assistance but either they didn't answer me or they bounced the problem between suppliers.

I do not know what to do ...

**Comment by udidol** [comment]
@ozbaster Could you paste a screenshot of your error here please?

**Comment by ozbaster** [comment]
Sure,
this the error.
<img width="426" alt="Schermata 2022-09-04 alle 18 50 11" src="https://user-images.githubusercontent.com/98642559/188324555-ff2e390d-c7a4-434c-b434-3fc2e8c3b88c.png">

**Comment by ozbaster** [comment]
Here, also a small video ...

https://user-images.githubusercontent.com/98642559/188324713-94adec82-802d-44ff-8c6a-67f7e7decda3.mov

**Comment by udidol** [comment]
@ozbaster
Your error is unrelated to this thread.
Feel free to open a new issue with your error screenshot and video.
If you do so, please include your System Info report in your issue description, and provide detailed steps to reproduce your issue, because we need to re-create it on our end in order to solve it.

Good luck

**Comment by ozbaster** [comment]
It seemed the same to me, in a logical way but with different conflicting elements.

Anyway, thanks.

**Comment by kenarsuleyman** [comment]
![image](https://user-images.githubusercontent.com/22281003/193563285-1631b489-dbe8-4ba8-8278-463778f29625.png)
Issue still there, I don't want rollback to 3.6.8 but seems like it's the only option. There are many releases between, I'm afraid rollback might cause more problems.

**Comment by yairz83** [comment]
Any update? I'm getting the same error on a multisite with every version or free/pro I've tried. Can't use the editor. very frustrating and disappointing.
