### ISSUE TITLE
🔃 🔗 🐞 Bug Report: REPEATER control prevents document "save" after "copy/paste styles" if added to any TAB other than TAB_CONTENT

### ISSUE THREAD

**Issue by VadymPogorelov** [elementor/elementor#19895]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

An error occurs when copying the styles of one widget to another, if any tab (except TAB_CONTENT) of the source widget has a field of the REPEATER type added.
But there is no error when adding a REPEATER type field to the TAB_CONTENT.
Also, after copying styles between widgets with the added REPEATER field in any tab except TAB_CONTENT, the document cannot be saved - an error occurs.

The following error appears in the console: `TypeError: self.attributes[control.name].each is not a function in editor-modules.js`

There is no TAB_CONTENT tab in sections and columns and an error occurs when adding a REPEATER type field to any existing tab. But if you specify TAB_CONTENT when adding, it appears and there are no errors when copying styles and saving the document!

### Steps to reproduce

1. Activating the theme "Twenty Twenty One"
2. Activating the plugin "Elementor"
3. Add the following code to functions.php:

```php
// Add "Audio Effects" to all elements
if ( ! function_exists( 'add_params_audio_effects' ) ) {
	add_action( 'elementor/element/before_section_start', 'add_params_audio_effects', 10, 3 );
	function add_params_audio_effects( $element, $section_id, $args ) {

		if ( ! is_object( $element ) ) return;

		if ( in_array( $element->get_name(), array( 'common' ) ) && $section_id == '_section_responsive' ) {
			
			$element->start_controls_section( 'section_audio_effects', array(
																		'tab' => \Elementor\Controls_Manager::TAB_ADVANCED,
																		'label' => 'Audio Effects'
																	) );
			$repeater = new \Elementor\Repeater();
			
			$repeater->add_control( 'event', array(
							'label' => 'Event',
							'label_block' => false,
							'type' => \Elementor\Controls_Manager::SELECT,
							'options' => array(
								'hover' => 'Hover',
								'click' => 'Click'
							),
							'default' => 'hover',
			) );
			
			$controls = $repeater->get_controls();

			$element->add_control( 'audio_effects', array(
				'label' => '',
				'type' => \Elementor\Controls_Manager::REPEATER,
				'default' => array(
								array(
									'event' => 'hover'
								)
							),
				'fields' => $controls,
				'title_field' => '{{{ event }}}'
			) );

			$element->end_controls_section();
		}
	}
}

```
4. Create a new page and click "Edit with Elementor" or open an existing one in the editor
5. Add a new section, insert two elements into it (for example, a Heading). 
6. For the first widget, change any property that can be copied in styles, such as color.
7. Right click on the first element, select "Copy" https://prnt.sc/pO9DvvJZSWql
8. Right click on the second element, select "Paste style" https://prnt.sc/lFWiYZhKF7GG
9. The styles were copied, but we get an error message "Uncaught TypeError: self.attributes[control.name].each is not a function" in the editor-modules.js https://prnt.sc/PzGrbOYluCXR
10. If you try to save the document after copying the styles, the following error occurs: https://prnt.sc/5TvZtbYVt5N7

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

https://pastebin.com/zFAWpRLr

**Comment by nicholaszein** [comment]
Thank you for the report @VadymPogorelov.

Can you confirm this happens with native Elementor widgets?

**Comment by VadymPogorelov** [comment]
> Can you confirm this happens with native Elementor widgets?

Yes. As you can see from the screenshots above, I demonstrated all the actions on the native "Heading" widget.
This problem occurs with all elements (including sections and columns). Moreover, if in any element (including in a section and column) you add a field of type REPEATER to TAB_CONTENT - everything works fine and there are no problems.

**Comment by sayedulsayem** [comment]
Faced the same issue. I was going to report it. Thank you @VadymPogorelov

**Comment by nicholaszein** [comment]
Hello @VadymPogorelov,

thanks for the feedback. 🙏 

Can you please confirm you followed the documentation outlined [here](https://developers.elementor.com/docs/controls/classes/control-repeater/) and [here](https://developers.elementor.com/docs/hooks/injecting-controls/)?

Can you share the entirety of your code?

**Comment by VadymPogorelov** [comment]
In the first post, I described the detailed steps to reproduce the problem. In the same place, I have provided the complete code snippet that was added to the functions.php file in the twentytwentyone theme: https://prnt.sc/ox247ld5y_kX
No plugins other than Elementor installed. No more code has been added to the theme.

**Comment by rami-elementor** [comment]
I've managed to recreate the issue. But... when saving and reloading, the new values work as expected.

**Comment by VadymPogorelov** [comment]
See screenshots below:

https://prnt.sc/eAyzcZ5vBxFT
https://prnt.sc/0mX0eVQlJkuN
https://prnt.sc/ciKcH4dqxhUW
https://prnt.sc/8WW_Hl9-koWn

**Comment by nicholaszein** [comment]
Hello @VadymPogorelov,

Thanks for sharing the screenshots! 🙏 

Although we are managing to recreate your issue, we still haven't reproduced it in its entirety.

I know you've already said you're following the API, but please make sure your code does not have any errors or is not using invalid, or unsupported methods.

**Comment by VadymPogorelov** [comment]
All my code is presented in the first post of this thread.  No other code has been added to the theme! 
The default theme "Twentytwentyone" and the Elementor plugin are active.
No third party plugin is active anymore: https://prnt.sc/IibXo-mRrO9i
Elementor latest version: https://prnt.sc/rOrwPN4v9GfY
Wordpress also: https://prnt.sc/ufEPSAtSlMxQ

New installation of WordPress on a clean database.
I did the steps described in the first post again.
Result after "Paste Style": https://prnt.sc/203e7blfO_hP

**Comment by nicholaszein** [comment]
Thanks @VadymPogorelov!

We will look into it and see if we can reproduce the issue.

**Comment by VadymPogorelov** [comment]
In version 3.9, the problem is partially solved. Indeed, now when adding fields of the REPEATER type to any tab, updating the document after copying the styles works well.

But the problem remains in some fields of the REPEATER type (I have not figured out the pattern yet). 
And it is treated if the 'tab' attribute with the desired value is added to each field inside the REPEATER (if it differs from TAB_CONTENT, because Elementor assigns this value to such an attribute by default). 
After this "improvement" there is no problem with updating the document after copying the styles.

Let me remind you that all this happens only if the REPEATER type field is found in the widget on any tab, except for TAB_CONTENT

**Comment by dsolimini** [comment]
I want to double-down on the importance of this bug. We have been updating a website to new branding and sorely missed paste-styles.

**Comment by VadymPogorelov** [comment]
The problems are not over.
For example, if I add REPEATER with only MEDIA and SLIDER fields - everything is ok: https://prnt.sc/9orR1OmnoQUT
But if you add another TEXT field (and not even the first one) - after copying the styles, an error occurs when saving the document: https://prnt.sc/pKZ3Fu_vKRDu

**Comment by udidol** [comment]
> 

Why is your condition value an array?

**Comment by udidol** [comment]
> It seems to me that I found a dependency in which an error appears. If the REPEATER field has a 'condition' attribute, an error occurs after copying the styles and click 'Update': https://prnt.sc/vmYuPNO03gnE and https://prnt.sc/yczQ_yDs5VPs If 'condition' is removed (commented out) - there will be no error: https://prnt.sc/q75RqYEwu7VY and https://prnt.sc/xcdhoO3c6S4l For testing, use the following code snippet pasted in the functions.php of the Twenty Twenty One theme:
> 
> ```
> // Add "Audio Effects" to all elements
> if ( ! function_exists( 'add_params_audio_effects' ) ) {
> 	add_action( 'elementor/element/before_section_start', 'add_params_audio_effects', 10, 3 );
> 	function add_params_audio_effects( $element, $section_id, $args ) {
> 
> 		if ( ! is_object( $element ) ) return;
> 
> 		if ( in_array( $element->get_name(), array( 'common' ) ) && $section_id == '_section_responsive' ) {
> 			
> 			$element->start_controls_section( 'section_audio_effects', array(
> 																		'tab' => \Elementor\Controls_Manager::TAB_ADVANCED,
> 																		'label' => 'Audio Effects'
> 																	) );
> 			$element->add_control( 'audio_effects_allowed', array(
> 				'label' => 'Allow audio effects',
> 				'label_block' => false,
> 				'type' => \Elementor\Controls_Manager::SWITCHER,
> 				'return_value' => 'on'
> 			) );
> 
> 			$repeater = new \Elementor\Repeater();
> 			
> 			$repeater->add_control( 'event', array(
> 							'tab' => \Elementor\Controls_Manager::TAB_ADVANCED,
> 							'label' => 'Event',
> 							'label_block' => false,
> 							'type' => \Elementor\Controls_Manager::SELECT,
> 							'options' => array(
> 								'hover' => 'Hover',
> 								'click' => 'Click'
> 							),
> 							'default' => 'hover',
> 			) );
> 			
> 			$element->add_control( 'audio_effects', array(
> 				'label' => '',
> 				'type' => \Elementor\Controls_Manager::REPEATER,
> 				'default' => array(
> 								array(
> 									'event' => 'hover',
> 									'selectors' => ''
> 								)
> 							),
> 				'fields' => $repeater->get_controls(),
> 				'condition' => array(
> 					'audio_effects_allowed' => array( 'on' ),
> 				),
> 				'title_field' => '{{{ event }}}'
> 			) );
> 
> 			$element->end_controls_section();
> 		}
> 	}
> }
> ```

Also, this code has a lot of problems with it.

This bug was fixed in 3.9.0.

Any 3rd party extensions that use workarounds such as wrapping the repeater controls with an `array_values()` call, like so - `'fields' => array_values( $repeater->get_controls() )` - will not work until they remove the wrapping with `array_values()` and call the repeater fields like is intended.

**Comment by VadymPogorelov** [comment]
> @VadymPogorelov Why is your condition value an array?

Why these replies? The elementor allows using both single values ​​and arrays of values ​​in the values ​​of the 'condition' parameters. Moreover, in the code of the Elementor itself, there are also such cases when one value is wrapped in an array: https://prnt.sc/HoY10NsyhTkA
After all, it is clear that this has nothing to do with the problem.

> Also, this code has a lot of problems with it. Any 3rd party extensions that use workarounds such as wrapping the repeater controls with an array_values() call, like so - 'fields' => array_values( $repeater->get_controls() ) - will not work until they remove the wrapping with array_values() and call the repeater fields like is intended.

Where did you see array_values() being called in my code?

> This bug was fixed in 3.9.0.

Partially. If the REPEATER field is not on the TAB_CONTENT tab and has the 'condition' ( I removed array from the condition to avoid further questions https://prnt.sc/SdsJu2JfKS-1 ), the error after copying the styles when updating the document still remains: https://prnt.sc/clouAkBA7iG2

Only the Twenty Twenty One theme and Elementor plugin are active

**Comment by udidol** [comment]
@VadymPogorelov
You are right, using the value as an array has nothing to do with the problem. It is still not the best practice.

The `array_values()` usage comment wasn't pointed at you personally, it was pointed at other 3rd party developers that utilize this practice.

I took your code, fixed it where it needed to be fixed, and implemented it. Could not reproduce your error with or without a condition on the control.

**Comment by VadymPogorelov** [comment]
I reproduced the following steps again:

1) On a fresh install, WordPress activated the Twenty Twenty One theme and the Elementor plugin:
https://prnt.sc/MgL0s5ve0s_T
https://prnt.sc/kW9ddaw3RbBA
https://prnt.sc/jDczMYlcRpAX

2) The following code is added to the end of the functions.php file: https://prnt.sc/QhCEYM7Nuo2n
```
// Add "Audio Effects" to all elements
if ( ! function_exists( 'add_params_audio_effects' ) ) {
	add_action( 'elementor/element/before_section_start', 'add_params_audio_effects', 10, 3 );
	function add_params_audio_effects( $element, $section_id, $args ) {

		if ( ! is_object( $element ) ) return;

		if ( in_array( $element->get_name(), array( 'common' ) ) && $section_id == '_section_responsive' ) {
			
			$element->start_controls_section( 'section_audio_effects', array(
																		'tab' => \Elementor\Controls_Manager::TAB_ADVANCED,
																		'label' => 'Audio Effects'
																	) );
			$element->add_control( 'audio_effects_allowed', array(
				'label' => 'Allow audio effects',
				'label_block' => false,
				'type' => \Elementor\Controls_Manager::SWITCHER,
				'return_value' => 'on'
			) );

			$repeater = new \Elementor\Repeater();
			
			$repeater->add_control( 'event', array(
							'tab' => \Elementor\Controls_Manager::TAB_ADVANCED,
							'label' => 'Event',
							'label_block' => false,
							'type' => \Elementor\Controls_Manager::SELECT,
							'options' => array(
								'hover' => 'Hover',
								'click' => 'Click'
							),
							'default' => 'hover',
			) );
			
			$element->add_control( 'audio_effects', array(
				'label' => '',
				'type' => \Elementor\Controls_Manager::REPEATER,
				'default' => array(
								array(
									'event' => 'hover',
									'selectors' => ''
								)
							),
				'fields' => $repeater->get_controls(),
				'condition' => array(
					'audio_effects_allowed' => 'on',
				),
				'title_field' => '{{{ event }}}'
			) );

			$element->end_controls_section();
		}
	}
}
```

3) Then I created a new page in Elementor, added a section with two columns to it, and inserted the Heading widget into each:
https://prnt.sc/14psE494vKLj
https://prnt.sc/LUD4DbFVI442

4) On the left widget I pressed the right mouse button and selected 'Copy', then on the right I pressed the right mouse button and selected "Paste Style" (you can not even change the widget styles before that)
https://prnt.sc/i7nuxEqN4cAO
https://prnt.sc/1lhCeV6XfVXt

5) Press the "Publish" button (or "Update" if the document was previously saved). 
I didn't even have time to do it - while I was writing here, Elementor was autosaving and an error occurred
https://prnt.sc/pSL2SsRr2Wja

**Comment by iamsparkfactory** [comment]
> I reproduced the following steps again:
> 
> 1. On a fresh WordPress installation, I am activate the Twenty Twenty One theme and the Elementor plugin:
>    https://prnt.sc/MgL0s5ve0s_T
>    https://prnt.sc/kW9ddaw3RbBA
>    https://prnt.sc/jDczMYlcRpAX
> 2. The following code is added to the end of the functions.php file: https://prnt.sc/QhCEYM7Nuo2n
> 
> ```
> // Add "Audio Effects" to all elements
> if ( ! function_exists( 'add_params_audio_effects' ) ) {
> 	add_action( 'elementor/element/before_section_start', 'add_params_audio_effects', 10, 3 );
> 	function add_params_audio_effects( $element, $section_id, $args ) {
> 
> 		if ( ! is_object( $element ) ) return;
> 
> 		if ( in_array( $element->get_name(), array( 'common' ) ) && $section_id == '_section_responsive' ) {
> 			
> 			$element->start_controls_section( 'section_audio_effects', array(
> 				'tab' => \Elementor\Controls_Manager::TAB_ADVANCED,
> 				'label' => 'Audio Effects'
> 			) );
> 			$element->add_control( 'audio_effects_allowed', array(
> 				'label' => 'Allow audio effects',
> 				'label_block' => false,
> 				'type' => \Elementor\Controls_Manager::SWITCHER,
> 				'return_value' => 'on'
> 			) );
> 
> 			$repeater = new \Elementor\Repeater();
> 			
> 			$repeater->add_control( 'event', array(
> 							'tab' => \Elementor\Controls_Manager::TAB_ADVANCED,
> 							'label' => 'Event',
> 							'label_block' => false,
> 							'type' => \Elementor\Controls_Manager::SELECT,
> 							'options' => array(
> 								'hover' => 'Hover',
> 								'click' => 'Click'
> 							),
> 							'default' => 'hover',
> 			) );
> 			
> 			$element->add_control( 'audio_effects', array(
> 				'label' => '',
> 				'type' => \Elementor\Controls_Manager::REPEATER,
> 				'default' => array(
> 								array(
> 									'event' => 'hover',
> 									'selectors' => ''
> 								)
> 							),
> 				'fields' => $repeater->get_controls(),
> 				'condition' => array(
> 					'audio_effects_allowed' => 'on',
> 				),
> 				'title_field' => '{{{ event }}}'
> 			) );
> 
> 			$element->end_controls_section();
> 		}
> 	}
> }
> ```
> 
> 3. Then I'm create a new page in Elementor, add a section with two columns to it, and insert the Heading widget into each:
>    https://prnt.sc/14psE494vKLj
>    https://prnt.sc/LUD4DbFVI442
> 4. I'm press the right mouse button on the left widget and select 'Copy', then I'm press the right mouse button on the right widget and select "Paste Style"
>    https://prnt.sc/i7nuxEqN4cAO
>    https://prnt.sc/1lhCeV6XfVXt
> 5. Press the "Publish" button (or "Update" if the document was previously saved).
>    I didn't even have time to do it - while I was writing here, Elementor was autosaving and an error occurred
>    https://prnt.sc/pSL2SsRr2Wja

The same errors persist after updating Elementor to the latest version (v3.9.0) by following the same exact steps (while using the same default WordPress theme and on a fresh WordPress installation without having any other active plugins).
![elementor-copy-paste-error](https://user-images.githubusercontent.com/120528328/207468919-bb56d0d2-ca25-44f1-aa29-392b4efe4af7.png)

**Comment by udidol** [comment]
A fix for this issue will be released in the next patch version of Elementor.

**Comment by nicholaszein** [comment]
Hello there @VadymPogorelov, @sayedulsayem, @dsolimini, and @iamsparkfactory!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor **v3.9.1**! 🥳 

✔️ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
