### ISSUE TITLE
When "Page Transitions" is active the lightbox in Woocommerce product page isn't working

### ISSUE THREAD

**Issue by webreach** [elementor/elementor#19943]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When the experiment "Page Transitions" is active, the lightbox in woocommerce product page isn't working

### Steps to reproduce

make sure Woocommerce is installed 
1) go to Elementor - settings - experiments
2) make "Page Transitions" active
3) at the product page clicking the image takes you to the image page (direct URL) instead of opening the lightbox

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.23.1
	MySQL version: MariaDB Server v5.5.40-MariaDB-36.1
	PHP Version: 7.3.33
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.2
	Site URL: https://ufo.ussl.co.il
	Home URL: https://ufo.ussl.co.il
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 128M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: Asia/Jerusalem
	Admin Email: roi@webreach.co.il
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.6.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: he_IL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields PRO
		Version: 6.0.0
		Author: WP Engine

	ATUM Inventory Management for WooCommerce
		Version: 1.9.21
		Author: Stock Management Labs™

	Elementor
		Version: 3.7.7
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.7
		Author: Elementor.com

	JetMenu
		Version: 2.2.3
		Author: Crocoblock

	JetSmartFilters
		Version: 2.3.14
		Author: Crocoblock

	Loco Translate
		Version: 2.6.2
		Author: Tim Whitlock

	One Click Accessibility
		Version: 2.0.3
		Author: One Click Accessibility

	Safe SVG
		Version: 2.0.3
		Author: 10up

	Smash Balloon Instagram Feed
		Version: 6.0.7
		Author: Smash Balloon

	Ultimate Gift Cards For WooCommerce
		Version: 2.4.5
		Author: WP Swings

	User Switching
		Version: 1.7.0
		Author: John Blackbourn & contributors

	Variation Swatches for WooCommerce
		Version: 2.0.10
		Author: Emran Ahmed

	WooCommerce
		Version: 6.9.4
		Author: Automattic

	WP Sitemap Page
		Version: 1.9.1
		Author: Tony Archambeau

	YITH WooCommerce Wishlist
		Version: 3.13.0
		Author: YITH

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast

== Elements Usage ==
	
	footer : 1
		container : 1
		form : 1
		heading : 1
		icon : 1
		icon-list : 1
		nav-menu : 3
		social-icons : 1
		text-editor : 6
		theme-site-logo : 1
	header : 1
		icon-list : 3
		jet-mega-menu : 1
		nav-menu : 1
		search-form : 1
		text-editor : 1
		theme-site-logo : 1
		woocommerce-menu-cart : 1
	popup : 1
		image : 1
		shortcode : 1
		text-editor : 1
	product : 1
		button : 1
		heading : 4
		icon : 1
		share-buttons : 1
		shortcode : 4
		text-editor : 2
		woocommerce-breadcrumb : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-content : 1
		woocommerce-product-images : 1
		woocommerce-product-price : 1
		woocommerce-product-short-description : 1
		woocommerce-product-title : 1
		woocommerce-products : 1
	wp-post : 0
		button : 2
		image : 48
	wp-page : 13
		button : 1
		form : 2
		google_maps : 1
		heading : 27
		icon : 6
		icon-list : 2
		image : 3
		jet-smart-filters-checkboxes : 1
		jet-smart-filters-range : 1
		jet-smart-filters-select : 3
		jet-smart-filters-sorting : 1
		media-carousel : 2
		nav-menu : 1
		shortcode : 8
		social-icons : 1
		text-editor : 17
		woocommerce-products : 6
		wp-widget-instagram-feed-widget : 1
	search-results : 1
		jet-smart-filters-pagination : 1
		theme-archive-title : 1
		wc-archive-products : 1
		woocommerce-breadcrumb : 1
	product-archive : 2
		button : 2
		image : 1
		jet-smart-filters-checkboxes : 1
		jet-smart-filters-pagination : 2
		jet-smart-filters-range : 2
		jet-smart-filters-select : 5
		jet-smart-filters-sorting : 2
		shortcode : 2
		text-editor : 1
		theme-archive-title : 2
		theme-post-featured-image : 1
		theme-post-title : 1
		wc-add-to-cart : 1
		wc-archive-products : 2
		woocommerce-breadcrumb : 2
		yith_wcwl_add_to_wishlist : 1
	error-404 : 1
		button : 1
		heading : 1
		text-editor : 1

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 352022-09-20 16:16:54 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.7.6',
)]
2022-09-20 16:16:55 [info] elementor::elementor_updater Started 
2022-09-20 16:16:55 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-20 16:16:56 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-20 16:16:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.4',
  'to' => '3.7.6',
)]
2022-09-20 16:20:01 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.5',
  'to' => '3.7.6',
)]
2022-09-20 16:20:01 [info] elementor-pro::elementor_pro_updater Started 
2022-09-20 16:20:01 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-09-20 16:20:01 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-09-20 16:20:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.5',
  'to' => '3.7.6',
)]
2022-09-20 16:20:02 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'אלמנטור פרו',
  'from' => '3.7.5',
  'to' => '3.7.6',
)]
2022-09-21 01:53:28 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.6',
  'to' => '3.7.7',
)]
2022-09-21 01:53:29 [info] elementor::elementor_updater Started 
2022-09-21 01:53:29 [info] Elementor/Upgrades - _on_each_version Start  
2022-09-21 01:53:29 [info] Elementor/Upgrades - _on_each_version Finished 
2022-09-21 01:53:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.6',
  'to' => '3.7.7',
)]
2022-09-21 02:07:39 [info] elementor-pro::elementor_pro_updater Started 
2022-09-21 02:07:39 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-09-21 02:07:39 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-09-21 02:07:40 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.6',
  'to' => '3.7.7',
)]

PHP: showing 4 of 4PHP: 2022-08-09 14:58:41 [notice X 10][/home/ufousslc/domains/ufo.ussl.co.il/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-21 01:30:22 [error X 1][/home/ufousslc/domains/ufo.ussl.co.il/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /home/ufousslc/domains/ufo.ussl.co.il/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /home/ufousslc/domains/ufo.ussl.co.il/public_html/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /home/ufousslc/domains/ufo.ussl.co.il/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /home/ufousslc/domains/ufo.ussl.co.il/public_html/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /home/ufousslc/domains/uf [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-21 02:17:03 [error X 1][/home/ufousslc/domains/ufo.ussl.co.il/public_html/wp-content/plugins/elementor-pro/plugin.php::465] Uncaught Error: Class 'ElementorPro\Core\Connect\Manager' not found in /home/ufousslc/domains/ufo.ussl.co.il/public_html/wp-content/plugins/elementor-pro/plugin.php:465
Stack trace:
#0 /home/ufousslc/domains/ufo.ussl.co.il/public_html/wp-content/plugins/elementor-pro/plugin.php(121): ElementorPro\Plugin->__construct()
#1 /home/ufousslc/domains/ufo.ussl.co.il/public_html/wp-content/plugins/elementor-pro/plugin.php(511): ElementorPro\Plugin::instance()
#2 /home/ufousslc/domains/ufo.ussl.co.il/public_html/wp-content/plugins/elementor-pro/elementor-pro.php(57): require('/home/ufousslc/...')
#3 /home/ufousslc/domains/ufo.ussl.co.il/public_html/wp-includes/class-wp-hook.php(307): elementor_pro_load_plugin('')
#4 /home/ufousslc/domains/ufo.ussl.co.il/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#5 /home/ufousslc/domains/ufo.ussl.co.il/public_html/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#6 /home/ufousslc/domains/ufo.ussl.co.il/public_html/wp-settings.php(461): do_ [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-09-28 16:46:59 [notice X 23][/home/ufousslc/domains/ufo.ussl.co.il/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-image.php::40] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 3 of 3JS: 2022-08-09 12:21:40 [error X 1][https://ufo.ussl.co.il/wp-content/plugins/elementor/assets/lib/backbone/backbone.marionette.min.js?ver=2.4.5.e1:24:19952] View (cid: \"view15909\") has already been destroyed and cannot be used. 
JS: 2022-09-13 17:03:23 [error X 6][https://ufo.ussl.co.il/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.4:3:1060434] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-09-28 14:20:46 [error X 1][https://ufo.ussl.co.il/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.7.7:2:19453] Cannot read properties of undefined (reading \'top\') 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @webreach! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by genilto** [comment]
Same problem here. If I enable page transitions, the lightbox feature stops working. When I click in some image, it opens the lightbox, but enables the page transition at the same time, redirecting the page to the media file.

**Comment by nicholaszein** [comment]
Hello @webreach and @genilto!

We made some tests and couldn't reproduce your issue. Can you please give me some more information?

1. Did you try to test it using only Elementor, Elementor Pro, WooCommerce, and Hello Elementor active?
2. Just to confirm, this happens with a Single Product template active, or you are editing product-by-product with Elementor?
3. Does this happen with any Elementor add-on active? Including Yoast (it has an integration)?
4. I see there is an add-on for WC for Variation Swatches. Usually, these add-ons tend to modify the Product Gallery, have you tested without them enabled?

**Comment by webreach** [comment]
Hey, same as @genilto
1. yes
2. single product template is activated
3. no
4. switched it off, didn't help
5. yes

**Comment by genilto** [comment]
5. Yes.

**Comment by nicholaszein** [comment]
Thank you guys @webreach @genilto. 🙏 

I could reproduce your issue. I'm forwarding my findings to the team! 💪 

Best regards!

**Comment by hking1991** [comment]
Any update on this? This is not just affecting the WooCommerce Gallery, but a lot of third party gallery solutions.

**Comment by runthegold** [comment]
I notice a similar issue with popup instance, in this case for mobile menu, seems to create the same direct to url instead of opening popup. Is this related?

**Comment by adrian0015** [comment]
3.10.2 and Page transition still breaks Lightbox. Any progress/update on this issue? Thx.

**Comment by dameer** [comment]
This problem exists for soooooooooooooooooooo long time and nobody in charge doesn't give a sh**. 
Elementor developers will sooner or later figure out that adding a ton of useless features doesn't mean much as long as all of these old bugs and issues are kept under the carpet. Shame on you people in charge!

**Comment by sushmak02** [comment]
Any update on this issue?

**Comment by dameer** [comment]
People, this isn't going anywhere nor there's anyone willing to fix it. This is just another insignificant Elementor bug in the sea of bugs, marinating for almost a year. You should see how swiftly and thoroughly bugs are fixed with Bricks Builder. It makes you think that the Elementor bug report is a joke.

**Comment by nicholaszein** [comment]
Hello everyone!

Thank you for your patience! 🙏 

I wanted to update you on this issue. We are aware of the problem and our team is working on a fix. Please keep in mind that since this affects multiple components, it's not something that could be fixed easily. It requires intrinsic changes that need to be carefully considered to avoid breaking backward compatibility. We can’t say exactly when it'll be sorted out, but we kindly ask for your patience. Thanks for understanding! 😉

Best regards

**Comment by ogio** [comment]
+1, small issue but ruining UX on website hugly. Is it possible to find some custom code that can kill showing page transitons on appearing of elementor lightbox?

**Comment by Raymondhou0917** [comment]
The problem still exists, it seems that it hasn't been resolved after over a year. 
Page transitions is a great feature that can greatly enhance the UX, but currently it conflicts with Lightbox. 

Clicking on an image will directly go to the image's URL, which greatly disrupts the reading experience. 
Please prioritize the bug fix for this issue as soon as possible, Elementor official team. Thank you! 🙏🏼

**Comment by femcofocus** [comment]
This is still an existing problem.
Elementor... please fix this!
As a photographer, it is an absolute MUST for me to have a working lightbox gallery. 
It's actually a first priority as a photographer, to have a working portfolio.

I've disabled the preloader and page transition option for now, because the problem still isn't resolved. But please FIX THIS.

**Comment by DougCapron** [comment]
This is still not fixed 2 years in. I am so disappointed. The page transitions look great but the UX is terrible with the page transitions being triggered by lightbox activation. I don't understand how they prioritize. Any image oriented website uses the  lightbox. The page transitions are useless in this case.

**Comment by Girovagante** [comment]
Please, FIX THIS. Thanks!

**Comment by Milord85** [comment]
Still need a FIX after 730 days. C'mon let's go to the moon...

**Comment by Streder** [comment]
something like this in hello theme functions.php?  Subbing out FooGallery for whatever the initial lightbox tag is?

`shouldPageTriggerTransition(element) {
    // Existing checks...
    
    // Add this check
    if (element.closest('.foogallery')) {
        return false;
    }
    
    // Rest of the existing function...
}`

**Comment by Streder** [comment]
"data-e-disable-page-transition|true"

Fine for a single image, but what about a galley?  https://ederfan.com/experimental/
