### ISSUE TITLE
✔️ 🐞 Bug Report: Column widths do not add up to 100%

### ISSUE THREAD

**Issue by LearnWPBasics** [elementor/elementor#2042]
Elementor 1.5.5

This has been apparent since the first beta of 1.5.

When attempting to manually (or dragging) set the column widths on more than 2 columns, the percentages do not add up to 100%. There will be one that is decimal. 

Example: If you set the left one to 30 and the center one to 30, the right one is 39.333 (or some other decimal value) instead of 40. Setting the right one to 40 will cause one of the other two to have a decimal value. 

This makes it extremely difficult (if not impossible) to have columns in adjacent sections to line up or to be accurately placed. For example, in the preceding 30 30 40 setup, if you wanted a section above this one to have two columns with the first one 60 and the second one 40, that would work, but one or the other below will be a "bit off".

Cheers!
Lyle

**Comment by dougm1966** [comment]
And it's a bugger...

**Comment by PascalBernhard** [comment]
I have a similar problem with elementor but in my case the last column (doesn't matter if 2,3 or more) will go over 100%. This is conflicting with my responsive design template. If I use the structure presets, everything works fine. This error only appears if I'll type in the column width manualy or drag the column to resize it. This is very annoying since I'm working on a site for a customer based on the elementor page builder. Any help would be very much appreciated.

**Comment by renehamburger** [comment]
I've got the same problem.. But also a more serious issue with invalid column width css rules due to decimal comma instead of decimal point being used::
```
@media(min-width: 768px) {
    .elementor-3909 .elementor-element.elementor-element-sydnowc {
        width:72%;
    }

    .elementor-3909 .elementor-element.elementor-element-ekgvbj9 {
        width: 28,02%;
    }
}
```
This may due to the WordPress language/locale being set to German. But as I can't set the two widths both to integer values (the other one always changes as well), the decimal comma is always present.

**Comment by drank** [comment]
I can confirm that this is still a problem in 1.8.11. This is extremely annoying bug I must say. In addition, sometimes it is not possible to manually edit the column width percentage - one has to resize them via the handle.

**Comment by drank** [comment]
Is there a chance this gets fixed in 1.9?

**Comment by black-eye** [comment]
I can confirm this bug too. When you start to mess with the widths of the 3 column section, it's practically impossible to get the numbers back to sum of 100%. 

As far as I tried, the problem concernes only to 3, 6 and 7 columns.

One solution could be to (optionally) turn off the automatic adding up to 100% width. Which would actually resolve another grid problem (multiple rows in one section) mentioned here: #2218 and here: #2261.

**Comment by td75** [comment]
Is there any progress on this bug? Also having problems with 3 columns sizing.

**Comment by Zach-Toth** [comment]
Problem still present in 2.4.3 on almost every site I use Elementor on. Ex. Happens after changing column width of 2 column row. Start with 2 columns at 50%. Change one column to 40% then the other will not go to 60%. It's like changing the one column to 40% deletes 10% of the row and no matter what proportions I input the total width will only add up to 90%. PLEASE ADDRESS THIS! Below is an image of the affect: 
<img width="464" alt="screen shot 2019-01-22 at 1 23 00 pm" src="https://user-images.githubusercontent.com/32491990/51559992-019ca600-1e49-11e9-84e4-ebdd8bcee56e.png">

**Comment by mgustavs** [comment]
Same same..  3 columns tweaked and now they leave a gap even on 0,000001 % off from 100%..

Any workaround for this?...

<img width="692" alt="Screen Shot 2019-04-05 at 16 10 05" src="https://user-images.githubusercontent.com/47918624/55630550-9feca680-57be-11e9-9f5f-4316c7d15931.png">

**Comment by mgustavs** [comment]
Same same.. 3 columns tweaked and now they leave a gap even on 0,000001 % off from 100%..

Any workaround for this?...

<img width="360" alt="Screen Shot 2019-04-05 at 16 10 05" src="https://user-images.githubusercontent.com/47918624/55630767-1ab5c180-57bf-11e9-93dd-a0fdde427bf2.png">

**Comment by mgustavs** [comment]
Same same on 2.5.11 (2.5.4.Pro)..   3 columns tweaked and now they leave a gap even on 0,000001 % off from 100%..

Any workaround for this?...
<img width="360" alt="Screen Shot 2019-04-05 at 16 10 05" src="https://user-images.githubusercontent.com/47918624/55630854-59e41280-57bf-11e9-869d-11d8c2b95684.png">

**Comment by mgustavs** [comment]
Same still on 2.5.11 (2.5.4.Pro).. 3 columns tweaked and now they don't add up to be 100%. I set first and last column to 31,98 and middle one automatically jumped to 36,039.

I think this problem is mathematical nature because 1/3 is 0,333333333333333333..... Then min column width adjustment in Elementor is 0,001 and if I count my three columns together, they add up to be exactly 99,999 thus program does not know which one to round up by this division leftover 0,001 and leaves it in "no mans land”.

My guess there are two possible solutions - add 0,001 on uneven number column grids (3,5,7…) to the middle column or set negative margins for all columns content. First seems to be more correct, but maybe second one is easier to implement. BTW I have had this 1px gap coming up also on 4 column grid with default column widths exactly in a middle vertically and every row horizontally (Mother section settings: full width, no gap, default height), but that is far less occurrent. Maybe negative content margins for all columns is the way to go.

At least that is the solution I go with now:
I used negative left and right margins for widgets inside the columns. But NOT the columns themselves - cause that shifts the column only leftwards and leaves a gap on the other side. But if you negative margin left and right the content widget, it expands both ways covering the gap (again - no negative margins on top cause that leaves gap at the bottom). To compensate the expand of the middle columns content downwards, I negative margined both side columns with equal negative sum as middle one (towards middle, cause I don’t want to cause possible overlay problems for +1920 screen lovers). Here I also tried adjusting column widths again, but that doesn’t seem to get as even result on the bottom as equal negative margin sums.

**Comment by antoanst** [comment]
The issue comes from using the default multi-column layouts and then modifying them with custom widths. Try creating a single column section, select that column and duplicate it as many times as you need and then set the desired width %.

**Comment by jellyfyi** [comment]
@shilo-ey This issue not fixed yet? I'm 90% into a client build only to find out this is a BIG issue!

**Comment by litmol** [comment]
Issue is still a problem in version 2.7.5 (2.7.3 in Pro). Tried antoanst suggestion but it didn't solve the problem. Once changed the columns width the last one was a fraction of a percentage.

**Comment by realstephenzhao** [comment]
This problem is still not solved.

**Comment by klainser** [comment]
This problem is still here, two years later.

**Comment by jotcreative** [comment]
+1

**Comment by tatumrae** [comment]
Also having the same issue. On Elementor Pro 2.8.3

**Comment by mukeshpanchal27** [comment]
Any update on this?

**Comment by yoneth** [comment]
Still having this issue as in version 2.8.4

**Comment by StrategyLLC** [comment]
same for me, creating a single column and then copy/pasting or duplicating doesn't help. it's insane that something this simple hasn't been fixed.

**Comment by farresto** [comment]
I have the same problem, and unfortunately solution provided in the comments doesn't work.

**Comment by MichaelDarko** [comment]
After almost 3 years of using Elementor i still have to write my own CSS to make column widths add up to 100%.

I know that fixing the basics probably doesn't generate new customers like the new "cool" features, but this is just silly.

**Comment by biomars** [comment]
> 
> 
> After almost 3 years of using Elementor i still have to write my own CSS to make column widths add up to 100%.
> 
> I know that fixing the basics probably doesn't generate new customers like the new "cool" features, but this is just silly.

+1, is there any "easy" way to do it? solve it "manually"? where do you exactly add the code?

Thanks

**Comment by ahmetsali** [comment]
Hi, I think I got a **solution** for this annoying bug; 

- just edit the "Section" and navigate to "Layout > Structure" tab and select anything except "33,33,33" and "16,66,16" (the sum of these numbers are 99 and 98, not 100), 

- then you can adjust the width of the columns by dragging without getting the unwanted gap :)

**Comment by MaxNadeev** [comment]
Elementor, shame on you! I using Elementor PRO. 9 April 2020 problem still exists. 🤦‍♂️🤦‍♂️🤦‍♂️
I should fix using strange way to fix it as described below.

"- just edit the "Section" and navigate to "Layout > Structure" tab and select anything except "33,33,33" and "16,66,16" (the sum of these numbers are 99 and 98, not 100),

then you can adjust the width of the columns by dragging without getting the unwanted gap :)" 

Confirm. Solution works.

**Comment by biomars** [comment]
I already tried this method, but when I try to adjust it manually the other columns randomly change their width, ridiculously sometimes those random percentages never reach 100% and there is a small "bleed" compared to the other containers. Am I the only one experiencing this result?

**Comment by ahmetsali** [comment]
@biomars I no longer have any unwanted gap with the method I shared above, changing a column's width by dragging effects other columns width too, that's the expected behavior if you want to have total control over column widths you need to edit columns one by one starting by the first one and set column width for each column.

**Comment by passananteg** [comment]
> Hi, I think I got a **solution** for this annoying bug;
> 
> * just edit the "Section" and navigate to "Layout > Structure" tab and select anything except "33,33,33" and "16,66,16" (the sum of these numbers are 99 and 98, not 100),
> * then you can adjust the width of the columns by dragging without getting the unwanted gap :)

This works perfectly for me!

**Comment by twerkema** [comment]
+1 on this issue. I have multiple rows that all need to have the exact same widths. Dragging does work but then the other columns in other rows are not exactly the same. When making charts and tables, this is not a viable options. Would love to see this functionality actually work. Other bugs are apparent in columns so it would be nice to see this feature get some love.

**Comment by D3vJust** [comment]
> Elementor, shame on you! I using Elementor PRO. 9 April 2020 problem still exists. 🤦‍♂️🤦‍♂️🤦‍♂️
> I should fix using strange way to fix it as described below.
> 
> "- just edit the "Section" and navigate to "Layout > Structure" tab and select anything except "33,33,33" and "16,66,16" (the sum of these numbers are 99 and 98, not 100),
> 
> then you can adjust the width of the columns by dragging without getting the unwanted gap :)"
> 
> Confirm. Solution works.

Thank you for this.
You safed our live :D

It must be an even number of sections.

**Comment by wpacademy** [comment]
> Elementor, shame on you! I using Elementor PRO. 9 April 2020 problem still exists. 🤦‍♂️🤦‍♂️🤦‍♂️
> I should fix using strange way to fix it as described below.
> 
> "- just edit the "Section" and navigate to "Layout > Structure" tab and select anything except "33,33,33" and "16,66,16" (the sum of these numbers are 99 and 98, not 100),
> 
> then you can adjust the width of the columns by dragging without getting the unwanted gap :)"
> 
> Confirm. Solution works.

Thank you. You saved our miserable lives.

**Comment by jeremyxtech** [comment]
> Hi, I think I got a **solution** for this annoying bug;
> 
> * just edit the "Section" and navigate to "Layout > Structure" tab and select anything except "33,33,33" and "16,66,16" (the sum of these numbers are 99 and 98, not 100),
> * then you can adjust the width of the columns by dragging without getting the unwanted gap :)

Works!

**Comment by teocns** [comment]
100% column width Is still not working.

Time to switch to dive :)

**Comment by atelierdusite** [comment]
Unbelievable,
This bug was reported in **July 2015** and today, **5 years later**, the guys at Elementor have still neither answered nor fixed the issue!

> 
> 
> Hi, I think I got a **solution** for this annoying bug;
> 
>     * just edit the "Section" and navigate to "Layout > Structure" tab and select anything except "33,33,33" and "16,66,16" (the sum of these numbers are 99 and 98, not 100),
> 
>     * then you can adjust the width of the columns by dragging without getting the unwanted gap :)

Alas, does not work to me :(

**Comment by iscottjones** [comment]
**Really disappointing that this isn't fixed after 5 years.** I pay for the unlimited websites package which I am now regretting. May have to find another builder.

Also, don't know if this helps but I calculated the actual width to be 97.87 with 5 columns (32, 2, 32, 2, 29.87). I am spacing how I need them by working out the measures from 97.87% instead of 100%.

**Comment by OsoBear** [comment]
The posted solution did not work for me. Steps to reproduce
1. created a section (defaults to 1 column)
2. add a background image to the section so you can easily see how this still does not work ( a color would work as well)
3. make sure the section is set to no gap
4, make sure the column widget space is set to 0
5. fill the column with a background color (verifies it covers the full section)
6. duplicate the column (still covers the full section)
7. duplicate it again for a total of 3 column ( still covers the full section)
8. now pick you poison - either way it will fail. a. drag to resize a column or b. change it's width value in layout
9. see your section image showing through on the right? you can't get rid of it.

I must agree...to let a bug go on this long is totally unacceptable.

SOLUTION: set your column widths manually using CSS.

**Comment by jeremyxtech** [comment]
@OsoBear @iscottjones @atelierdusite @teocns 

To remove gap for 3 columns just do these 2 steps:

1. Edit Section > Structure > 25, 50, 25

2. Then resize the columns.

If you start with 33. 33. 33 there will always be a gap because they don't add up to 100%.

**Comment by atelierdusite** [comment]
To @OsoBear @iscottjones @teocns

The @jeremyxtech solution works perfectly well!

I implemented it and I was able to resize the columns as I wanted.

The principle is to create a structure with 3 columns in 25, 25, 50 or 25, 50, 25 or even 50, 25, 25, then to resize each column to the desired size.

Hope this will help :-)

**Comment by davinito** [comment]
This problem continues still. I tried everything that i can, I could only fix less than 4 columns using the structure option, but that's all. even i am paying for the elementor pro! I tried to an alternative option; create 2 inner sections with 3 columns and put these into each 2 columns of parent section.-> but this made http 500 error as i used moo many div things.

**Comment by OsoBear** [comment]
I too am a paid Elementor Pro subscriber. I was shocked to see this bug report has been open for 3 years. So I decided to submit a support ticket to see if I could get it resolved.

Here was their reply:

....
First of all, I would like to offer you a sincere apology on behalf of all Elementors' team. We strive to reply to each ticket as soon as possible, with a goal of first response within 24 hours. However, in the midst of the COVID crisis, we have been experiencing a higher than usual volume of tickets whereby delivering responses has been taking us some more time.

I can see this has already been reported to our dev team as a bug. But there is still no fix available for it.

Please keep an eye on https://docs.elementor.com/article/178-changelog to see when this issue gets resolved.

Sorry for the inconvenience. 

......

If they can't resolve an issue as simple as this... it make you wonder. Where does all their subscription money go? For three columns, seems like it would be as simple as:
` #column1, #column2 {
    width: 33%;
}

#column3 {
    width: auto;
}`

Or here's a Javascript function that solves the equation for any number of columns:

`function foo(l, target) {
    var off = target - _.reduce(l, function(acc, x) { return acc + Math.round(x) }, 0);
    return _.chain(l).
            sortBy(function(x) { return Math.round(x) - x }).
            map(function(x, i) { return Math.round(x) + (off > i) - (i >= (l.length + off)) }).
            value();
}

foo([13.626332, 47.989636, 9.596008, 28.788024], 100) // => [48, 29, 14, 9]
foo([16.666, 16.666, 16.666, 16.666, 16.666, 16.666], 100) // => [17, 17, 17, 17, 16, 16]
foo([33.333, 33.333, 33.333], 100) // => [34, 33, 33]
foo([33.3, 33.3, 33.3, 0.1], 100) // => [34, 33, 33, 0]`

I'm really surprised Elementor has not solved this bug.

**Comment by isaldoryt** [comment]
+1

**Comment by joehdevwp** [comment]
+1 
How many years has it been since this was first reported? Elementor, fix your software. 
(The above fix did not work)

**Comment by Fubart** [comment]
> @OsoBear @iscottjones @atelierdusite @teocns
> 
> To remove gap for 3 columns just do these 2 steps:
> 
> 1. Edit Section > Layout > Structure > 25, 50, 25
> 2. Then resize the columns.
> 
> If you start with 33. 33. 33 there will always be a gap because they don't add up to 100%.

Thank you!!!!

**Comment by iscottjones** [comment]
> > @OsoBear @iscottjones @atelierdusite @teocns
> > To remove gap for 3 columns just do these 2 steps:
> > 
> > 1. Edit Section > Layout > Structure > 25, 50, 25
> > 2. Then resize the columns.
> > 
> > If you start with 33. 33. 33 there will always be a gap because they don't add up to 100%.
> 
> Thank you!!!!
> 
> Fixed it for me

I'm glad this worked for you but I think you need to read the thread properly. The problem isn't that 3 collums won't be equal, it's that when you create 3 collums and then try to revert back to 4 columns, the total column width will be less than 100%.

The total column width actually fluctuates between 96% and 99% when this issue occurs, and when resizing individual columns. It's a bug that Removes some of this pixel dimensions.

**Comment by jeremyxtech** [comment]
> I'm glad this worked for you but I think you need to read the thread properly. The problem isn't that 3 collums won't be equal, it's that when you create 3 collums and then try to revert back to 4 columns, the total column width will be less than 100%.
>
>The total column width actually fluctuates between 96% and 99% when this issue occurs, and when resizing individual columns. It's a bug that Removes some of this pixel dimensions.

@iscottjones I think you need to read the thread properly. Nobody is talking about reverting to 4 columns from 3. And besides, the problem you are talking about is an easy fix.

You just have to reset the structure after you change from 3 columns to 4 columns.

Edit Section > Layout > Structure > Reset (small reset button on the bottom left of the structure section)

And way to give a thumbs up to your own post.

**Comment by iscottjones** [comment]
> > I'm glad this worked for you but I think you need to read the thread properly. The problem isn't that 3 collums won't be equal, it's that when you create 3 collums and then try to revert back to 4 columns, the total column width will be less than 100%.
> > The total column width actually fluctuates between 96% and 99% when this issue occurs, and when resizing individual columns. It's a bug that Removes some of this pixel dimensions.
> 
> @iscottjones I think you need to read the thread properly. Nobody is talking about reverting to 4 columns from 3. And besides, the problem you are talking about is an easy fix.
> 
> You just have to reset the structure after you change from 3 columns to 4 columns.
> 
> Edit Section > Layout > Structure > Reset (small reset button on the bottom left of the structure section)
> 
> And way to give a thumbs up to your own post.

I'm not going to debate with you. Not really up for childish comments. If think you've read the thread properly and replied appropriately, then great! Have fun.

**Comment by feidaman** [comment]
This is Elementor's most irritating bug, and it shouldn't be too hard to fix. Decimal places are not really needed unless you have 50 columns, which is very unlikely. Programmatically this is not a very difficult problem to solve as long as you are familiar with addition and subtraction. To Elementor devs: PLEASE FIX THIS STUPID BUG!!

**Comment by log-out** [comment]
> Hi, I think I got a **solution** for this annoying bug;
> 
> * just edit the "Section" and navigate to "Layout > Structure" tab and select anything except "33,33,33" and "16,66,16" (the sum of these numbers are 99 and 98, not 100),
> * then you can adjust the width of the columns by dragging without getting the unwanted gap :)

Worked for me. Thank you so much

**Comment by BAtiyat** [comment]
Hey guys, I'm not a programmer here, just an actor doing his website, and here's my Work-Around that worked for me;

Set Main section
Content Width: (BOXED) @ with a Numerical Value @ 1200.... try other values.
Column Gap: No Gap (Also worked with Extended, Wide, Wider)
Inside the Main Section I'm using 4 column (but i tried with 5, 6 & 7 columns, all worked the same)
Inside each column, insert an (Inner Section)
Each inner section set to (BOXED) and (No Gap)...... and **DO NOT** use a numerical value here

That's it.... this worked for me, i tried with 4, 5, 6, and 7 columns.... all divided the screen 100% equally.

cheers

**Comment by projectpi-ca** [comment]
How is this not fixed after so many years? This is beyond embarrassing for Elementor.

**Comment by lior-sh** [comment]
Hi all,

Thanks for reporting, we are checking now this issue and we will update soon.
Please follow this thread for updates.
Thanks!

**Comment by TheBigBanik** [comment]
One week until 2021 and the issue is still here. HO HO HO! Even Santa would laugh with that.

**Comment by projectpi-ca** [comment]
> One week until 2021 and the issue is still here. HO HO HO! Even Santa would laugh with that.

Apparently it's quicker to develop a vaccine for COVID than it is to fix an obvious bug at Elementor.

**Comment by FPCSJames** [comment]
> Hi, I think I got a **solution** for this annoying bug;
> 
> * just edit the "Section" and navigate to "Layout > Structure" tab and select anything except "33,33,33" and "16,66,16" (the sum of these numbers are 99 and 98, not 100),
> * then you can adjust the width of the columns by dragging without getting the unwanted gap :)

I hate that this is the solution but it absolutely works. Thanks ahmetsali.

**Comment by jonathandhn** [comment]
I'm all on these issue. It messed everthing. Elementor pro is not usable because of this ... 2021 - 2017 MAYDAY

**Comment by MickeyMick00** [comment]
Its 2021, still the problem exists.
They don't even care their products and keeps on increasing subscription money.
What a waste of such a beautiful builder.

**Comment by joexcm** [comment]
Crazy. Third bug I've had to find a github workaround to today...

**Comment by soxhi8** [comment]
New customer here, this bug is really annoying and not easily fixed without looking it up on here. Please fix soon, I bought into Elementor, thinking I was paying for long-term-support. This thread tells a different story.

**Comment by webinsightin** [comment]
> Hi all,
> 
> Thanks for reporting, we are checking the issue and we will update soon.
> Please follow this thread for updates.
> Thanks!

Elementor Version 3.3.1, Elementor Pro Version 3.3.4.
And the issue still exists.

**Comment by ibrahimhajjaj** [comment]
```
Elementor Version 3.3.1, Elementor Pro Version 3.3.4.
And the issue still exists.
```

Same here!!

**Comment by soxhi8** [comment]
> 
> 
> you can modify css on each column. its my solution for this column width problem.
> `selector { width: 35% !important; }`

Try to refer to this solution, before hacking up the CSS: https://github.com/elementor/elementor/issues/2042#issuecomment-655901035

**Comment by mik-bcmllp** [comment]
The really odd thing about this issue is column layouts are using flexbox with fixed percentage widths. There must be some very simple fix to the JS that deals with the editor auto-sizing columns since flexbox necessitates using 100% of the div space available. For instance, if I select three equal columns, it makes no sense to use 33% as the width; most frontend devs know that it's better to use a fraction as the browser will auto-convert this to a pixel size relative to the parent div.
I'm scratching my head why the devs are taking so long to fix this. They could easily just give us an option to use a fraction width and/or have a checkbox on each row preventing the editor from auto-sizing the width?

**Comment by webster-mcwebby** [comment]
> you can modify css on each column. its my solution for this column width problem. `selector { width: 35% !important; }`

To the person who suggested the #2042 (comment) before "hacking up the CSS" it DOES NOT WORK unless you only have 3 columns! I really wish people would get that.

So thank you ibennya! This will work for me until Elementor gets it shit together.

**Comment by Hans-Zamorano-Matamala** [comment]
Hi guys, well, I'm having this issue right now on Elementor Builder 3.5.3 + Hello Elementor.

For me it was fixed by selecting the section element which wraps the affected columns and select some structure to reset the faulty state, like 50% - 50%. Then going back to columns and selecting the desired width 👍 .

I'm pretty sure this can be fixed at least by validating the sum and resetting width to (100% / number of columns) if something goes wrong, or truncate the width percentage to 2-3 decimals and then ignore the width of the last column to use all available space and balance values (you know, like flex: 1).

**Comment by biomars** [comment]
Hi guys 😊, please try out this plugin that solves this issue and some else. If works for you please react to this comment, then people can easily find the solution 🙂 ▶️ https://wordpress.org/plugins/ooohboi-steroids-for-elementor/

**Comment by chicoco07** [comment]
Still a problem in the latest version: 2022/03/15

**Comment by eminozturk58** [comment]
I can't believe this issue has been around since 2017. The problem still continues.

**Comment by jonathandhn** [comment]
It's finally understood,

Easy to reproduce on elementor pro

Create a template for a post or a page type, add three columns, set page content on the central column, save.  Go on the page the template is applied on, edit add columns here and play with the size of the columns. Huston we've got a problem, but it's normal.

If your template or your elementor settings are ruling the width of a given page, set your columns accordingly in order to allows a given number to be divided correctly.

I use 1140px width, set all the settings correctly in order to always fall on fixed value, never get the bug anymore.

That's a math problem.
________________________________

**Comment by vishal-g** [comment]
> For me it was fixed by selecting the section element which wraps the affected columns and select some structure to reset the faulty state, like 50% - 50%. Then going back to columns and selecting the desired width 👍 .
>

This worked for me!

**Comment by chicoco07** [comment]
There are multiple ways of fixing it, the issue is, this problem shouldn't be there.

**Comment by SiavashKhazaei** [comment]
2022-04-02 the problem still exists. why element or don't wanna fixed and we have to follow all of these long ways?
IT IS SOMETHING FUNDAMENTAL NOT JUST A FEATURE, PLEASEEEE FIX IT

**Comment by SiavashKhazaei** [comment]
i found a way! start resizing the columns from the left and don't type anything, just resize them with arrows and then the next one. don't miss any column from left to right. all of the must-have percentage and you must do it with arrows

**Comment by snelly1998** [comment]
2022-05-11 still happening
had to make a new div and type in the widths

**Comment by klainser** [comment]
Apparently Elementor team has found the time, for us paupers to make important changes to the row / column grid by implementing the [Containers ](https://elementor.com/help/container-element/) Widget, that seems to be a replacement of the current grid system of section, column, and inner section.

They are still pretty quiet about it because it's still in Alpha development and has a decent number of bugs, but it's available in the Experiments section Elementor.

**Comment by IPSsharma** [comment]
HI Here is solution for this 
please watch video 

[Untitled_ Jul 28, 2022 4_25 PM.webm](https://user-images.githubusercontent.com/110169455/181489740-c17fa741-7a5d-4d1a-bc35-e94acac5d7bd.webm)
I

**Comment by luisceladita** [comment]
almost 2023 and stills this problem exists...

**Comment by Zexler** [comment]
I've been using Elementor for three years now, but only now have I encountered this problem (complex layout with pixel perfect), which has still not been solved. It's just a shame.

**Comment by KoolerNolan** [comment]
I had the problem with two columns not adding up to 100%.
Everything works great after selecting 50/50 and then manually typing 60 for the left column.
Resizing via dragging does not work for me.

And yes, the issue is still present. Even after 3.8.1.

**Comment by nicholaszein** [comment]
Hello all!

We have great news! 🙌 

### 📢 We're happy to announce that this issue can now be solved by using the <ins>stable</ins> version of the Flexbox Container experiment introduced with Elementor  **v3.8**! 🥳 

You now have total control over the width of your child containers using the power of CSS Flexbox!

✔️ We invite everyone to check it out and update your plugin to the new version (and also enable the Flexbox Container experiment).

Thank you all for contributing and giving your feedback! 🙏 

Cheers 🥂

**Comment by ravicha123** [comment]
Infact there is no such issue, it is only related to structure. Because we many times edit the design but everytime we forget to  reset the structure. Do it like this. First go to EDIT SECTION---->LAYOUT------>STRUCTURE-------->Click on RESET.
I think, now issue will be resolved.
