### ISSUE TITLE
The problem of displaying the box shadow in the loop carousel widget.

### ISSUE THREAD

**Issue by Michaelgimii** [elementor/elementor#21239]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Hi @nicholaszein 

When I set a Box shadow for the loop carousel item, the box shadow is not displayed correctly. The box shadow is visible only in the intermediate distances of the loop items and is not displayed around each loop item.

### Steps to reproduce

1- Add the Grid loop widget.
2- Click on the Create Template button.
3- Add a container and set a box shadow for it.
4- Add desired content such as title, image and...
5- Click on the save and back button.

If you view the carousel in the frontend, the box shadow doesn't display well.

![box shadow](https://user-images.githubusercontent.com/88034902/216793931-eb77e01d-1b0a-4bc0-8c27-3dbcf4bab339.png)

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
Operating System: WINNT
Software: Apache/2.4.38 (Win32) OpenSSL/1.1.1a PHP/7.3.2
MySQL version: mariadb.org binary distribution v5.6.42-84.2
PHP Version: 7.3.2
PHP Memory Limit: 128M
PHP Max Input Vars: 2500
PHP Max Post Size: 128M
GD Installed: Yes
ZIP Installed: Yes
Write Permissions: All right
Elementor Library: Connected

== WordPress Environment ==
Version: 6.1.1
Site URL: https://domain.com
Home URL: https://domain.com
WP Multisite: Yes
Max Upload Size: 128 MB
Memory limit: 2048M
Max Memory limit: 512M
Permalink Structure: /%postname%/
Language: en-US
Timezone: Europe/berlin
Debug Mode: Inactive

== Theme ==
Name: Hello Elementor Child
Version: 1.0.1
Author: Elementor Team
Child Theme: Yes
Parent Theme Name: Hello Elementor
Parent Theme Version: 2.6.1
Parent Theme Author: Elementor Team

== User ==
Role:
WP Profile lang: en_GB
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.11.0-beta1
		Author: Elementor.com

	Elementor Pro
		Version: 3.11.0-beta1
		Author: Elementor.com

	WooCommerce
		Version: 7.3.0
		Author: Automattic

== Features ==
Custom Fonts: 0
Custom Icons: 0

== Integrations ==

woocommerce: Active
== Elementor Experiments ==
Optimised DOM Output: Active by default
Improved asset loading: Active by default
Improved CSS Loading: Active by default
Inline Font Icons: Active
Accessibility improvements: Active by default
Additional Custom Breakpoints: Active by default
admin_menu_rearrangement: Inactive by default
Flexbox Container: Active
Upgrade Swiper Library: Active
Default to New Theme Builder: Active by default
Hello Theme Header & Footer: Inactive
Editor V2: Inactive by default
Landing pages: Inactive
Nested Elements: Active
Lazy Load Background Images: Inactive
Save as Default: Active
Page Transitions: Active by default
Notes: Inactive
Loop: Active
Form Submissions: Active by default
Scroll Snap: Active by default
Mega Menu: Inactive by default

== Log ==

Log: showing 20 of 402023-01-10 08:51:06 [info] Elementor data updater process has been queued. [array (
'plugin' => 'Elementor Pro',
'from' => '3.10.0-beta3',
'to' => '3.10.1',
)]
2023-01-24 12:36:53 [info] elementor::elementor_updater Started
2023-01-24 12:36:53 [info] Elementor/Upgrades - _on_each_version Start
2023-01-24 12:36:53 [info] Elementor/Upgrades - _on_each_version Finished
2023-01-24 12:36:53 [info] Elementor data updater process has been completed. [array (
'plugin' => 'Elementor',
'from' => '3.10.0',
'to' => '3.10.1',
)]
2023-01-24 12:36:56 [info] elementor-pro::elementor_pro_updater Started
2023-01-24 12:36:56 [info] Elementor Pro/Upgrades - _on_each_version Start
2023-01-24 12:36:56 [info] Elementor Pro/Upgrades - _on_each_version Finished
2023-01-24 12:36:56 [info] Elementor data updater process has been completed. [array (
'plugin' => 'Elementor Pro',
'from' => '3.10.0',
'to' => '3.10.2',
)]
2023-01-24 12:38:18 [info] elementor::elementor_updater Started
2023-01-24 12:38:18 [info] Elementor/Upgrades - _on_each_version Start
2023-01-24 12:38:18 [info] Elementor/Upgrades - _on_each_version Finished
2023-01-24 12:38:18 [info] Elementor data updater process has been completed. [array (
'plugin' => 'Elementor',
'from' => '3.10.1',
'to' => '3.11.0-beta1',
)]
2023-01-24 12:38:18 [info] Elementor data updater process has been queued. [array (
'plugin' => 'Elementor',
'from' => '3.10.1',
'to' => '3.11.0-beta1',
)]
2023-01-24 12:38:19 [info] Elementor data updater process has been queued. [array (
'plugin' => 'Elementor',
'from' => '3.10.1',
'to' => '3.11.0-beta1',
)]
2023-01-24 15:12:36 [info] Elementor data updater process has been queued. [array (
'plugin' => 'Elementor Pro',
'from' => '3.10.2',
'to' => '3.11.0-beta1',
)]
2023-01-24 15:12:37 [info] elementor-pro::elementor_pro_updater Started
2023-01-24 15:12:37 [info] Elementor Pro/Upgrades - _on_each_version Start
2023-01-24 15:12:37 [info] Elementor Pro/Upgrades - _on_each_version Finished
2023-01-24 15:12:37 [info] Elementor data updater process has been completed. [array (
'plugin' => 'Elementor Pro',
'from' => '3.10.2',
'to' => '3.11.0-beta1',
)]

JS: showing 2 of 2JS: 2023-01-24 12:44:14 [error X 6][https://domain.com/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1.1:4:51824] Cannot read properties of undefined (reading 'replace')
JS: 2023-01-26 08:54:57 [error X 2][https://domain.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.11.0-beta1:2:4825] Cannot read properties of undefined (reading 'attributes')

== Elementor - Compatibility Tag ==

Elementor Pro: Incompatible
== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hi @Michaelgimii! 

Thank you for submitting your issue! 🙏 

🏷️ This issue has been labeled and will be forwarded to the team for validation and possible solution. Please keep in mind that we can't provide any ETA on when this issue could be fixed if it is validated. We ask for patience.

Best regards

**Comment by Michaelgimii** [comment]
Hi @avivu and @nicholaszein.

I've looked into this a lot and haven't come up with a solution. Using the box shadow in the carousel loop widget is a huge limitation.
The only solution I found was to use an internal container. to use the box shadow for the inner container. This solution worked, but it had one major problem. The problem was that it made Equal height not work. So will this be fixed in a future release? Please don't forget it.

**Comment by 79ho3ein** [comment]
Hi @nicholaszein

Even if we use the border, the situation is still not good. See the left side of the widget in the screenshot below : 

![download](https://user-images.githubusercontent.com/77163248/219951454-27741791-cc92-491d-a610-b9b39ac3d09c.png)

**Comment by s5t5n** [comment]
Maybe someone have a code to fix z-index right?

**Comment by ellengardt** [comment]
You can solve the problem in the following way:

1. Select the Loop Carrousel widget.
2. Go to the Advanced tab
3. Custom CSS.
4. Add: `selector .swiper {
    overflow: unset!important;
}`
5. So that the layout does not break on phones, select the container inside which the Loop Carousel widget is located.
6. Go to the Layout
7. Additional options
8. Change the Overflow value to hidden;

**Comment by dev-foysal** [comment]
I have an issue that can't find any solution, I have one solution that is easy but not user-friendly. when I use display none for duplicate slider. it's okay for me..but it's not user-friendly. plz, help me find the proper solution...check the link to view the screenshot. 
![slide](https://github.com/elementor/elementor/assets/84332388/86e2b6e1-448c-46cf-85f7-7641bc7bb7bf)

**Comment by phkoon** [comment]
Same problem here with transform scaleup animation here. When the loop item is set to scale up on hover, the overflow portion gets clipped off by the carousel widget boundaries. Any update yet?

**Comment by phkoon** [comment]
> You can solve the problem in the following way:
> 
> 1. Select the **Loop Carousel** widget.
> 2. Go to the **Advanced tab**
> 3. **Custom CSS**.
> 4. Add: `selector .swiper { overflow: unset!important; }`
> 5. So that the layout does not break on phones, select the **Container** inside **which the Loop Carousel widget is located.**
> 6. Go to the **Layout**
> 7. **Additional options**
> 8. Change the **Overflow** value to **hidden**;

This helps, but doesn't fully address the issue.
In order to fix it, I added your code and also added enough padding to the loop item template's main container, shadows with scaling animation working like a charm now =D

P.S.: @ellengardt, thank you, by the way!

**Comment by Adamski77** [comment]
I've been having the same problem on a site I'm working now, and I've had it in the past. The solution that worked for me was to add the following CSS to the Loop Carousel widget. Make sure that the .swiper padding is set to be larger than the distance of your box shadow. See below that the .swiper-slide box shadow is down 5px on the Y axis plus 10px blur, so add 15px to the bottom padding, and 10px to the other sides. You will also need to change the gap between slides in the Style tab, otherwise the box shadow of the previous and next slides may show at the sides of the widget. If you have border-radius on your Loop items, you will need to also apply it to .swiper-slide.

Using this solution doesn't require nesting your Loop item, it works with the Equal Height option, and you don't have to mess with visibility of different containers.

`selector .swiper { 
    padding: 10px 10px 15px 10px;
}

selector .swiper-slide {
    box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.22);
}

selector .swiper-slide:hover {
    box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.22) !important;
}`

**Comment by digitalcompass** [comment]
For me, the following CSS on the loop carrousel works nicely: 

`selector .swiper-slide {
    overflow: visible;
}`
