### ISSUE TITLE
Elementor pro conflict with woocommerce order-received page

### ISSUE THREAD

**Issue by DevWael** [elementor/elementor#22299]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When Elementor pro is active on a website along with WooCommerce, the redirection to order-received page go with bad URL.

The original order-received URL is like this:
`domain/checkout/order-received/2855/?key=wc_order_xxxxx`

But when Elementor pro is active, the redirection URL become like this:
`domain/order-received/?key=wc_order_xxxxx`

As you can see, the redirection URL is missing `/checkout/` and `order_id`.

To be able to bypass this issue, you have to assign the checkout page into Elementor site settings → WooCommerce settings → checkout page dropdown.

This will add the created page to the link and apply the WooCommerce endpoint to the link properly, and the redirection link will be fine.

The issue is related to this file inside Elementor pro plugin:
`modules/woocommerce/module.php`
Line: 953
Function name: `get_order_received_endpoint_url()`

### Steps to reproduce

1) Install a fresh copy of WordPress + WooCommerce + Elementor + Elementor pro
2) After activating all those plugins, go and create a product and go with the purchase process.
3) After doing a successful checkout you have to be redirected to the order-received page and you won't see any order details, and you will see the URL that you have been redirected to is wrong and miss some parts (`/checkout/` and `order_id`).

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: Apache / ZoneOS
	MySQL version: Source distribution v10.6.10
	PHP Version: 8.0.28
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 20000
	PHP Max Post Size: 2047M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.2
	Site URL: https://www.example.com
	Home URL: https://www.example.com
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Max Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en
	Timezone: 0
	Admin Email: morgan@example.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 2.7.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.12.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.12.3
		Author: Elementor.com

	ShopEngine
		Version: 4.1.1
		Author: Wpmet

	ShopEngine Pro
		Version: 2.2.1
		Author: Wpmet

	WooCommerce
		Version: 7.6.1
		Author: Automattic

	WooCommerce Shipping &amp; Tax
		Version: 2.2.4
		Author: WooCommerce

	WooCommerce Stripe Gateway
		Version: 7.3.0
		Author: WooCommerce

== Must-Use Plugins ==
	WordPress automation by Installatron
		Version: 
		Author: 

== Elements Usage ==
	
	footer : 1
		animated-headline : 1
		form : 1
		heading : 3
		nav-menu : 2
		text-editor : 4
	header : 3
		icon : 3
		image : 4
		nav-menu : 3
	page : 4
		button : 27
		divider : 1
		form : 1
		heading : 46
		html : 3
		icon : 14
		icon-box : 37
		image : 13
		menu-anchor : 1
		shopengine-add-to-cart : 1
		shopengine-product-description : 1
		shopengine-product-price : 1
		shopengine-product-title : 1
		shopengine-single-product-images : 1
		slides : 1
		social-icons : 2
		spacer : 13
		text-editor : 45
		toggle : 1
	section : 31
		blockquote : 1
		button : 22
		form : 1
		heading : 45
		icon : 4
		icon-box : 16
		image : 9
		nav-menu : 1
		spacer : 14
		text-editor : 49
	wp-post : 0
		button : 1
		heading : 12
		icon-box : 25
		image : 5
		shopengine-add-to-cart : 1
		shopengine-advanced-search : 1
		shopengine-archive-products : 1
		shopengine-archive-result-count : 1
		shopengine-cart-table : 1
		shopengine-cart-totals : 1
		shopengine-checkout-coupon-form : 1
		shopengine-checkout-form-billing : 1
		shopengine-checkout-form-shipping : 1
		shopengine-checkout-payment : 1
		shopengine-checkout-review-order : 1
		shopengine-product-description : 1
		shopengine-product-price : 1
		shopengine-product-title : 1
		shopengine-single-product-images : 1
		spacer : 1
		text-editor : 9
		toggle : 1
	wp-page : 16
		blockquote : 1
		button : 18
		form : 2
		heading : 62
		icon : 11
		icon-box : 8
		spacer : 11
		text-editor : 39
		toggle : 6

== Settings ==
	
	cpt_support: post, page
	allow_tracking: yes

== Features ==
	Custom Fonts: 3
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active

== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Active
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Upgrade Swiper Library: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header &amp; Footer: Active by default
	Editor Top Bar: Inactive by default
	Landing Pages: Active by default
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Page Transitions: Active by default
	Notes: Active by default
	Loop: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default
	Menu: Inactive by default

== Log ==
	
JS: showing 14 of 14JS: 2023-02-06 15:36:12 [error X 7][https://www.example.com/wp-admin/load-scripts.php?c=0&loadchunk_0=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request,regenerator-runtime,wp-polyfill,wp-&loadchunk_1=hooks&ver=6.1.1:4:51824] Cannot read properties of undefined (reading \&#039;replace\&#039;) 
JS: 2023-02-16 19:12:02 [error X 30][https://www.example.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.4:3:631780] elementorFrontend.elements.window.jQuery is not a function 
JS: 2023-03-13 21:29:25 [error X 1][https://www.example.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.7.4:2:4795] Cannot read properties of undefined (reading \&#039;data\&#039;) 
JS: 2023-03-15 19:09:56 [error X 29901][https://www.example.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:16820] Cannot read properties of null (reading \&#039;clone\&#039;) 
JS: 2023-03-15 19:09:57 [error X 654][https://www.example.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js?ver=1.5.0:2:21012] Cannot read properties of null (reading \&#039;changestop\&#039;) 
JS: 2023-03-19 20:06:58 [error X 3][https://www.example.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.4:3:1060434] Cannot read properties of null (reading \&#039;getBoundingClientRect\&#039;) 
JS: 2023-03-20 12:12:14 [error X 132][https://www.example.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.4:3:600652] Cannot read properties of undefined (reading \&#039;get\&#039;) 
JS: 2023-03-31 14:56:44 [error X 1][https://www.example.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.12.0:2:5009] Cannot read properties of undefined (reading &#039;attributes&#039;) 
JS: 2023-03-31 14:57:00 [error X 2][https://www.example.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.0:3:632658] Cannot read properties of undefined (reading &#039;isDesignable&#039;) 
JS: 2023-03-31 15:30:21 [error X 12][https://www.example.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.0:3:785238] Cannot read properties of undefined (reading &#039;toLowerCase&#039;) 
JS: 2023-03-31 17:55:16 [error X 8][https://www.example.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.0:3:1081267] Cannot read properties of null (reading &#039;getBoundingClientRect&#039;) 
JS: 2023-04-02 16:04:16 [error X 12][https://www.example.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.12.1:2:63893] Cannot convert undefined or null to object 
JS: 2023-04-06 17:00:21 [error X 7][https://www.example.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.12.1:3:785745] Cannot read properties of undefined (reading &#039;localized&#039;) 
JS: 2023-04-19 16:17:43 [error X 5][https://www.example.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.12.1:2:4997] Cannot read properties of undefined (reading &#039;data&#039;) 

Log: showing 20 of 272023-04-02 15:43:10 [info] elementor::elementor_updater Started 
2023-04-02 15:43:10 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-02 15:43:11 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-02 15:43:11 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-02 15:43:11 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.0',
  'to' => '3.12.1',
)]
2023-04-02 15:43:37 [info] elementor-pro::elementor_pro_updater Started 
2023-04-02 15:43:37 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-02 15:43:37 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-02 15:43:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.5',
  'to' => '3.12.1',
)]
2023-04-02 15:43:37 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.5',
  'to' => '3.12.1',
)]
2023-04-25 23:31:17 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]
2023-04-25 23:31:18 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.12.3',
)]
2023-04-25 23:31:18 [info] elementor-pro::elementor_pro_updater Started 
2023-04-25 23:31:18 [info] Elementor/Upgrades - _on_each_version Start  
2023-04-25 23:31:18 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-04-25 23:31:18 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-04-25 23:31:18 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.12.3',
)]
2023-04-25 23:31:19 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.12.1',
  'to' => '3.12.3',
)]
2023-04-25 23:31:19 [info] Elementor/Upgrades - _on_each_version Finished 
2023-04-25 23:31:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.12.1',
  'to' => '3.12.2',
)]

PHP: showing 1 of 1PHP: 2023-03-31 17:17:38 [warning X 21][/data01/virt108238/domeenid/www.example.com/htdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php::175] Undefined array key &quot;data&quot; [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

**Comment by nicholaszein** [comment]
Hello @DevWael! 

Thank you for submitting your issue! 🙏 

Please allow us some time to investigate it, and get back to you with our findings. 🧐 

Best regards

**Comment by DevWael** [comment]
Take your time @nicholaszein

**Comment by Haaland-James** [comment]
Hi guys, just to let you know that I also is currently experiencing this same issue. Have this been resolved yet?

**Comment by DevWael** [comment]
@Haaland-James Looks like it takes forever to investigate the issue :)

**Comment by Haaland-James** [comment]
@DevWael This is amazing. Have you found any outside solutions considering its been since May you actually put it out here?

**Comment by anonunder** [comment]
QUICK FIX:
The issue is related to this file inside Elementor pro plugin:
`modules/woocommerce/module.php`
Line: 953
Function name: get_order_received_endpoint_url()

```
public function get_order_received_endpoint_url( $url, $endpoint, $value ) {
		$order_received_endpoint = get_option( 'woocommerce_checkout_order_received_endpoint', 'order-received' );
		if ( $order_received_endpoint === $endpoint ) {
			$woocommerce_purchase_summary_page_id = get_option( 'elementor_woocommerce_purchase_summary_page_id' );
			$order = wc_get_order( $value );

            return $order_received_endpoint ."/". $value;
			if ( $woocommerce_purchase_summary_page_id && $order ) {
				$url = trailingslashit( trailingslashit( trailingslashit( get_permalink( $woocommerce_purchase_summary_page_id ) ) . $order_received_endpoint ) . $order->get_id() );
			}
		}

		return $url;
	}
```

This is only quick fix, updating plugin will override this.

**Comment by RL-890** [comment]
Any update? We also have this issue combined with Mollie payment provider

**Comment by colabcolibri** [comment]
Any update? it is bringing a lot of headaches.

**Comment by anonunder** [comment]
> Any update? it is bringing a lot of headaches.

Did you try my solution?

**Comment by danceshorribly** [comment]
Wow, I've been trying to solve this issue for so long not finding anything. Apparently I am not alone and I'm baffled that Elementor haven't fixed this as of yet?

I've tried your fix and it seems to work.

**Comment by MindsEyeDesign** [comment]
Hi @anonunder Thank you, the temp. fix works. When will it be fixed in Elementor @nicholaszein as it's been since March 2023 and the issue appears all over the web? Thank you.

**Comment by danceshorribly** [comment]
I believe this is actually already fixed. What you need to do is to open up site settings, go to woocommerce section and then make sure ALL WooCommere-pages have a corresponding page set. So checkout and purchase-summary can have the same page or different depending on your desired outcome.

**Comment by MindsEyeDesign** [comment]
@danceshorribly thank you, that was hidden away. All fixed now.

**Comment by mangoweblab** [comment]
@danceshorribly Thank you for your help. I was flummoxed by this until I saw your comment. Best wishes!

**Comment by MasterJuan** [comment]
Hello,

I am experiencing that weird issue with the following setup! I have two identical environments (Production & Staging) under the same hosting using different DB).
Production website using Betheme theme, **having Elementor & Elementor pro** and using POD method (pay on delivery) the redirection to the order-received page works: checkout/order-received/78264/?key=wc_order_X6yhx7IBNaV9A
Staging website using Betheme **without Elementor & Elementor pro** and using POD method redirects to checkout/order-received/78264/?key=wc_order_X6yhx7IBNaV9A but shows 404 error page.

I have done everything but nothing makes sense. The weird thing is that I have returned back to the default Wordpress theme having only the Woocommerce enable and still redirects me to 404 page.

**Comment by OsoBear** [comment]
It's still an issue. v.3.22.1  i updated the module file as @anonunder  suggested...and it fixed it.
Anytime soon it's going to be REALLY fixed?

**Comment by doominio** [comment]
> I believe this is actually already fixed. What you need to do is to open up site settings, go to woocommerce section and then make sure ALL WooCommere-pages have a corresponding page set. So checkout and purchase-summary can have the same page or different depending on your desired outcome.

Thank you! This has saved me too. My problem was slightly different, the payment gateway was receiving the endpoint URL without the domain name, just a relative link. So instead of returning to WC, the customer was getting a 404 error in the payment gateway server.

I chose the checkout page as the purchase summary page and it all seems to work correctly. I'm puzzled as to what the purchase summary IS and why it hijacks the endpoint, though. I'm going to need to do this retroactively on all my live sites just in case.

**Comment by mike-asuncion** [comment]
> QUICK FIX: The issue is related to this file inside Elementor pro plugin: `modules/woocommerce/module.php` Line: 971 Function name: get_order_received_endpoint_url()
> 
> ```
> public function get_order_received_endpoint_url( $url, $endpoint, $value ) {
> 		$order_received_endpoint = get_option( 'woocommerce_checkout_order_received_endpoint', 'order-received' );
> 		if ( $order_received_endpoint === $endpoint ) {
> 			$woocommerce_purchase_summary_page_id = get_option( 'elementor_woocommerce_purchase_summary_page_id' );
> 			$order = wc_get_order( $value );
> 
>                         return $order_received_endpoint ."/". $value;
> 			if ( $woocommerce_purchase_summary_page_id && $order ) {
> 				$url = trailingslashit( trailingslashit( trailingslashit( get_permalink( $woocommerce_purchase_summary_page_id ) ) . $order_received_endpoint ) . $order->get_id() );
> 			}
> 		}
> 
> 		return $url;
> 	}
> ```
> 
> This is only quick fix, updating plugin will override this.

been looking for this fix. This worked for me :D

**Comment by mastersofimagination** [comment]
> > QUICK FIX: The issue is related to this file inside Elementor pro plugin: `modules/woocommerce/module.php` Line: 971 Function name: get_order_received_endpoint_url()
> > ```
> > public function get_order_received_endpoint_url( $url, $endpoint, $value ) {
> > 		$order_received_endpoint = get_option( 'woocommerce_checkout_order_received_endpoint', 'order-received' );
> > 		if ( $order_received_endpoint === $endpoint ) {
> > 			$woocommerce_purchase_summary_page_id = get_option( 'elementor_woocommerce_purchase_summary_page_id' );
> > 			$order = wc_get_order( $value );
> > 
> >                         return $order_received_endpoint ."/". $value;
> > 			if ( $woocommerce_purchase_summary_page_id && $order ) {
> > 				$url = trailingslashit( trailingslashit( trailingslashit( get_permalink( $woocommerce_purchase_summary_page_id ) ) . $order_received_endpoint ) . $order->get_id() );
> > 			}
> > 		}
> > 
> > 		return $url;
> > 	}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is only quick fix, updating plugin will override this.
> 
> been looking for this fix. This worked for me :D

The fix works fine. The bug is still an issue!

**Comment by atcdomsol** [comment]
For anyone still experiencing this issue, what DevWael (THANK YOU as I spent 2+ hours troubleshooting this before finding this thread) suggested worked for me:

**Quote:**

_To be able to bypass this issue, you have to assign the checkout page into Elementor site settings → WooCommerce settings → checkout page dropdown._

**End Quote.**

I am using Elementor Pro + WooCommerce. I just used the Checkout page twice on the Elementor Site Settings screen (WooCommerce Option). Just like the below screenshot:

![Image](https://github.com/user-attachments/assets/4cac489d-a951-4fa7-92cb-e5a09d0b2885)

**Comment by apaulo2004** [comment]
> For anyone still experiencing this issue, what DevWael (THANK YOU as I spent 2+ hours troubleshooting this before finding this thread) suggested worked for me:
> 
> **Quote:**
> 
> _To be able to bypass this issue, you have to assign the checkout page into Elementor site settings → WooCommerce settings → checkout page dropdown._
> 
> **End Quote.**
> 
> I am using Elementor Pro + WooCommerce. I just used the Checkout page twice on the Elementor Site Settings screen (WooCommerce Option). Just like the below screenshot:
> 
> ![Image](https://github.com/user-attachments/assets/4cac489d-a951-4fa7-92cb-e5a09d0b2885)

I initially implemented the temp fix in the code but then elementor updated and I forgot to reapply it. Your suggestion on the site settings worked for me. Its just a really hidden setting that I think could be brought out more in the actual settings of Elementor.

**Comment by bewjrayyan** [comment]
> QUICK FIX: The issue is related to this file inside Elementor pro plugin: `modules/woocommerce/module.php` Line: 971 Function name: get_order_received_endpoint_url()
> 
> ```
> public function get_order_received_endpoint_url( $url, $endpoint, $value ) {
> 		$order_received_endpoint = get_option( 'woocommerce_checkout_order_received_endpoint', 'order-received' );
> 		if ( $order_received_endpoint === $endpoint ) {
> 			$woocommerce_purchase_summary_page_id = get_option( 'elementor_woocommerce_purchase_summary_page_id' );
> 			$order = wc_get_order( $value );
> 
>                         return $order_received_endpoint ."/". $value;
> 			if ( $woocommerce_purchase_summary_page_id && $order ) {
> 				$url = trailingslashit( trailingslashit( trailingslashit( get_permalink( $woocommerce_purchase_summary_page_id ) ) . $order_received_endpoint ) . $order->get_id() );
> 			}
> 		}
> 
> 		return $url;
> 	}
> ```
> 
> This is only quick fix, updating plugin will override this.

this one only work on [Direct bank transfer] Transfer Bank Manual gateway. not work on other payment gateway i have. can you help me.

**Comment by ThriftyWP** [comment]
> > For anyone still experiencing this issue, what DevWael (THANK YOU as I spent 2+ hours troubleshooting this before finding this thread) suggested worked for me:
> > **Quote:**
> > _To be able to bypass this issue, you have to assign the checkout page into Elementor site settings → WooCommerce settings → checkout page dropdown._
> > **End Quote.**
> > I am using Elementor Pro + WooCommerce. I just used the Checkout page twice on the Elementor Site Settings screen (WooCommerce Option). Just like the below screenshot:
> > ![Image](https://github.com/user-attachments/assets/4cac489d-a951-4fa7-92cb-e5a09d0b2885)
> 
> I initially implemented the temp fix in the code but then elementor updated and I forgot to reapply it. Your suggestion on the site settings worked for me. Its just a really hidden setting that I think could be brought out more in the actual settings of Elementor.

Thank you! I was pulling my hair out trying to figure out why order confirmations were hitting /order-received instead of /checkout/order-received. 

Ridiculous that this isn't the default in Elementor.

**Comment by atcdomsol** [comment]
> > For anyone still experiencing this issue, what DevWael (THANK YOU as I spent 2+ hours troubleshooting this before finding this thread) suggested worked for me:
> > **Quote:**
> > _To be able to bypass this issue, you have to assign the checkout page into Elementor site settings → WooCommerce settings → checkout page dropdown._
> > **End Quote.**
> > I am using Elementor Pro + WooCommerce. I just used the Checkout page twice on the Elementor Site Settings screen (WooCommerce Option). Just like the below screenshot:
> > ![Image](https://github.com/user-attachments/assets/4cac489d-a951-4fa7-92cb-e5a09d0b2885)
> 
> I initially implemented the temp fix in the code but then elementor updated and I forgot to reapply it. Your suggestion on the site settings worked for me. Its just a really hidden setting that I think could be brought out more in the actual settings of Elementor.

I'm glad this worked for you. Hopefully they will address this in future updates.

**Comment by diginomic-digital-done** [comment]
It should just default to whatever the page assigned value of Checkout is set in Woocommerce > Settings > Advanced. 

Then if you want to make a special order summary page with the Purchase Summary widget then you can do that and go to Elementor Site Settings and override the Purchase Summary value only. 

No one knows to go set this value currently and it is 2 years later.

**Comment by golubov-csaba-antal** [comment]
Kudos, after an update, the Purchase Summary has changed to empty for a reason only God knows. 🤔
