### ISSUE TITLE
🐞 Style Guide throws a JS error in the frontend: e.0 is not a function

### ISSUE THREAD

**Issue by tamelander** [elementor/elementor#24492]
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

When Global Style Guide is enabled in Elementor > Settings > Features I get an error in dev console in a fresh created page with no content.

```
Uncaught TypeError: e.O is not a function
    at frontend.min.js?ver=3.18.0:2:40340
    at webpackJsonpCallback (styleguide-app-initiator.min.js?ver=3.18.0:3:12265)
    at webpackJsonpCallback (webpack.runtime.min.js?ver=3.18.0:2:4680)
    at frontend.min.js?ver=3.18.0:2:74
```

When I disable Global Style Guide the error goes away.

### Steps to reproduce

Enable Global Style Guide
Create a new page.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently following the steps above.

### System Info

<details>
<summary>Click to reveal</summary>

````txt


					
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.6.16
	PHP Version: 8.1.25
	PHP Memory Limit: 1024M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 512M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.1
	Site URL: 
	Home URL: 
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 1024M
	Max Memory limit: 1024M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 1
	Debug Mode: Inactive

== Theme ==
	Name: Astra Child
	Version: 1.0.0
	Author: 
	Child Theme: Yes
	Parent Theme Name: Astra
	Parent Theme Version: 4.4.0
	Parent Theme Author: Brainstorm Force

== User ==
	Role: administrator
	WP Profile lang: sv_SE
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

== Active Plugins ==
	Asset CleanUp: Page Speed Booster
		Version: 1.3.9.3
		Author: Gabe Livan

	Astra Pro
		Version: 4.4.0
		Author: Brainstorm Force

	Burst Statistics - Privacy-Friendly Analytics for WordPress
		Version: 1.5.2
		Author: Really Simple Plugins

	CAOS
		Version: 4.7.12
		Author: Daan from Daan.dev

	Checkout Field Editor for WooCommerce
		Version: 2.0.0
		Author: ThemeHigh

	Classic Editor
		Version: 1.6.3
		Author: WordPress Contributors

	Classic Widgets
		Version: 0.3
		Author: WordPress Contributors

	Cookie Notice & Compliance for GDPR / CCPA
		Version: 2.4.11.1
		Author: Hu-manity.co

	Customizer Search
		Version: 1.1.6
		Author: Brainstorm Force

	Custom Product Tabs Lite for WooCommerce
		Version: 1.8.0
		Author: SkyVerge

	Custom Sidebars
		Version: 3.36
		Author: WebFactory Ltd

	Elementor
		Version: 3.18.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.18.0
		Author: Elementor.com

	Extra Product Options & Add-Ons for WooCommerce
		Version: 6.3.2
		Author: ThemeComplete

	Feed Them Social - Page, Post, Video and Photo Galleries
		Version: 4.1.9
		Author: SlickRemix

	FiboSearch - AJAX Search for WooCommerce (Pro)
		Version: 1.26.1
		Author: FiboSearch Team

	Formidable Forms
		Version: 6.5.4
		Author: Strategy11 Form Builder Team

	Formidable Forms Pro
		Version: 6.5.4
		Author: Strategy11

	Hash Link Scroll Offset
		Version: 0.2.1
		Author: WebDevStudios

	HTML in Category Descriptions
		Version: 1.2.3
		Author: Arno Esterhuizen

	Kadence WooCommerce Email Designer
		Version: 1.5.12
		Author: Kadence WP

	LiteSpeed Cache
		Version: 5.7.0.1
		Author: LiteSpeed Technologies

	Loco Translate
		Version: 2.6.6
		Author: Tim Whitlock

	Max Mega Menu
		Version: 3.2.4
		Author: megamenu.com

	Max Mega Menu - Pro Addon
		Version: 2.3.1
		Author: megamenu.com

	OMGF
		Version: 5.7.6
		Author: Daan from Daan.dev

	OoohBoi Steroids for Elementor
		Version: 2.1.6
		Author: OoohBoi

	PDFjs Viewer - Embed PDFs
		Version: 2.1.8
		Author: <a href="http://byterevel.com/">Ben Lawson</a>, <a href="https://www.twistermc.com/">Thomas McMahon</a>

	Photonic Gallery & Lightbox for Flickr, SmugMug, Google Photos & Others
		Version: 3.02
		Author: Sayontan Sinha

	Post SMTP
		Version: 2.8.5
		Author: Post SMTP

	Product SKU Generator for WooCommerce
		Version: 2.5.0
		Author: SkyVerge

	Rank Math SEO
		Version: 1.0.206
		Author: Rank Math

	Really Simple SSL
		Version: 7.2.0
		Author: Really Simple Plugins

	Sequential Order Numbers for WooCommerce
		Version: 1.5.7
		Author: WebToffee

	Smash Balloon Instagram Feed
		Version: 6.2.6
		Author: Smash Balloon

	TablePress
		Version: 2.2.3
		Author: Tobias Bäthge

	Ultimate Addons for Elementor
		Version: 1.36.25
		Author: Brainstorm Force

	WooCommerce
		Version: 8.3.1
		Author: Automattic

	WooCommerce Expand Tabs
		Version: 1.26
		Author: SilkyPress

	Wordfence Security
		Version: 7.10.7
		Author: Wordfence

	WPS Hide Login
		Version: 1.9.9
		Author: WPServeur, NicolasKulka, wpformation


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active


== Elementor Experiments ==
	Optimized DOM Output: Active
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Additional Custom Breakpoints: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active
	Grid Container: Active
	Default to New Theme Builder: Active
	Editor Top Bar: Active
	Optimized Gutenberg Loading: Active by default
	Build with AI: Active
	Landing Pages: Inactive
	Nested Elements: Active
	Lazy Load Background Images: Inactive
	Optimize Image Loading: Active
	Pages Panel: Inactive by default
	Global Style Guide: Active
	Page Transitions: Inactive
	Notes: Inactive
	Form Submissions: Inactive
	Scroll Snap: Inactive
	Menu: Inactive by default
	Taxonomy Filter: Active


== Log ==
	
PHP: showing 7 of 7PHP: 2023-11-27 10:33:38 [notice X 36][../wp-content/plugins/elementor/includes/elements/container.php::43] Creation of dynamic property Elementor\Includes\Elements\Container::$logical_dimensions_inline_end is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-27 11:04:49 [notice X 6][../wp-content/plugins/elementor-pro/core/editor/editor.php::129] Using ${var} in strings is deprecated, use {$var} instead [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-27 11:09:51 [warning X 1][../wp-content/plugins/elementor/core/page-assets/data-managers/font-icon-svg/font-awesome.php::50] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-27 11:09:59 [notice X 17][../wp-content/plugins/elementor-pro/modules/custom-css/module.php::76] trim(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-27 11:15:32 [notice X 25][../wp-content/plugins/elementor/includes/utils.php::727] strtolower(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-27 11:38:23 [notice X 9][../wp-content/plugins/elementor-pro/modules/woocommerce/module.php::607] parse_str(): Passing null to parameter #1 ($string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2023-11-30 13:28:43 [warning X 2][../wp-content/plugins/elementor-pro/modules/video-playlist/widgets/video-playlist.php::1690] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

Log: showing 10 of 102023-12-05 03:02:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.3',
  'to' => '3.18.0',
)]
2023-12-05 03:02:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.17.1',
  'to' => '3.18.0',
)]
2023-12-05 03:02:23 [info] elementor::elementor_updater Started 
2023-12-05 03:02:23 [info] Elementor/Upgrades - _on_each_version Start  
2023-12-05 03:02:23 [info] elementor-pro::elementor_pro_updater Started 
2023-12-05 03:02:23 [info] Elementor Pro/Upgrades - _on_each_version Start  
2023-12-05 03:02:23 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2023-12-05 03:02:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.17.1',
  'to' => '3.18.0',
)]
2023-12-05 03:02:27 [info] Elementor/Upgrades - _on_each_version Finished 
2023-12-05 03:02:27 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.3',
  'to' => '3.18.0',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified
	OoohBoi Steroids for Elementor: Compatibility not specified
	Ultimate Addons for Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

````

</details>

**Comment by mbaierl** [comment]
Happens on every single page. Please fix together with #19345 
Also happens on every page load in Firefox.

**Comment by digitalwording** [comment]
Any Updates?

In new version can't even deactivate

**Comment by askwpgirl** [comment]
This happens regardless of whether the Style Guide is active, and happens on ALL Elementor Editor pages whether or not content is there. I see it on all sites on all Elementor Editor pages.

**Comment by nicholaszein** [comment]
@askwpgirl The title is correct based on what the script is doing. Please do not submit duplicates of the same issue.

**Comment by CodeConnectPtyLtd** [comment]
Is there any movement on this bug?

We cannot deliver client sites using Elementor that:

a) Look like page updates aren't saving

and

b) roll back the plugin and then deliver sites that aren't up to date.

This is making my move over to Breakdance Builder much more urgent!

**Comment by askwpgirl** [comment]
> @askwpgirl The title is correct based on what the script is doing. Please do not submit duplicates of the same issue.

@nicholaszein  - I did not see this issue before due I submitted my report. I searched GitHub for error and did not see this. I have not changed any titles. 

Also steps to reproduce are not correct on this issue as described above. The description of this is incorrect. This issue is NOT related to enabling the Style Guide Preview or Site Settings. So the issue should be edited. This error is ubiquitous in Elementor on all Elementor Editor pages, even with all Features turned off. It has nothing to do with the Global Style Guide as far as I can tell. Please let me know how are you managing to make the error go away, as I can see nothing that will prevent this error from occurring in any settings. Can someone edit this report to be accurate? 

@CodeConnectPtyLtd  - This error does not effect page updates. Not sure what this error effects practically speaking which is probably why it isn't fixed. But now with more updates, there are more JS errors in the Editor.

**Comment by askwpgirl** [comment]
@tamelander  - What do you mean by "When I disable Global Style Guide the error goes away." What exactly are you disabling and where? I have found nothing that can be disabled in Settings that will make this error go away.

**Comment by nicholaszein** [comment]
@askwpgirl the issue is caused by the Style Guide component, whether you agree with it or not. The title of the issue follows an internal pattern created to be easily recognized not only by the public, but by our team of engineers as well. What decides if a title is right or wrong, is the component that the issue affects. 

I am well aware of what is the origin of the issue, how to reproduce it, and how it can possibly be solved.

Despite showing an error in the console, this issue does not affect the functionality of Elementor on the front-end, neither in the backend.

The Style Guide was merged to Core not long ago, and this is why this error appears in the console.

We appreciate the effort to communicate and report issues. We will fix it as soon as other (more pressing) tasks are resolved.

Kind regards

**Comment by askwpgirl** [comment]
@nicholaszein - I am not saying I disagree, I am saying the steps to reproduce are not clear. 

I have not made any changes to this, only recommended that the description be clear for any one reading this to understand the details since the wording is very generic and therefore confusing. 

Yes, it does not appear to be effecting the functionality.

**Comment by CodeConnectPtyLtd** [comment]
@askwpgirl - The error does not affect the page actually saving but when you got o close the page it says that there are unsaved changes...  I cannot present this stuff to my clients.

Perhaps we can stop arguing over the title semantics and ensure that the error is fixed.

**Comment by nicholaszein** [comment]
Thank you @CodeConnectPtyLtd.

**Comment by ev88** [comment]
I have been experiencing this issue on more and more websites over the past week.  I don't even have a Global Style Guide option to enable/disable, so I'm not able to apply any kind of temporary fix.  With clients asking to make their own edits, I'm not very happy handing over control if the editor isn't working as it should.

```
Uncaught TypeError: e.O is not a function
    at frontend.min.js?ver=3.21.7:2:39876
    at webpackJsonpCallback (styleguide-app-initiator.min.js?ver=3.21.7:3:13486)
    at webpackJsonpCallback (webpack.runtime.min.js?ver=3.21.7:2:4680)
    at frontend.min.js?ver=3.21.7:2:74
```

I'm getting the same issues as reported by others: The Update button is always active, and pressing it doesn't make it inactive.  Leaving the page shows  the 'are you sure you want..' pop-up, implying my changes didn't get saved (when they did).

I created a staging copy and disabled all plugins other than Elementor and Elementor Pro, and the issue went away.  I enabled each plugin one at a time and discovered that enabling Rank Math brought the issue back.  Disabling it, the issue went away again.  However, while the button issue is resolved, the same error is thrown in the console.

I re-enabled Rank Math and disabled each feature before narrowing it down to Titles & Meta -> Pages, and disabling Add SEO Controls.  For whatever reason, disabling this brought back normal 'Update' functionality when editing pages.  However, the same error persists in the dev console, so I'm not sure what's that all about.

In any case, if anyone happens to be experiencing this issue and also have Rank Math installed, try going to  Titles & Meta -> Pages, and disabling Add SEO Controls.  This has fixed the issue on two of my websites so far.

**Comment by ColbyDevOps** [comment]
> @askwpgirl.
> 
> The issue will remain they way it is, unless we need to change something. This matter is closed.
> 
> We appreciate the feedback.

So its just going to stay broken? 
By the way, it does break editor functionality. Image controls fail for one thing, not that it matters since "the matter is closed"

**Comment by ColbyDevOps** [comment]
> @askwpgirl the issue is caused by the Style Guide component, whether you agree with it or not. The title of the issue follows an internal pattern created to be easily recognized not only by the public, but by our team of engineers as well. What decides if a title is right or wrong, is the component that the issue affects.
> 
> Despite showing an error in the console, this issue does not affect the functionality of Elementor on the front-end, neither in the backend.
> 
> When this issue was reported, the Style Guide was still an experimental feature that could be turned off. Now, the Style Guide was merged to Core not long ago, and this is why this error appears in the console.
> 
> I am well aware of what is the origin of the issue, how to reproduce it, and how it can possibly be solved.
> 
> We appreciate the effort to communicate and report issues. We will fix it as soon as other (more pressing) tasks are resolved.
> 
> Kind regards

@nicholaszein 
Are you confirming that the style guide feature was pushed into core, knowing that this issue persists and that we don't have a way to disable it?

**Comment by nicholaszein** [comment]
@ColbyDevOps yes, because it doesn't affect anything in terms of functionality or stability. It's just a console error that only appears in edge cases.

**Comment by CodeConnectPtyLtd** [comment]
> @ColbyDevOps yes, because it doesn't affect anything in terms of functionality or stability. It's just a console error that only appears in edge cases.
> 
> Having a way to disable it, was never in the plans for this feature.

I've created a short screen recording to demonstrate that the issue is actually affecting the user interface and therefore usability.  Please take 1.5 minutes to view the screen recording below:

[](https://streamable.com/859waf)

**Comment by CodeConnectPtyLtd** [comment]
There is a RankMath beta release that actually fixes the UI issue that prevents closing the window.

https://support.rankmath.com/ticket/conflict-with-elementor-10/

https://rankmath.com/kb/version-control/#beta-updates

**Comment by nicholaszein** [comment]
> _I've created a short screen recording to demonstrate that the issue is actually affecting the user interface and therefore usability. Please take 1.5 minutes to view the screen recording below:_
> 
> _https://streamable.com/859waf_

@CodeConnectPtyLtd, the Update button issue is caused by a bug in the Rank Math plugin, and has absolutely nothing to do with this one, as stated multiple times [here](https://github.com/elementor/elementor/issues/24492#issuecomment-2122943197), [here](https://github.com/elementor/elementor/issues/24492#issuecomment-2126148184), [here](https://github.com/elementor/elementor/issues/24492#issuecomment-2129531657), and [here](https://github.com/elementor/elementor/issues/24492#issuecomment-2130000802). And, as you already saw for yourself [here](https://github.com/elementor/elementor/issues/24492#issuecomment-2140844098).

**Comment by nicholaszein** [comment]
> So its just going to stay broken?
> By the way, it does break editor functionality. Image controls fail for one thing, not that it matters since "the matter is closed"

@ColbyDevOps nobody said it was going to stay broken. The "matter" in this case was the unnecessary discussion about the title and description of this issue. The issue is not closed. It will be closed when we address it. But it isn't a priority right now. We are going to handle it most likely in the next quarter.

I can also edit images just fine, so it doesn't affect image controls at all. If you are having trouble with those, it's something else entirely, and likely a conflict with another plugin.

**Comment by crascher** [comment]
This is a really annoying error,  especially if you want to do some error catching for the whole site to be informed if something is going wrong in JavaScript. Why it is not fixed after reporting over 6 month ago...

**Comment by ashokdesai64** [comment]
@nicholaszein I am not using the Rank Math plugin and I am still facing this issue. My backend Elementor editor is not loading.

https://prnt.sc/rRuSVN3eHEHW

**Comment by john4242** [comment]
> @nicholaszein I am not using the Rank Math plugin and I am still facing this issue. My backend Elementor editor is not loading.
> 
> https://prnt.sc/rRuSVN3eHEHW

I have the same issue as you, editor not loading, same error message.

If you have time and the possibility, I propose to do: 1. a fresh new Wordpress install 2. then install elementor plugin
I did that and the error still occured even with the fresh install but at least that would rule out other things.

**Comment by adewaleolaore** [comment]
I am experiencing this same issue, it's been happening for some time. I have tried all troubleshooting options, disabled all plugins leaving just Elementor but the error remains.

Team, please look into this error. It's really annoying, no edit can be made on client's website and it's stalling deliverables.

**Comment by askwpgirl** [comment]
@adewaleolaore  - as far as I can tell, this error does not cause any issues. It's there, but it's like so many Javascript errors which are ubiquitous in web dev. There is nothing for you to disable or do. The original posting for this is VERY old, and it has old information so doesn't apply to the current interface. So there are no longer any settings that control this as the functionality that is causing this error is rolled into core Elementor. You can ignore it, and it seems that at some point, they will include a fix in an upcoming release. It appears to be not a priority due to it not causing any real issues.

**Comment by john4242** [comment]
I think there is some misunderstanding in the thread.

The real error is "Elementor editor doesn't work (doesn't load page)".

Maybe people are just looking at the console and assuming that "e.0 is not a function" is the cause of the error but that's not the cause I guess. The problem remains: Elementor pages cannot be edited, editor doesn't load.

**Comment by mbelic** [comment]
For me the issue was the plugin [WP Smart import](https://wordpress.org/plugins/wp-smart-import/). Once disabled, sidebar and publish are available again.

e.0 is not a function error still remains and has nothing to do with this issue.

My recommendation is to try and disable plugins one at a time until you find the culprit at your website.

**Comment by askwpgirl** [comment]
@john4242  - Yes, that is how I came to this error. I was troubleshooting something and stumbled upon it. And, yes, it is unrelated to the problem you are experiencing, i.e. it's a red herring.

In terms of the problem "Elementor pages cannot be edited, editor doesn't load" - you will need to troubleshoot that to determine why this is happening, typically it is related to a plugin conflict as @mbelic mentioned, something specific to content on that page layout (if only happens on one page), or low memory issue. A few ways to get help for that would be to use Elementor Support, join the Elementor Discord, or participate in any number of Elementor Facebook groups.

**Comment by theRealRizeo** [comment]
Hello,

In my case I found the function `gzencode` in the path `elementor/core/common/modules/ajax/module.php on line 270` is the issue. Takes too much time to load and in return fails

**Comment by futureyoon** [comment]
following..

**Comment by quintonv** [comment]
Also getting the same Menu issues as nicholaszein reported. My Global Header won't even accept the background color I have. On the website it just stays white, but my header has a black background.

Rolling back before 3.24.0 fixes it on all my websites that auto updated...

**Comment by askwpgirl** [comment]
@mister-pc @quintonv @abr4xas - Issues you might be having are unrelated to this JS error. Any issues will be related to themes or other plugins or unrelated update issue not pertaining to this error.

**Comment by shahadul878** [comment]
`frontend.min.js?ver=3.24.5:2 Uncaught TypeError: e.O is not a function
    at frontend.min.js?ver=3.24.5:2:41225
    at webpackJsonpCallback (styleguide-app-initiator.min.js?ver=3.24.5:3:13486)
    at webpackJsonpCallback (webpack.runtime.min.js?ver=3.24.5:2:4680)
    at frontend.min.js?ver=3.24.5:2:74` Issues on latest version

**Comment by brunojuliao** [comment]
I manually edited the code (frontend.min.js) to check if e.O exists and, if it doesn't, just return. That worked for me. I hope this helps someone else with this issue.

**Comment by pierre14100-lis** [comment]
> I manually edited the code (frontend.min.js) to check if e.O exists and, if it doesn't, just return. That worked for me. I hope this helps someone else with this issue.

Hi Bruno, 
can you share your edit or explain it ? 
the version of the frontend.min.js is compressed, so that's so boring to try to understand anything ^^ 
Thanks


Same there for me : 
Uncaught TypeError: e.O is not a function
    <anonymous>/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.24.6:2
    webpackJsonpCallback /wp-content/plugins/elementor/assets/js/styleguide-app-initiator.min.js?ver=3.24.6:3
    webpackJsonpCallback /wp-content/plugins/elementor/assets/js/webpack.runtime.min.js?ver=3.24.6:2
    <anonymous> /wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.24.6:2
frontend.min.js:2:41225

**Comment by kimek** [comment]
I have same error. Additional info :
![image](https://github.com/user-attachments/assets/af9a3e63-966e-45ad-9db4-70f5207b9127)
![image](https://github.com/user-attachments/assets/ccb4caf9-6f86-4052-af70-ceb999224eb4)
I'm going to try update it if I got more info.

**Comment by mentorvid** [comment]
📂 [elemntor.zip](https://github.com/user-attachments/files/17789827/elemntor.zip)

👋 Hello everyone,
I'm Payam Yazdanian. To resolve the issue, simply replace the following three files with the ones provided in the attached zip.

📁 File Paths:
/public_html/wp-content/plugins/elementor/assets/js/

✅ After replacing these files, the problem should be resolved.

If you have any questions or need assistance, feel free to reach out to me on Telegram: @payam_yazdanian ✉️

**Comment by mentorvid** [comment]
> ⚠️⚠️⚠️⚠️⚠️ Don't use these 3th files. ⚠️⚠️⚠️⚠️⚠️

why? This is a temporary solution to eliminate the error without introducing additional issues.

**Comment by m1ga** [comment]
Looks like they are finally fixing this: https://github.com/elementor/elementor/pull/29422

**Comment by voxsar** [comment]
> @ev88 - Please read Nicholas' comment above about how there is no setting for this now that it is in core.
> 
> Also, to be clear, this error is minor and does NOT affect ANY functionality.
> 
> If you are experiencing functional issues then in all likelihood it is not related to this.

liar liar plants for hire

**Comment by nicholaszein** [comment]
Hi @voxsar .

Please make sure you read this document carefully:

https://elemn.to/gh-code-of-conduct

We will not tolerate misconduct of any kind in this repository.

Please, kindly keep the discussion civilized and On-Topic.

Thank you

**Comment by bugnumber9** [comment]
This issue is still there in the latest version.

**Comment by menshinobi** [comment]
Hi,

Why is this still an issue with a big theme like  Elementor? It has been opened for 1 year and eventually, there is no fix. It still happened in the latest version of Elementor Pro.

**Comment by nicholaszein** [comment]
Heeey patient people! 😃 

We have awesome news! 🙌 🙌 🙌 

### 📢 We're happy to announce that this issue was FINALLY SOLVED in Elementor Core v3.27.0! 🥳 🎉 

The Style Guide no Longer Throws a Console Error **`e.0 is not a function`** anymore! 💪 

It took us a while to find the right spot to fix this issue while working on v4, but we finally found a spot!

Thank you for those who showed some patience! We really appreciate it! 🙏 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
