### ISSUE TITLE
✅ 🔗 🚀 Feature Request: Accordion - setting for all closed at start (Merged with #2756)

### ISSUE THREAD

**Issue by ghost** [elementor/elementor#2481]
## Description

When Accordion is first displayed at page load, the first element is always open - would like a setting so all can be closed when page loads.

 arielk commented (and closed the issue) "For this option please use Toggle widget instead of Accordion"

Unfortunately, Toggle doesn't work the same as Accordion ... elements have to be closed manually. In Accordion, there is only ever one open at a time - which is the behavior I want - so Toggle isn't a substitute.

Where there is a longish list (e.g. and FAQ), it's better for the visitor to see all the list headings before chosing ... it doesn't make sense to have the first item open, as it probably isn't appropriate to the visitor.

**Comment by Basilakis** [comment]
@davidmcc3 that is also possible with some JS.
Take a look here: https://stackoverflow.com/questions/9419470/how-do-i-get-my-accordion-to-load-with-all-the-menus-closed

on how to make it happen.

**Comment by davidmcc3** [comment]
Hi Basilakis
I looked at the link, and I'm none the wiser. I know nothing of JS (except that it is JavaScript), and I've never been able to master coding in any langauge ... in part why I use WordPress and Plugins. I can change settings, but not add or change code.
I looked at the Elementor Accordion on a test page using Chrome's 'Inspect', but couldn't see what was different between open and closed elements.
But thanks for making the suggestion.

**Comment by nicktereh** [comment]
Please use the Toggle widget instead of the Accordion, It’s a similar widget but all items closed by default

Source https://wordpress.org/support/topic/close-first-accordion-item/

**Comment by enviedbymost** [comment]
+1 for this feature request.

Odd it's not closed by default. Kinda defeats the purpose of an accordion.

**Comment by userabuser** [comment]
In the mean time you can apply the following fix (extract into your own code/architecture if required)

```
function theme_wp_footer() {

    ?>
    
    <script>
        ;(function($) {
            $(function() {

                $('.elementor-accordion-title').each(function() {
                    $(this).removeClass('active').next('.elementor-accordion-content').hide();
                });

            });
        })(jQuery);
    </script>

    <?php
    
}

add_action('wp_footer', 'theme_wp_footer', PHP_INT_MAX);
```

It would be more ideal to have the configurable from within the widget however.

**Comment by davidmcc3** [comment]
Thanks for the code snippet ... but I don't do code/programming (have never mastered it) ... which is why I use plugins like Elementor.

Agree with enviedbymost's comment ... other Accordions I've used have been closed to start with.

**Comment by bainternet** [comment]
Should be added and default from version 1.8 and up.

If not please feel free to reopen this.

**Comment by casperroux** [comment]
@bainternet 
Can you please confirm if this is now possible, as I am using v1.8 and I don't see any option for this

Thanks
Casper

**Comment by philrp** [comment]
Same here. Updated to 1.8.1 and don't see an option for all closed at start.

And now neither the code above or the one I was using as a workaround work.

Thanks,
Phil

**Comment by jaessi** [comment]
One way to solve this would be to create an empty accordion item as the first item, then remove it.

`if ($('.elementor-accordion').length) {
                $('.elementor-accordion > .elementor-accordion-item:first-child').remove();
            }`

**Comment by bainternet** [comment]
In 1.8 we fixed the issue we had with the toggle, which is now closed by default.

**Comment by Dave-LeDev** [comment]
This still seems to be an issue with 1.8.5 free; the first element auto-opens and I'm not finding a setting to toggle this feature.

https://i.gyazo.com/b82815f87057e772d24c7428146d1ef4.png

https://i.gyazo.com/ffec2559eded647b76874555bbab73d5.png

**Comment by aymeric-wisepass** [comment]
I am facing the same issue.
@bainternet  The toggle function is not the same as the accordion (requires user to manually close each item) therefore there is still a need for a feature to have the 1st item of each accordion closed by default.

**Comment by torndownunit** [comment]
I can't believe this is still an issue.  Why would an accordion even be open by default?  Thanks for the fixes provided.

**Comment by kkaii** [comment]
I'm apologizing for my ignorance but where can I insert this code as I am working on the back end in Wordpress.  I utilized code snippets plugin before but really I do not know where to inject this code properly.  Thank you for your indulgence.

**Comment by davidmcc3** [comment]
I've started a new issue #4015 as one this has been closed (and I think it's been forgotten)

**Comment by Tomgalpo** [comment]
@osmanpro 

Thanks for the code,
I did what you said, but it writing me an error

> The code snippet you are trying to save produced a fatal error on line 7:

syntax error, unexpected end of file


why Is that?

**Comment by TeslaKudryavtsev** [comment]
> @Tomgalpo 
These code have an error, please copy this code. Enjoy!

function elementor_accordion_title() { ?>
	<script>
		jQuery(document).ready(function() {
			jQuery( '.elementor-accordion .elementor-tab-title' ).removeClass( 'elementor-active' );
			jQuery( '.elementor-accordion .elementor-tab-content' ).css( 'display', 'none' );
		});
	</script>
<?php }
add_action( 'wp_footer', 'elementor_accordion_title', 99 );`

**Comment by textfriseur** [comment]
Hello,
experiencing the same problem.
The code still seems to produce an error in line 7 (last line).
I am no expert in coding. But to me it seems, like the function braces in line one "{" never gets closed. (Also the "?>" looks incomplete to me.) I tried closing the function by adding "}" in line 8, but that produces an error in line 8.

**Comment by textfriseur** [comment]
I have found a workarround:
Add a HTML code element to the page and paste this code:

<script> 
jQuery(document).ready(function($) { 
var delay = 100; setTimeout(function() { 
$('.elementor-tab-title').removeClass('elementor-active');
$('.elementor-tab-content').css('display', 'none'); }, delay); 
}); 
</script>

It will close the first element after loading the page. It's ugly but it works.
source: https://voidcoders.com/elementor-accordion-closed-by-default/

**Comment by bentalgad** [comment]
+1

**Comment by bentalgad** [comment]
+1

**Comment by bentalgad** [comment]
Btw - Same thing with the "Toggle Widget"

**Comment by laughingboy9000** [comment]
As far as I can tell, both accordion and toggle still default open and I cannot see an option to alter this. I am not an avid Github user and certainly no coder but I'd thought I'd contribute nonetheless. Cheers.

**Comment by unstoppableaffiliate** [comment]
Okay ladies and gentlemen,

We have solved this issue & I'm happy to give you the solution. 

Step 1:  Drag the SHORTCODE element onto your page.

Step 2:  Copy and Paste this HTML inside that SHORTCODE.

<script> jQuery(document).ready(function($) { var delay = 100; setTimeout(function() { $('.elementor-tab-title').removeClass('elementor-active'); $('.elementor-tab-content').css('display', 'none'); }, delay); }); </script>

That worked for me on three sites.    Let me know  if that worked for you by giving me a heart...

**Comment by Zer0ne83** [comment]
Yeah not sure what 'fix' @v1.8+ the Team refers to way back in Nov 2017... maybe paid version? Anyway, with freebie-ver the first-child accordion tab (#tab1) still deffo adorned with .elementor-active Class by default in @latest. Cheers for the snippet @unstoppableaffiliate, did the job - need a shower after dropping a setTimeout loop in my header but don't have time to sort accordian.php so *tips hat*

**Comment by laughingboy9000** [comment]
So where does the shortcode widget go in respect to the accordion widget?

Cheers.

**Comment by mauro22it** [comment]
I've the same problem, I have tried the solutions given by@textfriseur and  @unstoppableaffiliate  to grad the HTML or SHORTCODE but it always returns 403 Error and the accordion elements remain always open when the page loads. 
I've found also this https://toolset.com/forums/topic/set-accordion-default-to-closed/
but I'm cannot find "Toolset > Layouts CSS & JS" is that for the PRO version only?

**Comment by unstoppableaffiliate** [comment]
You can put the shortcode ANYWHERE on the page because it’s just “code” to make the accordion work.

 

Thanks!
Kit

**Comment by davidmcc3** [comment]
I've been putting the code in the HTML widget, and placing it immediately below the Accordion ... seems the most logical place so you know where it is and you cxan easily see it's been added.

**Comment by davidmcc3** [comment]
mauro22it ... you've found the fix for a different plugin - Toolset (Types & Views) is a powerful plugin for creating custom posts and creating forms & data entry systems. Toolset describe it as  ... Custom WordPress Development For Non-CodersWordPress Development For Non-Coders  ... and it is very powerful.

**Comment by unstoppableaffiliate** [comment]
I like using the shortcode widget because it handles “scripts” while the HTML does not.

**Comment by laughingboy9000** [comment]
Thanks for all the answers guys - gives me the confidence to give it a try :)

**Comment by latin625** [comment]
Simply fix.  No code needed. 
Set the INITIAL PARAMETER to 0
Loads up collapsed.

[gdlr_accordion style="style-1" initial="0"]
[gdlr_tab title="ACCORDION_TITLE_1"]ACCORDION_CONTENT_1[/gdlr_tab]
[gdlr_tab title="ACCORDION_TITLE_2"]ACCORDION_CONTENT_2[/gdlr_tab]
[gdlr_tab title="ACCORDION_TITLE_3"]ACCORDION_CONTENT_3[/gdlr_tab]
[/gdlr_accordion]

**Comment by dougm1966** [comment]
> Simply fix. No code needed.
> Set the INITIAL PARAMETER to 0
> Loads up collapsed.
> 
> [gdlr_accordion style="style-1" initial="0"]
> [gdlr_tab title="ACCORDION_TITLE_1"]ACCORDION_CONTENT_1[/gdlr_tab]
> [gdlr_tab title="ACCORDION_TITLE_2"]ACCORDION_CONTENT_2[/gdlr_tab]
> [gdlr_tab title="ACCORDION_TITLE_3"]ACCORDION_CONTENT_3[/gdlr_tab]
> [/gdlr_accordion]

I don't believe that is a possible solution for the Elementor accordion not starting out closed.

Does anyone have any updated code to get this to work?

**Comment by Goodgitter** [comment]
> Okay ladies and gentlemen,
> 
> We have solved this issue & I'm happy to give you the solution.
> 
> Step 1: Drag the SHORTCODE element onto your page.
> 
> Step 2: Copy and Paste this HTML inside that SHORTCODE.
> 
> <script> jQuery(document).ready(function($) { var delay = 100; setTimeout(function() { $('.elementor-tab-title').removeClass('elementor-active'); $('.elementor-tab-content').css('display', 'none'); }, delay); }); </script>
> That worked for me on three sites. Let me know if that worked for you by giving me a heart...

Thank you - it's working here. I dragged the shortcode-widgtet above the accordion-widget.

**Comment by TheMangoTrain** [comment]
The shared script is a just band-aid fix. Javascript, which runs client-side, is 'dirty' and risks [FOUC](https://en.wikipedia.org/wiki/Flash_of_unstyled_content) and that's exactly what's happening. The page downloads and then scripts get processed, and a moment later new styling kicks in. The result is a user see's 'jumping & shifting' of your page when it loads. So, is that a lesser evil than the original issue?

In the land of drag-and-drop convenience, please still be mindful to just not keep layering on plugins and javascripts all over the place. You end up with a 10-second page load and slow/clunky user experiences.

### **A more elegant fix, CSS-only, no plugins:**
**1. Make the first accordion item a dummy element.**
Use whatever title and content you wish; it will never be seen by the user. If you're paranoid, and think a spider or page-reader will see the content, use a statement that is relevant. E.g. "Here you can get answers to your questions!" in the case of an accordion being used for an FAQ.

**2. Use CSS to hide the dummy accordion item**
Place this custom CSS wherever you prefer. In the widget itself probably makes sense. This will hide the dummy first accordion item, and voila, your accordion renders with first item visibly open.

```
/* Hides the first accordion item */
.elementor-accordion .elementor-accordion-item:first-child {
    display: none;
}
```


**To those trying the Javascript fix and getting an error 403:**
You may have a security plugin (like WordFence) kicking in doing it's thing. In this case it has nothing to do with your page-builder, and everything to do with you trying to input script in an HTML field in WP. In the case of WordFence, you need to enable learning mode so it can discover that what you're doing is okay.

Ultimately, the Elementor devs are probably working on this or considering it. So just be patient. **_Frying pans are only big enough to hold so many fish._**

**Comment by acal** [comment]
@TheMangoTrain has the best solution for me. I used the js solution and it worked fine until the most recent Elementor Pro update and now the js doesn't fire in the correct sequence to work properly.

**Comment by Franky-Four-Fingers** [comment]
How is this still not fixed???

**Comment by Franky-Four-Fingers** [comment]
> 
> 
> The shared script is a just band-aid fix. Javascript, which runs client-side, is 'dirty' and risks [FOUC](https://en.wikipedia.org/wiki/Flash_of_unstyled_content) and that's exactly what's happening. The page downloads and then scripts get processed, and a moment later new styling kicks in. The result is a user see's 'jumping & shifting' of your page when it loads. So, is that a lesser evil than the original issue?
> 
> In the land of drag-and-drop convenience, please still be mindful to just not keep layering on plugins and javascripts all over the place. You end up with a 10-second page load and slow/clunky user experiences.
> 
> Ultimately, the Elementor devs are probably working on this or considering it, so just be patient. **_Frying pans are only big enough to hold so many fish._**
> 
> In the meantime...
> ### **A more elegant fix, CSS-only, no plugins:**
> 
> **1. Make the first accordion item a dummy element.**
> Use whatever title and content you wish; it will never be seen by the user. If you're paranoid, and think a spider or page-reader will see the content, use a statement that is relevant. E.g. "Here you can get answers to your questions!" in the case of an accordion being used for an FAQ.
> 
> **2. Use CSS to hide the dummy accordion item**
> Place this custom CSS wherever you prefer. In the widget itself probably makes sense. This will hide the dummy first accordion item, and voila, your accordion renders with all items closed.
> 
> ```
> /* Hides the first accordion item */
> .elementor-accordion .elementor-accordion-item:first-child {
>     display: none;
> }
> ```
> 
> ### **To those trying the Javascript fix and getting an error 403:**
> 
> You may have a security plugin (like WordFence) kicking in doing it's thing. In this case it has nothing to do with your page-builder, and everything to do with you trying to input script in an HTML field in WP. In the case of WordFence, you need to enable learning mode so it can discover that what you're doing is okay.

This worked for now but pretty stupid it isn't build in.

**Comment by jimn10** [comment]
TheMangoTrain's solution also takes away the bottom border of the item # 1 which would have been the top border of item #2.
To fix this add the following CSS. Note: the color set to default. If you have a different border color, update the color in the following CSS.

_.elementor-accordion-item:nth-child(2) {
    border-top: 1px solid #D4D4D4 !important;
}_

**Comment by nvmom** [comment]
@TheMangoTrain and @jimn10: You two are AMAZING! These two fixes worked perfectly. Could not thank you enough for sharing your knowledge.

**Comment by RoyeA** [comment]
Use the elementor "Granular Control" and set "yes" for "Accordions closed?".
![image](https://user-images.githubusercontent.com/17787738/54732297-6cc4d900-4b69-11e9-8fef-90d0acd0adfe.png)

**Comment by nvmom** [comment]
Unfortunately, Granular Controls are only available to Pro users. :(

**Comment by mrbenjaminjo** [comment]
@bainternet Hi. What is the official Elementor resolution for this please? I don't want to hack around in CSS or code.

**Comment by davidmcc3** [comment]
Hi mrbenjaminjo
There is no official Elementor resolution - they've been ignoring this for about two years.
This is one of a number of threads which have been ignored, and people (say they) are beginning to find alternatives to Elementor.
As well as responsive design, we'd all like a responsive Elementor.

**Comment by henriweg** [comment]
> Okay ladies and gentlemen,
> 
> We have solved this issue & I'm happy to give you the solution.
> 
> Step 1: Drag the SHORTCODE element onto your page.
> 
> Step 2: Copy and Paste this HTML inside that SHORTCODE.
> 
> <script> jQuery(document).ready(function($) { var delay = 100; setTimeout(function() { $('.elementor-tab-title').removeClass('elementor-active'); $('.elementor-tab-content').css('display', 'none'); }, delay); }); </script>
> That worked for me on three sites. Let me know if that worked for you by giving me a heart...

It worked, but when you start, the contents of the accordion appear quickly. Could you hide this effect?

**Comment by MorganSkarin** [comment]
Guys, why don't you just install and use the accodions from Essential Addons (free version)? 😄

**Comment by lord-srujan** [comment]
Here is the final fix to this problem

A workaround I’ve seen is to leave the first item blank (or put anything in it, doesn’t matter what) and then use this CSS to hide it:

`/* Hides the first accordion item */
.elementor-accordion .elementor-accordion-item:first-child {
display: none;
}
`
This must fix the issue.

**Comment by dougm1966** [comment]
Why do I keep getting notifications for this thread when I've unsubscribed from it?

**Comment by bkno** [comment]
+1

Elementor please add this to the built-in accordion options.

**Comment by webersonloureiro** [comment]
**Solução que desenvolvemos para isso:**

`// Procedimento para iniciar todos os menus dos widgets de sanfona do elementor iniciando fechados

/**
* Se quiser que um Widget do tipo sanfona ou tabs exiba o primeiro item aberto basta
* pelo Elementor editar na aba Avançada do Widget adicionando no campo Classe Css o valor qwp-aberto
*/

setTimeout(function() {  

    if( $('.elementor-widget-accordion').length > 0 ){

        $('.elementor-widget-accordion').each( function(){ 

            if( $(this).hasClass('qwp-aberto') ){

                console.log('Aberto');
            }else{

                $(this).find('.elementor-tab-title:first').removeClass('elementor-active');
                $(this).find('.elementor-tab-content:first').css('display', 'none');  
                console.log('Fechado');
            }
        } );
    }

}, 100); `

**Comment by spac-em** [comment]
I feel very disgusted by this act by the developer and the team. the have just ignored all the request to the paying customer, its time to move to Brizzy since they have app-sumo lifetime plan. 
not only this I've seen many issues brought up they just ignore.

**Comment by Jenn0014** [comment]
Hi All, and @nvmom 

The Granular Control @RoyeA mentions is a Plugin https://wordpress.org/plugins/granular-controls-for-elementor/ after adding this I was able to switch accordion items to be closed on the entrance. 

A very easy fix, but should be in Elementor options not an additional plugin. 

Thanks
Jenn

**Comment by vvvamik** [comment]
Simply the best solution!

[https://digitalfreelancing.eu/how-to-close-by-default-the-accordion-in-elementor/](url)

**Comment by thallysondiasdmc** [comment]
> Simply the best solution!
> 
> [https://digitalfreelancing.eu/how-to-close-by-default-the-accordion-in-elementor/](url)

This page is not found.
Im using this script: https://bitbucket.org/snippets/quarteldesign/4AbKpX

**Comment by vvvamik** [comment]
> 
> 
> > Simply the best solution!
> > [https://digitalfreelancing.eu/how-to-close-by-default-the-accordion-in-elementor/](url)
> 
> This page is not found.
> Im using this script: https://bitbucket.org/snippets/quarteldesign/4AbKpX

Sorry, I fixed the link.

**Comment by vgstef** [comment]
I have the latest Elementor (Pro) version, and I'm facing this issue. Any updates from the developers?

**Comment by jongoodey** [comment]
I know it may be a slightly hacky way but I added custom css:

`.elementor-accordion-item:first-child` {
    display: none;
}`

and then duplicated the first item on the list, the great thing with this is if you have multiple accordions on the page or site you only need to do this once.

**Comment by TheoKoenig** [comment]
I can't believe this feature is not available. +1 for making it happen.

**Comment by jessetuttle** [comment]
**FIX WITHOUT INSTALLING ANY OTHER PLUGINS, NO CODING OF FILES, NO NEED TO HIDE FIRST-CHILD.**

As I would like to see this added as a setting, one of many settings I would like to see added. It is pretty easy to fix.

Use the **HTML Elementor Block**, then inside the block put the following code.

```
<script> 
jQuery(document).ready(function($) { 
var delay = 100; setTimeout(function() { 
$('.elementor-tab-title').removeClass('elementor-active');
 $('.elementor-tab-content').css('display', 'none'); }, delay); 
}); 
</script>
```

Want this effect across your entire site? Place it in your header or footer.

Source: https://digitalfreelancing.eu/how-to-close-by-default-the-accordion-in-elementor/

**Comment by advivesolutions** [comment]
<script>
  jQuery(function($) {
      $(function() {

          $('.elementor-tab-title').each(function() {
              $(this).removeClass('elementor-active').next('.elementor-tab-content').hide();
          });

      });
  });
</script>

You can install any headers & footers plugin to add this code.

**Comment by beepmeapp** [comment]
### ### ### ### ###

**Comment by ajn2199** [comment]
In case anyone is still interested, there is a much simpler CSS only work around here.  The idea was inspired by @jaessi. 

Add an extra item at the top of the accordion, then under the accordion's Advanced / Custom CSS enter this:

selector .elementor-accordion-item:first-child{
    display: none;
}

That turns of display of the first, open, accordion item, leaving only the closed ones visible.

**Comment by TheoKoenig** [comment]
> In case anyone is still interested, there is a much simpler CSS only work around here. The idea was inspired by [**@jaessi**](https://github.com/jaessi).
> 
> Add an extra item at the top of the accordion, then under the accordion's Advanced / Custom CSS enter this:
> 
> selector .elementor-accordion-item:first-child{  
> display: none;  
> }
> 
> That turns of display of the first, open, accordion item, leaving only the closed ones visible.

This is what I ended up using. Good solution, except when it's time to explain to the site editor why he has to leave an empty item at the top of the list :/

**Comment by userabuser** [comment]
> Good solution, except when it's time to explain to the site editor why he has to leave an empty item at the top of the list :/

I wonder if it's possible to inject an item at the top of the list programmatically via a hook to remove the burden/technical implementation-debt from the author?

Been a while since I looked at it but may be worth looking into the module.

**Comment by jessetuttle** [comment]
> In case anyone is still interested, there is a much simpler CSS only work around here. The idea was inspired by @jaessi.
> 
> Add an extra item at the top of the accordion, then under the accordion's Advanced / Custom CSS enter this:
> 
> selector .elementor-accordion-item:first-child{
> display: none;
> }
> 
> That turns of display of the first, open, accordion item, leaving only the closed ones visible.



> > In case anyone is still interested, there is a much simpler CSS only work around here. The idea was inspired by [**@jaessi**](https://github.com/jaessi).
> > Add an extra item at the top of the accordion, then under the accordion's Advanced / Custom CSS enter this:
> > selector .elementor-accordion-item:first-child{
> > display: none;
> > }
> > That turns of display of the first, open, accordion item, leaving only the closed ones visible.
> 
> This is what I ended up using. Good solution, except when it's time to explain to the site editor why he has to leave an empty item at the top of the list :/



> > Good solution, except when it's time to explain to the site editor why he has to leave an empty item at the top of the list :/
> 
> I wonder if it's possible to inject an item at the top of the list programmatically via a hook to remove the burden/technical implementation-debt from the author?
> 
> Been a while since I looked at it but may be worth looking into the module.

A good solution was provided without the need of leaving the first line empty.

https://github.com/elementor/elementor/issues/2481#issuecomment-622359366

Enjoy! :)

**Comment by TheoKoenig** [comment]
> A good solution was provided without the need of leaving the first line empty.
> 
> [#2481 (comment)](https://github.com/elementor/elementor/issues/2481#issuecomment-622359366)
> 
> Enjoy! :)

This hack isn't what I would call a "good solution" as it only takes effects when the page is loaded (and slows down the loading)

**Comment by maxin0** [comment]
> In case anyone is still interested, there is a much simpler CSS only work around here. The idea was inspired by @jaessi.
> 
> Add an extra item at the top of the accordion, then under the accordion's Advanced / Custom CSS enter this:
> 
> selector .elementor-accordion-item:first-child{
> display: none;
> }
> 
> That turns of display of the first, open, accordion item, leaving only the closed ones visible.

Thanks for this, it works well. I do have a question though: is this solution compatible with screen readers, ie. will the first row be hidden for screen readers?

**Comment by plethoradesign** [comment]
I had a bunch of accordions on my site and didn't relish the idea of manually adding a blank tab to each of those. I wrote some JS to handle this. This has to run on document load (not on ready), because of the way the accordion JS loads. This is working for me. It is possible that the JS load order will cause issues for others. Hopefully this helps some. 

`$(window).on('load', function() {
       $('.elementor-accordion').each(function(){
        $(this).find('.elementor-accordion-item:first-child > div').removeClass("elementor-active").removeAttr("style");
       });
    });`

**Comment by deepak-crebos** [comment]
> In the mean time you can apply the following fix (extract into your own code/architecture if required)
> 
> ```
> function theme_wp_footer() {
> 
>     ?>
>     
>     <script>
>         ;(function($) {
>             $(function() {
> 
>                 $('.elementor-accordion-title').each(function() {
>                     $(this).removeClass('active').next('.elementor-accordion-content').hide();
>                 });
> 
>             });
>         })(jQuery);
>     </script>
> 
>     <?php
>     
> }
> 
> add_action('wp_footer', 'theme_wp_footer', PHP_INT_MAX);
> ```
> 
> It would be more ideal to have this configurable from within the widget however.

Snippet worked for me and Thanks a lot for that.

**Comment by Makedonec115** [comment]
This is the CSS solution for elementor accordion all closed with adding an extra empty item at the top of the accordion:
.elementor-accordion .elementor-accordion-item:first-child { display: none; }
.elementor-accordion-item:nth-child(2) {
border-top: 1px solid #D4D4D4 !important;
}

**Comment by koddajr** [comment]
2021 and nothing... maybe 2022?

**Comment by alexplayer** [comment]
Still waiting for this - need it even more now that RankMath has built a nice FAQ schema to work with this module. But it just looks crap with it left open on load.

**Comment by djnorrisdev** [comment]
Elementor provides the Toggle Widget which has the first item closed by default. The only difference I see is the outer border is not there and the icons need to be changed if you want to (both of which can be changed through the elementor panel)

**Comment by olasek** [comment]
Omg why are you looking for such a complex solution?

My solution via CSS:
1) Create first accordion item
2) Write to Setting template code:
.elementor-accordion > div:first-of-type { display:none;}

Thats all
Easy Peasy Japanesey

**Comment by cirkut** [comment]
We're not looking for a complex solution, we're simply asking for Accordions and Toggles to be closed by default, which they're not.

Accordions by nature are supposed to only allow one item open at a time, and when you open another, the previous closes.

Toggles by nature are supposed to allow multiple items open at a time.

For whatever reason, Elementor decided to make Accordions open by default, which is not what an accordion is actually intended for.

**Comment by ajoah** [comment]
Hi all,

I found a new JS solution without delay, custom css or empty item :

```javascript
jQuery( window ).on( 'elementor/frontend/init', () => {
  elementorFrontend.hooks.addAction( 'frontend/element_ready/accordion.default', function ( $scope ) {
	  $scope.find( '.elementor-tab-title' ).first().addClass( 'elementor-active' );
  }
);
```
Yes it is not intuitive :
The code pretend to activate the first item before the widget is initialized. So when the widget run, it thinks that the first item is activated and toggle it. (so close it)

Anyway, it is very easy to Elementor Team to permit to us to auto open or not the first item on init : 
There is already an `autoExpand` setting in widget javascript. (which is always at `true`). They just have to add control settings in panel editor to change it.

An opinion @bainternet ?

**Comment by jasonb4u** [comment]
its 21st May 2021 and still no option to have closed or open on page load, come on Elementor !

**Comment by Franky-Four-Fingers** [comment]
Unbelievable!! How is this still not fixed? Stupid to still use a HTML snippet!

Ultimate Addons has an accordion that starts closed but the plugin uses too much resources to just use one widget.

**Comment by pinkgerbils** [comment]
why is this closed when it's still an issue?!

**Comment by mrandt** [comment]
I also require the option to start with a closed accordion sections. Please reopen the ticket and fix this once and for all! Thanks!

**Comment by phil-hei** [comment]
Can't believe that this is still an issue...

The JS workaround works only if I'm logged in as a user to my page, while the accordion is open when I open the page in a private tab without being logged in as a user. Any ideas what could be the problem here?

**Comment by liranbp** [comment]
its still an issue and even the js not works anymore!!! please reopen it and fix it

**Comment by liranbp** [comment]
YES! reopen this please. all the js solutions don't think about the user experience and page score, closing after 200ms means the page will jump and change after loading and its important not to use these kind of things by Core Web Vitals

**Comment by pinkgerbils** [comment]
Yes please re-open - someone promised to update in 2017 and closed the issue but it never materialised!

**Comment by pinkgerbils** [comment]
Here is working JS if anyone needs it.

<script> 
jQuery(document).ready(function($) { 
var delay = 100; setTimeout(function() { 
$('.elementor-tab-title').removeClass('elementor-active');
 $('.elementor-tab-content').css('display', 'none'); }, delay); 
}); 
</script>

**Comment by phil-hei** [comment]
This JS snippet isn't working for me, neither with Safari nor with Chrome

**Comment by liranbp** [comment]
Anyway as I said either the JS snippet works or not its very bad for user experience and google scores because its moving on the screen after load

**Comment by pinkgerbils** [comment]
> This JS snippet isn't working for me, neither with Safari nor with Chrome

Are you adding via HTML widget? Just tested again and works fine on Chrome, Safari, Firefox on OSX and iOS.

**Comment by pinkgerbils** [comment]
> Sincerely shocked that this is still an ongoing issue. Something so simple, yet fundamental, and still no resolution after 5 years.

It's because someone accidentally closed it thinking the issue was fixed, not sure anyone from Elementor bothers looking at closed tickets.

**Comment by phil-hei** [comment]
> > This JS snippet isn't working for me, neither with Safari nor with Chrome
> 
> Are you adding via HTML widget on the same page? I have just tested again and works fine on Chrome, Safari, Firefox on OSX, Windows and iOS.

Yes, I added it to the same page via the HTML widget:
<img width="333" alt="Bildschirmfoto 2022-01-18 um 13 14 35" src="https://user-images.githubusercontent.com/36535721/149935771-f43f5bc2-9e9d-434a-968a-e7de5597cc5f.png">

On this page we're currently using the free version. Maybe this causes the behaviour?

**Comment by pinkgerbils** [comment]
Could be that, or the fact something else is blocking the jQuery code.. it's 100% working across all sites I use it on, though they are all pro plans.

**Comment by pinkgerbils** [comment]
> Anyway as I said either the JS snippet works or not its very bad for user experience and google scores because its moving on the screen after load

Agree - I think the blank first accordion + hide via css is nicer.

**Comment by Crushtests** [comment]
Well... I believe after i pudated the elementor, the script didn't work now. nothing works now...

**Comment by liranbp** [comment]
because this one is closed and they probably don't see it or mention it. I just opened new one.
you all welcome to comment and +1 there
https://github.com/elementor/elementor/issues/17592

**Comment by cdibut** [comment]
How can we hide title and tab-content for multiple section in a DOC. 

With the code below I am able to hide content across accordions (Assumed we have more than one on a DOC)  but what if I want to hide content by sections instead of applying the function to the whole document ? 

`<script>
jQuery(document).ready(function($) {
var delay = 100; setTimeout(function() {
$('.elementor-tab-title').removeClass('elementor-active');
 $('.elementor-tab-content').css('display', 'none'); }, delay);
});
</script>`

Anyone resolved this issue via CSS code?

**Comment by BrandBox22** [comment]
3/11/2022

No solution yet? 😭

**Comment by nicholaszein** [comment]
Hello everybody!

Thank you for your submission! 🙏 

### 🔗 This issue is a Duplicate of #2756

Which is on the same subject. 

For this reason, I'm closing this issue and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### ✔️ Please, in the future, remember to check if there isn't an issue similar to yours already opened. 

Best regards,

Nick
