### ISSUE TITLE
🔗 🐞 Uncaught TypeError: e.O is not a function (Duplicate of #24492)

### ISSUE THREAD

**Issue by askwpgirl** [elementor/elementor#26121]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

The Elementor Editor shows the following error on all sites:

Uncaught TypeError: e.O is not a function
    at frontend.min.js?fsum=fe720b41891a:2:39876
    at webpackJsonpCallback (styleguide-app-initiator.min.js?fsum=c3f449f87f77:3:13486)
    at webpackJsonpCallback (webpack.runtime.min.js?fsum=d3c859a3d439:2:4680)
    at frontend.min.js?fsum=fe720b41891a:2:74
    
   
![JS_error_in_Elementor_Editor](https://github.com/elementor/elementor/assets/329025/576c0752-40b0-4ee7-8643-8bf29e3d1287)

### Steps to reproduce

1. Open Elementor Editor
2. Use browser Inspect Tool
3. Click on Console tab

### Expected behavior

No Javascript errors. 

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: nginx/1.22.0
	MySQL version: mariadb.org binary distribution v10.3.16
	PHP Version: 8.0.30
	PHP Memory Limit: 768M
	PHP Max Input Vars: 5000
	PHP Max Post Size: 500M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5.2
	Site URL: https://mysite.com
	Home URL: https://mysite.com
	WP Multisite: No
	Max Upload Size: 500 MB
	Memory limit: 768M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: 8
	Debug Mode: Inactive

== Theme ==
	Name: GeneratePress
	Version: 3.4.0
	Author: Tom Usborne
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.21.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.21.1
		Author: Elementor.com


== Must-Use Plugins ==
	SiteDistrict Single Sign-on
		Version: 0.1.0
		Author: SiteDistrict Team


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active
	Inline Font Icons: Active
	Additional Custom Breakpoints: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Active
	Upgrade Swiper Library: Active by default
	Grid Container: Active
	Nested Elements Performance: Inactive by default
	Optimized Control Loading: Inactive by default
	Default to New Theme Builder: Inactive
	Elementor Home Screen: Active by default
	Editor Top Bar: Inactive by default
	Build with AI: Inactive
	Landing Pages: Active
	Nested Elements: Inactive by default
	Lazy Load Background Images: Inactive by default
	Display Conditions: Inactive by default
	Form Submissions: Inactive
	Menu: Inactive by default
	Taxonomy Filter: Inactive by default


== Log ==
	
Log: showing 20 of 382024-03-27 07:58:25 [info] elementor-pro::elementor_pro_updater Started 
2024-03-27 07:58:25 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-03-27 07:58:25 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-03-27 07:58:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.20.1',
  'to' => '3.20.2',
)]
2024-03-27 07:58:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.20.1',
  'to' => '3.20.2',
)]
2024-04-26 00:38:42 [info] elementor::elementor_updater Started 
2024-04-26 00:38:42 [info] Elementor/Upgrades - _on_each_version Start  
2024-04-26 00:38:42 [info] Elementor/Upgrades - _on_each_version Finished 
2024-04-26 00:38:42 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.3',
  'to' => '3.21.2',
)]
2024-04-26 00:38:42 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.20.3',
  'to' => '3.21.2',
)]
2024-04-26 08:01:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.2',
  'to' => '3.21.3',
)]
2024-04-26 08:01:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.20.2',
  'to' => '3.21.1',
)]
2024-04-26 08:01:41 [info] elementor::elementor_updater Started 
2024-04-26 08:01:41 [info] Elementor/Upgrades - _on_each_version Start  
2024-04-26 08:01:41 [info] Elementor/Upgrades - _on_each_version Finished 
2024-04-26 08:01:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.21.2',
  'to' => '3.21.3',
)]
2024-04-26 08:01:41 [info] elementor-pro::elementor_pro_updater Started 
2024-04-26 08:01:41 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-04-26 08:01:41 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-04-26 08:01:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.20.2',
  'to' => '3.21.1',
)]

JS: showing 2 of 2JS: 2024-03-28 03:01:18 [error X 1]../wp-content/plugins/elementor/assets/js/frontend.min.js?fsum=7ed27d9a197c:2:19856] Cannot read properties of undefined (reading &#039;top&#039;) 
JS: 2024-03-28 03:01:21 [error X 1]../wp-content/plugins/elementor/assets/js/ai.min.js?fsum=b06cd57fc2e9:3:7564] ReactUtils is not defined 

PHP: showing 2 of 2PHP: 2024-04-26 00:42:17 [warning X 4][../wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-04-26 08:01:41 [warning X 2][../wp-content/plugins/elementor/core/files/manager.php::111] unlink(../wp-content/uploads/elementor/css/min): Is a directory [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by m1ga** [comment]
duplicate of https://github.com/elementor/elementor/issues/24492

but yes: should be fixed as it's not good to have errors in the frontend.min.js

**Comment by askwpgirl** [comment]
Thanks @m1ga - I searched for this and couldn't find it. It's been give months, so yes, perhaps should be fixed. However, that original ticket is incorrect. This happens on every Elementor edit page regardless of whether the Style Guide is active. It is the Edit page that throws this error, not the Style Guide.

**Comment by m1ga** [comment]
I think when the other issue was posted you still had the "global styleguide" feature in the settings and could turn it off. Now that is not there anymore and you can only change it in the site settings of the editor but it doesn't switch it off completely like before. Nevertheless it shouldn't be there :smile:

**Comment by stephroseg** [comment]
definitely an issue in subsequent versions of 3.20.x -- I have rolled back to 3.20.0 for both Elementor and Elementor Pro and the issue does not occur - all pages/templates and posts  load in the editor if you upgrade - and throw the Uncaught Exception. I'll be staying at 3.20.0  until there's a fix.

**Comment by m1ga** [comment]
Out of curiosity @stephroseg : does it break something for you in the Editor? I do see that error but the editor works fine. The only error that is causing it not to open is https://github.com/elementor/elementor/issues/19345#issuecomment-2085235911 (you have to open the devtools and reload so it will open)

Both issue should be fixed immediately as "opening the Editor"  should be daily business and not produces any error!

**Comment by pthompson-cloudinary** [comment]
> Out of curiosity @stephroseg : does it break something for you in the Editor? I do see that error but the editor works fine. The only error that is causing it not to open is [#19345 (comment)](https://github.com/elementor/elementor/issues/19345#issuecomment-2085235911) (you have to open the devtools and reload so it will open)
> 
> Both issue should be fixed immediately as "opening the Editor" should be daily business and not produces any error!

Hi @m1ga 

This appears to be causing an issue for me, I can't select or use the Manual Post Selection functionality with Unlimited Elements - though everything else seems to work.

I can't be 100% sure, but this seems to be the only new error being thrown

**Comment by peixotorms** [comment]
I noticed this error today, as I was editing a page and bought a license for Essential Addons For Elementor.
Adding their posts element, shows the layout completely broken and on console log it's the same thing.

```
frontend.min.js?ver=3.21.5:2 Uncaught TypeError: e.O is not a function
    at frontend.min.js?ver=3.21.5:2:39876
    at webpackJsonpCallback (styleguide-app-initi…?ver=3.21.5:3:13486)
    at webpackJsonpCallback (webpack.runtime.min.js?ver=3.21.5:2:4680)
    at frontend.min.js?ver=3.21.5:2:74
```

**Comment by askwpgirl** [comment]
@peixotorms  - I think your issue with Essential Addons is independent of this error since this error occurs without Essential Addons installed. It might be, like most people, you only noticed because you happened to look at the Console tab due to having issues with something else.

**Comment by peixotorms** [comment]
> @peixotorms - I think your issue with Essential Addons is independent of this error since this error occurs without Essential Addons installed. It might be, like most people, you only noticed because you happened to look at the Console tab due to having issues with something else.

That would be correct. It was the only issue in the console log.

Essential Addons eventually worked, by downgrading elementor all the way down to 3.20 and back again to the latest version.
However, the error is still there and it's not great to have these errors, when a simple check to see if it's available could solve it.

ex:

```
if (e && typeof e.O === 'function') {
   // Safely call the function since we've confirmed it's a function
} else {
    console.error('e.O is not a function');
}
```

Anyway, not critical.

Thanks!

**Comment by m1ga** [comment]
You have to think that "using the editor without errors" would be a high priority because if you can't open it you can't use it :shrug:  

But most PRs at the moment are about the new `Conversion Center` (i know, different teams and so on):
> A powerful feature to enhance your online presence. With the ability to create compelling Link in bio pages and easily accessible contact buttons, the Conversion Center is tailored to significantly boost your conversions.

But is there not one Elementor dev that is using Elementor and sees those errors and wants to get rid of them?

**Comment by michaelhaberle** [comment]
Echoing what many others have experienced already ~ the error seems to be present in all current 3.2x.x versions (3.20.0 and 3.21.0 included) even with a vanilla theme and all other plugins disabled. Only downgrading to 3.19.4 + disabling the Global Style Guide has fixed it on my end thus far.

Settings -> Features -> Stable Features -> Global Style Guide --- select "Inactive"

Not ideal from a security or compatibility perspective. Hopefully it gets resolved soon!

**Comment by asansano** [comment]
thumbs up for @michaelhaberle . same here on all our websites with elementor 3.2.x.x (incl. PRO) and Hello Elementor 3.0.1. only way to get around is to rollback and deactivate the global style guide. it throughs not only this error in console, it prevents the elementor editor to get into saved status after saving. means that it still saved the updated content, but don't let the browser know about this. for the browser (chrome) the pages remains unsaved... which is really annoying as it throughs a nasty leaving alert on autosave or leaving the editor page.

**Comment by nicholaszein** [comment]
### 🔗 🐞 This issue is a Duplicate of #24492

Which is on the same subject. 

For this reason, I'm closing this thread and 🔃 **Merging** it with the original, so we can have all the discussions in one location, and deal with it more efficiently.

Feel free to continue the conversation there. 😉 

### 🔍 Please, in the future, remember to check if there isn't any thread similar to yours already opened. 

Kind regards
