### ISSUE TITLE
Elementor loop grid's post taxonomy custom query not working

### ISSUE THREAD

**Issue by bilalkhan891** [elementor/elementor#27647]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

I am trying to display only the child terms on an archive page of a custom taxonomy's term called "verticals".

```
function filter_elementor_loop_widget_terms($query) {
    // Check if it's a taxonomy archive for 'verticals'
    if (is_tax('verticals')) {
        // Get the current term object
        $current_term = get_queried_object();

        // Get child terms of the current term
        $args = array(
            'taxonomy'   => 'verticals',
            'child_of'   => $current_term->term_id,
            'hide_empty' => false,  // Set to true if you want to hide empty terms
            'fields'     => 'ids', // We only need the IDs
        );

        $child_terms = get_terms($args);

        if (!empty($child_terms) && !is_wp_error($child_terms)) {
            // Modify the query to include only child terms
            $query->set('post_type', 'any'); // This ensures we're adding a tax_query and not replacing it
            $query->set('tax_query', array(
                array(
                    'taxonomy' => 'verticals',
                    'field'    => 'term_id',
                    'terms'    => $child_terms,
                ),
            ));
        } else {
            // Ensure no results are returned if no child terms are found
            $query->set('tax_query', array(
                array(
                    'taxonomy' => 'verticals',
                    'field'    => 'term_id',
                    'terms'    => array(0), // This ensures no results
                ),
            ));
        }
    }
}
add_action('elementor/query/child_verticals_terms', 'filter_elementor_loop_widget_terms');
```

This does not display anything at all. I have tried other options as well but no luck.

I even tried giving the query manual IDs for terms to display but that does not work either.

So I am assuming there is something wrong with the way I am trying to apply this hook.

Right below this book, I created another hook to filter posts by their title and it worked fine.

### Steps to reproduce

1. I added loop gird to an archive page
2. I Selected taxonomy as the query to show only child items of the current term
3. I Wrote custom query and add the ID in the query section 

### Expected behavior

1. I want to expect to see the child items of the current term.
2. It didn't show any results at all.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [ ] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
This does not display anything at all. I have tried other options as well but no luck.

I even tried giving the query manual IDs for terms to display but that does not work either.

So I am assuming there is something wrong with the way I am trying to apply this hook.

Right below this book, I created another hook to filter posts by their title and it worked fine.
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by cesgarma** [comment]
I have the same problem. I don't think my query ID is ever called at all when using Taxonomy as a query.

**Comment by Ainner** [comment]
I have the same problem too. The loop taxonomy is not working with query id.

**Comment by Ainner** [comment]
If I enter the query ID, the loop will be interrupted, the page will empty.

**Comment by johnnny-bravoo** [comment]
I'm also having the same issue. "Custom Taxonomy ->Manual Selection -> Include By" returns empty result.

**Comment by BakkerHenk** [comment]
If you have a Query ID set, you should be able to manipulate the query arguments using:
`$args = apply_filters(
	"elementor/loop_taxonomy/args",
	$this->get_additional_allowed_args( $args, $display_settings ),
	$settings,
	$display_settings,
);`

I needed a random order for a taxonomy loop grid and used this filter to manipulate the order.
```add_filter( "elementor/loop_taxonomy/args", function( $args, $settings, $display_settings ) {
	if( $args["term_taxonomy_id"] == "my_query_id" ) {
		// Manipulate the query arguments here
		// See: https://developer.wordpress.org/reference/classes/wp_term_query/__construct/
		$args["orderby"] = "none";
		// Keeping the term_taxonomy_id set will prevent the query from working
		// so unset it here. :(
		unset( $args["term_taxonomy_id"] );
	}
	// Make sure to return the query arguments
	return $args;
}, 10, 3 );```

**Comment by steveindzine** [comment]
I am trying to use a custom query with a post loop set to taxonomy, to show terms which are set on particular post type. When add my simple query the terms all vanish.

This is my PHP:
`function partner_image_query( $query ) {
	$query->set( 'post_type', 'partner_image' );
}
add_action( 'elementor/query/partner_image', 'partner_image_query' );`

Am I doing something wrong?

**Comment by steveindzine** [comment]
Can anyone at Elementor confirm if the custom query is giving us access to the args in WP_Term_Query:  https://developer.wordpress.org/reference/classes/WP_Term_Query/__construct/

I have tried object_ids but always get an empty loop. I also tried with nothing and also get an empty loop. I think it's properly broken.

**Comment by carlos-blazquez-global** [comment]
Hello.

Regarding this issue, I have found that when assigning a custom query id to a taxonomy loop grid that value is assigned to the `term_taxonomy_id` parameter of the [WordPress term query constructor](https://developer.wordpress.org/reference/classes/wp_term_query/__construct/), hich ends up causing empty loops.

So, to fix this, what you need to do is to clean up the argument passed to the query, and then do whatever you need to do:

```
function elementor_loop_taxonomy_args( $args, $settings, $display_settings ) {
	if( isset( $settings['term_taxonomy_id'] ) && $settings['term_taxonomy_id'] === 'my_custom_query_id' ) {
		$args['term_taxonomy_id'] = '';
		//do some stuff
	}
	return $args;
}
add_filter( 'elementor/loop_taxonomy/args', 'elementor_loop_taxonomy_args', 20, 3 );
```

**Comment by basicmatrix** [comment]
@carlos-blazquez-global 
THANK YOU!!! I scoured the Internet trying to find out why the custom query functionality [outlined in Elementor's documentation here](https://developers.elementor.com/docs/hooks/custom-query-filter/) didn't work. I found many other dejected souls out there pulling their hair out as well. Your solution IMMEDIATELY fixed the issue of empty results.

For clarity here, your //do some stuff section here doesn't appear to have access to the WP Query object. What are we supposed to manipulate here to customize, filter, and otherwise modify the query?

Particularly, I'm after a simple and basic functionality that should be included by default. I simply want to specify a category and have my query display all the subcategories in that category. Believe it or not this doesn't appear to be available anywhere within Elementor. I would prefer to simply pick the category in the "include" filter of Elementor and then use that ID in my custom query PHP code to modify the filter to display all the children of that cateogry ID instead.

Any help would be appreciated.

**Comment by manuel-will** [comment]
I've been banging my head for two days on creating a query that works. I just want to add that the defining success factor was using

_elementor/loop_taxonomy/args_

instead of just using elementor/query/{$query_id}

Elementor should fix their [dev documentation page](https://developers.elementor.com/docs/hooks/custom-query-filter/) on this one. Would have saved me hours of work.

**Comment by hackerwebdesign** [comment]
@manuel-will You're saying just changing `add_action('elementor/query/query_name' )` to `add_action('elementor/loop_taxonomy/query_name')` works, but I have tried this and I see no change in my loop grid output (or am I missing something here?). 
Here is what I am using (and was working) to filter the loop to show CPTs that match 2 categories:
`add_action( 'elementor/query/query_filter', function ( $query ) {
    
    $tax_query = [
        'relation' => 'AND',
        [
            'taxonomy'  => 'resource-category',
            'field'     => 'slug',
            'terms'     => 'category1'
		],
		[
	    'taxonomy'  =>  'resource-category',
            'field'     =>  'slug',
            'terms'     =>  'category2'
		]
    ];

    // inject tax_query to query
    $query->set( 'tax_query', $tax_query );
} );`

**Comment by manuel-will** [comment]
@hackerwebdesign Are you trying to show posts or categories (taxonomies) themselves? I think I don't yet fully understand what your query should output.

The comment I made is specifically for setting the loop grid to "Post Taxonomies" instead of posts. So when one wants to show taxonomies not posts.

**Comment by arekuki** [comment]
+1

**Comment by SamP-dgt** [comment]
It looks like the issue is still there. In my case, the code suggested by @carlos-blazquez-global 


```
function elementor_loop_taxonomy_args( $args, $settings, $display_settings ) {
	if( isset( $settings['term_taxonomy_id'] ) && $settings['term_taxonomy_id'] === 'my_custom_query_id' ) {
		$args['term_taxonomy_id'] = '';
		//do some stuff
	}
	return $args;
}
add_filter( 'elementor/loop_taxonomy/args', 'elementor_loop_taxonomy_args', 20, 3 );
```


works in terms of cleaning the argument passed to the query. However, when more than 1 result should be returned, it turns out that the first is returned properly, the following just repeat the current product ID, which makes no sense. 

I tried to returns all the termsof a custom taxonomy ('autore') associated to the current product with the following code

```
add_filter( 'elementor/loop_taxonomy/args', function( $args, $settings, $display_settings ) {

    $target_query_id = 'autori_correlati';

    if ( isset( $settings['term_taxonomy_id'] ) && $settings['term_taxonomy_id'] === $target_query_id ) {

        $args['term_taxonomy_id'] = ''; 
        $args['term_id'] = '';         
        $args['include'] = [];         

        if ( is_singular('product') ) {
            global $product;
            if ( $product ) {
                $taxonomy = 'autore';
                $terms = get_the_terms( $product->get_id(), $taxonomy );

                if ( $terms && ! is_wp_error( $terms ) ) {
                    $term_ids = array_map( 'intval', wp_list_pluck( $terms, 'term_id' ) );

                    $args = [
                        'taxonomy'   => $taxonomy,
                        'include'    => $term_ids,
                        'orderby'    => 'name',
                        'order'      => 'ASC',
                        'hide_empty' => false,
                    ];
                }
            }
        }
    }
    return $args;
}, 20, 3 );
```


but to no avail, as soon as terms are more than 1.

Please someone in the community advise, or at Elementor Team provide some guidance or up-to-date documentation on how to properly use Query_IDs in terms loops.

**Comment by brajno** [comment]
@SamP-dgt you should probably set your $args['meta_query']. 
https://developer.wordpress.org/reference/classes/wp_meta_query/

**Comment by devdanielsun** [comment]
Thanks @carlos-blazquez-global for your answer!

For anyone who is still struggling this is what worked for me. @SamP-dgt 

**Situation:**
On my custom 'single post' template I wanted to show ACF fields of the custom category(s) linked to that specific post. Through a template and Loop Raster, and the following code I got it working.

**Working code:**

```php
function elementor_loop_taxonomy_args( $args, $settings, $display_settings ) {
	if (isset( $settings['term_taxonomy_id'] ) && $settings['term_taxonomy_id'] === 'my_custom_query_id') {
		$args['term_taxonomy_id'] = '';
		//do some stuff

        if ( is_singular() ) {
            // Get current post id
            $post_id = get_the_ID();

            echo 'Current post ID: ' . $post_id . '<br>';

            // Taxonomy comes from $args, NOT from a query object
            if ( empty( $args['taxonomy'] ) ) {
                return $args;
            }

            echo 'found taxonomy in args: ';
            var_dump( $args['taxonomy'] );
            echo '<br>';

            $taxonomies = (array) $args['taxonomy'];

            // Get term ids related to post id
            $term_ids = wp_get_post_terms(
                $post_id,
                $taxonomies,
                [ 'fields' => 'ids' ]
            );

            echo 'found terms: ';
            var_dump( $term_ids );
            echo '<br>';

            if ( empty( $term_ids ) ) {
                $args['include'] = [ 0 ];
                return $args;
            }

            // Update $args
            $args['include'] = $term_ids;
            $args['orderby'] = 'include';
            $args['order'] = 'ASC';

            // Remove any offset or number limits to avoid skipping
            unset( $args['offset'], $args['number'] );

            echo 'final args: ';
            var_dump( $args );
            echo '<br>';
        }
	}
	return $args;
}
add_filter( 'elementor/loop_taxonomy/args', 'elementor_loop_taxonomy_args', 20, 3 );
```

**Note:**

Through debugging (echoing) I understood what happend and knew I get correct or incorrect responds back. Of course the echo's will be deleted in my production code.
