### ISSUE TITLE
Importing a template on the middle of a document causes the template to be appended to the end of the document

### ISSUE THREAD

**Issue by cdiaz23** [elementor/elementor#28091]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

When using the latest Elementor version 3.23.1 and pro 3.23, using add from my templates, add template to the bottom of the page, instead of selected position

### Steps to reproduce

1. Click "Add container" icon
2. Click "Add template" icon
3. Select "My templates" tab
4. Select a saved template

### Expected behavior

Template is inserted in selected position, but is added to the bottom of the page

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: nginx/1.25.3
	MySQL version: (Ubuntu) v8.0.37
	PHP Version: 8.1.26
	PHP Memory Limit: 512M
	PHP Max Input Vars: 2000
	PHP Max Post Size: 501M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.5.5
	Site URL: https://dev.lanzadigital.com
	Home URL: https://dev.lanzadigital.com
	WP Multisite: No
	Max Upload Size: 500 MB
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /%category%/%postname%/
	Language: es_ES
	Timezone: Europe/Madrid
	Debug Mode: Inactive

== Theme ==
	Name: Lanza Digital
	Version: 2.0.0
	Author: CIM Internet
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.1.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: es
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Ads
		Version: 1.52.4
		Author: Advanced Ads GmbH

	Advanced Ads Pro
		Version: 2.26.2
		Author: Advanced Ads GmbH

	Advanced Ads – AMP Ads
		Version: 1.12.1
		Author: Advanced Ads GmbH

	Advanced Ads – Sticky Ads
		Version: 1.8.5
		Author: Advanced Ads GmbH

	Advanced Custom Fields PRO
		Version: 6.3.3
		Author: WP Engine

	Ajax Load More
		Version: 7.1.2
		Author: Darren Cooney

	Ajax Load More: Pro
		Version: 1.2.25
		Author: Darren Cooney

	Ajax Load More for ACF
		Version: 1.3.2
		Author: Darren Cooney

	AMP
		Version: 2.5.4
		Author: AMP Project Contributors

	AMP Sidebar Hamburger Menu
		Version: 1.2.0
		Author: James Osborne

	Change wp-admin login
		Version: 1.1.9
		Author: wpexpertsio

	Code Snippets
		Version: 3.6.5.1
		Author: Code Snippets Pro

	Duplicate Page and Post
		Version: 2.9.4
		Author: Arjun Thakur

	Elementor
		Version: 3.23.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.23.0
		Author: Elementor.com

	Elementor Widget Manager
		Version: 1.0.1
		Author: IdeaBox

	Health Check & Troubleshooting
		Version: 1.7.0
		Author: The WordPress.org community

	Imagify
		Version: 2.2.2
		Author: Imagify – Optimize Images & Convert WebP & Avif

	JSM Show Post Metadata
		Version: 4.3.0
		Author: JS Morisset

	MailPoet
		Version: 4.55.0
		Author: MailPoet

	Max Mega Menu
		Version: 3.3.1
		Author: megamenu.com

	Monkeyman Rewrite Analyzer
		Version: 1.0
		Author: Jan Fabry

	My YouTube Channel
		Version: 3.24.7
		Author: Aleksandar Urošević

	PublishPress Capabilities
		Version: 2.13.0
		Author: PublishPress

	Purge Varnish
		Version: 2.6
		Author: Dsingh <dev.firoza@gmail.com>

	Rank Math SEO
		Version: 1.0.223
		Author: Rank Math

	Rank Math SEO PRO
		Version: 3.0.66
		Author: Rank Math

	Show IDs
		Version: 1.1.10
		Author: DraftPress

	TablePress
		Version: 2.4
		Author: Tobias Bäthge

	Unlimited Elements for Elementor (Premium)
		Version: 1.5.113
		Author: Unlimited Elements

	User Role Editor
		Version: 4.64.2
		Author: Vladimir Garagulya

	White Label CMS
		Version: 2.7.4
		Author: www.videousermanuals.com

	WordPress Popular Posts
		Version: 7.0.1
		Author: Hector Cabrera

	wplightbox
		Version: 1.0.3
		Author: We-Serve-You ApS

	WP Rollback
		Version: 2.0.7
		Author: WP Rollback


== Must-Use Plugins ==
	Health Check Troubleshooting Mode
		Version: 1.9.1
		Author: 


== Uso de los elementos ==
	
	archive : 26
		ajax-load-more : 2
		ajax-load-more-elementor-posts : 2
		author-box : 1
		container : 88
		divider : 9
		heading : 15
		html : 1
		image : 2
		loop-grid : 1
		nested-tabs : 2
		posts : 1
		shortcode : 3
		template : 6
		text-editor : 3
		ucaddon_agenda_lanza : 1
		ucaddon_load_more_filter : 4
		ucaddon_noticias_relacionadas : 6
		ucaddon_post_blocks : 1
		ucaddon_post_grid : 20
		ucaddon_ue_listing_grid : 1
		wp-widget-advads_ad_widget : 6
	container : 18
		container : 35
		divider : 18
		heading : 1
		social-icons : 1
		text-editor : 2
		ucaddon_noticias_relacionadas : 4
		ucaddon_post_grid : 10
		ucaddon_post_news_tickers : 1
		wp-widget-advads_ad_widget : 19
	footer : 2
		ajax-load-more : 1
		container : 3
		template : 2
	page : 47
		button : 2
		container : 123
		divider : 1
		heading : 28
		html : 3
		icon : 10
		image : 11
		shortcode : 4
		template : 1
		ucaddon_arrow_navigation : 2
		ucaddon_blox_btn_group : 1
		ucaddon_content_carousel_new : 4
		ucaddon_noticias_relacionadas : 20
		ucaddon_post_grid : 38
		ucaddon_remote_counter_display : 2
		ucaddon_separador_blanco : 2
		wp-widget-advads_ad_widget : 2
	section : 31
		ajax-load-more-elementor-posts : 1
		button : 5
		container : 124
		divider : 17
		heading : 11
		icon : 2
		icon-box : 7
		image : 3
		loop-grid : 1
		post-info : 1
		share-buttons : 1
		shortcode : 4
		template : 2
		theme-post-title : 1
		ucaddon_agenda_lanza : 2
		ucaddon_arrow_navigation : 1
		ucaddon_blox_btn_group : 1
		ucaddon_content_carousel_new : 2
		ucaddon_noticias_relacionadas : 9
		ucaddon_noticias_relacionadas_sin_foto : 7
		ucaddon_post_grid : 41
		ucaddon_remote_counter_display : 1
		ucaddon_ue_listing_accordion : 1
		ucaddon_ue_listing_carousel : 1
		wp-widget-advads_ad_widget : 8
	wp-page : 7
		container : 81
		divider : 24
		heading : 1
		icon-box : 2
		posts : 1
		shortcode : 5
		template : 1
		text-editor : 8
		ucaddon_mega_menu_inner_links : 2
		ucaddon_noticias_relacionadas_sin_foto : 4
		ucaddon_post_blocks : 1
		ucaddon_post_grid : 36
		wp-widget-advads_ad_widget : 3
	single-post : 3
		ajax-load-more : 2
		container : 18
		heading : 1
		share-buttons : 3
		shortcode : 8
		template : 3
		text-editor : 2
		theme-post-content : 2
		theme-post-title : 2
		ucaddon_post_grid : 1
	single-page : 10
		container : 118
		divider : 27
		form : 1
		heading : 9
		icon : 1
		icon-box : 12
		image : 2
		loop-grid : 1
		nested-tabs : 2
		shortcode : 3
		template : 2
		text-editor : 21
		theme-post-content : 1
		theme-post-excerpt : 1
		theme-post-title : 1
		ucaddon_agenda_lanza : 1
		ucaddon_archive_pagination : 1
		ucaddon_noticias_relacionadas_sin_foto : 4
		ucaddon_post_carousel : 2
		ucaddon_post_grid : 28
		ucaddon_ue_listing_grid : 2
		ucaddon_ue_select_post_filter : 3
		wp-widget-advads_ad_widget : 13
	loop-item : 7
		container : 16
		divider : 1
		post-info : 4
		shortcode : 9
		text-editor : 3
		theme-post-excerpt : 1
		theme-post-featured-image : 1
		theme-post-title : 5
	error-404 : 1
		container : 1
		text-editor : 2


== Ajustes ==
	
	cpt_support: page
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap
	meta_generator_tag: 1


== Caracteristicas ==
	Custom Fonts: 2
	Custom Icons: 0

== Integraciones ==
	


== Experimentos de Elementor ==
	Carga de CSS mejorada: Activo
	Fuentes de iconos integradas: Inactivo
	Puntos de ruptura personalizados adicionales: Inactivo
	Contenedor Flexbox: Activo
	Contenedor Grid: Activo
	Actualizar la librería Swiper: Activo
	Rendimiento de los elementos anidados: Activo por defecto
	Carga de controles optimizada: Inactivo por defecto
	Marcado optimizado: Inactivo por defecto
	Puesta en marcha del plugin: Activo por defecto
	Por defecto, el nuevo constructor de temas: Inactivo
	Cabecera y pie de página: Activo por defecto
	Pantalla de inicio de Elementor: Activo por defecto
	Barra superior del editor: Inactivo
	Construir con IA: Inactivo
	Páginas de destino: Inactivo
	Elementos anidados: Activo
	Carga diferida de imágenes de fondo: Inactivo
	Caché de elementos: Inactivo por defecto
	Enlace en la biografía: Inactivo por defecto
	Botones flotantes: Inactivo por defecto
	Eventos del editor de Elementor: Inactivo por defecto
	Condiciones de visualización: Activo
	Envíos de formulario: Activo por defecto
	Menú: Inactivo por defecto
	Filtro de taxonomía: Activo
	Buscar: Inactivo por defecto


== Registro ==
	
Log: showing 20 of 352024-06-25 07:58:10 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.0',
  'to' => '3.22.1',
)]
2024-06-26 13:57:17 [info] elementor::elementor_updater Started 
2024-06-26 13:57:17 [info] Elementor/Upgrades - _on_each_version Start  
2024-06-26 13:57:17 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.2',
  'to' => '3.22.3',
)]
2024-06-26 13:57:20 [info] Elementor/Upgrades - _on_each_version Finished 
2024-06-26 13:57:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.2',
  'to' => '3.22.3',
)]
2024-07-15 17:36:48 [info] elementor-pro::elementor_pro_updater Started 
2024-07-15 17:36:48 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-07-15 17:36:48 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-07-15 17:36:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.1',
  'to' => '3.23.0',
)]
2024-07-15 17:36:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.1',
  'to' => '3.23.0',
)]
2024-07-15 17:36:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.3',
  'to' => '3.23.0',
)]
2024-07-15 17:36:48 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-15 17:36:51 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-15 17:36:51 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.3',
  'to' => '3.23.0',
)]
2024-07-16 11:23:22 [info] elementor::elementor_updater Started 
2024-07-16 11:23:23 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-16 11:23:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.0',
  'to' => '3.23.1',
)]
2024-07-16 11:23:25 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-16 11:23:25 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.0',
  'to' => '3.23.1',
)]

JS: showing 5 of 5JS: 2024-06-25 11:23:44 [error X 56][../wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.22.2:3:14246] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `ucaddon_post_grid` got as `content_width` value. Expected array or object.',
)]
JS: 2024-06-25 11:39:46 [error X 18][../wp-content/plugins/elementor/assets/js/editor-modules.min.js?ver=3.22.2:3:14246] An invalid argument supplied as multiple control value [array (
  'category' => 'InvalidElementData',
  'tag' => 'Element `ucaddon_noticias_relacionadas_sin_foto` got as `content_width` value. Expected array or object.',
)]
JS: 2024-06-25 12:46:47 [error X 7][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.22.2:3:336944] Cannot read properties of undefined (reading 'html') 
JS: 2024-06-25 12:54:35 [error X 4][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.22.2:3:706805] this.model.isValidChild is not a function 
JS: 2024-06-25 14:44:41 [error X 1][../wp-content/plugins/unlimited-elements-for-elementor-premium/provider/core/unlimited_elements/elementor/assets/uc_editor_admin.js?ver=1.5.111:685:17] Cannot read properties of null (reading 'replace') 

PHP: showing 3 of 3PHP: 2024-06-25 14:46:47 [warning X 7][../wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-25 16:40:10 [warning X 2][../wp-content/plugins/elementor/includes/elements/container.php::1835] Undefined array key "size" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-09 17:58:34 [warning X 2][../wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-color.php::34] Undefined array key 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibilidad no especificada
	Elementor Widget Manager: Compatibilidad no especificada
	Unlimited Elements for Elementor (Premium): Compatibilidad no especificada

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by cdiaz23** [comment]
Issue is still here in 3.23.2

**Comment by cdiaz23** [comment]
Issue don't be corrected in 3.23.4 
It's very important for me

**Comment by DaanVermunt** [comment]
Same issue here

**Comment by tbenci** [comment]
Why is this NOT being screamed about. Fix it Elementor it is making your product unusable in a large site (and ours is a large site used for documentation of enterprise level software development).

**Comment by cdiaz23** [comment]
New version Elementor 3.24.0  and issue is still here :(

**Comment by jinxymon** [comment]
We also have this issue and reported it to Elementor, and they referred us to this GITHUB issue.
It's dissapointing that it is still not fixed since July 16 - It causes a lot of extra work to re-position the template insertion.
And still not fixed with Elementor version 3.24.4

**Comment by cdiaz23** [comment]
Still not fixed with Elementor version 3.24.5 :(

**Comment by mariaesschmecktmir** [comment]
We have now Elementor Version 3.25.3 - the same issue is still not solved! 
It is soooo annoying! Working with Elementor is not much fun anymore. It seems the developers just concentrate on new AI stuff and don't care much about paying customers.

**Comment by jinxymon** [comment]
When will this be fixed? - we have been waiting since July.

**Comment by cdiaz23** [comment]
Updated to 3.25.4. Still not fixed!!!

**Comment by jinxymon** [comment]
When will someone from Elementor start looking at this issue ???

**Comment by mariaesschmecktmir** [comment]
Still the same problem, lots of more work for content creators. This is the WORST SUPPORT I HAVE EVER EXERIENCED!!!!!

**Comment by tbenci** [comment]
Come on Elementor Sack Barnie who's responsible for this stuff up and fix the bloody thing...

**Comment by jinxymon** [comment]
Updated to 3.26.0 Still not fixed!!!

**Comment by jinxymon** [comment]
Still not fixed in Elementor Version 3.27.0 👎

**Comment by cdiaz23** [comment]
Issue is still here with Elementor 3.27.2 

Please, fix it!!!

**Comment by jinxymon** [comment]
Any chance of fixing this bug, which was introduced into Elementor in July of last year ?

**Comment by tbenci** [comment]
How can it be that  a year in this is still not fixed. I was working on a huge document yesterday and my keyboard went sailing across the room.

What are we paying form Elementor? Does anyone have a suggestion for what we should try in place of this rubbish?

**Comment by jinxymon** [comment]
Yes it is fixed in 3.28.0 - Its great , and takes away a big pain point for our Blog!

**Comment by tbenci** [comment]
As the Innovations Manager for a large multi-national software company I watch the behaviour we saw with this issue and shake my head. I can't image what would happen if our business patched out changes that completely broke an expected functionality and then, as the Jira issues started to flow into our support department we immediately proceeded to do NOTHING.

What's more, we never acknowledged the issue and over 12 months later, we snuck the fix into a patch WITHOUT anyone knowing about it.

Elementor needs to do better. Whilst it is good to have this fixed it is a disgrace the way the development and support team handled this issue. They should be recognise that in the modern work of SaaS communication is EVERYTHING.

**Comment by mariaesschmecktmir** [comment]
It is fixed now but it took over 8 MONTH!!!! to fix this problem which made our lives so difficult. I have regretted to start with Elementor at the first place because of that experience we all had with the very bad customer service. 

For my foodblog I have different plugins, an important and powerful one is "WP Recipe maker". When I have a question or a problem this people are incredibly helpful and answer within ours. This is customer service as its best! :-) Luckily there are also helpful people out there.

Have a nice day.
