### ISSUE TITLE
Display Conditions for dynamic tags broken on empty values

### ISSUE THREAD

**Issue by ruhatch** [elementor/elementor#28127]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Display conditions on dynamic tags offer a condition of 'Is Empty', but this doesn't actually work for empty string values. I've looked through the code and it seems that the dynamic tag data provider turns empty strings to 'false' and then the check function in dynamic tags condition always returns false, i.e. the condition can never be met. This code needs to be rewritten to carefully distinguish between 'null' values and empty values of the right type.

### Steps to reproduce

1. Create two posts, one with a featured image with alt text and one with a featured image with blank alt text
2. Create a heading element on single post template that has display condition when Dynamic Tags > Featured Image Alt Text > Is Not Empty and it should show up on one page and not the other
3. Change the condition to Is Empty and it will not show up on either page

### Expected behavior

1. The heading element should show up on the page with empty alt text, when the Is Empty condition is selected

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.6.18
	PHP Version: 7.4.33
	PHP Memory Limit: 256M
	PHP Max Input Vars: 4000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6
	Site URL: https://climateclarity.co.uk
	Home URL: https://climateclarity.co.uk
	WP Multisite: No
	Max Upload Size: 64 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%category%/%post_id%/%postname%/
	Language: en_GB
	Timezone: Europe/London
	Admin Email: admin@climateclarity.co.uk
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.1.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-GB
	User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36

== Active Plugins ==
	Code Snippets
		Version: 3.6.5.1
		Author: Code Snippets Pro

	Copy & Delete Posts
		Version: 1.4.7
		Author: Inisev

	Elementor
		Version: 3.22.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.22.1
		Author: Elementor.com

	EmbedPress
		Version: 4.0.6
		Author: WPDeveloper

	Event Tickets
		Version: 5.11.0.5
		Author: The Events Calendar

	Event Tickets/Eventbrite Extension: Show Cost Field
		Version: 1.0.1
		Author: Modern Tribe, Inc.

	Event Tickets Plus
		Version: 5.10.2
		Author: The Events Calendar

	Favicon by RealFaviconGenerator
		Version: 1.3.30
		Author: Philippe Bernard

	GA Google Analytics
		Version: 20240701
		Author: Jeff Starr

	Hotjar
		Version: 1.0.16
		Author: Hotjar

	Jetpack
		Version: 13.6
		Author: Automattic

	LiteSpeed Cache
		Version: 6.2.0.1
		Author: LiteSpeed Technologies

	Pluginception
		Version: 1.3
		Author: Otto

	Redirection
		Version: 5.4.2
		Author: John Godley

	TEC Dynamic Tags
		Version: 
		Author: 

	The Events Calendar
		Version: 6.5.1.6
		Author: The Events Calendar

	The Events Calendar: Event Automator
		Version: 1.7.0
		Author: The Events Calendar

	The Events Calendar Pro
		Version: 6.5.0
		Author: The Events Calendar

	UpdraftPlus - Backup/Restore
		Version: 1.24.4
		Author: UpdraftPlus.Com, DavidAnderson

	URL Params
		Version: 2.5
		Author: Jeremy B. Shapiro

	WPIDE - File Manager & Code Editor
		Version: 3.4.9
		Author: XplodedThemes

	Yoast SEO
		Version: 23.0
		Author: Team Yoast


== Features ==
	Custom Fonts: 2
	Custom Icons: 0

== Integrations ==
	
	recaptcha: Active


== Elementor Experiments ==
	Improved asset loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	Flexbox Container: Active
	Grid Container: Active by default
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Inactive by default
	Optimized Control Loading: Inactive by default
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Active by default
	Header and footer: Active by default
	Elementor Home Screen: Active by default
	Editor Top Bar: Active
	Build with AI: Active by default
	Landing pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Inactive by default
	Pages Panel: Inactive by default
	Element Caching: Inactive by default
	Conversion Center: Inactive by default
	Display Conditions: Active by default
	Form Submissions: Active by default
	Menu: Inactive by default
	Taxonomy Filter: Active by default


== Log ==
	
Log: showing 20 of 332024-02-14 10:47:10 [info] Elementor/Upgrades - _on_each_version Start  
2024-02-14 10:47:10 [info] Elementor/Upgrades - _on_each_version Finished 
2024-02-14 10:47:10 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Start  
2024-02-14 10:47:10 [info] Elementor/Upgrades - _v_3_17_0_site_settings_updates Finished 
2024-02-14 10:47:10 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.17.3',
  'to' => '3.18.3',
)]
2024-02-14 10:48:04 [info] elementor::elementor_updater Started 
2024-02-14 10:48:04 [info] Elementor/Upgrades - _on_each_version Start  
2024-02-14 10:48:04 [info] Elementor/Upgrades - _on_each_version Finished 
2024-02-14 10:48:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.3',
  'to' => '3.19.2',
)]
2024-02-14 10:48:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.3',
  'to' => '3.19.2',
)]
2024-02-14 10:48:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.18.3',
  'to' => '3.19.2',
)]
2024-07-01 14:57:34 [info] elementor-pro::elementor_pro_updater Started 
2024-07-01 14:57:34 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-07-01 14:57:34 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-07-01 14:57:34 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.3',
  'to' => '3.22.1',
)]
2024-07-01 14:57:34 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.18.3',
  'to' => '3.22.1',
)]
2024-07-01 15:00:28 [info] elementor::elementor_updater Started 
2024-07-01 15:00:28 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-01 15:00:28 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-01 15:00:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.19.2',
  'to' => '3.22.3',
)]

PHP: showing 4 of 4PHP: 2023-12-04 10:53:18 [notice X 4][/home/climat55/public_html/wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-04-24 15:28:25 [notice X 1][/home/climat55/public_html/wp-content/plugins/elementor/includes/managers/image.php::113] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-05-28 15:15:23 [notice X 13][/home/climat55/public_html/wp-content/plugins/elementor-pro/modules/forms/classes/ajax-handler.php::121] Undefined index: form_fields [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-07-09 16:33:12 [notice X 1][/home/climat55/public_html/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::271] Trying to get property 'ID' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 6 of 6JS: 2024-01-10 14:15:22 [error X 5][https://climateclarity.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.17.3:3:953240] Cannot read properties of undefined (reading 'settings') 
JS: 2024-02-15 09:45:15 [error X 1][https://climateclarity.co.uk/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.19.2:2:16880] Cannot read properties of undefined (reading 'attributes') 
JS: 2024-02-15 10:50:51 [error X 2][https://climateclarity.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.19.2:3:850583] Cannot convert undefined or null to object 
JS: 2024-04-02 10:44:06 [error X 1][https://climateclarity.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.19.2:3:609436] Cannot read properties of null (reading 'id') 
JS: 2024-04-11 12:36:34 [error X 19][https://climateclarity.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.19.2:3:814672] Cannot read properties of undefined (reading 'localized') 
JS: 2024-07-09 14:57:13 [error X 1][https://climateclarity.co.uk/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.22.3:3:825128] Cannot read properties of undefined (reading 'toLowerCase') 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @ruhatch! 

Thank you for submitting your issue! 🙏 

🏷️ We've labeled this issue and our team will take a look at it. If there is indeed a problem, they'll work on fixing it. We can't say exactly when it'll be sorted out, but we kindly ask for your patience. Thanks for understanding!

Best regards

**Comment by ruhatch** [comment]
Thanks @nicholaszein 

I've patched the files on my site to fix the issue, so I can share that, if it's helpful.

**Comment by ruhatch** [comment]
Also the new title is a little misleading, it doesn't work for any dynamic tags, not just image alt

**Comment by nicholaszein** [comment]
Hi, @ruhatch, thank you for the feedback!

You can share the code here if you want.

I've updated the title as well.

Regards

**Comment by ruhatch** [comment]
Sure, here's the git patch:
```
diff --git a/modules/display-conditions/classes/dynamic-tags/dynamic-tags-data-provider.php b/modules/display-conditions/classes/dynamic-tags/dynamic-tags-data-provider.php
index 7c5712e..4869894 100644
--- a/modules/display-conditions/classes/dynamic-tags/dynamic-tags-data-provider.php
+++ b/modules/display-conditions/classes/dynamic-tags/dynamic-tags-data-provider.php
@@ -89,7 +89,11 @@ class Dynamic_Tags_Data_Provider implements Data_Provider {
 			return false;
 		}
 
-		return Plugin::elementor()->dynamic_tags->get_tag_data_content( null, $dt_options['dynamic_tag_name'], $dt_options['settings'] ) ?? false;
+		$dt_value = Plugin::elementor()->dynamic_tags->get_tag_data_content( null, $dt_options['dynamic_tag_name'], $dt_options['settings'] );
+		if ($dt_value === null) {
+		    return false;
+		}
+		return $dt_value;
 	}
 
 	private function get_control_groups(): array {
diff --git a/modules/display-conditions/conditions/dynamic-tags-condition.php b/modules/display-conditions/conditions/dynamic-tags-condition.php
index 22991c9..b53254b 100644
--- a/modules/display-conditions/conditions/dynamic-tags-condition.php
+++ b/modules/display-conditions/conditions/dynamic-tags-condition.php
@@ -101,7 +101,7 @@ class Dynamic_Tags_Condition extends Condition_Base {
 	private function get_condition_value( array $args ) {
 		$dt_value = $this->dynamic_tags_data_provider->get_value( $args );
 
-		if ( $dt_value ) {
+		if ( $dt_value !== false ) {
 			return $dt_value;
 		}
```

The issue is that the check in `get_condition_value` was checking for truthyness, and otherwise dropping through to the custom value provider, rather than the dynamic tag provider. But of course the value we're returning for the check is empty, so it was never coming back truthy and so will never be returned for checking.

My solution might not be the most elegant, as I'm not sure exactly what the original intention of the code was, but this should point you in the right direction.

Please keep me updated with the fix, because I'm going to have to manually patch on any upgrades until this is done.

Thanks!

**Comment by kampiamodikuesto** [comment]
Has this problem been resolved in the latest versions?

**Comment by kampiamodikuesto** [comment]
Hi, after last update only modules/display-conditions/classes/dynamic-tags/dynamic-tags-data-provider.php was fixed. /modules/display-conditions/conditions/dynamic-tags-condition.php isn't fixed.

**Comment by gerardreches** [comment]
Same bug.

<img width="1222" alt="Image" src="https://github.com/user-attachments/assets/abf7b371-47cf-4856-b390-3e0d15400fe3" />

When the custom field doesn't exist in the database for the current post, the condition isn't met.

**Expected behaviour:** an inexistent custom field should evaluate as "is empty".
**Current behaviour:** an inexistent custom field does not evaluate as "is empty" nor as "is not empty".

**Comment by ruhatch** [comment]
> Hi, after last update only modules/display-conditions/classes/dynamic-tags/dynamic-tags-data-provider.php was fixed. /modules/display-conditions/conditions/dynamic-tags-condition.php isn't fixed.

Yes, this part of the diff is still not applied:
```
diff --git a/modules/display-conditions/conditions/dynamic-tags-condition.php b/modules/display-conditions/conditions/dynamic-tags-condition.php
index 22991c9..b53254b 100644
--- a/modules/display-conditions/conditions/dynamic-tags-condition.php
+++ b/modules/display-conditions/conditions/dynamic-tags-condition.php
@@ -101,7 +101,7 @@ class Dynamic_Tags_Condition extends Condition_Base {
 	private function get_condition_value( array $args ) {
 		$dt_value = $this->dynamic_tags_data_provider->get_value( $args );
 
-		if ( $dt_value ) {
+		if ( $dt_value !== false ) {
 			return $dt_value;
 		}
```
For my case of an empty custom field, rather than a non-existent custom field, this is enough to get it working.

@gerardreches does this change work for you?

**Comment by eartahhj** [comment]
Hello, I have the same problem with a Dynamic Tag that comes from an ACF field which should return an array of objects (it is a Relation Field). I get this error:
```
ElementorPro\Modules\DisplayConditions\Classes\Comparators_Checker::check_string_contains_and_empty(): Argument #3 ($actual_value) must be of type string, array given, 
```
in: `plugins/elementor-pro/modules/display-conditions/classes/comparators-checker.php`

Is a solution planned for this?

Version used: 3.28.4

**Comment by TOTLD** [comment]
I am experiencing this issue trying to use the 'is empty' condition with any type of ACF custom field attached to a Woo product post-type.

This is pretty much the main use-case for display conditions with dynamic tags. Any input from Elementor? This thread is very old, as is a similar thread https://github.com/elementor/elementor/issues/28203 

Yet another area where Elementor is rapidly falling behind.
