### ISSUE TITLE
🐞 Mega Menu Dropdown Content does not open on the frontend after upgrading Elementor to v3.23.X

### ISSUE THREAD

**Issue by ufastovsky** [elementor/elementor#28194]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

When the dropdown effect on the mega menu is set to hover it is not possible to select the items in the dropdown. The dropdown menu disappears when trying to select an item. This started happening in version Version 3.23.1.

### Steps to reproduce

1. Select hover on the mega menu dropdown effect
2. Try to select item in the dropdown of a mega menu

### Expected behavior

On hover one should be able to select the items in the dropdown.

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.6.18
	PHP Version: 8.2.20
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.1
	Site URL: https://sbk.nyc
	Home URL: https://sbk.nyc
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: SBK Theme
	Version: 1.0
	Author: intox creative
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.1.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 6.3.4
		Author: WP Engine

	Custom Post Type UI
		Version: 1.17.1
		Author: WebDevStudios

	Elementor
		Version: 3.23.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.22.1
		Author: Elementor.com

	Limit Login Attempts Reloaded
		Version: 2.26.12
		Author: Limit Login Attempts Reloaded

	Really Simple SSL
		Version: 8.1.5
		Author: Really Simple Plugins

	WP Fastest Cache
		Version: 1.2.9
		Author: Emre Vona


== Must-Use Plugins ==
	WordPress automation by Installatron
		Version: 
		Author: 


== Elements Usage ==
	
	container : 2
		container : 12
		divider : 1
		form : 1
		heading : 4
		image : 2
		mega-menu : 1
		nav-menu : 2
		text-editor : 2
	footer : 1
		container : 7
		heading : 4
		icon-list : 1
		image : 1
		social-icons : 1
		text-editor : 5
	header : 2
		container : 11
		heading : 2
		icon-list : 3
		image : 2
		mega-menu : 1
		nav-menu : 2
	wp-page : 3
		button : 9
		container : 83
		divider : 11
		form : 1
		heading : 35
		icon : 5
		image : 11
		image-box : 4
		reviews : 1
		social-icons : 1
		template : 1
		text-editor : 20
		video : 1
	single-post : 1
		button : 1
		container : 8
		heading : 5
		image : 1
		template : 1
		text-editor : 2


== Settings ==
	
	cpt_support: post, page
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved CSS Loading: Active by default
	Inline Font Icons: Active by default
	Additional Custom Breakpoints: Active by default
	Flexbox Container: Active by default
	Grid Container: Active by default
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Control Loading: Inactive by default
	Optimized Markup: Inactive by default
	Plugin Onboarding: Active by default
	Default to New Theme Builder: Active by default
	Header &amp; Footer: Active by default
	Elementor Home Screen: Active by default
	Editor Top Bar: Inactive by default
	Build with AI: Active by default
	Landing Pages: Active by default
	Nested Elements: Active
	Lazy Load Background Images: Active by default
	Element Caching: Inactive by default
	Link In Bio: Inactive by default
	Floating Buttons: Inactive by default
	Elementor Editor Events: Inactive by default
	Display Conditions: Active by default
	Form Submissions: Active by default
	Menu: Active
	Taxonomy Filter: Active by default


== Log ==
	
Log: showing 20 of 392024-06-28 02:49:55 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.2',
  'to' => '3.22.3',
)]
2024-07-15 11:34:05 [info] elementor::elementor_updater Started 
2024-07-15 11:34:05 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-15 11:34:06 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-15 11:34:06 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.3',
  'to' => '3.23.0',
)]
2024-07-15 11:34:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.22.3',
  'to' => '3.23.0',
)]
2024-07-15 23:49:06 [info] elementor::elementor_updater Started 
2024-07-15 23:49:07 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-15 23:49:07 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-15 23:49:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.0',
  'to' => '3.23.1',
)]
2024-07-15 23:49:07 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.0',
  'to' => '3.23.1',
)]
2024-07-23 19:26:23 [info] elementor::elementor_updater Started 
2024-07-23 19:26:23 [info] Elementor/Upgrades - _on_each_version Start  
2024-07-23 19:26:23 [info] Elementor/Upgrades - _on_each_version Finished 
2024-07-23 19:26:23 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.1',
  'to' => '3.23.2',
)]
2024-07-23 19:26:23 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.1',
  'to' => '3.23.2',
)]
2024-07-23 19:37:59 [info] elementor-pro::elementor_pro_updater Started 
2024-07-23 19:37:59 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-07-23 19:37:59 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-07-23 19:37:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.22.1',
  'to' => '3.23.1',
)]

PHP: showing 2 of 2PHP: 2024-06-28 05:08:50 [notice X 41][../wp-content/plugins/elementor/includes/base/controls-stack.php::229] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-06-28 21:56:34 [notice X 10][../wp-content/plugins/elementor-pro/modules/screenshots/module.php::33] Function utf8_decode() is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 1 of 1JS: 2024-07-23 22:41:14 [error X 4][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.23.2:3:663451] Cannot read properties of undefined (reading &#039;isDesignable&#039;) 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello, @ufastovsky!

Thank you for reaching out! I can see that you are not using the latest version of Elementor Pro, which at this moment is at **v3.23.1**.

Please, update to the latest version, run the Elementor Data Updater, purge your cache, and let me know if the problem is fixed.

Best regards

**Comment by tamerax** [comment]
@nicholaszein 
Just coming in to say I am having the same issue. 
I followed your instructions but the issue is persisting.  
Wordpress 6.6.1
Elementor pro 3.23.1
Ran data updater 
Cleared NGIX and Cloudflare cache (no other caching is installeD)

**Comment by tamerax** [comment]
Thanks for the quick reply @nicholaszein !

Unfortunately, still not working.   New test item showed up after clearing everything and then had to clear everything out again to make it go away so I know the cache isn't the issue (at least not one I can control).
Here is my site for reference
https://regdevnet.ca/

Another thing that has also changed at the same time this start happening was the menu on our French side  which had all the menu items with longer titles that had breaks in them (like "centre de document" had "centre" ontop of "de document") have all gone back to being on one line and thus overlapping and being illegible.
https://regdevnet.ca/fr/

Please let me know if there anything else I can do for testing / additional troubleshooting information.

**Comment by nicholaszein** [comment]
Hi @tamerax!

Thank you for letting me know. We will need to investigate this further.

Do you mind sending us copies of your templates containing the Menu widget? Just export the JSON files and drag them to the text box here when commenting. This would allow us to check them closer and see if we can find a common denominator.

This is very unusual and definitely not the expected behavior. Your site's should all have updated the DOM structure to accommodate the new layout.

Thanks 🙏

**Comment by hein-obox** [comment]
@tamerax @nicholaszein 

I think the issue on the French version has to do with the custom styling that was added: 

<img width="553" alt="Screenshot 2024-07-26 at 15 02 28" src="https://github.com/user-attachments/assets/621ec1f9-5e14-44be-9d81-983c8712bb3f">

It might work to update this: 

`.elementor-7155 .elementor-element.elementor-element-e383a8d li`

To: 

`.elementor-7155 .elementor-element.elementor-element-e383a8d li > div`.

This is related to a style update needed for the change of the order of DOM elements.

**Comment by tamerax** [comment]
Thanks @nicholaszein !
Please see attached file.  I hope that is what you were looking for.  I inherited this site and I am still very new to elementor.

[elementor-16-2024-07-26.json](https://github.com/user-attachments/files/16393590/elementor-16-2024-07-26.json)

**Comment by tamerax** [comment]
> @tamerax @nicholaszein
> 
> I think the issue on the French version has to do with the custom styling that was added:
> <img alt="Screenshot 2024-07-26 at 15 02 28" width="553" src="https://private-user-images.githubusercontent.com/94352322/352538583-621ec1f9-5e14-44be-9d81-983c8712bb3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMDczNzEsIm5iZiI6MTcyMjAwNzA3MSwicGF0aCI6Ii85NDM1MjMyMi8zNTI1Mzg1ODMtNjIxZWMxZjktNWUxNC00NGJlLTlkODEtOTgzYzg3MTJiYjNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDE1MTc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyYTQ5NDBhM2Q2NGFlNDlkZDVmNTIwNDFhZmJmM2M2MTczY2NlZmRhN2RhMGVjNWNkYzdjZWI3YjA1MmJmMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SrvP3nvuA8QEB_RK2V2H4_674Y6-oLJ4Eqw2os8N5ps">
> 
> It might work to update this:
> 
> `.elementor-7155 .elementor-element.elementor-element-e383a8d li`
> 
> To:
> 
> `.elementor-7155 .elementor-element.elementor-element-e383a8d li > div`.
> 
> This is related to a style update needed for the change of the order of DOM elements.

This worked! Thank you!

**Comment by nicholaszein** [comment]
Thank you @tamerax! That's exactly what I wanted! 🙏 

Apologies for the trouble with the update. Let's see if we can fix this issue without you having to rebuild the Menu widget, which for now is the only way to fix it!

We'll investigate it further and I'll update you as soon as I have something new to share! 💪

**Comment by janhenrydesign** [comment]
We have the same issue on at least one of our client sites (I'm working through them at the moment). I don't have time to rebuild 
 mega menus at the moment, so I'm rolling back Elementor where needed.

**Comment by callendo** [comment]
Just to confirm. 
We have same issue. 


https://github.com/user-attachments/assets/05b5b949-7c27-48a8-b61e-932e548414ca

Elementor  Version 3.23.3

**Comment by hein-obox** [comment]
@callendo @janhenrydesign We are releasing an update today. Could you check the update in like 4 hours from now?

**Comment by callendo** [comment]
@hein-obox i found a workaround for this. 
It just just to set the cointiner of the dropdown menu to -10px in margin-top and it works like a charm.

**Comment by nicholaszein** [comment]
Hi @callendo!

Thank you for joining the conversation! 🙏 

It seems that the problem you are reporting is unrelated to this issue. In your case it's about the distance between the Menu Items and the content. Usually, it depends on the user's settings on both the Menu Styles tab > Menu Items section > **Distance from content** setting. If possible, we ask you to check that option and see if it's not set too high, adding too much of a distance between the content and the Menu Items. And if after you find out it still happens even when reducing that setting, we kindly ask you to open a new issue so we can take a better look at your case.

The issue reported here is different. In the last update we changed the structure of the Menu, and moved the content position. After updating and running the Data Updater, the position of the content should have been moved for all users, but it seems in some cases it hasn't, and people couldn't open the dropdown content at all.

I hope this clarifies this issue!

**Comment by nicholaszein** [comment]
Hey @ufastovsky , @tamerax , and @janhenrydesign !

As @hein-obox pointed out, we just released a new version of Elementor Pro (**v3.23.2**) with a fix for this issue! 🙌 

Can you please update and let us know if the issue is fixed for you?

Please, backup your sites before proceeding!

Kind regards

**Comment by tamerax** [comment]
Hi @nicholaszein  !

I can confirm it fixed the issues on one side of the website but the FR side is now broken in a different way where the menu is pushed off the right as well as the dropdown menu issue is still present.
https://regdevnet.ca/fr/

Could this be from the FR menu fix present earlier in the thread conflicting with the changes?

**Comment by nicholaszein** [comment]
Hi @tamerax,

Thank you for confirming it was fixed! 🙏 

As for the FR version, after I disabled the custom styling the dropdown content appeared correctly for me!

![image](https://github.com/user-attachments/assets/c15ca0cf-e28f-4d11-9076-08dead5c7d79)
![image](https://github.com/user-attachments/assets/6960d7be-a932-4c9a-a002-97fff79d7a57)

Although I think there are some things you might need to fix. Content is overflowing.

**Comment by tamerax** [comment]
@nicholaszein 
I removed the max-width line and now it formats properly BUT for some reason the "Programmes" dropdown is still doing original issue while the other dropdown is fine.  So close...

**Comment by ufastovsky** [comment]
The plugin update did not fix the issue for me because I have custom CSS on
one of the menu items which sets the height and width to make it look like
a button. I guess the new mega menu structure does not allow that. As a
workaround, I removed that item from the mega menu and added a button
widget.

**Comment by hein-obox** [comment]
@ufastovsky What is your Url?

**Comment by hein-obox** [comment]
@nicholaszein @tamerax I think the programmes dropdown is giving me problems as well. I will try to study it tomorrow in more detail.

**Comment by tamerax** [comment]
@nicholaszein @hein-obox 

I just cleared the various caches (cloudflare, NGINX) and browser and it is still not working on that one item in the French side.  Also just tried in 2 other browsers and on an entirely different computer.

**Comment by ufastovsky** [comment]
Hein,

Here is the URL to my test site with the broken mega menu. The formatting
on the Contact Us link is causing it to break in v 3.23.x
https://intoxcreative.com/client/sbk/demo/

Here is the URL to the live site with my workaround applied:
https://sbk.nyc/

Ursula

**Comment by hein-obox** [comment]
@ufastovsky @nicholaszein @tamerax I have opened a task for a final fix.

**Comment by janhenrydesign** [comment]
Hi team, I can confirm we still have issues if we update Elementor.  One one site, custom CSS styling is broken on one menu item (styled to look like a button), which is changing the alignment of the mega menu, and the drop down menu still can't be selected (probably related to the first part). It's not a simple matter of just removing that menu item and replacing it with a button, because there are two of these menu items and there is custom PHP that determines which menu item is displayed, depending on login status.
If I then roll back the update by restoring a backup, then global typography styles of the menu don't display. I then have to add a menu item, save, and then go back and remove the item, and re-save.
It's something I'll need to look at when I have more time. We have a number of sites with mega menus, and right now I don't have time to go through each one one-by-one to manually fix those that are having issues.

**Comment by hein-obox** [comment]
@janhenrydesign Can you please share the Urls, so that we can study the problems?

**Comment by nicholaszein** [comment]
Hey @ufastovsky , @tamerax , and @janhenrydesign!

We just released **Elementor Pro v3.23.3** with a new fix for this issue! 🙌 

Would you be so kind to let us know if this update fixes the problem on your end?

Don't forget to backup your site before updating, and make sure to clear and purge all levels of cache applied to your websites, including browser cache after updating, and running the **Elementor Data Updater**.

Best Regards

**Comment by ufastovsky** [comment]
This update fixed the issue for me.

**Comment by tamerax** [comment]
Working great here! Thanks!!

**Comment by janhenrydesign** [comment]
@nicholaszein Issue is fixed for me also :)

**Comment by ginosamotics** [comment]
The update didn't fix the issue for me, so I changed to 'Click' interaction instead of 'Hover'.

**Comment by hein-obox** [comment]
@ginosamotics Can you please share your Url?

**Comment by ginosamotics** [comment]
> @ginosamotics Can you please share your Url?

Find the URL with the issue here: https://z0jp8sonl0-staging.onrocket.site/

**Comment by hein-obox** [comment]
@ginosamotics 
We would really like to understand what is going wrong on your website. It would be great if you could register a support ticket, and provide the support with the login to your staging site. Then we can study the problem in more detail.

@nicholaszein Can you please guide us here?

**Comment by nicholaszein** [comment]
Hi @ginosamotics!

As @hein-obox mentioned, it would really help us if you could [submit a Support Ticket](https://elementor.com/help/how-to-submit-a-support-ticket/). 
When talking to a representative, just reference this issue, and say that the Editor developers need a secure access to your website. You'll be asked to install the [Temporary Login plugin](https://wordpress.org/plugins/temporary-login/) (which we recommend you install beforehand), which will allow you to create a safe login credential for us to access your site. You can share the credential in the ticket.

Then, all you need to do is to come back and share the ticket number here so we can find that information and login to your site.

We will create backup copy of your site, and test it on a secure and private environment. Once we finish, we will delete the copy. 

If you can, please follow the instructions above and let us know the number of the ticket. 🙏

**Comment by ginosamotics** [comment]
> Hi @ginosamotics!
> 
> As @hein-obox mentioned, it would really help us if you could [submit a Support Ticket](https://elementor.com/help/how-to-submit-a-support-ticket/). When talking to a representative, just reference this issue, and say that the Editor developers need a secure access to your website. You'll be asked to install the [Temporary Login plugin](https://wordpress.org/plugins/temporary-login/) (which we recommend you install beforehand), which will allow you to create a safe login credential for us to access your site. You can share the credential in the ticket.
> 
> Then, all you need to do is to come back and share the ticket number here so we can find that information and login to your site.
> 
> We will create a backup copy of your site, and test it on a secure and private environment. Once we finish, we will delete the copy.
> 
> If you can, please follow the instructions above and let us know the number of the ticket. 🙏

Hi, there already was an open ticket. Here's the ID: #TSN9ISLUEUDD

**Comment by nicholaszein** [comment]
Thank you @ginosamotics! ❤️ 

Please, allow us some time to investigate your site. 🙏

**Comment by nicholaszein** [comment]
Hi @ginosamotics!

I just tested your staging site, and the Menu is working fine on Hover there.

I think maybe your problem is caused by your multiple levels of cache. Can you please purge all levels of cache on your production site (including Server/Object Cache), and switch the Menu's Dropdown effect to on Hover again? Let's see if this solves the issue for you. 🤞

**Comment by hein-obox** [comment]
@nicholaszein I will wait for your feedback about this, before I have a look at it.

**Comment by hein-obox** [comment]
@nicholaszein Do you have an update with your findings?

**Comment by nicholaszein** [comment]
@hein-obox yes.

The problem reported by @ginosamotics is not the same problem reported in this issue. It's something else.

I will explain it better soon. 

As far as I can tell, this issue can be closed, and I will as soon as I have a detailed answer to give to Gino, who has been super cooperative.

**Comment by mhktanbir** [comment]
Hello, we are still facing the issue on version Version 3.23.3

**Comment by hein-obox** [comment]
@mhktanbir Can you please share your Url?

**Comment by mhktanbir** [comment]
> @mhktanbir Can you please share your Url?

@hein-obox https://www.mimsms.com/  please check

**Comment by hein-obox** [comment]
@mhktanbir If I understand it correctly, you have reversed to the 3.22 version.

Is there a staging environment that we could test?

Alternatively, could you please open a support ticket, so that we can get your login details, and create our own staging environment, to understand the problem better.

See above: https://github.com/elementor/elementor/issues/28194#issuecomment-2273607363.

**Comment by hein-obox** [comment]
@mhktanbir From what I can see in the screenshot, the dropdown icon weren't generated in your version. That seems to be a different problem from the problems mentioned above.

From your live website, I can see that you use caching or CSS and JS optimization. Could you please test it with all CSS and JS optimizations switched off or by flushing the files first?

**Comment by Silvix974** [comment]
Same problem here: **leftside** mega menu **working properly**. Right side **not working properly**: as you try to hover dropdown section it disappears.
**Elementor** Version 3.24.7
**Elementor Pro** Version 3.24.4

https://github.com/user-attachments/assets/086a1d81-c68e-4e3c-8a04-cf5335f5ac45

**Comment by hendratmo** [comment]
Hi, same problem here, my dropdown wont appear. I was hovering to my dropdown, there's menu inside menu, and the inside menu wont appear.
![dropdown not work](https://github.com/user-attachments/assets/ca6b66eb-8b8b-4082-b556-4da115c0f861)

**Comment by Silvix974** [comment]
> Hi @nicholaszein same problem here: **left side** mega menu **not working properly** : as you try to hover dropdown section it disappears. Right side **working properly** **Elementor** Version 3.24.7 **Elementor Pro** Version 3.24.4
> 
>  menu.mp4

@hein-obox confirmed! v3.25.x fix the problem!

**Comment by nicholaszein** [comment]
Hy everyone!

We have great news! 🙌 

### 📢 We're happy to announce that the issue you raised was resolved in Elementor Pro v3.25.0! 🥳 

✅ Feel free to check it out and update your plugin to the new version!

> _Check the changelog for more information:_
> [Changelog of Elementor and Elementor Pro](https://elementor.com/help/changelog-of-elementor/)

Cheers 🥂
