### ISSUE TITLE
RE: Elementor global widget bug🐞 Bug report

### ISSUE THREAD

**Issue by drdiercks** [elementor/elementor#28892]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Here are the steps I took to cretae and resolve the issue:

1. Create global widget (button) on homepage.
2. After some time, the homepage became uneditable. Error in console:
Error: id invalid type: string.

The editor stays in the loading screen forever, regardless of deactivating plugins, clearing cache, different browsers, elementor-safe-mode, different editor loading turned on/off, etc.

How to resolve:
- delete global widgets that are present on the page from elementor templates

Page loads once again.

I am posting this because this issue was raised two years ago. Since removing the global widgets from the elementor templates resolved the issue IMMEDIATLY, I am confident that this was causing the problem.

For reference of the earlier bug report: Bug report: #17954

### Steps to reproduce

1. Create global widget (button) on homepage.
2. After some time, the homepage became uneditable. Error in console:
Error: id invalid type: string.

### Expected behavior

Elementor editor should load

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [ ] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: LiteSpeed
	MySQL version: MariaDB Server v10.6.19
	PHP Version: 7.4.33
	PHP Memory Limit: 768M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.2
	Site URL: 
	Home URL: 
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 40M
	Max Memory limit: 768M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: nl_NL
	Timezone: Europe/Amsterdam
	Admin Email: 
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 4.8.2
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: 
	WP Profile lang: nl-NL
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36


== Eigenschappen ==
	Custom Fonts: 1
	Custom Icons: 1

== Integraties ==
	

== Elementor experimenten ==
	Verbeterd laden van CSS: Standaard inactief
	Inline lettertype iconen: Actief
	Extra aangepaste breakpoints: Standaard actief
	Flexbox container: Actief
	Raster container: Standaard actief
	Upgrade Swiper bibliotheek: Standaard actief
	Geneste elementen prestaties: Standaard actief
	Geoptimaliseerde laden van besturing: Inactief
	Geoptimaliseerde markup: Standaard inactief
	Swiper CSS bestanden conditioneel laden: Standaard inactief
	Plugin onboarding: Standaard actief
	Standaard naar nieuwe Thema bouwer: Standaard actief
	Elementor home scherm: Standaard actief
	Bouwen met AI: Inactief
	Landingspagina&#039;s: Standaard actief
	Launchpad checklist: Standaard inactief
	Geneste elementen: Actief
	Editor top balk: Actief
	Pagina&#039;s paneel: Standaard inactief
	Element caching: Standaard inactief
	Link in bio: Standaard actief
	Zwevende knoppen: Standaard actief
	Elementor editor gebeurtenissen: Standaard inactief
	Atomic widgets: Standaard inactief
	Weergave voorwaarden: Standaard actief
	Formulierinzendingen: Standaard actief
	Menu: Standaard inactief
	Taxonomiefilter: Standaard actief
	Zoeken: Standaard inactief
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by timossian** [comment]
I just stumbled upon exactly the same issue.

**Comment by jlgonzalezdiaz** [comment]
### Prerequisites
Global widget form inserted a section of a page.
The global widget does not appears on published page.
If you try to edit this widget then only "advanced" tab works. There are some missed CSS in widget at published page. Any changes, does not appears to be applied.
Deleted all cache, rebuilt all library and styles at elementor tools.

### how to resolve
Unlink global widget and then save. After this little change I could reopen the block and make changes.
This behaviour it has been tested before last update.

### Isolating the problem

This bug happens when only the Elementor (and Elementor Pro) plugins are active.
This bug happens with the Hello Elementor theme active.
I can reproduce this bug consistently by following the steps I described above.


Elementor System Info


== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Debian 11 v10.5.26
	PHP Version: 8.1.30
	PHP Memory Limit: 512M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.2
	Site URL: https://tudermaonline.com
	Home URL: https://tudermaonline.com
	WP Multisite: No
	Max Upload Size: 100 MB
	Memory limit: 512M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: es_ES
	Timezone: Europe/Madrid
	Admin Email: info@tudermaonline.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.1.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: es
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:131.0) Gecko/20100101 Firefox/131.0

== Active Plugins ==
	Admin Columns Pro
		Version: 6.4.12
		Author: AdminColumns.com

	Advanced Cron Manager
		Version: 2.5.10
		Author: BracketSpace

	All in One SEO
		Version: 4.7.3.1
		Author: All in One SEO Team

	Amelia
		Version: 7.8.2
		Author: TMS

	Back In Stock Notifier for WooCommerce | WooCommerce Waitlist Pro
		Version: 5.6.1
		Author: codewoogeek

	Birthday Coupons for WooCommerce
		Version: 2.5.0
		Author: Flintop

	Change Price Title for WooCommerce
		Version: 2.6
		Author: Kartik Parmar

	Complianz | GDPR/CCPA Cookie Consent
		Version: 7.1.4
		Author: Really Simple Plugins

	Contact Form 7
		Version: 5.9.8
		Author: Takayuki Miyoshi

	Contact Form 7 Multilingual
		Version: 1.3.1
		Author: OnTheGoSystems

	Disable Bloat for WordPress &amp; WooCommerce
		Version: 3.4.9
		Author: Disable Bloat

	Disable Coupons At Product Level
		Version: 1.2.1
		Author: Phil Clerkin

	EAN, UPC, ISBN Generator: Product Barcode Inventory for WooCommerce
		Version: 5.3.0
		Author: WPFactory

	Elementor
		Version: 3.25.1
		Author: Elementor.com

	Elementor Pro
		Version: 3.25.0
		Author: Elementor.com

	Favicon by RealFaviconGenerator
		Version: 1.3.36
		Author: Philippe Bernard

	Free Gifts for WooCommerce
		Version: 11.6.0
		Author: Flintop

	Google for WooCommerce
		Version: 2.8.6
		Author: WooCommerce

	GTM4WP - A Google Tag Manager (GTM) plugin for WordPress
		Version: 1.20.2
		Author: Thomas Geiger

	Guest Order Tracking for WooCommerce
		Version: 2.1.6
		Author: WPFactory

	If Menu - Visibility control for menus
		Version: 0.19.0
		Author: Layered

	Mailchimp for WooCommerce
		Version: 4.4.1
		Author: Mailchimp

	Out Of Stock Message Manage for WooCommere
		Version: 2.7
		Author: coderstime

	PDF Invoices &amp; Packing Slips for WooCommerce
		Version: 3.9.0
		Author: WP Overnight

	Product Recommendation Quiz for WooCommerce
		Version: 2.2.9
		Author: RevenueHunt

	PW WooCommerce Gift Cards
		Version: 2.3
		Author: Pimwick, LLC

	Qi Addons for Elementor
		Version: 1.8.1
		Author: Qode Interactive

	Redirection
		Version: 5.5.0
		Author: John Godley

	Tipsa Carrier
		Version: 2.3.7D
		Author: Tipsa Integraciones

	UpdraftPlus - Backup/Restore
		Version: 2.24.6.1
		Author: TeamUpdraft, DavidAnderson

	W3 Total Cache
		Version: 2.7.7
		Author: BoldGrid

	WC - APG Free Shipping
		Version: 2.8.3
		Author: Art Project Group

	WC - APG NIF/CIF/NIE Field
		Version: 3.0.7
		Author: Art Project Group

	WebP Express
		Version: 0.25.9
		Author: Bjørn Rosell

	Widgets for Google Reviews
		Version: 12.3
		Author: Trustindex.io <support@trustindex.io>

	WooCommerce
		Version: 9.3.3
		Author: Automattic

	WooCommerce.com Update Manager
		Version: 1.0.3
		Author: Automattic

	WooCommerce Cart Abandonment Recovery
		Version: 1.3.0
		Author: CartFlows Inc

	WooCommerce Multilingual &amp; Multicurrency
		Version: 5.3.8
		Author: OnTheGoSystems

	WooCommerce Redsys Gateway Light
		Version: 6.2.1
		Author: José Conti

	WP Armour - Honeypot Anti Spam
		Version: 2.2.03
		Author: Dnesscarkey

	WPCode Lite
		Version: 2.2.2
		Author: WPCode

	WPC Product Bundles for WooCommerce
		Version: 8.1.2
		Author: WPClever

	WP Mail Logging
		Version: 1.13.1
		Author: WP Mail Logging Team

	WP Mail SMTP
		Version: 4.1.1
		Author: WP Mail SMTP

	WP Menu Icons
		Version: 3.2.7
		Author: QuadLayers

	WPML CMS Nav
		Version: 1.5.5
		Author: OnTheGoSystems

	WPML Media Translation
		Version: 2.7.4
		Author: OnTheGoSystems

	WPML Multilingual CMS
		Version: 4.6.13
		Author: OnTheGoSystems

	WPML SEO
		Version: 2.1.0.1
		Author: OnTheGoSystems

	WPML Sticky Links
		Version: 1.5.4
		Author: OnTheGoSystems

	WPML String Translation
		Version: 3.2.14
		Author: OnTheGoSystems

	YayMail Pro - WooCommerce Email Customizer
		Version: 3.5.6
		Author: YayCommerce

	YITH WooCommerce Ajax Search
		Version: 2.8.1
		Author: YITH

	Yoast Duplicate Post
		Version: 4.5
		Author: Enrico Battocchi & Team Yoast


== Must-Use Plugins ==
	burst_rest_api_optimizer.php
		Version: 
		Author: 


== Uso de los elementos ==
	
	archive : 2
		archive-posts : 1
		heading : 1
		theme-archive-title : 1
	container : 2
		container : 1
		image-carousel : 1
	footer : 2
		heading : 4
		icon-list : 2
		image : 7
		nav-menu : 1
		text-editor : 2
	header : 2
		container : 9
		heading : 2
		image : 1
		nav-menu : 3
		social-icons : 2
		text-editor : 1
		theme-site-logo : 2
		woocommerce-menu-cart : 1
		wpml-language-switcher : 1
	page : 26
		accordion : 2
		button : 69
		container : 10
		divider : 7
		heading : 215
		html : 9
		icon-list : 1
		image : 100
		image-box : 27
		image-carousel : 1
		qi_addons_for_elementor_blog_list : 2
		qi_addons_for_elementor_product_list : 1
		qi_addons_for_elementor_product_slider : 1
		shortcode : 1
		spacer : 2
		testimonial-carousel : 2
		text-editor : 148
		woocommerce-cart : 1
		woocommerce-products : 1
	popup : 2
		button : 1
		container : 3
		heading : 5
		icon : 1
	product : 4
		container : 16
		heading : 2
		shortcode : 2
		spacer : 6
		text-editor : 1
		woocommerce-notices : 2
		woocommerce-product-add-to-cart : 2
		woocommerce-product-data-tabs : 2
		woocommerce-product-images : 2
		woocommerce-product-price : 2
		woocommerce-product-related : 2
		woocommerce-product-short-description : 2
		woocommerce-product-title : 2
	section : 14
		accordion : 1
		button : 10
		container : 1
		heading : 6
		image : 11
		image-box : 10
		stepbooking : 1
		text-editor : 11
	widget : 0
		form : 1
		image-carousel : 1
	wp-post : 8
		ameliacustomerpanel : 1
		ameliaemployeepanel : 1
		heading : 4
		image : 2
		text-editor : 7
		video : 3
	wp-page : 59
		accordion : 1
		button : 42
		container : 28
		divider : 3
		form : 1
		gallery : 2
		heading : 159
		html : 7
		icon : 1
		icon-list : 1
		image : 69
		image-box : 10
		image-carousel : 3
		media-carousel : 1
		qi_addons_for_elementor_blog_list : 3
		qi_addons_for_elementor_blog_slider : 4
		qi_addons_for_elementor_contact_form_7 : 1
		qi_addons_for_elementor_product_slider : 5
		search-form : 1
		shortcode : 1
		spacer : 12
		stepbooking : 9
		text-editor : 89
		woocommerce-cart : 1
		woocommerce-checkout-page : 1
		woocommerce-my-account : 1
		woocommerce-notices : 2
		woocommerce-products : 3
	single-post : 4
		heading : 2
		theme-post-content : 2
		theme-post-featured-image : 1
		theme-post-title : 2
	search-results : 2
		archive-posts : 1
		container : 1
		heading : 2
		search-form : 1
		theme-archive-title : 1
	product-archive : 4
		button : 5
		container : 10
		heading : 20
		html : 2
		image : 21
		qi_addons_for_elementor_blog_list : 2
		qi_addons_for_elementor_product_slider : 1
		shortcode : 2
		spacer : 4
		text-editor : 16
		theme-archive-title : 1
		wc-archive-products : 1
		woocommerce-products : 1
	loop-item : 2
		container : 1
		image : 1
		woocommerce-product-add-to-cart : 1
		woocommerce-product-price : 1
		woocommerce-product-title : 1
	error-404 : 2
		button : 1
		container : 1
		heading : 1
		text-editor : 1


== Ajustes ==
	
	cpt_support: page
	disable_color_schemes: yes
	allow_tracking: yes
	unfiltered_files_upload: 1
	font_display: swap
	load_fa4_shim: yes
	disabled_elements: counter, progress, audio, wp-widget-woocommerce_product_tag_cloud, hotspot, price-list, price-table, countdown, post-comments, facebook-comments, wp-widget-tag_cloud


== Caracteristicas ==
	Custom Fonts: 0
	Custom Icons: 0

== Integraciones ==
	
	google_maps: Activo
	recaptcha_v3: Activo
	woocommerce: Activo


== Experimentos de Elementor ==
	Carga de CSS mejorada: Inactivo por defecto
	Fuentes de iconos integradas: Activo
	Puntos de ruptura personalizados adicionales: Activo por defecto
	Contenedor: Activo
	Actualizar la librería Swiper: Activo por defecto
	Rendimiento de los elementos anidados: Activo por defecto
	Carga de controles optimizada: Activo
	Marcado optimizado: Inactivo por defecto
	Carga condicional de archivos CSS Swiper: Inactivo por defecto
	Puesta en marcha del plugin: Activo por defecto
	Scroll suave por CSS: Activo por defecto
	Por defecto, el nuevo constructor de temas: Activo por defecto
	Cabecera y pie de página: Activo por defecto
	Pantalla de inicio de Elementor: Activo por defecto
	Páginas de destino: Inactivo
	Elementos anidados: Activo
	Barra superior del editor: Activo por defecto
	Panel de páginas: Inactivo por defecto
	Caché de elementos: Inactivo por defecto
	Enlace en la biografía: Activo por defecto
	Botones flotantes: Activo por defecto
	Eventos del editor de Elementor: Inactivo por defecto
	Widgets atómicos: Inactivo por defecto
	Lista de control del Launchpad: Inactivo por defecto
	Menú: Inactivo por defecto


== Registro ==
	
Log: showing 20 of 332024-10-15 19:35:08 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.6',
  'to' => '3.24.7',
)]
2024-10-28 15:38:13 [info] elementor::elementor_updater Started 
2024-10-28 15:38:13 [info] Elementor/Upgrades - _on_each_version Start  
2024-10-28 15:38:14 [info] Elementor/Upgrades - _on_each_version Finished 
2024-10-28 15:38:14 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.7',
  'to' => '3.24.8',
)]
2024-10-28 18:30:24 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.8',
  'to' => '3.25.0',
)]
2024-10-28 18:35:03 [info] elementor::elementor_updater Started 
2024-10-28 18:35:03 [info] Elementor/Upgrades - _on_each_version Start  
2024-10-28 18:35:05 [info] Elementor/Upgrades - _on_each_version Finished 
2024-10-28 18:35:05 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.8',
  'to' => '3.25.0',
)]
2024-10-28 18:35:06 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.8',
  'to' => '3.25.0',
)]
2024-10-29 06:30:25 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.0',
)]
2024-10-29 06:30:26 [info] elementor-pro::elementor_pro_updater Started 
2024-10-29 06:30:26 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-10-29 06:30:26 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-10-29 06:30:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.0',
)]
2024-10-29 06:35:04 [info] elementor::elementor_updater Started 
2024-10-29 06:35:04 [info] Elementor/Upgrades - _on_each_version Start  
2024-10-29 06:35:07 [info] Elementor/Upgrades - _on_each_version Finished 
2024-10-29 06:35:07 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.0',
  'to' => '3.25.1',
)]

PHP: showing 7 of 7PHP: 2024-10-14 16:26:23 [warning X 7][/home/tudermaonline/www/wp-content/plugins/elementor-pro/modules/query-control/module.php::768] Attempt to read property &quot;name&quot; on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-10-23 17:16:38 [warning X 10][/home/tudermaonline/www/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key &quot;condition_type&quot; [array (
  'trace' => '
#0: /home/tudermaonline/www/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/tudermaonline/www/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/tudermaonline/www/wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/tudermaonline/www/wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-10-27 21:26:51 [warning X 41][/home/tudermaonline/www/wp-content/plugins/elementor/includes/base/controls-stack.php::695] Undefined array key -1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-10-28 01:17:40 [warning X 9][/home/tudermaonline/www/wp-content/plugins/elementor/includes/base/widget-base.php::223] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: /home/tudermaonline/www/wp-content/plugins/elementor/includes/base/widget-base.php(223): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/tudermaonline/www/wp-content/plugins/elementor/includes/base/controls-stack.php(1828): Elementor\Widget_Base -> get_pointer_index()
#2: /home/tudermaonline/www/wp-content/plugins/elementor/includes/controls/groups/base.php(130): Elementor\Controls_Stack -> end_popover()
#3: /home/tudermaonline/www/wp-content/plugins/elementor/includes/base/controls-stack.php(780): Elementor\Group_Control_Base -> add_controls()
#4: /home/tudermaonline/www/wp-content/plugins/elementor-pro/modules/carousel/widgets/media-carousel.php(493): Elementor\Controls_Stack -> add_group_control()
',
)]
PHP: 2024-10-28 01:17:40 [warning X 9][/home/tudermaonline/www/wp-content/plugins/elementor/includes/base/controls-stack.php::695] Undefined array key -1 [array (
  'trace' => '
#0: /home/tudermaonline/www/wp-content/plugins/elementor/includes/base/controls-stack.php(695): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/tudermaonline/www/wp-content/plugins/elementor/includes/base/controls-stack.php(1828): Elementor\Controls_Stack -> get_control_key()
#2: /home/tudermaonline/www/wp-content/plugins/elementor/includes/controls/groups/base.php(130): Elementor\Controls_Stack -> end_popover()
#3: /home/tudermaonline/www/wp-content/plugins/elementor/includes/base/controls-stack.php(780): Elementor\Group_Control_Base -> add_controls()
#4: /home/tudermaonline/www/wp-content/plugins/elementor-pro/modules/carousel/widgets/media-carousel.php(493): Elementor\Controls_Stack -> add_group_control()
',
)]
PHP: 2024-10-29 07:45:53 [warning X 1][/home/tudermaonline/www/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::1518] Undefined array key &quot;pages&quot; [array (
  'trace' => '
#0: /home/tudermaonline/www/wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1518): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/tudermaonline/www/wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1507): ElementorPro\Modules\Woocommerce\Module -> add_system_status_data()
#2: /home/tudermaonline/www/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\Woocommerce\Module -> ElementorPro\Modules\Woocommerce\{closure}()
#3: /home/tudermaonline/www/wp-includes/plugin.php(205): WP_Hook -> apply_filters()
#4: /home/tudermaonline/www/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php(1510): class type apply_filters()
',
)]
PHP: 2024-10-29 07:45:53 [warning X 1][/home/tudermaonline/www/wp-content/plugins/elementor-pro/modules/woocommerce/module.php::1518] foreach() argument must be of type array|object, null given [array (
  'trace' => '
#0: /home/tudermaonline/www/wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1518): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /home/tudermaonline/www/wp-content/plugins/elementor-pro/modules/woocommerce/module.php(1507): ElementorPro\Modules\Woocommerce\Module -> add_system_status_data()
#2: /home/tudermaonline/www/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\Woocommerce\Module -> ElementorPro\Modules\Woocommerce\{closure}()
#3: /home/tudermaonline/www/wp-includes/plugin.php(205): WP_Hook -> apply_filters()
#4: /home/tudermaonline/www/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-system-status-v2-controller.php(1510): class type apply_filters()
',
)]

JS: showing 2 of 2JS: 2024-10-29 09:01:52 [error X 1][https://tudermaonline.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.25.1:3:665948] this.view.container is undefined 
JS: 2024-10-29 09:09:43 [error X 3][https://tudermaonline.com/wp-content/plugins/elementor/assets/js/common-modules.min.js?ver=3.25.1:2:56026] q.functionName is undefined 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	Qi Addons for Elementor: Incompatible

== Elementor Pro - Compatibility Tag ==
	
	Qi Addons for Elementor: Incompatible

**Comment by Wendy-HL-24** [comment]
I also have this problem with my Elementor forms, Form widgets can't be used, and pages with Form widgets can't be opened for editing, it's amazing and I don't know how to fix it.

**Comment by umarbutler** [comment]
I reported this issue to Elementor via ticket #TSZ5JQCB0DU0 and interestingly discovered this solution at the same time their technical support was on my website making it seem like it suddenly started working 😆

To help out anyone else who doesn't know how to remove a global widget, you need to head to "Templates" (in your WP admin side panel), then just trash your global widgets. **But note this does remove the widgets from any pages that were using them instead of unlinking them**, which is quite destructive unfortunately.

@drdiercks This is a pretty serious bug, I'm not sure why the issue has been in triage since October and OP reports the issue was raised two years ago...

@elementor Can we get an update on this.

**Comment by umarbutler** [comment]
If anyone else has this issue, please comment to maximize visibility!

**Comment by libbeydesign** [comment]
@umarbutler I encountered this today after updating to the latest release and then added a global widget to my footer. My workaround was to export the file and then manually delete the offending widgets and re-upload, however that is not a practical fix.

**Comment by alexander-pankart** [comment]
Same here.

I have a global widget (button) on every cta element.
I had to delete the global widget from the wordpress backend to edit my page again.

But now the cta button is missing on every page, so i had to make a new one ...

**Comment by folkscreative** [comment]
Discovered this issue 6 months ago, and had the same issue today, proving it still hasn't been fixed.

**Comment by mrrees** [comment]
Yesterday Spent a few hours trying to fix this.  Ended up duplicated the pages as a "save as" method just in case. Today did a couple hours of work, created a global widget and broke the page.  Got desperate and found this page as very helpfull.  Deleted the globals in templates and back up and running.   This Problem is not fixed as of 4_6_25.  Big issue for those who depend on global widgets.  Even Updated to the latest Elementor with all plugins disabled.

**Comment by ProtoUI** [comment]
Hey @nicholaszein, can you please look at this issue ? it's from 2022 #17954 and with this bug, global widget is useless.
The label status/awaiting_triage is very concerning.

**Comment by drdiercks** [comment]
The fact that this bug was discovered in 2022 and still being rediscovered by many users in 2025 means that it never really got solved. Isn't it a good idea for Elementor to deprecate this feature when it's giving users issues?

**Comment by mateuscqueiros** [comment]
Came across this bug, hopefully it's patched soon.

**Comment by ryanalta** [comment]
Came across it today, so it is still an issue. Disabling the fairly trivial globals I had created, deleted them, and that fixed it.

**Comment by libbeydesign** [comment]
Just ran into this issue again (I thought this was fixed in a previous release). I replaced the global widget with a template which isn't ideal but at least it works. We really need a fix for this.

**Comment by drdiercks** [comment]
@libbeydesign Luckily very soon we will have components in v4, which a significant upgrade from the global widgets. V4 is not stable yet imo, but I think we'll have a more workable solutions for global widgets soon.

**Comment by vladninja** [comment]
This issue is still present :(
