### ISSUE TITLE
✅ 🐞 Global Widgets are still not appearing on the frontend and in backend after saving page

### ISSUE THREAD

**Issue by netnothing** [elementor/elementor#29112]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

After updating to Elementor 3.25.2 global widgets are still not properly saving and appearing on the frontend and backend.

### Steps to reproduce

1. Edit page
2. Create a new global widget, or add a global widget that has already been created
3. Save page
4. You will see the global widget in the editor, and you will see the global widget on the frontend if you are logged into the admin
5. You will NOT see the global widget on the frontent if you load the page while not being logged in
6. If you reload the editor, the global widget will no longer show in the admin, however, the widget is still shown on the frontend if you are logged in

### Expected behavior

1. To see the global widgets in the backend and frontend for all users

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

```txt

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Source distribution v8.0.36-28
	PHP Version: 8.2.24
	PHP Memory Limit: 768M
	PHP Max Input Vars: 3000
	PHP Max Post Size: 256M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.2
	Site URL: https://elementor.ourtestsite.net
	Home URL: https://elementor.ourtestsite.net
	WP Multisite: No
	Max Upload Size: 256 MB
	Memory limit: 256M
	Max Memory limit: 768M
	Permalink Structure: /%postname%/
	Language: en_US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.1.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.25.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.25.0
		Author: Elementor.com


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	Container: Active
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active by default
	Optimized Markup: Inactive by default
	Conditionally load Swiper CSS files: Inactive by default
	Plugin Onboarding: Active by default
	CSS Smooth Scroll: Active by default
	Default to New Theme Builder: Active by default
	Header & Footer: Inactive by default
	Elementor Home Screen: Active by default
	Landing Pages: Active by default
	Nested Elements: Active
	Editor Top Bar: Active
	Pages Panel: Inactive by default
	Element Caching: Inactive by default
	Link In Bio: Active by default
	Floating Buttons: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default
	Launchpad Checklist: Inactive by default
	Menu: Active


== Log ==
	
Log: showing 20 of 392024-10-11 11:12:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.5',
  'to' => '3.24.6',
)]
2024-10-11 11:12:47 [info] elementor-pro::elementor_pro_updater Started 
2024-10-11 11:12:47 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-10-11 11:12:47 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-10-11 11:12:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.3',
  'to' => '3.24.4',
)]
2024-10-22 13:59:53 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.6',
  'to' => '3.24.7',
)]
2024-10-22 13:59:55 [info] elementor::elementor_updater Started 
2024-10-22 13:59:55 [info] Elementor/Upgrades - _on_each_version Start  
2024-10-22 13:59:55 [info] Elementor/Upgrades - _on_each_version Finished 
2024-10-22 13:59:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.6',
  'to' => '3.24.7',
)]
2024-10-29 14:43:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.7',
  'to' => '3.25.2',
)]
2024-10-29 14:43:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.0',
)]
2024-10-29 14:43:48 [info] elementor::elementor_updater Started 
2024-10-29 14:43:48 [info] Elementor/Upgrades - _on_each_version Start  
2024-10-29 14:43:48 [info] Elementor/Upgrades - _on_each_version Finished 
2024-10-29 14:43:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.24.7',
  'to' => '3.25.2',
)]
2024-10-29 14:43:50 [info] elementor-pro::elementor_pro_updater Started 
2024-10-29 14:43:50 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-10-29 14:43:50 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-10-29 14:43:50 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.24.4',
  'to' => '3.25.0',
)]

PHP: showing 3 of 3PHP: 2024-09-24 14:36:51 [notice X 1][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(69): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(162): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> create_items()
',
)]
PHP: 2024-10-22 14:06:37 [notice X 24][../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined index: condition_type [array (
  'trace' => '
#0: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: ../wp-content/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: ../wp-content/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-10-29 14:44:06 [notice X 6][../wp-content/plugins/elementor/includes/base/controls-stack.php::229] hexdec(): Passing null to parameter #1 ($hex_string) of type string is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

```
</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by Leadsquad** [comment]
@nicholaszein Can you really look into the issue and do not close it like for 3.25.2

CHEERS!!!

omg, and that's a premium plugin with 59$ per year for single website

**Comment by nicholaszein** [comment]
Hi @netnothing!

Thank you for submitting your issue.

Please hold while we evaluate it. We will update you when we have more information.

Kind regards

**Comment by netnothing** [comment]
> Hi @netnothing!
> 
> Thank you for submitting your issue.
> 
> Please hold while we evaluate it. We will update you when we have more information.
> 
> Kind regards

Sure thing.  I have a test site setup if you need access I can share privately.

**Comment by steve1401** [comment]
> > Hi @netnothing!
> 
> > 
> 
> > Thank you for submitting your issue.
> 
> > 
> 
> > Please hold while we evaluate it. We will update you when we have more information.
> 
> > 
> 
> > Kind regards
> 
> 
> 
> Sure thing.  I have a test site setup if you need access I can share privately.

Likewise. We're continuing to see the exact same on our staging.

**Comment by rosskevin** [comment]
Us too, I filed an issue but @nicholaszein closed and locked my issue before I could even respond.  https://github.com/elementor/elementor/issues/29111

Perhaps I should have been more clear instead of linking to the issue, but I don't like the inability to correspond on an issue I took time to file.

**Comment by bureaubraam** [comment]
Not only global widgets, also simple stuff like a form is not appearing on the frontend and in backend after saving page...

**Comment by majus82** [comment]
jepp - persisting still, multiple sites, mainly global forms affected

**Comment by nicholaszein** [comment]
Hey everyone!

Apologies for the trouble. We will have new patches soon. 🙏 

PS: @bureaubraam, if you think you found an issue with forms that is unrelated to global widgets, please submit a [new bug report](https://elemn.to/gh-new-bug-report) and we will take a look.

**Comment by Roy-Orbison** [comment]
This killed the main lead form on one of our sites, which is costing us $$$ by the hour. We pay for pro, too.

Do you not have global widgets output as part of your automated tests before pushing a release?

I can see the Elementor data is still there in the `postmeta` table, but nothing is output in the admin editor or the (logged out) front-end.

**Comment by scarey149** [comment]
Is this also related to the issue with theme colors not inheriting? It looks like Elementor is ignoring the checkbox "Checking this box will disable Elementor's Default Colors, and make Elementor inherit the colors from your theme." The buttons appear as expected when editing in Elementor (displaying with theme colors), but when viewed on the live site, the colors are not showing as expected (uses Elementor's colors).

**Comment by lensbreak** [comment]
> This killed the main lead form on two of our sites, which is costing us $$$ by the hour. We pay for pro, too.
> 
> Do you not have global widgets output as part of your automated tests before pushing a release?
> 
> I can see the Elementor data is still there in the `postmeta` table, but nothing is output in the admin editor or the (logged out) front-end.

They have never been good in testing. We are the testers. However you can avoid most issues by not updating production sites immediately when a new major version is coming out. This applies for all types of software, always wait a bit and observe the change history. The real damage comes from bugs like https://github.com/elementor/elementor/issues/25091 which they take a year to fix, leading to ten thousands of dollars of revenue loss. I have explained it in detail in another thread.

**Comment by majus82** [comment]
Can confirm the issues is solved. Hard learning. Next time I really will sit updates out. Damn, what a ride. Thx for fixing it @nicholaszein

**Comment by netnothing** [comment]
I can confirm that 3.25.3 has fixed the issue on both the front and backends, including global widget visibility for non-logged in users.

Thank you @nicholaszein for your work.  

May I make a suggestion that for the future, you can comment with the status of fixed, but don't close the issue for 24 hours to make sure people can respond if the issue wasn't actually fixed?  That way you can get quicker responses to people saying they are still having issues.

**Comment by hakyoungJeong** [comment]
@nicholaszein What about elementor pro? My pro plugin is still 3.25.0 version...

**Comment by majus82** [comment]
> @nicholaszein What about elementor pro? My pro plugin is still 3.25.0 version... Is it fixed too?

this wasn't affected as far as I understand.

**Comment by BrainBuggedB** [comment]
Global widgets seem to be mostly working again, but for me are still bugged: e.g. in the 'media carousel' widget, there is no possibility to let the text appear on hover. Does appear in editor but not a frontend page when not logged in. Is this a related issue?

**Comment by nicholaszein** [comment]
Hi @scarey149,

> _Is this also related to the issue with theme colors not inheriting? It looks like Elementor is ignoring the checkbox "Checking this box will disable Elementor's Default Colors, and make Elementor inherit the colors from your theme." The buttons appear as expected when editing in Elementor (displaying with theme colors), but when viewed on the live site, the colors are not showing as expected (uses Elementor's colors)._

No, this is unrelated. Since version 3.24.0 we've been improving how CSS is loaded and fixing long-time issues with specificity (priority) caused by the order stylesheets are loaded. So somethings changed, [but for the best](https://developers.elementor.com/elementor-3-25-developers-update/#:~:text=Optimizing%20Frontend%20Styles). If you check the option to disable Global Colors, Elementor will honor the styles applied by your theme instead of applying default styles, but this can be overwritten if you have set styles in the Editor > Site Settings.

If you think this is causing a bug, please submit a new bug report following the instructions in the form, and we may investigate. Otherwise, please keep the conversation here about this issue. 🙏

**Comment by Kejserjorn** [comment]
Just updated to 3.25.3 on staging site. 

Everything seems fine except the background color of the menu cart widget. 

It now has the same background as my button default but it is set to a different color in the editor. This used to work just fine but now it doesn't any more.

Is this related to this issue?

**Comment by nicholaszein** [comment]
Hey @netnothing!

> _May I make a suggestion that for the future, you can comment with the status of fixed, but don't close the issue for 24 hours to make sure people can respond if the issue wasn't actually fixed? That way you can get quicker responses to people saying they are still having issues._

Thank you for the feedback! In fact, we are discussing adjusting our workflows to do just that, along other adjustments! 🙏

**Comment by nicholaszein** [comment]
Hi @Kejserjorn,

> _Everything seems fine except the background color of the menu cart widget._
> 
> _It now has the same background as my button default but it is set to a different color in the editor. This used to work just fine but now it doesn't any more._
> 
> _Is this related to this issue?_

No, this is not related. This issue is only about Global Widget rendering in the editor and frontend. Anything else like styling or layout issues are unrelated.

**Comment by nicholaszein** [comment]
Ok everyone,

### It seems this issue was finally solved with the release of Elementor Core v3.25.3! 🙌 

Although Global Widgets are a **Pro** feature, they have the template library as a dependency, and we did made some changes to improve the security of the library. So the fix needed to be made only in Core this time.

Anything else you may be experiencing, such as styling and layout issues, or dynamic data, such as forms and popups is unrelated to this issue. 

If you think you have found a bug, and can consistently reproduce it [after troubleshooting it](https://elemn.to/help-troubleshooting), please open a [new bug report](https://elemn.to/gh-new-bug-report) by following the required steps, including [isolating the problem](https://github.com/elementor/elementor/blob/main/.github/CONTRIBUTING.md#:~:text=Isolate%20the%20Problem%20and%20Validate%20your%20Issue) and sharing the [required information](https://github.com/elementor/elementor/blob/main/.github/CONTRIBUTING.md#how-to-report-a-bug), and we will take a look.

I will keep the comments here open until tomorrow, but please, keep the conversation about this issue, and [above all civilized](https://github.com/elementor/elementor/blob/main/.github/CODE_OF_CONDUCT.md). If you wish to file a complaint like @lensbreak 's comment here, please do so by submitting a ticket to Elementor Support.

Thank you everyone for your feedback, patience, and contributions! We had a rough release this time and we really appreciate your understanding while we worked on a fix. We've learned a lot and will definitely use this as an example to improve our workflow. 🙏 

I'm closing this issue as solved.

Kind regards ❤️

**Comment by BrainBuggedB** [comment]
> Hi @BrainBuggedB!
> 
> > _Global widgets seem to be mostly working again, but for me are still bugged: e.g. in the 'media carousel' widget, there is no possibility to let the text appear on hover. Does appear in editor but not a frontend page when not logged in. Is this a related issue?_
> 
> No, this is not related. We are working on making significant improvements to all carousels in a future release, hopefully in the next one. I'll share this with the team.

Okay, just rolled back elementor on staging site, and there the bug dissapeared. So definitely seems linked to the latest update somehow. Do I open an new bug report for this? Do you recommend rolling back elementor to a previous version? This does affect some main features on our websites, so we're in need of a solution here...

**Comment by majus82** [comment]
@nicholaszein mate, you're my new role model for patience. I will print the threads here and use it as wallpapers in my office. kudos to you. the bug really sucked but you guys reacted as fast as possible - thanks for that.

**Comment by LoganStrike** [comment]
@nicholaszein Global elements are still not appearing in the Elementor editor screen with Elementor 3.25.3. Do I need to open another ticket for this same issue?

**Comment by nicholaszein** [comment]
Hi @LoganStrike,

Can you elaborate? Are you running both Elementor Core v3.25.3 and Pro v3.25.0?

What type of global widget is not loading?

Where is it located (a page, a site part, etc)?

Have you isolated the problem and cleared the cache?

Can you see and use it in the frontend?

**Comment by LoganStrike** [comment]
@nicholaszein Yes, running Core 3.25.3 and Pro 3.25.0. Global elements not appearing include icon list, social icons, site logo, navigation menu, and buttons. The global elements are located on a Header type Theme Builder template. Elementor cache, server cache, browser cache cleared. Elements are visible on front end, but not when editing the header theme builder template.

					
== Server Environment ==
	Operating System: Linux
	Software: Flywheel/5.1.0
	MySQL version: (Google) v5.7.44
	PHP Version: 8.2.24
	PHP Memory Limit: 200M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 300M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.2
	Site URL: https://terikoonse.com
	Home URL: https://terikoonse.com
	WP Multisite: No
	Max Upload Size: 300 MB
	Memory limit: 200M
	Max Memory limit: 200M
	Permalink Structure: /%category%/%postname%/
	Language: en_US
	Timezone: America/Los_Angeles
	Admin Email: ***
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.1.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.25.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.25.0
		Author: Elementor.com


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	Container: Inactive by default
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active by default
	Optimized Markup: Inactive by default
	Conditionally load Swiper CSS files: Inactive by default
	Plugin Onboarding: Active by default
	CSS Smooth Scroll: Active by default
	Default to New Theme Builder: Active by default
	Header & Footer: Inactive by default
	Elementor Home Screen: Active by default
	Landing Pages: Active by default
	Nested Elements: Active by default
	Editor Top Bar: Active by default
	Pages Panel: Inactive by default
	Element Caching: Inactive by default
	Link In Bio: Active by default
	Floating Buttons: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default
	Launchpad Checklist: Inactive by default
	Menu: Inactive by default


== Log ==
	
Log: showing 20 of 412024-08-15 01:03:01 [info] Elementor/Upgrades - _on_each_version Finished 
2024-08-15 01:03:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.3',
  'to' => '3.23.4',
)]
2024-08-15 01:03:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.3',
  'to' => '3.23.4',
)]
2024-10-29 15:10:30 [info] elementor-pro::elementor_pro_updater Started 
2024-10-29 15:10:30 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-10-29 15:10:30 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-10-29 15:10:30 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.23.2',
  'to' => '3.25.0',
)]
2024-10-29 15:10:33 [info] elementor::elementor_updater Started 
2024-10-29 15:10:33 [info] Elementor/Upgrades - _on_each_version Start  
2024-10-29 15:10:33 [info] Elementor/Upgrades - _on_each_version Finished 
2024-10-29 15:10:33 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.23.4',
  'to' => '3.25.1',
)]
2024-10-29 15:11:14 [info] elementor::elementor_updater Started 
2024-10-29 15:11:14 [info] Elementor/Upgrades - _on_each_version Start  
2024-10-29 15:11:14 [info] Elementor/Upgrades - _on_each_version Finished 
2024-10-29 15:11:14 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.1',
  'to' => '3.25.2',
)]
2024-10-29 15:11:15 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.1',
  'to' => '3.25.2',
)]
2024-10-30 16:32:38 [info] elementor::elementor_updater Started 
2024-10-30 16:32:38 [info] Elementor/Upgrades - _on_each_version Start  
2024-10-30 16:32:38 [info] Elementor/Upgrades - _on_each_version Finished 
2024-10-30 16:32:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.2',
  'to' => '3.25.3',
)]

PHP: showing 2 of 2PHP: 2024-08-01 15:39:54 [warning X 3][/www/wp-content/plugins/elementor/modules/ai/module.php::190] Attempt to read property "is_block_editor" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-10-29 09:20:06 [warning X 1][/www/wp-content/plugins/elementor/modules/history/revisions-manager.php::363] Undefined array key "editor_post_id" [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

**Comment by LoganStrike** [comment]
@nicholaszein I've discovered the cause. The editor was loading an autosave from a day or two ago when I was editing the site with previous versions and the elements were missing. It appears to be working fine now that I've re-added the elements and re-saved. No further action needed.

Thank you for the response!

**Comment by nicholaszein** [comment]
Great to hear that @LoganStrike! 🙌

Also, thanks for sharing the previous info. I'm glad it worked out in the end! 🙂

Cheers 🥂

**Comment by hendratmo** [comment]
I got problem here, my menu widgets didnt work properly. When i click the menu, the inside menu wont appear.
![dropdown not work](https://github.com/user-attachments/assets/eaf0c621-77da-4a4f-8cad-49f12ea9eae4)
This is my elementor version.
![elementor version](https://github.com/user-attachments/assets/25801b2b-e325-4efb-ab08-4ec4cae1ea3b)

When i rollback to older version, the elementor pro wont rollback, it stay at the current version. Any help please?

**Comment by nicholaszein** [comment]
Hi @hendratmo, please keep the conversation about this issue. This is not a thread to discuss other problems, and I am unable to provide personal support.

The issue you're reporting has nothing to do with this one.

Please read the instructions on [this comment](https://github.com/elementor/elementor/issues/29112#issuecomment-2447257023).

Guys, this is why we lock the comments. Please, respect our [Contribution Guidelines](https://elemn.to/gh-contributing).

Thank you for understanding.

**Comment by GerardPerret** [comment]
Hi,
Not sure this bug was only about Global widgets, I do have some widgets like hot spot taht are now showing up in the backend but not displayed in the UI, could this be related to the same issue?
