### ISSUE TITLE
⛔ Unable to add Nested Accordion

### ISSUE THREAD

**Issue by gmariani** [elementor/elementor#29220]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [ ] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

Unable to add the Accordion element/widget. Gives errors.

```
09:55:09.804 Uncaught TypeError: e.O is not a function
    <anonymous> https://example.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.25.4 line 3 > srcScript:2
    webpackJsonpCallback https://example.com/wp-content/plugins/elementor/assets/js/styleguide-app-initiator.min.js?ver=3.25.4 line 3 > srcScript:3
    webpackJsonpCallback https://example.com/wp-content/plugins/elementor/assets/js/webpack.runtime.min.js?ver=3.25.4 line 3 > srcScript:2
    <anonymous> https://example.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.25.4 line 3 > srcScript:2
frontend.min.js:2:44016
```

After bypassing the initial error by putting an if(e.O) { ... } around the problem section, this is the error I see:
```
09:49:36.754 Error: Element type not found: 'container'
    _construct editor.min.js:72773
    Wrapper editor.min.js:73638
    _createSuperInternal editor.min.js:40763
    ElementTypeNotFound editor.min.js:40773
    model editor.min.js:35710
    Backbone 2
web-cli.min.js:3:158024
```

```
09:49:36.755 TypeError: t is null
    getConditions https://example.com/wp-content/plugins/elementor-pro/assets/js/editor.min.js?ver=3.25.2:3
    run https://example.com/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.25.4:3
    runCallback https://example.com/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.25.4:3
    runCallbacks https://example.com/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.25.4:3
    run https://example.com/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.25.4:3
    run https://example.com/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.25.4:3
    runDataAfter https://example.com/wp-content/plugins/elementor/assets/js/web-cli.min.js?ver=3.25.4:3
    onAfterApply https://example.com/wp-content/plugins/elementor/assets/js/editor-document.min.js?ver=3.25.4:2
web-cli.min.js:3:158024
```

I did some tracking down of the error and in the stack I found a different error that is normally silenced:
`Call Error: Adding model to element collection is allowed only by the dedicated addChildModel() method.`

I have only Elementor and Elementor Pro active on a new site build. Running version 3.25.4 of Elementor, and version 3.25.2 or Elementor Pro using Hello Elementor theme version 3.1.1. This is on a WordPress 6.6.2 site.

I'm not sure the e.O error is related as other people are complaining about it here https://wordpress.org/support/topic/uncaught-typeerror-e-o-is-not-a-function-again/ . But figured I'd mention it as I'm seeing it here too.

### Steps to reproduce

1. On a fresh updated WordPress install install Hello Elementor theme, Elementor and Elementor Pro
2. Try to add an accordion using the Elementor editor

### Expected behavior

1. The accordion gets added without issue

### Isolating the problem

- [ ] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

<details>
<summary>Click to reveal</summary>

````txt

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.5.16
	PHP Version: 8.3.8
	PHP Memory Limit: 2048M
	PHP Max Input Vars: 16384
	PHP Max Post Size: 1536M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.6.2
	Site URL: https://example.com
	Home URL: https://example.com
	WP Multisite: No
	Max Upload Size: 2 GB
	Memory limit: 40M
	Max Memory limit: 2048M
	Permalink Structure: /%category%/%postname%
	Language: en_US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor
	Version: 3.1.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en-US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0

== Active Plugins ==
	Elementor
		Version: 3.25.4
		Author: Elementor.com

	Elementor Pro
		Version: 3.25.2
		Author: Elementor.com


== Must-Use Plugins ==
	Nexcess Managed Apps
		Version: 1.53.0
		Author: Nexcess


== Elements Usage ==
	
	archive : 1
		archive-posts : 1
		theme-archive-title : 1
	footer : 1
		text-editor : 2
		theme-site-logo : 1
	header : 1
		nav-menu : 1
		theme-site-logo : 1
	single-post : 1
		post-info : 1
		theme-post-content : 1
		theme-post-title : 1
	single-page : 2
		button : 2
		heading : 2
		posts : 1
		text-editor : 1
		theme-post-content : 2
		theme-post-title : 2
	landing-page : 0
		button : 3
		heading : 2
		icon-box : 3
		icon-list : 1
		image : 2
		nav-menu : 2
		reviews : 1
		text-editor : 4


== Settings ==
	
	disable_color_schemes: yes
	disable_typography_schemes: yes
	allow_tracking: yes


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Additional Custom Breakpoints: Active by default
	Container: Inactive by default
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Control Loading: Active by default
	Optimized Markup: Inactive by default
	Conditionally load Swiper CSS files: Inactive by default
	Plugin Onboarding: Active by default
	CSS Smooth Scroll: Active by default
	Default to New Theme Builder: Inactive
	Header & Footer: Active by default
	Elementor Home Screen: Active by default
	Landing Pages: Active by default
	Nested Elements: Active by default
	Editor Top Bar: Active by default
	Pages Panel: Inactive by default
	Element Caching: Inactive by default
	Link In Bio: Active by default
	Floating Buttons: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default
	Launchpad Checklist: Inactive by default
	Menu: Inactive by default


== Log ==
	
Log: showing 20 of 382024-11-07 09:27:56 [info] elementor::elementor_updater Started 
2024-11-07 09:27:56 [info] Elementor/Upgrades - _on_each_version Start  
2024-11-07 09:27:56 [info] Elementor/Upgrades - _on_each_version Finished 
2024-11-07 09:27:56 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.0',
  'to' => '3.25.4',
)]
2024-11-07 09:27:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.0',
  'to' => '3.25.4',
)]
2024-11-07 09:39:28 [info] elementor-pro::elementor_pro_updater Started 
2024-11-07 09:39:28 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-11-07 09:39:28 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-11-07 09:39:28 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.25.0',
  'to' => '3.25.2',
)]
2024-11-07 09:39:29 [info] elementor-pro::elementor_pro_updater Started 
2024-11-07 09:39:29 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-11-07 09:39:29 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-11-07 09:39:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.25.0',
  'to' => '3.25.2',
)]
2024-11-07 09:39:29 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.25.0',
  'to' => '3.25.2',
)]
2024-11-07 09:39:36 [info] elementor-pro::elementor_pro_updater Started 
2024-11-07 09:39:36 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-11-07 09:39:36 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-11-07 09:39:36 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.25.0',
  'to' => '3.25.2',
)]
2024-11-07 09:39:36 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.25.0',
  'to' => '3.25.2',
)]
2024-11-07 09:39:37 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.25.0',
  'to' => '3.25.2',
)]

PHP: showing 1 of 1PHP: 2023-06-04 21:42:03 [warning X 72][../wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::265] Attempt to read property "ID" on null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 3 of 3JS: 2024-11-05 19:20:30 [error X 1][../wp-admin/load-scripts.php?c=1&loadchunk_0=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-tooltip&ver=febb201b710006b933bf47cd4c18bd98:2:28760] Cannot read properties of undefined (reading 'value') 
JS: 2024-11-05 19:31:02 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.25.0:3:817583] Cannot read properties of undefined (reading 'get') 
JS: 2024-11-05 19:56:11 [error X 1][../wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.25.0:3:932279] Cannot read properties of undefined (reading 'val') 



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==

````

</details>

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by nicholaszein** [comment]
Hello @gmariani,

Thank you for reaching out! 🙏 

### ⛔ While reviewing your report we concluded this is not an issue caused by Elementor. Here's what we found out:
You have Nested Elements Activated, while the Container is inactive. When you activate Nested Elements Both Tabs and Accordions are replaced by Nested Tabs and Nested Accordions respectively, and require the Container to function properly.
![image](https://github.com/user-attachments/assets/638ba3a5-6112-44b2-8c15-9250b44e4770)

### ✅ What you can do to solve your issue:
- If you plan to use Nested Elements, you have to **`Activate`** the **Container** on your website.
- If you don't plan to use Nested Elements you have do **`Deactivate`** **Nested Elements** on your site.

You can do this by going to your WordPress **`Dashboard`** > **`Elementor`** > **`Settings`** > **`Features`** and select your options there.

### 👍 For now, that's all we can help with. 

### ⚠️ Note that GitHub issues are reserved for Elementor 🐞 Bug Reports only, and should not be used for support.

❔ If you have questions, or need guidance, help, or general support, please use one of the following channels:

- [Elementor Global Community](https://facebook.com/groups/Elementors/) The main Facebook group where all kinds of users come together to help each other.
- [Elementor Academy](https://elementor.com/academy) Learn everything you need to know about using Elementor.
- [Elementor Developers Documentation](https://developers.elementor.com/) Learn everything about our Developer-API.
- [Free Support Forum](https://wordpress.org/support/plugin/elementor) Get help on WordPress.org.

💎 If you have an active [Elementor Pro](https://elementor.com/pro) license you are entitled to personal support, please see your purchase email or visit your [Elementor Account page](https://my.elementor.com/) for details.

Kind regards

**Comment by gmariani** [comment]
![image](https://github.com/user-attachments/assets/747faec3-008e-462a-b957-bc79a1923aaf)
![image](https://github.com/user-attachments/assets/633ef183-3f20-489f-a140-42c0f8333906)

So you're saying that this feature is enabled by default, but doesn't work without another feature being enabled that is disabled by default. So is it a bug that both aren't enabled by default? Or that nothing explains this feature and there is no error message explaining why it doesn't work? Because the UI doesn't show any error messages. You try to add an accordion and nothing happens. I would have never guessed it was related to a new feature.

Enabling containers did fix the issue, so thanks for pointing me int he right direction. But like i mentioned, this was not clear at all why it wasn't working and it was on the default settings.

**Comment by gmariani** [comment]
forgot to add @nicholaszein  so you see my reply.

**Comment by FilipRastovic** [comment]
There should at least be a proper warning that you can't add an accordion element unless you tick that container option...I to was strugling with this problem yesterday and today until I found this issue. Thanks.

**Comment by nicholaszein** [comment]
Hi @FilipRastovic, we are working on a solution for this issue. Most likely we will disable Nested Elements from being active by default if the Container is not active. To respect user preferences.

This, however, is not currently an option in our infrastructure, and it will take some time to add this behavior.

**Comment by element-software** [comment]
I had an issue similar to this, wasn't able to add any elements to a page/template. Contacted Elementor support and wasn't given a detailed or appropriate answer. Stumbled on this page and I disabled nested elements, and my issue has been resolved.

I've spent over a week trying to figure it out, switching themes, deactivating plugins, restoring and backing up etc. 

Disappointed that they responded with this:

> Thanks for the feedback @gmariani.
> 
> I recognize you have a point. We will discuss this internally, but for the time being we do not consider this as a bug.
> 
> Kind regards

**I would say that this is 100% a bug on Elementor's part and it needs to be resolved.**

**Comment by pluckrose** [comment]
I've not yet experienced an issue due to this message but it is showing in  @Consoleon my fresh install of WordPress and  Elementor Pro, which led to me this post. 

I changed both from Default to Active but made no difference and the error still exists.

I'm just posting to add weight to the above.
