### ISSUE TITLE
Soft 404 (200 response) when "All Archives" or "Categories" template conditions used

### ISSUE THREAD

**Issue by jamieburchell** [elementor/elementor#29789]
### Prerequisites

- [X] I have searched for similar issues in open and closed tickets and cannot find a duplicate.
- [X] I have troubleshooted my issue, and it still exists against the latest stable version of Elementor.

### Description

In Elementor 3.25.11 and Pro 3.25.5 accessing a non-existent URL would result in a 404 response code, and the 404 template. Accessing "/admin" would bring up the WP admin dashboard.

In Elementor 3.26.3 and Pro 3.26.2 accessing an invalid URL brings up the 404 template, with a 200 response code and "/admin" does the same.

When removing "All Archives" or "Categories" as conditions from all templates, the issue is resolved.

All plugins except Elementor/Pro disabled. No caching. Permalinks flushed.

### Steps to reproduce

1. Add a template with condition "All Archives" and/or "Categories"
2. Add 404 template with 404 condition
3. Access /admin or /someinvalidurl.
4. 404 template is shown, but response code is 200. On some of our sites, the archive template is shown instead
5. Remove the "All Archives" and/or "Categories" conditions and repeat

### Expected behavior

As in previous version

### Isolating the problem

- [X] This bug happens when only the Elementor (and Elementor Pro) plugins are active.
- [X] This bug happens with the Hello Elementor theme active.
- [X] I can reproduce this bug consistently by following the steps I described above.

### Elementor System Info

```txt
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.52 (Ubuntu)
	MySQL version: Ubuntu 22.04 v10.6.18
	PHP Version: 8.2.26
	PHP Memory Limit: 256M
	PHP Max Input Vars: 10000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.7.1
	Site URL: https://dmtt.local.test/wp
	Home URL: https://dmtt.local.test
	WP Multisite: No
	Max Upload Size: 50 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%category%/%year%/%monthnum%/%day%/%postname%/
	Language: en_GB
	Timezone: Europe/London
	Admin Email: team@ib3.uk
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor Child
	Version: 2.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.2.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en-GB
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.26.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.26.2
		Author: Elementor.com


== Must-Use Plugins ==
	Bedrock Autoloader
		Version: 1.0.3
		Author: Roots

	Disable status tests
		Version: 1.0.0
		Author: Roots

	Register Theme Directory
		Version: 1.0.0
		Author: Roots

	Set WordPress Mail From Address
		Version: 1.0.0
		Author: ib3 Limited


== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	


== Elementor Experiments ==
	Inline Font Icons: Active
	Additional Custom Breakpoints: Inactive
	Container: Active
	Upgrade Swiper Library: Active by default
	Nested Elements Performance: Active by default
	Optimized Markup: Inactive
	Plugin Onboarding: Active by default
	CSS Smooth Scroll: Active by default
	Head Loading Styles: Inactive by default
	Default to New Theme Builder: Active
	Header & Footer: Inactive
	Elementor Home Screen: Active by default
	Landing Pages: Inactive
	Nested Elements: Inactive
	Editor Top Bar: Inactive
	Element Caching: Inactive
	Link In Bio: Active by default
	Floating Buttons: Active by default
	Elementor Editor Events: Inactive by default
	Atomic Widgets: Inactive by default
	Global Classes: Inactive by default
	Launchpad Checklist: Inactive by default
	Menu: Inactive


== Log ==
	
PHP: showing 4 of 4PHP: 2024-11-06 08:04:28 [notice X 7][/var/www/vhosts/danmaskelltennistrust.org.uk/releases/164/web/app/plugins/elementor-pro/modules/screenshots/module.php::33] Function utf8_decode() is deprecated [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2024-11-07 13:56:12 [warning X 2][/var/www/vhosts/danmaskelltennistrust.org.uk/releases/165/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /var/www/vhosts/danmaskelltennistrust.org.uk/releases/165/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /var/www/vhosts/danmaskelltennistrust.org.uk/releases/165/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /var/www/vhosts/danmaskelltennistrust.org.uk/releases/165/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /var/www/vhosts/danmaskelltennistrust.org.uk/releases/165/web/app/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2024-11-26 09:50:50 [warning X 6][/var/www/vhosts/danmaskelltennistrust.org.uk/releases/171/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /var/www/vhosts/danmaskelltennistrust.org.uk/releases/171/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /var/www/vhosts/danmaskelltennistrust.org.uk/releases/171/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /var/www/vhosts/danmaskelltennistrust.org.uk/releases/171/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /var/www/vhosts/danmaskelltennistrust.org.uk/releases/171/web/app/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]
PHP: 2025-01-06 10:40:41 [warning X 6][/home/jamie/projects/danmaskelltennistrust.org.uk/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php::150] Undefined array key "condition_type" [array (
  'trace' => '
#0: /home/jamie/projects/danmaskelltennistrust.org.uk/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(150): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_template_json_item()
#2: /home/jamie/projects/danmaskelltennistrust.org.uk/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(120): class type array_map()
#3: /home/jamie/projects/danmaskelltennistrust.org.uk/web/app/plugins/elementor-pro/core/app/modules/site-editor/data/endpoints/templates.php(59): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> normalize_templates_json()
#4: /home/jamie/projects/danmaskelltennistrust.org.uk/web/app/plugins/elementor/data/base/endpoint.php(158): ElementorPro\Core\App\Modules\SiteEditor\Data\Endpoints\Templates -> get_items()
',
)]

Log: showing 20 of 382024-11-25 11:24:20 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-11-25 11:24:20 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.25.3',
  'to' => '3.25.4',
)]
2024-12-16 13:28:19 [info] Update DB has been started [array (
  'plugin' => 'Elementor',
  'from' => '3.25.10',
  'to' => '3.25.11',
)]
2024-12-16 13:28:19 [info] elementor::elementor_updater Started 
2024-12-16 13:28:19 [info] Elementor/Upgrades - _on_each_version Start  
2024-12-16 13:28:19 [info] Elementor/Upgrades - _on_each_version Finished 
2024-12-16 13:28:19 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.10',
  'to' => '3.25.11',
)]
2024-12-16 13:28:22 [info] Update DB has been started [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.25.4',
  'to' => '3.25.5',
)]
2024-12-16 13:28:22 [info] elementor-pro::elementor_pro_updater Started 
2024-12-16 13:28:22 [info] Elementor Pro/Upgrades - _on_each_version Start  
2024-12-16 13:28:22 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2024-12-16 13:28:22 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.25.4',
  'to' => '3.25.5',
)]
2025-01-06 09:43:31 [info] elementor::elementor_updater Started 
2025-01-06 09:43:31 [info] Elementor/Upgrades - _on_each_version Start  
2025-01-06 09:43:31 [info] Elementor/Upgrades - _on_each_version Finished 
2025-01-06 09:43:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.25.11',
  'to' => '3.26.3',
)]
2025-01-06 09:43:38 [info] elementor-pro::elementor_pro_updater Started 
2025-01-06 09:43:38 [info] Elementor Pro/Upgrades - _on_each_version Start  
2025-01-06 09:43:38 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2025-01-06 09:43:38 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.25.5',
  'to' => '3.26.2',
)]



== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible

== Elementor Pro - Compatibility Tag ==
```

### Agreement

- [X] I agree that my issue may be closed without action if it doesn't meet all the requirements.

**Comment by aLink536** [comment]
Can confirm, same exact issue here.

**Comment by JBNewhouse** [comment]
Hello,
Same here :(

**Comment by PaulGeorgeTPJ** [comment]
I'm seeing this behaviour on multiple websites as well.

**Comment by ceri-waterscreative** [comment]
Same issue here!

**Comment by jamieburchell** [comment]
@nicholaszein This is affecting multiple people. At the very least, it's giving the wrong signals to search engines.

**Comment by JBNewhouse** [comment]
Temporarily, you'll need to downgrade your Elementor Pro version before 3.26, i.e. max 3.25.5. an it's ok.

**Comment by jamieburchell** [comment]
> Temporarily, you'll need to downgrade your Elementor Pro version before 3.26, i.e. max 3.25.5. an it's ok.

There are other workarounds too (as mentioned in the bug report) such as being more specific with archive display conditions or changing the archive pagination type. Neither are ideal.

**Comment by enopuente** [comment]
Having this same issue as well. Any updates/fix to this?

**Comment by Steven-Nesty** [comment]
Still a issue even with the new 3.28 build, any way of getting more eyes on this? Quite the site breaking bug.

**Comment by kevinreyes00** [comment]
I've been experiencing this exact same issue on multiple sites. After upgrading to Elementor Pro 3.26.0+ (currently on 3.28.1), non-existent URLs are incorrectly displaying archive templates instead of the 404 page.

**My findings:**
After extensive debugging, I discovered that Elementor is incorrectly handling URL routing for single-level paths. When accessing URLs like /random/ or /fghfd/, Elementor is treating them as potential category archives, even when they don't exist.

**Debugging on a 404-page show:**
```
is_404: false
is_archive: true
is_category: true
queried_object: [empty]
```

**Working solution:**
I've implemented this fix in my functions.php file (Always use a child-theme) which resolves the issue without needing to downgrade:

```
add_action('template_redirect', function() {
    // Only target category archives with no posts and no valid category object
    if (is_category() && get_queried_object() === null) {
        global $wp_query;
        
        // Force WordPress to treat this as a 404
        $wp_query->set_404();
        status_header(404);
        
        // Make sure the 404 template is used (safely check if Elementor is active)
        if (function_exists('elementor_theme_do_location')) {
            add_filter('elementor/theme/template_include', function($template) {
                return get_404_template();
            }, 999);
        } else {
            // Fallback if Elementor is deactivated
            add_filter('template_include', function() {
                return get_404_template();
            }, 999);
        }
    }
}, 5);

```

This code intercepts the incorrect category archive detection and forces Elementor to use the proper 404 template.

This is a significant issue affecting SEO as search engines are seeing 200 responses for pages that should return 404s.

**Comment by freschstudio** [comment]
Just experienced this bug on a simple website. Oddly enough, more complex websites (multiple custom post types) don't exhibit this behavior.

@kevinreyes00 fix did the trick and now it properly returns 404 page template as set in Elementor Pro.

**Comment by zchgdn** [comment]
The fix @kevinreyes00 worked to get Elementor to distinguish an Archive from the 404, but the 404 page is just blank. It doesn't load my 404 template even though the display conditions are set. The 404 template itself just doesn't load - other templates (ie. global header and footer) do though. Any thoughts? This seems like a bit of an oversight. 

Elementor v3.28.3
Elementor Pro v3.28.2

**Comment by Steven-Nesty** [comment]
@nicholaszein Can we get an update on this issue please?

**Comment by janhenrydesign** [comment]
We've got the same issue. @kevinreyes00 code didn't work for us, and we were unable to get other code to override it. Since we're launching a new site, and we're on a tight deadline, we've had to opt for a standard permalink structure instead.

**Comment by tatsats** [comment]
Had the same issue.

Thank you @kevinreyes00 for the temp solution

**Comment by cdiaz23** [comment]
You could change line 3 

_if (is_category() && get_queried_object() === null) {_

to:

_if ((**is_tag()** || is_category()) && get_queried_object() === null) {_

in order to intercept also tags archive.

> 
> 
> **Working solution:** I've implemented this fix in my functions.php file (Always use a child-theme) which resolves the issue without needing to downgrade:
> 
> ```
> add_action('template_redirect', function() {
>     // Only target category archives with no posts and no valid category object
>     if (is_category() && get_queried_object() === null) {
>         global $wp_query;
>         
>         // Force WordPress to treat this as a 404
>         $wp_query->set_404();
>         status_header(404);
>         
>         // Make sure the 404 template is used (safely check if Elementor is active)
>         if (function_exists('elementor_theme_do_location')) {
>             add_filter('elementor/theme/template_include', function($template) {
>                 return get_404_template();
>             }, 999);
>         } else {
>             // Fallback if Elementor is deactivated
>             add_filter('template_include', function() {
>                 return get_404_template();
>             }, 999);
>         }
>     }
> }, 5);
> ```
> 
> This code intercepts the incorrect category archive detection and forces Elementor to use the proper 404 template.
> 
> This is a significant issue affecting SEO as search engines are seeing 200 responses for pages that should return 404s.

**Comment by gmariani-cv** [comment]
Spoke with support. They confirmed "that [their developers] are aware of the issue and that it is planned to be resolved. The case is officially on the developers' pending list."

No ETA... "the only supported workaround is adjusting the permalink structure" to remove the category from the permalink.

**Comment by rl-sandy** [comment]
Thanks for raising this. My suspicions on /admin no longer redirecting to admin dashboard being broken may have other broken pieces as a result of the same bug has been confirmed. This makes me nervous to upgrade.

**Comment by dakman** [comment]
still not fixed??

**Comment by gmariani-cv** [comment]
No update on this? Tested it with Elementor 3.34.1 and Elementor Pro 3.34.0, still broken a year later...

**Comment by mikedoyledesign** [comment]
I just noticed this today when a client tried logging in with an incorrect URL and sent me their screenshot which looked odd (showing the "It seems we can't find what you're looking for." page. Version 3.33.4/3.33.2. 

It is a recent site launch so I still have the mirrored development site up with 3.33.1 and the 404 is working fine. I absolutely tested this many times live as I was literally doing redirect checks and rules on the live site the same night after launching a month ago. 

Rolling back to 3.33.4/3.33.2 on the development site shows the correct 404 page still - so I am not sure this is a version-related issue. It seems it could happen randomly with any version? 

Not interested in changing permalink structure on a live and important law firm site right now. 

EDIT: Just noticed someone posted a similar issue but it contained enough information for me to patch my site (and maybe yours). https://github.com/elementor/elementor/issues/34209

It occurs when the Archive template has a pagination feature enabled. I had infinite scroll. Removing that caused the 404 pages to work as intended again. I did not have infinite scroll pagination enabled on the development site, hence working the entire time. Perhaps try remove this if you don't think it's a critical feature (it's not for my site). 

EDIT 2: Further - I noticed 'Numbers' pagination option works as intended, but the other options 'Prev/Next, Infinite Scroll, Load on Click' cause the issue.

**Comment by itfirmaet** [comment]
@mikedoyledesign I was posting the #34209 issue . Thank you for the EDIT 2 finding. The issue could also be fixed with a mu plugin checking if the category exits, but I really hope that Elementor will fix the problem the right way.

**Comment by black-eye** [comment]
Still issue in 2026

**Comment by ardalanelf** [comment]
I found a temporary fix.

The root cause is located in elementor-pro/modules/theme-builder/classes/locations-manager.php.

Find (around line 131): 

```
if ( $this->is_valid_pagination( $document->get_elements_data(), $current_page ) ) {
    $handled = true;
}
```
Replace it with:

```
if ( $current_page > 1 && $this->is_valid_pagination( $document->get_elements_data(), $current_page ) ) {
    $handled = true;
}
```
I hope this issue will be fixed in the next release.

**Comment by s60v5** [comment]
Same thing is happening to us on Elementor 3.34.1 and Elementor Pro 3.34.0

**Comment by swinggraphics** [comment]
Over a year and still not fixed. This issue persists in version 4.

**Comment by MatthewMa5163858** [comment]
same problem here, any update on this ?

**Comment by Yahav** [comment]
Same issue here, this is a MAJOR seo problem.

**Comment by rl-sandy** [comment]
Still not fixed. We're considering moving away from Elementor/WordPress due to this issue
