### ISSUE TITLE
Feature Request for Posts widget: allow full text of post, not just an excerpt

### ISSUE THREAD

**Issue by HmCody** [elementor/elementor#4617]
Currently, the Posts widget provides an option to include an excerpt of post and allows the length of the excerpt to be selected. The excerpt is a compressed version of the first X words of text which ignores all formatting, links, and other HTML.

I have several places on my site where I would like to have the entire post, with HTML and especially links, included rather than just an excerpt. We use this as a newsfeed/coming events listing and it would be more convenient for users to be able to click on links directly, rather than have to open the actual blog post, then click through to the link page.

Thanks for considering this!

**Comment by black-eye** [comment]
+1

**Comment by corsa** [comment]
Would love this option also.

**Comment by ssdzd** [comment]
+1

**Comment by HmCody** [comment]
I found a plugin, Elementor Custom Skin for Posts and Archive Posts https://wordpress.org/plugins/ele-custom-skin, that allows me to create custom skins that are used by the posts and archive widgets. It provides the functionality requested which is great, but it is something that would be even better if it were included in Elementor Pro itself.

**Comment by Nuyonuyonoina** [comment]
+1

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.7

Feel free to update

Thanks!

**Comment by RealBenihime** [comment]
I'm so appalled to learn that this feature would have a higher priority compared to this one ([#1284](https://github.com/elementor/elementor/issues/1284)) a feature request that has been for over **2 YEARS!** and has received upvotes and 76 comments! Yet this one was attended to just like (snaps finger) that. 

Does one have to have a certain status for their feature request to be taken seriously?

**Comment by corsa** [comment]
“Just like that?” This request is from over a year ago, and the related #2569 referenced in the very first comment is from 2 years ago.

**Comment by eculaban** [comment]
> This issue has been resolved in Elementor Pro v2.7
> 
> Feel free to update
> 
> Thanks!

![image](https://user-images.githubusercontent.com/17697587/98336064-258ea300-2041-11eb-8396-af6da73b6f1c.png)
Please add the full content on "Classic" skin, we badly need this one! This is not yet resolved, please open this ticket.

Thank you!
