### ISSUE TITLE
Slides Widget "Infinite Loop" Option Does Not Properly Work With Autoplay

### ISSUE THREAD

**Issue by zndinc** [elementor/elementor#6726]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest stable version of Elementor.

## Description

If Autoplay is enabled, and the infinite loop option is disabled, the Slides plugin will continue to loop through the slides endlessly. Infinite loop seems to only prevent looping if slides are changed manually.

## Steps to reproduce

1) Enable Autoplay
2) Disable Infinite Loop
3) Slide continues to loop infinitely

**Comment by zndinc** [comment]
Still no word on this, I can confirm this still happens in the updated versions as well

**Comment by marty-graybirch** [comment]
I reported this issue through Customer Support and was informed it was an enhancement request. Joining this thread as CS was opening their own request, but I need a resolution (that doesn't involve hacking Elementor JS code on the website :)

I would like to add that with Autoplay enabled and Infinite Loop disabled, the slides continue to rotate, but in order 1-2-3-2-1-2-3. (forward then reverse through the deck). With Infinite Loop enabled, the slides rotate in proper sequence 1-2-3-1-2-3 (forward to end and then repeat from beginning). 

In my case, this is for a Hero landing page. I want the slide overlay to run through 3 text-only slides, display the company logo and then stop so that the company logo remains on the screen while the user interacts with the page.

In other sliders I have worked with autoplay + loop controls whether or not to start playing the deck and whether or not to stop after the deck is cycled.

In Elementor Pro 2.5.4, the Infinite Loop option seems to *only* control navigation order from the last slide and has no impact on autoplay.

I will also note that I consider this more of a defect than an enhancement. Auto playing slides forward then backward continuously has no real use-case that's not covered in a repeating from start and is especially confusing when used with text that is designed to be sequentially displayed. The Infinite Loop flag can easily have dual use - allowing manual navigation from last to first while stopping autoplay after a single pass.

**Comment by marty-graybirch** [comment]
After doing a bit of debugging & research, I found this is known behavior in the [Slick](https://github.com/kenwheeler/slick/) slider that is the foundation for the Elementor Pro slider. The author argues that this is functioning as designed - although a number of issues have been reported against this behavior.

The solution is to add an action on the Slick _afterChange_ event to turn off the autoplay function if the last slide is reached.

The following javascript snippet added to my theme's javascript file handles this. I test for autoplay=on and infinite=off so I can still use looping sliders elsewhere.

```
jQuery( window ).on (
  'elementor/frontend/init', function () {
    elementorFrontend.hooks.addAction( 'frontend/element_ready/slides.default', function ($scope) {
      $scope.find('.slick-slider').on('afterChange', function (event, slick, currentSlide) {
        if ( 
            currentSlide === slick.$slides.length - 1 && 
            slick.getOption("autoplay") === true && 
            slick.getOption("infinite") === false 
           ) { slick.setOption("autoplay", false, true); }
        });
      }
    );
  }
);
```

Make sure the js file is loaded _after_ the Elementor front end libraries. The following from my functions.php loads the site javascript dependent on jQuery, Slick and the Elementor front end libraries.

```
function mytheme_enqueue_scripts() {
  wp_enqueue_script 
  ( 
    'mytheme_js', 
    get_stylesheet_directory_uri() . '/path/to/mytheme.js', 
    [
      'jquery',
      'jquery-slick',
      'elementor-frontend',
      'elementor-pro-frontend'
    ], 
    null, 
    true
  );
}
add_action( 'wp_enqueue_scripts', 'mytheme_enqueue_scripts', 999999 );

```

**Comment by zndinc** [comment]
I might try that out later. As I only needed two slides to switch, I did a simpler (but arguably more hacky) jquery opacity swap on the two slide layers. Would be great just to have this implemented so workarounds were not needed. 

`<script>
var $jq = jQuery.noConflict();
setTimeout(function() {
     $jq(".elementor-repeater-item-e5eeb41").css('opacity', '0');
     $jq(".elementor-repeater-item-47dd5b6").css('opacity', '1');
          $jq(".elementor-repeater-item-47dd5b6").css('z-index', '9999');

}, 7500); // mili

</script>`

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v2.7

Feel free to update

Thanks!

**Comment by apartofdev** [comment]
It have still error in  Elementor Pro v2.7

**Comment by trandinh2409** [comment]
This issue have still error in Elementor Pro v2.7

**Comment by tim-getfetchr** [comment]
Same here - this issue still persists Elementor Pro 2.7.3

**Comment by datascientistgonzo** [comment]
Unfortunately the issue still persists in Elementor Pro Version 2.8.3

**Comment by FrankvanCaspel** [comment]
+1 on this issue for me - still present in version 2.9.6.

**Comment by mimetog** [comment]
+1 for me as well. Still an issue (and a total pain)

**Comment by niccoloperazza** [comment]
I can confirm that the bug is still present

**Comment by mattiatravaglione** [comment]
Bug still present.

**Comment by msrougi** [comment]
Bug still present at the end of 2020.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor Pro v3.1.0

Feel free to update

Thanks!

**Comment by tobiasfeistmantl** [comment]
Still present in Elementor 3.1.4 and Pro 3.2.1.

**Comment by cdwm** [comment]
still present

**Comment by jgarcianewemage** [comment]
Still sucks balls at version 3.15.3

**Comment by mesmaili151** [comment]
There is another problem now, if autoplay, and infinite loop is activated, it will stop as soon as it moves `Slides to Show` times.
