### ISSUE TITLE
Improve performance: Reduce DOM elements

### ISSUE THREAD

**Issue by wpsumo** [elementor/elementor#7351]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Mentioned before but ticket closed and no real answer:
https://github.com/elementor/elementor/issues/6534
https://github.com/elementor/elementor/issues/2100

Right now we have way too many DOM elements on our mockup 2000+ My aim is to be below 800 this will be hard with page builders I know. But we should still aim for it and be maximum on a more comprehensive design eb below 1500.

We have no advanced custom things so. Don't see how elementor can add that many divs? Why not add ID and class directly to the tag of h2 or span or p instead of wrapping it into 2 divs?

Of course a plain html page would have minimum DOM and that we don't want but I still consider this amount of DOM elements not to be needed to structure this design. I've seen Divi pages etc use below 1500. Maybe this is a pure elementor issue according to you? I will address a ticket to them tomorrow morning as well.

Which will reduce or use fewest DOM elements.

Section + section + section
or
Section + inline section widget + inline section widget

Help me make the site much easier for browsers to render with what we have today and please comment on the DOM elements and make elementor build pages more lightweight when it comes to DOM elements.

**Comment by black-eye** [comment]
+1
Oh yes, the number of nested divs is quite insane and most likely unnecessary. 

On the other hand I understand, that such a reduction could cause significant backward compatibility issues. Some legacy render option would be needed if this update would come to life.

**Comment by shilo-ey** [comment]
Hi @alriksson 

Thanks for your feedback.

Elementor wraps widgets with multiple div tags because each element can support animations, background, and many more customization options.

If you have concrete suggestions for reducing the number of DOM elements - we are open to hearing it.

Waiting for your reply, 

Thanks.

**Comment by alriksson** [comment]
@shilo-ey I totally get your point here but I think the community together with your in-house team can come up with a smart solution in the future.

Just on the spot and based what you say above a solution like the css print. Performance or design preference settings. And if the user design and then want to add animations, backgrounds etc it will pop up a warning and say "your preferred settings do not support this and that, do you want to change settings or learn more?".

I'm just thinking openly here how we can sort it, I want to make websites built with elementor page builder faster and better to render for the browser. Especially when we moving towards a mobile web with 3G connections. And non of us in the industry want AMP.

Hope more smart people can jump into the thread and start brainstorm, maybe there is certain improvement that can be done on elements that don't need to be wrapped within divs? that does not require this customisations? Maybe my suggestion is very complex, but it's a start at least.

Maybe Elementor in general can run a function to remove unused css/js and divs on the frontend? So if user did not use any custom function that required this styling (css, js, div wraps) it will clean it up on frontend user. Like a running gulp on that can be triggered from tools/settings to re run if design is changed, or it automatically trigger on a save. Just brainstorming....

**Comment by black-eye** [comment]
Little bit offtopic, but concerning other types of bloat (CSS, JS): https://www.youtube.com/watch?v=RmIrqJ9Wd0U

Definitely not independent and not without bias, but the point is quite clear and cannot be easily ignored. 

Just to clearly declare it here: I'm definitely not an Oxygen user, nor the fond of it, but the way it handles the code is way better than Elementor's and shows the other page builders it's doable. I'm pointing this out here, because the clarity and bloat of the code concerns me a lot and as far as it's handled by Elementor, doesn't make me happy. And that's why I'm still on the search of the page builder Holy Grail and still without the success. Oh my, how happy would I be, if it was Elementor! Alas it isn't. At least not yet. Hopefully it will be in the future and this is one thing that would helped it a lot.

**Comment by daviedR** [comment]
+1

**Comment by hasti** [comment]
I'm also looking for this feature to reduce the number of divs.

**Comment by cuu508** [comment]
> If you have concrete suggestions for reducing the number of DOM elements - we are open to hearing it.

@shilo-ey do you mean isolated testcases? 

Here's one to get the ball rolling. I created a new page using the "Elementor Canvas" layout. I added a single heading element with the default properties. The resulting markup:

```
<div data-elementor-type="post" data-elementor-id="462" class="elementor elementor-462" data-elementor-settings="[]">
<div class="elementor-inner">
<div class="elementor-section-wrap">
<section class="elementor-element elementor-element-3c77f58 elementor-section-boxed elementor-section-height-default elementor-section-height-default elementor-section elementor-top-section" data-id="3c77f58" data-element_type="section">
<div class="elementor-container elementor-column-gap-default">
<div class="elementor-row">
<div class="elementor-element elementor-element-8d5dee6 elementor-column elementor-col-100 elementor-top-column" data-id="8d5dee6" data-element_type="column">
<div class="elementor-column-wrap  elementor-element-populated">
<div class="elementor-widget-wrap">
<div class="elementor-element elementor-element-09a1be6 elementor-widget elementor-widget-heading" data-id="09a1be6" data-element_type="widget" data-widget_type="heading.default">
<div class="elementor-widget-container">
<h2 class="elementor-heading-title elementor-size-default">Hello World</h2>	</div>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
</div>
</div>
</div>
```

It would be great to reduce the number of the nested div elements as much as possible. In this specific case, ideally, there would be a single `h2` element and no divs.

**Comment by alriksson** [comment]
@shilo-ey another ticket which is time to look into.

**Comment by ramonkcom** [comment]
Maybe should be merged with https://github.com/elementor/elementor/issues/7817#issue-431846134

**Comment by alriksson** [comment]
Oxigyn manage to keep design and flexibility without all nested divs: https://www.youtube.com/watch?v=KDGwVfj1jr4

**Comment by Alfred4444** [comment]
This issue should be a priority. As something necessary and mandatory. Even if I take work. Once finished, it will be an Elementor badge, a value, that the potential customer will see as something very important. I have customers who don't want Elementor because of their speed problems on smartphones and devices.
It is time to make the change and increase the quality.
I hope my words encourage you on this path. A strong hug.

**Comment by parasshah195** [comment]
Although I do support the idea, but contrary to the popular opinion in this thread, I think that the route Elementor has chosen for nested div outputs is the best way because **it's consistent**.

Whatever the widget may be, it has a main wrapper, container and then the element. This allows much more flexibility to extend its functionalities and more customization options in the future. Also, you have much more control over the widget's appearance via custom CSS as well because of the ability to target divs and its child wrappers uniquely.

If you were a Backbone developer, you would understand the beauty of Elementor's codebase and its modularity which is one of its biggest strengths.

Without this consistent nesting, they would probably have to manually define each widget's custom output which significantly limits the options available to both the users and the developers. Not to mention the increased backend complexity for them to deal with.

**Comment by Tahx** [comment]
I would suggest a reason to reduce the amount of nested div.

I understand that each div that Elementor creates has a meaning, but they're not all always being in use.

I would suggest that Elementor tries to compact things more if it can instead of relying so much on creating unnecessary extra div.

The message posted on Facebook on the previously closed issue mention that the difference between Elementor and Bootstrap, for instance, would be somewhere around 4 div per widget, with the conclusion that it is not a big deal.

Well, I disagree with that, with about 50 widgets or more as Elementor makes it so easy it tends to pile up very fast, that's 4x50 = 200 extra div, yeah, those extra 4 became 200 extra div.

That's 200 extra nodes to be parsed by the processor, both for the HTML and the CSS.

On a modern computer, it may not matter but aren't our website mostly made for smartphones & notebook on-the-go nowadays?

Although the decent majority of the US have modern smartphones, it isn't the case for the rest of the world which are using smartphones from 2014-2015 which struggle loading a page under 5-7s although it may loads under 2s on a modern one.

I think the matter is being "skipped" on although it's a very important one.

This should get some attention.

**Comment by parasshah195** [comment]
@Tahx agreed, but I don't think they can do much about it now. This was an architectural decision that they took in the early stages of building the plugin to keep the output of widgets consistent.

If they change the DOM output now, hundreds or thousands of sites (including designer's client's sites) that might have used custom CSS to target some of those nodes or external 3rd party plugins which would be using them to add extra functionalities.. all of that would stop working, pages would break in terms of design and it would be a haywire. Bad reputation for the company.

So, to me, it seems that it's too late to act on this to bring any major changes to their DOM output structure.

I guess divception is one of the primary reasons why they don't allow Inner Section nesting, which although is a big limitation when designing layouts, makes sense from that point of view.

**Comment by BroadBrander** [comment]
+1

**Comment by MichaelDarko** [comment]
The more I'm looking into performace issues with Elementor, the more I'm sceptical about Elementor's future and Elementor's focus on being a professional tool.

Professional tool should produce professional results. WebFlow produces clean code and is super-fast. Oxygen produces clean code and is also fast. Elementor produces huge amount of divs, loads unnecessary files and is just slow, if you build something more complex. (All the reasons why professionals hate page builders.)

I've been trying out Oxygen page builder and my early conclusion was this:

- It's posibble to build more complex websites with Oxygen.
- Performance is on a different level with Oxygen.
- Elementor is nicer and more comfortable to use.

I'm still not ready to switch from Elementor, but I'm more and more concerned about Elementor's focus. Is it going to be a "toy" page builder for amateur users, or is it going to be a professional tool (like WebFlow) for WordPress that professionals can confidently use to build professional websites?

I really hope something can be done about fundamentally improving Elementor's performance.

**Comment by portseif** [comment]
I totally agree with @MichaelDarko. I've been using Elementor for 2 years now and love the product, but the divception is INSANE! One tip that I've found to limit the DOM is to use 1 section with flex-wrapping columns. 

@shilo-ey doesn't it make sense that if the animations are off then each element shouldn't be wrapped in a div tag? Are their any future plans on this?

**Comment by roireshef** [comment]
I'm getting DOM depth of ~60 (sequences of nested elements). That's crazy, I'm practically not doing anything beyond text and photos. Let alone not creating recursive structure. There's so much overhead using this tool. I totally agree with @MichaelDarko. A professional tool needs some good engineer behind it. The Elementor product has all the blows and whistles but **just lacks good engineering**. So you can build a nice site, but if you are going to be scored low in google due bad site-building practices, and you're not going to get any traffic, then why did you build your site in the first place?

**Comment by Chertii** [comment]
I agree that Elementor should reduce DOM elements asap as (especially mobile) speed / Core Web Vitals are important! https://web.dev/vitals/

**Comment by quentinaurat** [comment]
The product works really great but the DOM is Ugly. It cause me lots of frustration when I need to put 'simple' or 'self' wrapped elements... I dont know if it's a big code challenge for you guys to add some "primitive" unwrapped elements that output just "<div></div>" etc... with a minimal set of options?

**Comment by digisavvy** [comment]
Dropping a comment here. The incessant div wrapping of elements is pretty ugly and just a poor practice. I hope the creators are looking into a meaningful solution to address this issue.

**Comment by ThomasFD** [comment]
H, having so many divs also negatively impacts the ability to get featured snippets in Google. Please fix this Elementor. I have to switch to Oxygen to be competative now!

**Comment by Alfred4444** [comment]
Finally, this is a serious problem ... It is clear that nothing is perfect and every day it is improved one step more and another step more. But the Elementor team looks the other way, when they really should be inspired by other companies like Webflow or Oxygen to improve.
Next week if I don't hear from Elementor on this topic, I will switch to Oxygen and not only that, but advise anyone to switch from Elementor to Oxygen. Sorry team, but if you look the other way, users will finely go the other way.
(sorry for my english)

**Comment by Slapbox** [comment]
I was surprised to find that even our simplest blog post with just 3 paragraphs and no links or anything  uses 1340 DOM nodes. The recommended maximum is 1500. Every page except that simplest blog post in over 1500 by quite a bit.

The only other content on that simplest page is 16 links total between header and footer and a pretty simple sidebar.

**Comment by Dylan-Yang** [comment]
Same I’ve only had to develop smaller sites and didn’t really notice that the DOM could have such adverse affects. But now that I’ve imputed so much time on designing a largerMore complex site withNo other plugins than elementor pro and Cpt could purchasing a larger hosting plan from somewhere like Kinsta or WP Engine with the speed(currently on Site ground go geek)? Or simply due to the fact there’s so many divs I’m screwed?

**Comment by Alfred4444** [comment]
Kinsta is very good. But it doesn't have a magic wand for you.
Imagine that you are advertising on IG and you have a landing page for your sales funnel and your visitors come, of course, from mobile devices .. having a great DOM, especially for devices is a big problem, so your landing will load in 4- 5 sec .... and this will cause% of visitors to leave the landing without having seen it. It directly affects your money, your business. So yes. Its a big problem. And as they add more widgets, more options, more and more, like this ... they will only add bricks to your loading time. Oxygen is not 100% clean code, it also says "divs". It is not the best option in the world. But it is better than Elementor at performance level, this is for sure.
For me, the dispute is not which to choose. It is that Elementor already put a solution to the problem. Meanwhile some of the advertising money is lost ...

(sorry for my english)

**Comment by myedgy** [comment]
+1 


> The more I'm looking into performace issues with Elementor, the more I'm sceptical about Elementor's future and Elementor's focus on being a professional tool.
> 
> Professional tool should produce professional results. WebFlow produces clean code and is super-fast. Oxygen produces clean code and is also fast. Elementor produces huge amount of divs, loads unnecessary files and is just slow, if you build something more complex. (All the reasons why professionals hate page builders.)
> 
> I've been trying out Oxygen page builder and my early conclusion was this:
> 
> * It's posibble to build more complex websites with Oxygen.
> * Performance is on a different level with Oxygen.
> * Elementor is nicer and more comfortable to use.
> 
> I'm still not ready to switch from Elementor, but I'm more and more concerned about Elementor's focus. Is it going to be a "toy" page builder for amateur users, or is it going to be a professional tool (like WebFlow) for WordPress that professionals can confidently use to build professional websites?
> 
> Google PageSpeed Insights hates Elementor, which must also be bad for SEO.
> 
> I really hope something can be done about fundamentally improving Elementor's performance.

I truly hope the staff / developers of Elementor are reading this. Would be nice that they listen too their clients and users that support them. 

Because this issue is really screaming to run to Oxygen, that is also a builder but with a clean output, meaning that it is possible to build a builder that outputs clean code.

**Comment by black-eye** [comment]
Well, it seems something is coming this way: https://developers.elementor.com/updated-convention-creating-new-widgets-for-improved-performance/

**Comment by mylimoproject** [comment]
I've been using Elementor for about 5 years now (1st year free and then PRO) and have quite a few sites running on it. My major issue has always been the styling constant safe loading/breaking up and having to clear, reset, clear, reset over and over again, but to the point at hand.... I gave up on the DOM issue and my solution was a "pick your poison" type of approach. Ideally, the less plugins, the better; but what if you actually need more plugins to offset the harm of the others? 

Aside from W3TC, I found that adding Hummingbird to handle asset optimization (which works very well with Cloudflare by the way) + Asset Cleanup + CAOS & OMGF solved every page-speed issue except the DOM/Facebook Analytics nightmare which I tried  fixing with "Host Everything Locally (HELL)", but it didn't work for Facebook. 

WordPress loads many resources/plugins on pages that you probably just use in one page. With Asset Cleanup you take care of that little problem and that's how I got to improve the score on the front-page (working on rest now).
Another problem with Elementor is that I have no idea why jquery has not been updated to the latest stable version (Current version is red flagged with two security issues on Lighthouse). I did try and update manually, but then the Elementor position breaks (Navigator + Right Click edit) and neither your icons or templates load. All you get is the empty dialog box.

ELEMENTOR... Take a break from adding new features and try to make your platform more stable and fix way overdue issues (Like the post excerpt length and many other bread and butter functions used on a daily basis). There will be the day, when one of those more efficient page builders are going to figure-out and develop a way of importing from one builder to another and you will be the first one on the their list.

**Comment by acornavi** [comment]
Elementor produces heavy code for no reason. This article nicely expresses the problem http://pagepipe.com/how-elementor-page-builder-affects-mobile-page-speed/

**Comment by MichaelDarko** [comment]
> Elementor produces heavy code for no reason. This article nicely expresses the problem http://pagepipe.com/how-elementor-page-builder-affects-mobile-page-speed/

Pretty "extremist" article, but some good points:

_"They’re working themselves compulsively into potential collapse from frenzied burnout. Out of control growth. They wrongly believe quantity translates into quality. It never does."_

_"They can’t stop adding junk. Their gold-rush panic and feature obsession make us have to think."_

Adding "cool" new widgets will work for generating new users for the next few years, but the lack of "first principles thinking" will catch up with Elementor. 

I've been building websites for clients with Elementor for years and with most new feature releases I've strongly felt like Elementor just doesn't understant what we actually need to build a website.

- **Custom posts and meta fields** - Needed if you want to build anything else than blog or businnes website. Only possible if you install many other plugins. 

If you're making a website PAGE BUILDER, surely creating post types and meta fileds has to be included. You can't leave it to other plugins, most people will not bother with that.

- **Performance** - Professionals are reluctant to adopt page builders, because the performance is bad. Some tools, like Webflow, managed to solve this, because they cared deeply about performance and put most of the effort into having a state of the art core. This can't be said about Elementor and is a massive problem in the long term, because the core is hard to change.

Things can change fast in this field and without solid fundamentals, Elementor will hit a wall sooner or later.

**Comment by acornavi** [comment]
Not to mention that you can't create a standard HTML5 semantic tag structure with Elementor. Semantic tags are completely useless. I raised this question in the Elementor Community Facebook group but admin deleted it. Hm.

**Comment by Netzlichter** [comment]
I really think about to try out Oxygen and switch from Elementor to oxygen if you cannot get rid of the DOM-Elements and output clean code :-/... I really like Elementor and the work flow but I think you must develop a more speedier elementor than more and more widgets...

**Comment by Alfred4444** [comment]
We all think alike. But the Elementor team says nothing about it. At least that I have seen.
For my part I have already bought Oxygen Builder (the complete pack) to test it. The truth is that it has some limitations that should be improved. But at a much better speed level and it feels very comfortable to build. How can I install it in multiple places. You can write to me if you want to try it. A greeting.

**Comment by Soetens** [comment]
I agree on this, there are to much DOM elements. This is against the Google policy to keep sites simple and fast to load, it would be a good thing if Elementor keep this kind of things in mind.

**Comment by Alfred4444** [comment]
Since beta 3.0 came out, I've been testing and testing it and examining the code. As a first step towards a clean code Elementor with a better UX, we are doing well and we must congratulate them on it, sincerely. I am looking forward to see what else they will bring us in the next stage of this beta. Hopefully it's CSS and JS optimization. Or being able to control all the styles of the elements. (especially in Woocommerce). Let's wait what it is about. Looking forward to seeing it.

**Comment by nfspck** [comment]
Unfortunately, it's a pretty simple conversation now, our Google overlords say you better get a good score on Google Insights or face our punishment. If Elementor doesn't deliver then we simply won't use it. That's something the peeps who develop Elementor should be pretty scared of, ie, less money coming in. 

Performance, content, and simple designs are the future in that order. Even WP 5.5's Gutenberg looks like it will fit the bill for most.

**Comment by MichaelDarko** [comment]
It's great they are focusing on performance improvements in the 3.0 version, but there is still a LOOONG way to go.

### **Google PageSpeed Insights**

As other people mentioned - Google PageSpeed Insights absolutely trashes websites built with Elementor. And Google WILL penalize you for bad performance score. Not even mentioning the impact a slow website can have on your business.

Unless you do some advanced next-level optimizing with other plugins, tools and tweaks, you can forget about achieving a professional results with Elementor.

### **A massive problem if you use Elementor for client work**

This is becoming a huge problem for me, because most clients demand good Google PageSpeed score upfront or they test the website after handoff. What do you tell them when the score is terrible? Because it alway is terrible with Elementor. 

### **It can be done: Webflow solved it**

It's such a shame Elementor doesn't focus on this enough. I know they say they strongly focus on performance, but the results are not there. 

I thought Elementor was supposed to be the page builder that solves this fundamental limitation of page builders - performance. They didn't solve it, not even close. You could say it can't be done, but it can. 

Webflow did it. They designed a page builder with professional performance in mind. Whatever you build with Webflow gets a very good score on Google PageSpeed Insights. And Webflow is much more capable than Elementor. The styling options and interactions are completely on another level form Elementor, yet the performance is superb.

We need something like Webflow for WordPress. I hoped Elementor will get there eventually, but the focus doesn't seem to be there. After 4 years of existence, we are still here talking about the fact that the performance is terrible and how it affects our client work. How does that suggest a strong focus on performance?

### **Gutenberg solved it**

Gutenberg is becoming more and more capable and is fast as hell. Soon it will be good enough page builder for most non-professional users and the performance is just great. 

Elementor needs to target professionals. Professionals care strongly about performance.

**Comment by dasigna** [comment]
> 
> 
> It's great they are focusing on performance improvements in the 3.0 version #11821 , but there is still a LOOONG way to go.
> ### **Google PageSpeed Insights**
> 
> As other people mentioned - Google PageSpeed Insights absolutely trashes websites built with Elementor. And Google WILL penalize you for bad performance score. Not even mentioning the impact a slow website can have on your business.
> 
> Unless you do some advanced next-level optimizing with other plugins, tools and tweaks, you can forget about achieving a professional results with Elementor.
> ### **A massive problem if you use Elementor for client work**
> 
> This is becoming a huge problem for me, because most clients demand good Google PageSpeed score upfront or they test the website after handoff. What do you tell them when the score is terrible? Because it alway is terrible with Elementor.
> ### **It can be done: Webflow solved it**
> 
> It's such a shame Elementor doesn't focus on this enough. I know they say they strongly focus on performance, but the results are not there.
> 
> I thought Elementor was supposed to be the page builder that solves this fundamental limitation of page builders - performance. They didn't solve it, not even close. You could say it can't be done, but it can.
> 
> Webflow did it. They designed a page builder with professional performance in mind. Whatever you build with Webflow gets a very good score on Google PageSpeed Insights. And Webflow is much more capable than Elementor. The styling options and interactions are completely on another level form Elementor, yet the performance is superb.
> 
> We need something like Webflow for WordPress. I hoped Elementor will get there eventually, but the focus doesn't seem to be there. After 4 years of existence, we are still here talking about the fact that the performance is terrible and how it affects our client work. How does that suggest a strong focus on performance?
> ### **Gutenberg solved it**
> 
> Gutenberg is becoming more and more capable and is fast as hell. Soon it will be good enough page builder for most non-professional users and the performance is just great.
> 
> Elementor needs to target professionals. Professionals care strongly about performance.

... i think there is absolutely nothing to add. completely agree.

period.

**Comment by All44** [comment]
totally agree. Not even this new Elementor approach is enough. It is simply not up to what the market demands and this is going to affect their product conversions. In the long run they will lose most of their customers and Elementor will be forgotten. It's a shame, I bet on Elementor since it was released.

**Comment by shilo-ey** [comment]
Hey all, we released Elementor v3.0 which addresses this issue, we will [keep on try reducing the DOM](https://developers.elementor.com/dom-improvements-ahead-html-wrappers-removal-from-v3-0/) elements in a responsible manner, and handle more performance metrics [such as this one](https://developers.elementor.com/css-rendering-performance-improvement/) in later versions.

If you have specific recommendations or requests, please create a new detailed issue.

Feel free to upgrade.

Thanks

**Comment by pzakhire** [comment]
I have a sugesstion to use optimized blocks in elementor for example instead of using simple text block and then paragraph block which will make divs for each use a optimized block which have both sections as one div with less customization. currently I thought elementor works this way but when I tested even if you use pro blocks which have both elements as one generates also generates individual divs.
another sugestion is that when compiling pages elementor first checks if any customization done to rows or columns and then usess less divs cus they are not necessary anymore with no customization.
Im not a pro nor a developer sorry if those I mentioned is not acceptable.

**Comment by Slapbox** [comment]
@pzakhire I think in the abstract those ideas are fine but in practice, since so many people are already using the system with potential heavy customization, those sorts of changes are a bigger deal to make than they sound like.

**Comment by dev-rashed** [comment]
> Oxigyn manage to keep design and flexibility without all nested divs: https://www.youtube.com/watch?v=KDGwVfj1jr4
This is horrible. After watching this video I am shocked! Holy

**Comment by JohnnyBravoTheBest** [comment]
I wonder why this issue is closed ? 

Still an issue in 2022~2023 

![dom size](https://user-images.githubusercontent.com/42011629/209782977-f57f444e-4153-4d66-ba26-73eb05d05613.png)

**Comment by nicholaszein** [comment]
Hello everyone!

We are happy to announce that the first beta implementation of the Grid Container is live! 🙌 

We would love to see you try this new feature and give your feedback in the [Beta Announcement](https://github.com/orgs/elementor/discussions/22119)! 💪 

Please try it out and let us know!

https://github.com/orgs/elementor/discussions/22119

Kind regards
