### ISSUE TITLE
Icon Alignment - Font Awesome 5

### ISSUE THREAD

**Issue by fxaviers** [elementor/elementor#8539]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description
Icon alignment overlaps the border of the column.
![image](https://user-images.githubusercontent.com/17536232/61064938-1e1da200-a3d9-11e9-9c70-b922453a2094.png)

Ideally it should look like the example below:
![image](https://user-images.githubusercontent.com/17536232/61065377-e400d000-a3d9-11e9-886a-853db0d4c888.png)

## Steps to reproduce
Just use the widget icon.

## How to solve
Can be easily corrected with CSS.
But it is necessary to add another class to the icon, corresponding to the alignment, because the code below solves the problem in the left alignment. While aligning to the right is required to use the "right" instead of the "left".
`.elementor-icon i:before, .elementor-icon svg:before {
    position: absolute;
    left: 0;
    -webkit-transform: translateX(0%);
    -ms-transform: translateX(0%);
    transform: translateX(0%);
}`

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by drawcard** [comment]
I wonder if it's related to the issues encountered sometimes when using FA in a list. Sometimes the icons are out of alignment and special classes need to be used on the <i> element to correct. 

More info:
https://fontawesome.com/how-to-use/on-the-web/styling/fixed-width-icons
https://fontawesome.com/how-to-use/on-the-web/styling/icons-in-a-list

**Comment by fxaviers** [comment]
Yes, this is caused by the different width between the icons.
In a list is worse, regardless of the alignment of the icons (as can be seen in the image below).
The link solution above should be adopted in all places where FA5 is used.

![image](https://user-images.githubusercontent.com/17536232/61125810-32b57500-a481-11e9-9006-e3ca64cb726b.png)

**Comment by shilo-ey** [comment]
@fxaviers 

Thanks, as you know, some of the icons have different width, which may cause this issue to occur.

It's visible in lists, and that's why we added to Elementor v2.6 the option to align the icons inside the list.

We will consider adding the option `fa-fw` that @drawcard suggested after we will make sure it won't affect existing users.

Thanks!

**Comment by fxaviers** [comment]
Thanks for listening @shilo-ey 
I understand that in lists is a somewhat more complex problem to solve.
However, my first message deals with simple icons, not list. The object being larger than the column border is rather inconvenient.

**Comment by drawcard** [comment]
```fa-fw``` should fix the problem whether or not the icons are in a list, the setting is applied to any independent element using an icon. Here's a quick demo I put together using h2 tags: https://codepen.io/drawcard/pen/GbazBL (icons shaded orange to demonstrate the full width effect applied to them)

Perhaps the ```fa-fw``` could be applied to the icon widget wrapper, and applied with a toggle somewhere in a settings pane @shilo-ey ?

**Comment by shilo-ey** [comment]
Thanks, we are considering your suggestions.

**Comment by drawcard** [comment]
Thank you @shilo-ey!

**Comment by fxaviers** [comment]
@shilo-ey Can you reopen this issue? In the first message I asked about the icon overflowing the widget border and this was not fixed. Update 2.7.0 has corrected the alignment of icons in the list, not in simple icon widget.
The image below shows two simple icons with the error, and also the icons list widget (now correctly).
![image](https://user-images.githubusercontent.com/17536232/64886658-18dd0d80-d63d-11e9-8f8a-0b65ef37acc9.png)

Thanks

**Comment by drawcard** [comment]
When you inspect the icons in Chrome do they show the `fa-fw` class being applied to them? That class should take effect on any instance of icon usage, as demoed in my earlier CodePen link.

**Comment by fxaviers** [comment]
@drawcard No, there is no such class. As far as I could understand, commit only affected the "assets/dev/scss/frontend/widgets/icon-list.scss " file.
This is frustrating, I described the problem, you showed the way to solve it, the issue was marked as solved, but the real problem still exists.
![image](https://user-images.githubusercontent.com/17536232/64956051-1dcdd700-d860-11e9-9db2-7095924a76f3.png)

**Comment by drawcard** [comment]
There may be a compatibility reason behind their decision not to roll it out for some widgets but I am curious, if you add the class in manually to the element does it work?

In Chrome Inspector, double click where it says `"fas fa-truck"` and type `fa-fw` in the middle space, I wonder if it will have any impact. It should given that `fa-fw` only adds a couple of simple properties like so:

```css
.fa-fw {
  text-align: center;
  width: 1.25em;
}
```

**Comment by fxaviers** [comment]
![image](https://user-images.githubusercontent.com/17536232/65062116-bdb75d80-d951-11e9-8696-21a876683b18.png)

It worked! `fa-fw` corrects the alignment problem. I just needed to add the `!important` because there was another style with more weight `.elementor-icon i`.

**Comment by drawcard** [comment]
Excellent - well if that's the case I would add my voice to getting Elementor's team to consider applying this to all icon applications across the board (or at least have it available as a toggle).
