### ISSUE TITLE
Font Awesome 5 and submenu indicator icon

### ISSUE THREAD

**Issue by vTechTeam** [elementor/elementor#8826]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

**Comment by vTechTeam** [comment]
After updating to Font Awesome 5 the submenu indicator changed to a box

Notice: https://www.screencast.com/t/sNvKPsDZd
Before: https://www.screencast.com/t/Ms1uyuPyF3Zc
After: https://www.screencast.com/t/yHbHWi4pkD76

**Comment by shilo-ey** [comment]
Hi @vTechTeam  

Please make sure you have the "Load Font Awesome 4 Support" set to "Yes" under WP Dashboard > Elementor > Settings > Advanced Tab

This should solve the issue in your case (or simply enter the template and edit the icons)

Thanks

**Comment by vTechTeam** [comment]
I had already verified that setting before ever sending this ticket. Also I have gone into the template to change the icon but there is no place to change that icon. Previous videos showed it but it is no longer there where it use to be. Please tell me where that setting is at. And I have tested this on 2 different sites with the same issue.

**Comment by mojician** [comment]
> Hi @vTechTeam
> 
> Please make sure you have the "Load Font Awesome 4 Support" set to "Yes" under WP Dashboard > Elementor > Settings > Advanced Tab
> 
> This should solve the issue in your case (or simply enter the template and edit the icons)
> 
> Thanks

I was looking everywhere for how to resolve. I even tried to go into my cpanel and adding some text with no success. I don't know why I didn't try this sooner. Was a lot easier than I expected!

**Comment by GIVINGtrax** [comment]
We are experiencing the same problem after updating the Elementor theme this weekend and had to remove the sub-menu icon (selected none) - as all options were displaying junk symbols.

**Comment by BlackBike** [comment]
I am having the same issue. Tried to disable and enable the Font Awesome 4 in the Advanced settings but the SVG is not loading. I enable Font Awesome 5 PRO with the new kit-ID. 

Any suggestions?

**Comment by ianrandmckenzie** [comment]
@shilo-ey could this please be re-opened? I'm having the same issue as @BlackBike — when using Font Awesome 5 Pro with a Kit that is set to use SVG, the icons do not load properly. Adding Font Awesome 4 support does not fix the issue (nor should it, in my opinion).

**Comment by Jsnrich** [comment]
Yeah I've also tried adding Font Awesome 4. It's not working

**Comment by BounceGvng** [comment]
also having this issue. Tried all the above solutions. It seems I can't find an answer anywhere online.

**Comment by BlackBike** [comment]
I fixed it with a work-around by putting the Fontawesome script in my header instead of loading the elementor kit ID option. It's probably a conflict with your theme or plugin and elementor. At least this worked for me.

**Comment by JeremyRAlexander** [comment]
Ditto! please re-open. I am using version 5.15.3 and I have enabled font awesome 4 support and tried inserting the font awesome script in the header, the elementor kit ID option, and both. Still getting the flashing question marks. I remove these options and they show again, but obviously any other icons inserted by <i> tags are not showing.

**Comment by BlackBike** [comment]
I updated my kit with FontAwesome and encountering the issue again. Why is this still an issue after 2 year of opening this thread? 

Enabling/disabling the "Load Font Awesome 4 Support" set to "Yes" under WP Dashboard > Elementor > Settings > Advanced Tab" is not solving the problem. 

I'm using Font Awesome Pro latest version
- Tried to insert my kit-ID - the issue still there
- Activate/deactivate Load Font Awesome 4 Support - the issue still there
- Inserted font awesome CDN in <head>  - the issue still there 

Using WordPress last version, Astra Pro (Child-theme) template (latest version)

Any directions would be much appreciated.

Does anybody have a solid solution for this??

**Comment by BlackBike** [comment]
@shilo-ey please re-open this topic because your solution is not solving the issue with other users too. Thanks =)

**Comment by Wicko-Design** [comment]
I have experience this and done a bit of testing.

Have entered a FontAwsome Kit script using the Elementor > Customer Code option. This kit is fontawesome 5 Pro

The kit has "Enable Version 4 Compatibility " ticked in the fontawesome settings. 

If I use the SVG technology option which is usually quicker the icons fail and are replaced with animated icons. 

If I then switch the kit technology to Web Font then the icons display ok. 

I hope this helps and that Elementor and FontAwesome can find a solution to fix these issues.

**Comment by BlackBike** [comment]
YES!! @Wicko-Design that fixed it for me too! Thank you very much for leaving this reply, it drove me crazy for some time. Cheers!

**Comment by portrayaloflife** [comment]
Seeing the same issue, submenu icons showing weird symbol instead of icon, can these not be updated to your own SVG or the font awesome icons menu like elementor has everywhere else? That would be so much better.
