### ISSUE TITLE
Multiple choice Checkbox required.

### ISSUE THREAD

**Issue by g-hofman** [elementor/elementor#9706]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
We are in need of an required check on the Elementor Pro Form widget. Customers need to check at least 1 option to submit the form. I.e: The label asks which languages the customer speaks. There are 2 options, French and German. The customer needs to choose either French or German in order to submit the form.

**Describe the solution you'd like**
A required check on the "checkbox" form field.

**Describe alternatives you've considered**
I have tried multiple acceptance fields, but this does not meet our requirements as we do not need multiple labels and customers need to choose either French or German.

**Comment by MichaelDarko** [comment]
Am i missing something or is this option simply not there?

There are many issues asking for the ability to make checkbox fields required and they're all closed and merged with one issue #1693 that says it was solved.

How was it solved? By adding the acceptance field? That only works for one checkbox. If you need users to select one of X number of options and make it required (As you would need in most cases.), how do you do that?

**Comment by daniilicic** [comment]
+1 

Not sure how Acceptance field solves the problem where we need multiple checbox options and the user is required to choose at least one of the options.

**Comment by kristinamertens** [comment]
+1

**Comment by kristinamertens** [comment]
+1 Yup, not solved until the option to make a checkbox field required is available

**Comment by lioncatde** [comment]
+1

**Comment by mbenady** [comment]
+1

**Comment by renzoesposito** [comment]
+1

**Comment by annettePixie** [comment]
+1

**Comment by mallegrini** [comment]
+1

**Comment by sermalefico** [comment]
Heloo!? Elementor?

**Comment by andretoldo** [comment]
+1

**Comment by LaurieCF** [comment]
+1, please. Incomplete submissions are causing problems in our database, we need to be able to make this a required field.

**Comment by RicPlan** [comment]
Given the price of licenses now they could start fixing the basic bugs. 
Hello Elementor, there is someone ????

**Comment by euene** [comment]
+1

**Comment by ywangwrs** [comment]
I'm surprised this feature is still not in place.

**Comment by luizfp** [comment]
+1

**Comment by maurocarreraok** [comment]
+1

**Comment by strive4impact** [comment]
+1.

Also just submitted to official Elementor Pro support...

**Comment by strive4impact** [comment]
Should be an option, like the "required" on other field types, to  "require at least [1]"  [OFF/ON]

**Comment by Xavvi** [comment]
+1

**Comment by IlPizza79** [comment]
+1

**Comment by usy666** [comment]
+1

**Comment by wordpressman** [comment]
+1

**Comment by nirkons** [comment]
+1

**Comment by wetpancake** [comment]
+1

**Comment by girl-mood** [comment]
+1

**Comment by pepkolajk** [comment]
+1

**Comment by Trinto610** [comment]
This basic functionality is still missing.....Almost three years now

**Comment by Elliria** [comment]
I agree that this should be available.

**Comment by frussane** [comment]
+1

**Comment by anybany** [comment]
we need it so bad
+1

**Comment by tmanaud** [comment]
we need this, thanks.
+1

**Comment by JB-Smiles** [comment]
Running into this problem now... Very annoying... This should finally be added!
+1

**Comment by vnt** [comment]
Dear Staff Member. It's been 4 years, now can you add the required on the checkboxes please?

**Comment by macazaga** [comment]
+1, at least let us know if it's on your plans or not

**Comment by buckmanhands** [comment]
Writing necessary forms is impossible without this feature. How did you think dropping the "acceptance" in the original feature request for this back in 2017 was going to solve this? We need to have a user check at least one of many checkboxes that are part of a group. Its an essential function of many forms.

**Comment by rezapr2** [comment]
+1

**Comment by vnt** [comment]
+1

**Comment by ravenswoodmedia** [comment]
+1

**Comment by VictorSCamargo** [comment]
+1

**Comment by steveindzine** [comment]
+1

**Comment by websplash** [comment]
+1

**Comment by rhuancolen** [comment]
+1

**Comment by vnt** [comment]
+1

**Comment by josephj11** [comment]
This would either be a mandatory radio button element or a requlrement that at least one option is selected. Both would be good enhancements. These could also contribute to more concise forms.

**Comment by Elliria** [comment]
I'm all for this. Related issues: [#1693](https://github.com/elementor/elementor/issues/1693) and [#45084](https://github.com/orgs/community/discussions/45084)

**Comment by therealgladius** [comment]
I made a plugin for that: https://github.com/therealgladius/required-checkboxes-for-elementor-forms

**Comment by bilalkk9** [comment]
I ran into the same issue where Elementor Forms doesn't provide a required validation option for checkbox fields. To solve it, I created a simple, lightweight plugin and published it on WordPress.org:

https://wordpress.org/plugins/required-checkbox-validation-for-elementor/

I hope it helps! Let me know if you have any questions or need any assistance with it.
